/**
 * Comprehensive Beauty Catalog Data Definition for Plugd
 * 
 * Expansive, creator-ready beauty discovery catalog covering Makeup, Skincare,
 * K-Beauty, Haircare, Hair Tools, Fragrance, Bath & Body, Sun Care, Lip Care,
 * Beauty Devices, Men's Grooming, Indian Ayurvedic Beauty, Luxury Beauty, and Gift Sets.
 */

import { getBeautyProductImage } from "./product-images";

export interface BeautyProduct {
  id: string;
  name: string;
  brand: string;
  category: "Beauty";
  subcategory: string;
  sectionId: string;
  sectionTitle: string;
  imageUrl: string;
  description: string;
  tags: string[];
  badge?: "HOT" | "TRENDING" | "VIRAL" | "NEW" | "POPULAR" | "PREMIUM" | "BESTSELLER";
  featured?: boolean;
  trending?: boolean;
  displayOrder: number;
}

export interface BeautySection {
  id: string;
  title: string;
  subtitle: string;
  badge?: string;
  displayOrder: number;
  productIds: string[];
}

export const BEAUTY_SECTIONS: BeautySection[] = [
  {
    id: "trending-beauty",
    title: "Trending Beauty",
    subtitle: "Viral beauty sensations, dewy liquid blushes, Korean skin elixirs, and signature luxury fragrances",
    badge: "🔥 Viral",
    displayOrder: 1,
    productIds: [
      "rare-beauty-soft-pinch-liquid-blush",
      "cosrx-advanced-snail-96-mucin-essence",
      "dyson-airwrap-multi-styler-complete-long",
      "sol-de-janeiro-cheirosa-68-perfume-mist",
      "laneige-lip-sleeping-mask-berry",
      "beauty-of-joseon-relief-sun-spf50",
      "dior-lip-glow-oil",
      "fenty-beauty-eaze-drop-skin-tint",
      "ysl-libre-eau-de-parfum",
      "anua-heartleaf-77-soothing-toner",
      "medicube-age-r-booster-pro",
      "minimalist-10-niacinamide-serum",
      "sol-de-janeiro-brazilian-bum-bum-cream",
      "charlotte-tilbury-flawless-filter",
      "rom-and-juicy-lasting-tint",
      "elf-halo-glow",
      "rhode-glazing-milk",
      "rhode-peptide-lip-treatment",
      "rare-beauty-positive-light-highlighter",
      "summer-fridays-lip-butter-balm"
    ],
  },
  {
    id: "viral-beauty-wishlist",
    title: "Beauty Wishlist",
    subtitle: "Aspirational, most-gifted and coveted beauty obsessions for creators and dream vanity setups",
    badge: "✨ Wishlist",
    displayOrder: 2,
    productIds: [
      "dyson-airwrap-multi-styler-complete-long",
      "dior-sauvage-eau-de-parfum",
      "ysl-libre-eau-de-parfum",
      "chanel-coco-mademoiselle-edp",
      "rare-beauty-soft-pinch-liquid-blush",
      "charlotte-tilbury-pillow-talk-palette",
      "sol-de-janeiro-cheirosa-68-perfume-mist",
      "laneige-lip-sleeping-mask-berry",
      "dior-lip-glow-oil",
      "kayali-vanilla-28-eau-de-parfum",
      "medicube-age-r-booster-pro",
      "forest-essentials-soundarya-radiance-cream",
      "charlotte-tilbury-magic-cream",
      "estee-lauder-advanced-night-repair-serum",
      "dior-lip-maximizer",
      "rhode-glazing-milk",
      "sol-de-janeiro-bom-dia-cream"
    ],
  },
  {
    id: "k-beauty-cult-favorites",
    title: "K-Beauty Cult Favorites (COSRX, Laneige, Joseon)",
    subtitle: "Glass-skin essences, soothing heartleaf toners, centella ampoules, and viral Korean sunscreens",
    badge: "🇰🇷 K-Beauty",
    displayOrder: 3,
    productIds: [
      "cosrx-advanced-snail-96-mucin-essence",
      "beauty-of-joseon-relief-sun-spf50",
      "laneige-lip-sleeping-mask-berry",
      "anua-heartleaf-77-soothing-toner",
      "skin1004-madagascar-centella-ampoule",
      "round-lab-birch-juice-sunscreen",
      "torriden-dive-in-hyaluronic-serum",
      "rom-and-juicy-lasting-tint",
      "peripera-ink-mood-glowy-tint",
      "cosrx-master-pimple-patch",
      "laneige-midnight-minis-lip-mask-set",
      "cosrx-bha-blackhead-power-liquid",
      "laneige-water-sleeping-mask"
    ],
  },
  {
    id: "makeup-face-base",
    title: "Makeup Obsession: Face & Base",
    subtitle: "Seamless skin tints, blurring loose powders, radiant concealers, and all-day setting sprays",
    badge: "💄 Base & Face",
    displayOrder: 4,
    productIds: [
      "rare-beauty-soft-pinch-liquid-blush",
      "fenty-beauty-eaze-drop-skin-tint",
      "nars-radiant-creamy-concealer",
      "huda-beauty-easy-bake-loose-powder",
      "charlotte-tilbury-flawless-filter",
      "charlotte-tilbury-airbrush-flawless-spray",
      "kay-beauty-matte-liquid-lipstick",
      "maybelline-fit-me-foundation",
      "maybelline-fit-me-concealer",
      "loreal-infallible-foundation",
      "loreal-true-match-foundation",
      "loreal-infallible-setting-spray",
      "lakme-9to5-primer-matte",
      "lakme-9to5-mousse",
      "kay-beauty-foundation",
      "kay-beauty-hd-concealer",
      "kay-beauty-creme-blush",
      "elf-halo-glow",
      "elf-camo-concealer",
      "elf-power-grip-primer",
      "rare-beauty-positive-light-highlighter",
      "fenty-beauty-pro-filtr-foundation",
      "mac-fix-plus",
      "benefit-benetint",
      "estee-lauder-double-wear"
    ],
  },
  {
    id: "eye-drama-lashes",
    title: "Eye Drama, Brows & Lashes",
    subtitle: "Tubing mascaras, smudge-proof Indian kajals, pigmented eye palettes, and micro brow pencils",
    badge: "👁️ Eyes",
    displayOrder: 5,
    productIds: [
      "maybelline-lash-sensational-sky-high",
      "kay-beauty-gel-kajal-black",
      "charlotte-tilbury-pillow-talk-palette",
      "benefit-precisely-my-brow-pencil",
      "maybelline-sky-high-mascara",
      "maybelline-colossal-kajal",
      "loreal-panorama-mascara",
      "lakme-eyeconic-kajal",
      "lakme-eyeconic-curling-mascara",
      "benefit-roller-lash"
    ],
  },
  {
    id: "lip-favorites-oils-tints",
    title: "Lip Favorites: Oils, Tints & Plumpers",
    subtitle: "Overnight sleeping masks, high-shine peptide lip oils, juicy Korean tints, and long-wear glosses",
    badge: "💋 Lip Care",
    displayOrder: 6,
    productIds: [
      "laneige-lip-sleeping-mask-berry",
      "dior-lip-glow-oil",
      "fenty-beauty-gloss-bomb-universal",
      "rom-and-juicy-lasting-tint",
      "peripera-ink-mood-glowy-tint",
      "kay-beauty-matte-liquid-lipstick",
      "lipstick-set",
      "maybelline-vinyl-ink",
      "maybelline-superstay-matte-ink",
      "charlotte-tilbury-pillow-talk-lipstick",
      "mac-ruby-woo",
      "mac-lipstick-velvet-teddy",
      "huda-beauty-liquid-matte",
      "nyx-butter-gloss",
      "nyx-fat-oil-lip-drip",
      "dior-lip-maximizer",
      "rhode-peptide-lip-treatment",
      "summer-fridays-lip-butter-balm",
      "rare-beauty-soft-pinch-lip-oil",
      "huda-beauty-lip-liner"
    ],
  },
  {
    id: "skincare-actives-serums",
    title: "Skincare Essentials: Actives & Serums",
    subtitle: "Barrier repair, clinical Niacinamide, BHA chemical exfoliants, Glycolic toners, and gentle cleansers",
    badge: "🧪 Skincare",
    displayOrder: 7,
    productIds: [
      "minimalist-10-niacinamide-serum",
      "face-serum",
      "the-ordinary-glycolic-acid-7-toning-solution",
      "cerave-hydrating-facial-cleanser",
      "paulas-choice-2-bha-liquid-exfoliant",
      "cosrx-advanced-snail-96-mucin-essence",
      "skin1004-madagascar-centella-ampoule",
      "torriden-dive-in-hyaluronic-serum",
      "skincare-routine",
      "cerave-moisturizing-cream",
      "cerave-foaming-cleanser",
      "cerave-sa-cleanser",
      "cetaphil-gentle-cleanser",
      "cetaphil-moisturizing-lotion",
      "the-ordinary-niacinamide",
      "the-ordinary-aha-bha-peel",
      "the-ordinary-hyaluronic-acid",
      "minimalist-salicylic-acid-cleanser",
      "minimalist-vitamin-c-serum",
      "dot-key-vitamin-c-serum",
      "dot-key-barrier-repair-cream",
      "plum-niacinamide-serum",
      "plum-vitamin-c-moisturizer",
      "deconstruct-retinol-serum",
      "deconstruct-aha-exfoliant",
      "clinique-moisture-surge",
      "clinique-dramatically-different"
    ],
  },
  {
    id: "sun-care-spf-shields",
    title: "Sun Care & Daily SPF Shields",
    subtitle: "No-white-cast chemical & mineral sunscreens, soothing cica gels, and on-the-go SPF sticks",
    badge: "☀️ Sun Care",
    displayOrder: 8,
    productIds: [
      "beauty-of-joseon-relief-sun-spf50",
      "round-lab-birch-juice-sunscreen",
      "dot-and-key-cica-calming-sunscreen",
      "minimalist-sunscreen-stick-spf50",
      "la-roche-posay-anthelios-spf50",
      "cosrx-aloe-soothing-sun-cream"
    ],
  },
  {
    id: "haircare-scalp-revival",
    title: "Haircare & Scalp Revival",
    subtitle: "Bond-building treatments, argan hair elixirs, deep repair masks, and frizz-control oils",
    badge: "💆 Haircare",
    displayOrder: 9,
    productIds: [
      "olaplex-no-3-hair-perfector",
      "kerastase-elixir-ultime-hair-oil",
      "moroccanoil-treatment-original",
      "loreal-professionnel-absolut-repair-mask",
      "hair-serum-general",
      "hair-mask-keratin",
      "heat-protectant-spray",
      "hair-oil-indulekha",
      "hair-styling-cream"
    ],
  },
  {
    id: "hair-styling-tools",
    title: "Hair Styling Tools (Dyson, Shark, Philips)",
    subtitle: "Intelligent thermal heat multi-stylers, ionic supersonic dryers, and blow-dry volumizing brushes",
    badge: "💨 Hair Tools",
    displayOrder: 10,
    productIds: [
      "dyson-airwrap-multi-styler-complete-long",
      "dyson-supersonic-hair-dryer",
      "shark-flexstyle-air-styling-system",
      "philips-thermoprotect-hair-dryer",
      "alan-truman-blow-dry-brush",
      "revlon-one-step-volumizer",
      "ghd-platinum-plus-straightener",
      "ghd-curve-curling-iron"
    ],
  },
  {
    id: "perfumes-fine-fragrances",
    title: "Perfumes & Fine Fragrances",
    subtitle: "Iconic designer Eau de Parfums, warm gourmand vanillas, middle-eastern oud blends, and luxury decants",
    badge: "🌸 Perfume",
    displayOrder: 11,
    productIds: [
      "dior-sauvage-eau-de-parfum",
      "ysl-libre-eau-de-parfum",
      "chanel-coco-mademoiselle-edp",
      "carolina-herrera-good-girl-edp",
      "kayali-vanilla-28-eau-de-parfum",
      "tom-ford-tobacco-vanille-edp",
      "maison-margiela-replica-jazz-club",
      "lattafa-khamrah-eau-de-parfum",
      "ajmal-aristocrat-perfume-for-her",
      "signature-perfume",
      "jo-malone-english-pear-and-freesia-cologne",
      "zara-red-vanilla",
      "zara-rich-warm-addictive",
      "dior-miss-dior-edp",
      "ariana-grande-cloud-edp",
      "kayali-eden-juicy-apple"
    ],
  },
  {
    id: "body-mists-bath-indulgence",
    title: "Body Mists & Indulgent Bath",
    subtitle: "Pistachio & salted caramel creams, exfoliating sugar scrubs, and mood-lifting scented candles",
    badge: "🛁 Bath & Body",
    displayOrder: 12,
    productIds: [
      "sol-de-janeiro-cheirosa-68-perfume-mist",
      "sol-de-janeiro-cheirosa-59-perfume-mist",
      "sol-de-janeiro-brazilian-bum-bum-cream",
      "tree-hut-shea-sugar-scrub-moroccan-rose",
      "bath-and-body-works-japanese-cherry-blossom",
      "scented-candle",
      "bath-body-works-vanilla-mist",
      "victorias-secret-bombshell-mist"
    ],
  },
  {
    id: "indian-heritage-ayurvedic",
    title: "Indian Heritage & Ayurvedic Beauty",
    subtitle: "24K gold Ayurvedic creams, Kumkumadi miraculous oils, Indian kajals, and botanical face washes",
    badge: "🦚 Indian Beauty",
    displayOrder: 13,
    productIds: [
      "forest-essentials-soundarya-radiance-cream",
      "kama-ayurveda-kumkumadi-beauty-fluid",
      "kay-beauty-matte-liquid-lipstick",
      "kay-beauty-gel-kajal-black",
      "plum-green-tea-pore-cleansing-face-wash",
      "dot-and-key-cica-calming-sunscreen"
    ],
  },
  {
    id: "beauty-devices-vanity-tools",
    title: "Beauty Devices & Vanity Tools",
    subtitle: "Microcurrent facial sculptors, LED light therapy masks, sonic cleansers, and natural rose quartz tools",
    badge: "🪞 Devices & Tools",
    displayOrder: 14,
    productIds: [
      "medicube-age-r-booster-pro",
      "foreo-luna-4-facial-cleansing-device",
      "nuface-trinity-microcurrent-device",
      "rose-quartz-gua-sha-facial-roller-set",
      "led-light-therapy-face-mask"
    ],
  },
  {
    id: "mens-grooming-beard",
    title: "Men's Grooming & Beard Care",
    subtitle: "Precision hybrid trimmers, cedarwood beard oils, stainless safety razors, and no-fuss skincare",
    badge: "🧔 Men's Grooming",
    displayOrder: 15,
    productIds: [
      "philips-oneblade-pro-face-and-body",
      "beardo-godfather-beard-oil",
      "bombay-shaving-company-precision-safety-razor",
      "minimalist-male-skincare-daily-duo",
      "dior-sauvage-eau-de-parfum"
    ],
  },
  {
    id: "luxury-beauty-gift-sets",
    title: "Luxury Beauty & Gift Sets",
    subtitle: "Prestige skincare elixirs, luxury makeup icons, curated mini sets, and bespoke cologne boxes",
    badge: "👑 Luxury & Gifts",
    displayOrder: 16,
    productIds: [
      "charlotte-tilbury-magic-cream",
      "estee-lauder-advanced-night-repair-serum",
      "jo-malone-english-pear-and-freesia-cologne",
      "laneige-midnight-minis-lip-mask-set",
      "tom-ford-tobacco-vanille-edp",
      "jo-malone-wood-sage"
    ],
  },
  {
    id: "bodycare-essentials",
    title: "Bodycare Essentials",
    subtitle: "Body lotions, body washes, scrubs, body oils, deodorants, and hand creams for full-body pampering",
    badge: "🧴 Bodycare",
    displayOrder: 17,
    productIds: [
      "body-lotion-nivea",
      "body-wash-dove",
      "body-scrub-mcaffeine",
      "body-oil-nuxe",
      "deodorant-wild-stone",
      "hand-cream-loccitane",
      "body-mist-nykaa",
      "sol-de-janeiro-body-wash"
    ],
  },
  {
    id: "beauty-tools-accessories",
    title: "Beauty Tools & Accessories",
    subtitle: "Makeup brushes, beauty blenders, vanity mirrors, heatless curlers, gua sha, skincare fridges, and nail kits",
    badge: "🪞 Tools",
    displayOrder: 18,
    productIds: [
      "makeup-brush-set",
      "beauty-blender-original",
      "makeup-organizer-acrylic",
      "vanity-mirror-led",
      "makeup-bag-travel",
      "heatless-curlers",
      "gua-sha-jade",
      "facial-roller-rose-quartz",
      "skincare-fridge",
      "nail-kit-gel",
      "hair-brush-wet",
      "at-home-manicure-set"
    ],
  },
  {
    id: "premium-aspirational",
    title: "Premium & Aspirational Beauty",
    subtitle: "Most-coveted luxury products from Rhode, Dior, Laneige, YSL, Clinique, and Sol de Janeiro",
    badge: "💎 Aspirational",
    displayOrder: 19,
    productIds: [
      "rhode-glazing-milk",
      "rhode-peptide-lip-treatment",
      "dior-backstage-face-body",
      "dior-lip-maximizer",
      "laneige-cream-skin-toner",
      "ysl-touche-eclat",
      "clinique-take-the-day-off",
      "sol-de-janeiro-bom-dia-cream",
      "dyson-airwrap-multi-styler-complete-long",
      "charlotte-tilbury-flawless-filter",
      "rare-beauty-soft-pinch-liquid-blush"
    ],
  }
];

/** Full list of Beauty products */
export const RAW_BEAUTY_PRODUCTS: Array<{
  id: string;
  name: string;
  brand: string;
  subcategory: string;
  sectionId: string;
  sectionTitle: string;
  description: string;
  tags: string[];
  badge?: "HOT" | "TRENDING" | "VIRAL" | "NEW" | "POPULAR" | "PREMIUM" | "BESTSELLER";
  featured?: boolean;
  trending?: boolean;
}> = [
  // === EXISTING MAKEUP (Face & Base) ===
  {
    id: "rare-beauty-soft-pinch-liquid-blush",
    name: "Soft Pinch Liquid Blush",
    brand: "Rare Beauty",
    subcategory: "Makeup",
    sectionId: "makeup-face-base",
    sectionTitle: "Makeup Obsession: Face & Base",
    description: "Weightless, long-lasting liquid blush infused with lotus, gardenia, and water lily that blends effortlessly for a soft, healthy flush.",
    tags: ["rare-beauty", "blush", "liquid-blush", "makeup", "viral", "trending", "selena-gomez"],
    badge: "VIRAL",
    featured: true,
    trending: true,
  },
  {
    id: "fenty-beauty-eaze-drop-skin-tint",
    name: "Eaze Drop Blurring Skin Tint",
    brand: "Fenty Beauty",
    subcategory: "Makeup",
    sectionId: "makeup-face-base",
    sectionTitle: "Makeup Obsession: Face & Base",
    description: "Lightweight buildable light-to-medium coverage skin tint featuring QuickBlur complex for an effortless, no-makeup makeup look.",
    tags: ["fenty", "fenty-beauty", "skin-tint", "foundation", "base", "blurring"],
    badge: "HOT",
    featured: true,
  },
  {
    id: "nars-radiant-creamy-concealer",
    name: "Radiant Creamy Concealer",
    brand: "NARS",
    subcategory: "Makeup",
    sectionId: "makeup-face-base",
    sectionTitle: "Makeup Obsession: Face & Base",
    description: "Multi-action concealer that contours, highlights, corrects, and hydrates with luminous 16-hour wear.",
    tags: ["nars", "concealer", "makeup", "radiant", "bestseller"],
    badge: "BESTSELLER",
  },
  {
    id: "huda-beauty-easy-bake-loose-powder",
    name: "Easy Bake Loose Baking & Setting Powder",
    brand: "Huda Beauty",
    subcategory: "Makeup",
    sectionId: "makeup-face-base",
    sectionTitle: "Makeup Obsession: Face & Base",
    description: "Ultra-fine setting powder that blurs pores, locks makeup in place for 10 hours, and leaves an airbrushed matte finish.",
    tags: ["huda-beauty", "setting-powder", "baking", "matte", "makeup"],
    badge: "POPULAR",
  },
  {
    id: "charlotte-tilbury-flawless-filter",
    name: "Hollywood Flawless Filter Complexion Booster",
    brand: "Charlotte Tilbury",
    subcategory: "Makeup",
    sectionId: "makeup-face-base",
    sectionTitle: "Makeup Obsession: Face & Base",
    description: "Customizable glow booster with smoothing polymers and glossy oil for a red-carpet lit-from-within glow.",
    tags: ["charlotte-tilbury", "glow", "highlighter", "primer", "luxury", "viral"],
    badge: "VIRAL",
    featured: true,
  },
  {
    id: "charlotte-tilbury-airbrush-flawless-spray",
    name: "Airbrush Flawless Setting Spray",
    brand: "Charlotte Tilbury",
    subcategory: "Makeup",
    sectionId: "makeup-face-base",
    sectionTitle: "Makeup Obsession: Face & Base",
    description: "Weightless, hydrating setting mist infused with aloe vera and Japanese green tea to lock makeup for 16 hours.",
    tags: ["charlotte-tilbury", "setting-spray", "airbrush", "makeup"],
    badge: "POPULAR",
  },

  // === EXISTING Eyes & Brows ===
  {
    id: "maybelline-lash-sensational-sky-high",
    name: "Lash Sensational Sky High Mascara",
    brand: "Maybelline",
    subcategory: "Makeup",
    sectionId: "eye-drama-lashes",
    sectionTitle: "Eye Drama, Brows & Lashes",
    description: "Flex Tower mascara brush with bamboo extract delivering limitless volume and lash extension length without clumps.",
    tags: ["maybelline", "mascara", "sky-high", "lashes", "viral", "bestseller"],
    badge: "BESTSELLER",
  },
  {
    id: "charlotte-tilbury-pillow-talk-palette",
    name: "Luxury Eyeshadow Palette - Pillow Talk",
    brand: "Charlotte Tilbury",
    subcategory: "Makeup",
    sectionId: "eye-drama-lashes",
    sectionTitle: "Eye Drama, Brows & Lashes",
    description: "Iconic 4-step nude-pink eyeshadow palette featuring prime, enhance, smoke, and pop shimmer shades.",
    tags: ["charlotte-tilbury", "eyeshadow", "palette", "pillow-talk", "luxury"],
    badge: "PREMIUM",
    featured: true,
  },
  {
    id: "kay-beauty-gel-kajal-black",
    name: "24HR Waterproof Gel Kajal",
    brand: "Kay Beauty",
    subcategory: "Makeup",
    sectionId: "eye-drama-lashes",
    sectionTitle: "Eye Drama, Brows & Lashes",
    description: "Intense 100% smudge-proof matte black kajal enriched with chamomile and ceramides for soothing Indian eye definition.",
    tags: ["kay-beauty", "kajal", "eyeliner", "smudgeproof", "indian-beauty"],
    badge: "POPULAR",
  },
  {
    id: "benefit-precisely-my-brow-pencil",
    name: "Precisely, My Brow Detailer Pencil",
    brand: "Benefit",
    subcategory: "Makeup",
    sectionId: "eye-drama-lashes",
    sectionTitle: "Eye Drama, Brows & Lashes",
    description: "Ultra-fine tip eyebrow pencil drawing natural, hair-like strokes with 12-hour waterproof wear.",
    tags: ["benefit", "brow-pencil", "brows", "makeup"],
  },

  // === EXISTING Lips ===
  {
    id: "laneige-lip-sleeping-mask-berry",
    name: "Lip Sleeping Mask (Berry)",
    brand: "Laneige",
    subcategory: "Lip Care",
    sectionId: "lip-favorites-oils-tints",
    sectionTitle: "Lip Favorites: Oils, Tints & Plumpers",
    description: "Overnight leave-on lip mask powered by Berry Fruit Complex and Vitamin C delivering supple, nourished lips by morning.",
    tags: ["laneige", "lip-mask", "lip-care", "k-beauty", "berry", "bestseller", "trending"],
    badge: "BESTSELLER",
    featured: true,
    trending: true,
  },
  {
    id: "dior-lip-glow-oil",
    name: "Dior Addict Lip Glow Oil",
    brand: "Dior",
    subcategory: "Lip Care",
    sectionId: "lip-favorites-oils-tints",
    sectionTitle: "Lip Favorites: Oils, Tints & Plumpers",
    description: "Nourishing cherry oil infused lip oil providing mirror shine and custom color-reviver rosy tint.",
    tags: ["dior", "lip-oil", "luxury", "gloss", "viral", "trending"],
    badge: "VIRAL",
    featured: true,
    trending: true,
  },
  {
    id: "fenty-beauty-gloss-bomb-universal",
    name: "Gloss Bomb Universal Lip Luminizer",
    brand: "Fenty Beauty",
    subcategory: "Makeup",
    sectionId: "lip-favorites-oils-tints",
    sectionTitle: "Lip Favorites: Oils, Tints & Plumpers",
    description: "The ultimate gotta-have-it lip gloss with explosive shine, conditioning shea butter, and addictive peach-vanilla scent.",
    tags: ["fenty", "gloss-bomb", "lip-gloss", "fenty-beauty", "bestseller"],
    badge: "POPULAR",
  },
  {
    id: "rom-and-juicy-lasting-tint",
    name: "Juicy Lasting Lip Tint",
    brand: "Rom&nd",
    subcategory: "Lip Care",
    sectionId: "lip-favorites-oils-tints",
    sectionTitle: "Lip Favorites: Oils, Tints & Plumpers",
    description: "3-in-1 lip tint offering the pigmentation of a lipstick, shine of a gloss, and long-lasting stain of a lip tint.",
    tags: ["romand", "lip-tint", "k-beauty", "juicy-tint", "trending"],
    badge: "HOT",
  },
  {
    id: "peripera-ink-mood-glowy-tint",
    name: "Ink Mood Glowy Lip Tint",
    brand: "Peripera",
    subcategory: "Lip Care",
    sectionId: "lip-favorites-oils-tints",
    sectionTitle: "Lip Favorites: Oils, Tints & Plumpers",
    description: "Watery moisture film glow tint with refreshing texture that clings lightly to lips without stickiness.",
    tags: ["peripera", "lip-tint", "k-beauty", "glowy"],
  },
  {
    id: "kay-beauty-matte-liquid-lipstick",
    name: "Matteinee Matte Liquid Lipstick",
    brand: "Kay Beauty",
    subcategory: "Makeup",
    sectionId: "lip-favorites-oils-tints",
    sectionTitle: "Lip Favorites: Oils, Tints & Plumpers",
    description: "Weightless transfer-proof matte lipstick enriched with grape seed and marula oil tailored for Indian skin tones.",
    tags: ["kay-beauty", "liquid-lipstick", "matte", "indian-beauty"],
    badge: "POPULAR",
  },
  {
    id: "lipstick-set",
    name: "Lipstick Set",
    brand: "Plugd Beauty",
    subcategory: "Makeup",
    sectionId: "lip-favorites-oils-tints",
    sectionTitle: "Lip Favorites: Oils, Tints & Plumpers",
    description: "A curated set of versatile lip shades for everyday wear and evening glam.",
    tags: ["lipstick", "lip-set", "makeup"],
  },

  // === EXISTING Skincare & K-Beauty ===
  {
    id: "cosrx-advanced-snail-96-mucin-essence",
    name: "Advanced Snail 96 Mucin Power Essence",
    brand: "COSRX",
    subcategory: "K-Beauty",
    sectionId: "k-beauty-cult-favorites",
    sectionTitle: "K-Beauty Cult Favorites (COSRX, Laneige, Joseon)",
    description: "96.3% Snail Secretion Filtrate lightweight essence that soothes damaged skin, enhances elasticity, and imparts intense glass-skin hydration.",
    tags: ["cosrx", "snail-mucin", "essence", "k-beauty", "glass-skin", "viral", "trending"],
    badge: "VIRAL",
    featured: true,
    trending: true,
  },
  {
    id: "beauty-of-joseon-relief-sun-spf50",
    name: "Relief Sun: Rice + Probiotics SPF 50+ PA++++",
    brand: "Beauty of Joseon",
    subcategory: "Sun Care",
    sectionId: "k-beauty-cult-favorites",
    sectionTitle: "K-Beauty Cult Favorites (COSRX, Laneige, Joseon)",
    description: "Organic chemical sunscreen with 30% rice extract and fermented grain probiotics that moisturizes skin with zero white cast.",
    tags: ["beauty-of-joseon", "sunscreen", "spf50", "k-beauty", "rice", "viral", "bestseller"],
    badge: "BESTSELLER",
    featured: true,
    trending: true,
  },
  {
    id: "anua-heartleaf-77-soothing-toner",
    name: "Heartleaf 77% Soothing Toner",
    brand: "Anua",
    subcategory: "K-Beauty",
    sectionId: "k-beauty-cult-favorites",
    sectionTitle: "K-Beauty Cult Favorites (COSRX, Laneige, Joseon)",
    description: "Sub-acidic soothing toner formulated with 77% heartleaf extract to calm acne, redness, and balance skin moisture.",
    tags: ["anua", "heartleaf", "toner", "k-beauty", "acne", "calming", "trending"],
    badge: "HOT",
    featured: true,
  },
  {
    id: "skin1004-madagascar-centella-ampoule",
    name: "Madagascar Centella Asiatica Ampoule",
    brand: "SKIN1004",
    subcategory: "K-Beauty",
    sectionId: "k-beauty-cult-favorites",
    sectionTitle: "K-Beauty Cult Favorites (COSRX, Laneige, Joseon)",
    description: "100% Centella Asiatica pure extract ampoule that repairs compromised skin barriers and calms irritation immediately.",
    tags: ["skin1004", "centella", "ampoule", "k-beauty", "barrier-repair"],
    badge: "POPULAR",
  },
  {
    id: "round-lab-birch-juice-sunscreen",
    name: "Birch Juice Moisturizing Sun Cream SPF 50+",
    brand: "Round Lab",
    subcategory: "Sun Care",
    sectionId: "sun-care-spf-shields",
    sectionTitle: "Sun Care & Daily SPF Shields",
    description: "Hyaluronic acid and birch juice enriched sunscreen providing deep dewy hydration and broad-spectrum UV protection.",
    tags: ["round-lab", "birch-juice", "sunscreen", "k-beauty", "hydrating"],
    badge: "POPULAR",
  },
  {
    id: "torriden-dive-in-hyaluronic-serum",
    name: "DIVE-IN Low Molecular Hyaluronic Acid Serum",
    brand: "Torriden",
    subcategory: "K-Beauty",
    sectionId: "k-beauty-cult-favorites",
    sectionTitle: "K-Beauty Cult Favorites (COSRX, Laneige, Joseon)",
    description: "5D complex low molecular hyaluronic acid serum replenishing inner skin moisture with light, non-sticky finish.",
    tags: ["torriden", "hyaluronic-acid", "serum", "k-beauty", "hydration"],
  },
  {
    id: "minimalist-10-niacinamide-serum",
    name: "10% Niacinamide + Zinc Face Serum",
    brand: "Minimalist",
    subcategory: "Skincare",
    sectionId: "skincare-actives-serums",
    sectionTitle: "Skincare Essentials: Actives & Serums",
    description: "Clinical grade Vitamin B3 serum with pure EUK-134 antioxidant that reduces sebum, clears dark spots, and refines texture.",
    tags: ["minimalist", "niacinamide", "serum", "skincare", "indian-beauty", "bestseller"],
    badge: "BESTSELLER",
    featured: true,
  },
  {
    id: "face-serum",
    name: "Face Serum",
    brand: "Plugd Skincare",
    subcategory: "Skincare",
    sectionId: "skincare-actives-serums",
    sectionTitle: "Skincare Essentials: Actives & Serums",
    description: "A potent active facial treatment serum targeted for glow, hydration, and skin barrier health.",
    tags: ["serum", "skincare", "glow"],
  },
  {
    id: "the-ordinary-glycolic-acid-7-toning-solution",
    name: "Glycolic Acid 7% Exfoliating Toner",
    brand: "The Ordinary",
    subcategory: "Skincare",
    sectionId: "skincare-actives-serums",
    sectionTitle: "Skincare Essentials: Actives & Serums",
    description: "AHA exfoliating toner with Tasmanian Pepperberry and aloe vera that gently resurfaces skin and boosts luminosity.",
    tags: ["the-ordinary", "glycolic-acid", "toner", "exfoliant", "skincare", "viral"],
    badge: "POPULAR",
  },
  {
    id: "cerave-hydrating-facial-cleanser",
    name: "Hydrating Facial Cleanser with Ceramides",
    brand: "CeraVe",
    subcategory: "Skincare",
    sectionId: "skincare-actives-serums",
    sectionTitle: "Skincare Essentials: Actives & Serums",
    description: "Non-foaming lotion cleanser with 3 essential ceramides and hyaluronic acid that cleanses without stripping skin.",
    tags: ["cerave", "cleanser", "ceramides", "dermatologist", "skincare"],
    badge: "BESTSELLER",
  },
  {
    id: "paulas-choice-2-bha-liquid-exfoliant",
    name: "Skin Perfecting 2% BHA Liquid Exfoliant",
    brand: "Paula's Choice",
    subcategory: "Skincare",
    sectionId: "skincare-actives-serums",
    sectionTitle: "Skincare Essentials: Actives & Serums",
    description: "Salicylic acid leave-on exfoliant that unclogs enlarged pores, smooths wrinkles, and evens out tone.",
    tags: ["paulas-choice", "bha", "salicylic-acid", "pores", "skincare", "cult"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "dot-and-key-cica-calming-sunscreen",
    name: "Cica Calming Water-Gel Sunscreen SPF 50+",
    brand: "Dot & Key",
    subcategory: "Sun Care",
    sectionId: "sun-care-spf-shields",
    sectionTitle: "Sun Care & Daily SPF Shields",
    description: "Ultra-lightweight oil-free sunscreen with cica and niacinamide designed for acne-prone Indian skin.",
    tags: ["dot-and-key", "sunscreen", "cica", "gel-sunscreen", "indian-beauty"],
    badge: "POPULAR",
  },
  {
    id: "minimalist-sunscreen-stick-spf50",
    name: "SPF 50 Sunscreen Stick with Adenosine",
    brand: "Minimalist",
    subcategory: "Sun Care",
    sectionId: "sun-care-spf-shields",
    sectionTitle: "Sun Care & Daily SPF Shields",
    description: "Easy swipe-on sun protection stick for effortless on-the-go reapplication over makeup with zero mess.",
    tags: ["minimalist", "sun-stick", "sunscreen", "portable", "spf50"],
    badge: "HOT",
  },
  {
    id: "la-roche-posay-anthelios-spf50",
    name: "Anthelios UVMune 400 Invisible Fluid SPF 50+",
    brand: "La Roche-Posay",
    subcategory: "Sun Care",
    sectionId: "sun-care-spf-shields",
    sectionTitle: "Sun Care & Daily SPF Shields",
    description: "Ultra-long UVA protection with Mexoryl 400 filter in an ultra-resistant non-greasy invisible fluid.",
    tags: ["la-roche-posay", "anthelios", "sunscreen", "dermatology", "premium"],
  },
  {
    id: "cosrx-master-pimple-patch",
    name: "Acne Pimple Master Patch (24 Patches)",
    brand: "COSRX",
    subcategory: "Skincare",
    sectionId: "k-beauty-cult-favorites",
    sectionTitle: "K-Beauty Cult Favorites (COSRX, Laneige, Joseon)",
    description: "Hydrocolloid spot patches that absorb impurities, protect blemishes from bacteria, and speed up recovery.",
    tags: ["cosrx", "pimple-patch", "acne", "k-beauty", "emergency"],
  },
  {
    id: "skincare-routine",
    name: "Skincare Routine Kit",
    brand: "Plugd Skincare",
    subcategory: "Skincare",
    sectionId: "skincare-actives-serums",
    sectionTitle: "Skincare Essentials: Actives & Serums",
    description: "A complete daily regimen kit covering cleansing, toning, active treatment, and barrier hydration.",
    tags: ["skincare", "routine", "kit"],
  },

  // === EXISTING Haircare & Hair Tools ===
  {
    id: "dyson-airwrap-multi-styler-complete-long",
    name: "Airwrap Multi-Styler Complete Long",
    brand: "Dyson",
    subcategory: "Hair Tools",
    sectionId: "hair-styling-tools",
    sectionTitle: "Hair Styling Tools (Dyson, Shark, Philips)",
    description: "Pioneering Coanda airflow styling that curls, shapes, smooths, and hides flyaways with intelligent heat control and zero extreme heat damage.",
    tags: ["dyson", "airwrap", "hair-tool", "multi-styler", "luxury", "wishlist", "trending"],
    badge: "VIRAL",
    featured: true,
    trending: true,
  },
  {
    id: "dyson-supersonic-hair-dryer",
    name: "Supersonic Nural Hair Dryer",
    brand: "Dyson",
    subcategory: "Hair Tools",
    sectionId: "hair-styling-tools",
    sectionTitle: "Hair Styling Tools (Dyson, Shark, Philips)",
    description: "Fast drying with Nural sensors that auto-adjust heat to protect scalp health and enhance natural shine.",
    tags: ["dyson", "supersonic", "hair-dryer", "luxury", "styling"],
    badge: "PREMIUM",
    featured: true,
  },
  {
    id: "shark-flexstyle-air-styling-system",
    name: "FlexStyle Air Styling & Drying System",
    brand: "Shark",
    subcategory: "Hair Tools",
    sectionId: "hair-styling-tools",
    sectionTitle: "Hair Styling Tools (Dyson, Shark, Philips)",
    description: "Versatile wand rotating effortlessly from a powerful hair dryer into a multi-styler with auto-wrap curlers.",
    tags: ["shark", "flexstyle", "hair-tool", "curler", "styler"],
    badge: "POPULAR",
  },
  {
    id: "olaplex-no-3-hair-perfector",
    name: "No. 3 Hair Perfector Repair Treatment",
    brand: "Olaplex",
    subcategory: "Haircare",
    sectionId: "haircare-scalp-revival",
    sectionTitle: "Haircare & Scalp Revival",
    description: "Patented Bis-Aminopropyl Diglycol Dimaleate bond-builder that repairs broken disulfide bonds in color-treated and heat-damaged hair.",
    tags: ["olaplex", "hair-treatment", "bond-builder", "repair", "haircare", "cult"],
    badge: "BESTSELLER",
    featured: true,
  },
  {
    id: "kerastase-elixir-ultime-hair-oil",
    name: "Elixir Ultime L'Huile Originale Hair Oil",
    brand: "Kérastase",
    subcategory: "Haircare",
    sectionId: "haircare-scalp-revival",
    sectionTitle: "Haircare & Scalp Revival",
    description: "Precious wild French camellia oil blend offering 48 hours of shine, thermal heat protection up to 230°C, and frizz control.",
    tags: ["kerastase", "hair-oil", "luxury-haircare", "shine", "frizz-control"],
    badge: "PREMIUM",
  },
  {
    id: "moroccanoil-treatment-original",
    name: "Moroccanoil Treatment Original",
    brand: "Moroccanoil",
    subcategory: "Haircare",
    sectionId: "haircare-scalp-revival",
    sectionTitle: "Haircare & Scalp Revival",
    description: "Argan oil infused conditioning formula that detangles, speeds up blow-drying time, and leaves hair silky smooth.",
    tags: ["moroccanoil", "argan-oil", "treatment", "haircare"],
    badge: "POPULAR",
  },
  {
    id: "loreal-professionnel-absolut-repair-mask",
    name: "Serie Expert Absolut Repair Golden Mask",
    brand: "L'Oréal Professionnel",
    subcategory: "Haircare",
    sectionId: "haircare-scalp-revival",
    sectionTitle: "Haircare & Scalp Revival",
    description: "Gold quinoa and protein deep conditioning hair mask that instantly resurfaces and repairs damaged hair fibers.",
    tags: ["loreal", "hair-mask", "repair", "haircare", "salon"],
  },
  {
    id: "philips-thermoprotect-hair-dryer",
    name: "ThermoProtect Ionic 2100W Hair Dryer",
    brand: "Philips",
    subcategory: "Hair Tools",
    sectionId: "hair-styling-tools",
    sectionTitle: "Hair Styling Tools (Dyson, Shark, Philips)",
    description: "Powerful 2100W airflow with ionic conditioning and ThermoProtect constant temperature care.",
    tags: ["philips", "hair-dryer", "ionic", "budget", "hair-tool"],
  },
  {
    id: "alan-truman-blow-dry-brush",
    name: "Hot Pro Ceramic Blow-Dry Volumizer Brush",
    brand: "Alan Truman",
    subcategory: "Hair Tools",
    sectionId: "hair-styling-tools",
    sectionTitle: "Hair Styling Tools (Dyson, Shark, Philips)",
    description: "Oval barrel styling brush with ceramic tourmaline coating creating salon-grade blowout volume at home.",
    tags: ["alan-truman", "blow-dry-brush", "volumizer", "styling"],
    badge: "POPULAR",
  },

  // === EXISTING Fragrances ===
  {
    id: "dior-sauvage-eau-de-parfum",
    name: "Sauvage Eau de Parfum",
    brand: "Dior",
    subcategory: "Fragrance",
    sectionId: "perfumes-fine-fragrances",
    sectionTitle: "Perfumes & Fine Fragrances",
    description: "Calabrian bergamot, Sichuan pepper, and Papua New Guinean vanilla absolute creating a powerful, sensual woody-oriental trail.",
    tags: ["dior", "sauvage", "perfume", "men-fragrance", "luxury", "bestseller", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "ysl-libre-eau-de-parfum",
    name: "Libre Eau de Parfum",
    brand: "YSL",
    subcategory: "Fragrance",
    sectionId: "perfumes-fine-fragrances",
    sectionTitle: "Perfumes & Fine Fragrances",
    description: "Grand floral fragrance fusing Moroccan orange blossom with French lavender and bold Madagascar vanilla.",
    tags: ["ysl", "libre", "perfume", "floral", "luxury", "trending"],
    badge: "VIRAL",
    featured: true,
    trending: true,
  },
  {
    id: "chanel-coco-mademoiselle-edp",
    name: "Coco Mademoiselle Eau de Parfum",
    brand: "Chanel",
    subcategory: "Fragrance",
    sectionId: "perfumes-fine-fragrances",
    sectionTitle: "Perfumes & Fine Fragrances",
    description: "Vibrant orange sparks with transparent Grasse jasmine, May rose, and pure accents of patchouli and vetiver.",
    tags: ["chanel", "coco-mademoiselle", "luxury", "perfume", "timeless"],
    badge: "PREMIUM",
    featured: true,
  },
  {
    id: "carolina-herrera-good-girl-edp",
    name: "Good Girl Eau de Parfum",
    brand: "Carolina Herrera",
    subcategory: "Fragrance",
    sectionId: "perfumes-fine-fragrances",
    sectionTitle: "Perfumes & Fine Fragrances",
    description: "Iconic stiletto bottle carrying sweet tuberose, roasted tonka beans, rich cocoa, and white Sambac jasmine.",
    tags: ["carolina-herrera", "good-girl", "perfume", "stiletto", "gourmand"],
    badge: "POPULAR",
  },
  {
    id: "sol-de-janeiro-cheirosa-68-perfume-mist",
    name: "Cheirosa 68 Beija Flor Perfume Mist",
    brand: "Sol de Janeiro",
    subcategory: "Bath & Body",
    sectionId: "body-mists-bath-indulgence",
    sectionTitle: "Body Mists & Indulgent Bath",
    description: "Fruity floral body mist with Brazilian jasmine, pink dragonfruit, ocean air, and sheer vanilla.",
    tags: ["sol-de-janeiro", "cheirosa-68", "body-mist", "viral", "sweet", "trending"],
    badge: "VIRAL",
    featured: true,
    trending: true,
  },
  {
    id: "sol-de-janeiro-cheirosa-59-perfume-mist",
    name: "Cheirosa 59 Delícia Drench Mist",
    brand: "Sol de Janeiro",
    subcategory: "Bath & Body",
    sectionId: "body-mists-bath-indulgence",
    sectionTitle: "Body Mists & Indulgent Bath",
    description: "Uplifting woody gourmand mist blending velvet plum, sugared violet, and warm amber woods.",
    tags: ["sol-de-janeiro", "cheirosa-59", "body-mist", "vanilla"],
    badge: "NEW",
  },
  {
    id: "kayali-vanilla-28-eau-de-parfum",
    name: "Vanilla | 28 Eau de Parfum",
    brand: "Kayali",
    subcategory: "Fragrance",
    sectionId: "perfumes-fine-fragrances",
    sectionTitle: "Perfumes & Fine Fragrances",
    description: "Rich decadent gourmand vanilla fusing creamy jasmine, rich Madagascan vanilla orchid, brown sugar, and amber woods.",
    tags: ["kayali", "vanilla-28", "perfume", "gourmand", "huda-kattan"],
    badge: "POPULAR",
  },
  {
    id: "tom-ford-tobacco-vanille-edp",
    name: "Tobacco Vanille Private Blend EDP",
    brand: "Tom Ford",
    subcategory: "Fragrance",
    sectionId: "perfumes-fine-fragrances",
    sectionTitle: "Perfumes & Fine Fragrances",
    description: "Opulent artisanal scent with aromatic tobacco leaf, warm spices, tonka bean, cocoa, and sweet wood sap.",
    tags: ["tom-ford", "tobacco-vanille", "luxury-perfume", "niche"],
    badge: "PREMIUM",
  },
  {
    id: "maison-margiela-replica-jazz-club",
    name: "REPLICA Jazz Club Eau de Toilette",
    brand: "Maison Margiela",
    subcategory: "Fragrance",
    sectionId: "perfumes-fine-fragrances",
    sectionTitle: "Perfumes & Fine Fragrances",
    description: "Heady cocktail of pink pepper, rum absolute, tobacco leaf, and vanilla evoking a cozy Brooklyn jazz club.",
    tags: ["maison-margiela", "replica", "jazz-club", "niche", "unisex"],
    badge: "HOT",
  },
  {
    id: "lattafa-khamrah-eau-de-parfum",
    name: "Khamrah Eau de Parfum",
    brand: "Lattafa",
    subcategory: "Fragrance",
    sectionId: "perfumes-fine-fragrances",
    sectionTitle: "Perfumes & Fine Fragrances",
    description: "Sweet boozy oriental fragrance with cinnamon, dates, praline, vanilla, and tonka in a crystal glass bottle.",
    tags: ["lattafa", "khamrah", "arabian-perfume", "gourmand", "viral"],
    badge: "POPULAR",
  },
  {
    id: "ajmal-aristocrat-perfume-for-her",
    name: "Aristocrat Femme Eau de Parfum",
    brand: "Ajmal",
    subcategory: "Fragrance",
    sectionId: "perfumes-fine-fragrances",
    sectionTitle: "Perfumes & Fine Fragrances",
    description: "Rich amber floral fragrance combining saffron, tagetes, jasmine, ambergris, and mossy oak.",
    tags: ["ajmal", "aristocrat", "perfume", "oriental"],
  },
  {
    id: "signature-perfume",
    name: "Signature Perfume",
    brand: "Plugd Fragrance",
    subcategory: "Fragrance",
    sectionId: "perfumes-fine-fragrances",
    sectionTitle: "Perfumes & Fine Fragrances",
    description: "A premium scent creators love to wishlist and share for signature personal aura.",
    tags: ["perfume", "fragrance", "scent"],
  },
  {
    id: "scented-candle",
    name: "Scented Luxury Candle",
    brand: "Plugd Home",
    subcategory: "Bath & Body",
    sectionId: "body-mists-bath-indulgence",
    sectionTitle: "Body Mists & Indulgent Bath",
    description: "Soy wax scented candle with natural essential oils to set a calming mood for self-care routines.",
    tags: ["candle", "scented", "aromatherapy", "bath"],
  },

  // === EXISTING Bath & Body & Indian Heritage ===
  {
    id: "sol-de-janeiro-brazilian-bum-bum-cream",
    name: "Brazilian Bum Bum Body Cream",
    brand: "Sol de Janeiro",
    subcategory: "Bath & Body",
    sectionId: "body-mists-bath-indulgence",
    sectionTitle: "Body Mists & Indulgent Bath",
    description: "Fast-absorbing body cream infused with caffeine-rich Guaraná extract, cupuaçu butter, and iconic Cheirosa '62 pistachio scent.",
    tags: ["sol-de-janeiro", "bum-bum-cream", "body-cream", "pistachio", "viral", "trending"],
    badge: "VIRAL",
    featured: true,
    trending: true,
  },
  {
    id: "tree-hut-shea-sugar-scrub-moroccan-rose",
    name: "Moroccan Rose Shea Sugar Body Scrub",
    brand: "Tree Hut",
    subcategory: "Bath & Body",
    sectionId: "body-mists-bath-indulgence",
    sectionTitle: "Body Mists & Indulgent Bath",
    description: "Real sugar crystals with certified organic shea butter, Moroccan argan oil, and rosehip oil for satin smooth skin.",
    tags: ["tree-hut", "body-scrub", "exfoliator", "sugar-scrub", "bath"],
    badge: "BESTSELLER",
  },
  {
    id: "bath-and-body-works-japanese-cherry-blossom",
    name: "Japanese Cherry Blossom Ultimate Hydration Body Cream",
    brand: "Bath & Body Works",
    subcategory: "Bath & Body",
    sectionId: "body-mists-bath-indulgence",
    sectionTitle: "Body Mists & Indulgent Bath",
    description: "Rich 24-hour hydration body cream with hyaluronic acid and shea butter in the classic cherry blossom floral fragrance.",
    tags: ["bath-and-body-works", "body-lotion", "cherry-blossom", "hydration"],
  },
  {
    id: "forest-essentials-soundarya-radiance-cream",
    name: "Soundarya Radiance Cream with 24K Gold & SPF 25",
    brand: "Forest Essentials",
    subcategory: "Indian Beauty",
    sectionId: "indian-heritage-ayurvedic",
    sectionTitle: "Indian Heritage & Ayurvedic Beauty",
    description: "Traditional Ayurvedic formulation infused with pure 24 Karat gold Bhasma, saffron, and cold-pressed oils for youthful radiance.",
    tags: ["forest-essentials", "soundarya", "gold-cream", "ayurveda", "luxury-ayurveda", "indian-beauty"],
    badge: "PREMIUM",
    featured: true,
  },
  {
    id: "kama-ayurveda-kumkumadi-beauty-fluid",
    name: "Kumkumadi Miraculous Beauty Ayurvedic Night Fluid",
    brand: "Kama Ayurveda",
    subcategory: "Indian Beauty",
    sectionId: "indian-heritage-ayurvedic",
    sectionTitle: "Indian Heritage & Ayurvedic Beauty",
    description: "Rare Kashmiri saffron and lotus extracts formulated according to ancient Ayurvedic texts for blemish-free bright skin.",
    tags: ["kama-ayurveda", "kumkumadi", "face-oil", "ayurveda", "saffron"],
    badge: "POPULAR",
  },
  {
    id: "plum-green-tea-pore-cleansing-face-wash",
    name: "Green Tea Pore Cleansing Face Wash",
    brand: "Plum",
    subcategory: "Skincare",
    sectionId: "indian-heritage-ayurvedic",
    sectionTitle: "Indian Heritage & Ayurvedic Beauty",
    description: "Soap-free gentle foaming cleanser with green tea extracts and glycolic acid beads to control excess oil.",
    tags: ["plum", "face-wash", "green-tea", "vegan", "indian-beauty"],
  },

  // === EXISTING Devices & Tools ===
  {
    id: "medicube-age-r-booster-pro",
    name: "Age-R Booster Pro 6-in-1 Smart Glow Device",
    brand: "Medicube",
    subcategory: "Beauty Tools",
    sectionId: "beauty-devices-vanity-tools",
    sectionTitle: "Beauty Devices & Vanity Tools",
    description: "Next-gen Korean aesthetic device with electroporation, microcurrent, EMS, electric needles, LED light therapy, and sonic vibration.",
    tags: ["medicube", "booster-pro", "beauty-device", "k-beauty", "glow", "viral", "trending"],
    badge: "VIRAL",
    featured: true,
    trending: true,
  },
  {
    id: "foreo-luna-4-facial-cleansing-device",
    name: "LUNA 4 Smart Facial Cleansing & Firming Device",
    brand: "Foreo",
    subcategory: "Beauty Tools",
    sectionId: "beauty-devices-vanity-tools",
    sectionTitle: "Beauty Devices & Vanity Tools",
    description: "Ultra-hygienic silicone bristles with T-Sonic pulsations that remove 99% of dirt, oil, and makeup residue.",
    tags: ["foreo", "luna4", "cleansing-brush", "beauty-device"],
    badge: "POPULAR",
  },
  {
    id: "nuface-trinity-microcurrent-device",
    name: "Trinity+ Advanced Facial Toning Device",
    brand: "NuFACE",
    subcategory: "Beauty Tools",
    sectionId: "beauty-devices-vanity-tools",
    sectionTitle: "Beauty Devices & Vanity Tools",
    description: "Clinically tested microcurrent therapy that visibly contours, tones, and tightens facial muscles in 5 minutes.",
    tags: ["nuface", "microcurrent", "anti-aging", "facial-toning", "device"],
    badge: "PREMIUM",
  },
  {
    id: "rose-quartz-gua-sha-facial-roller-set",
    name: "Natural Rose Quartz Gua Sha & Facial Roller Set",
    brand: "Dermoora",
    subcategory: "Beauty Tools",
    sectionId: "beauty-devices-vanity-tools",
    sectionTitle: "Beauty Devices & Vanity Tools",
    description: "Authentic 100% natural Brazilian rose quartz stone for lymphatic drainage, de-puffing, and jawline sculpting.",
    tags: ["gua-sha", "face-roller", "rose-quartz", "lymphatic-drainage"],
    badge: "POPULAR",
  },
  {
    id: "led-light-therapy-face-mask",
    name: "7-Color LED Photon Light Therapy Face Mask",
    brand: "CurrentBody",
    subcategory: "Beauty Tools",
    sectionId: "beauty-devices-vanity-tools",
    sectionTitle: "Beauty Devices & Vanity Tools",
    description: "Flexible medical-grade silicone mask emitting red, near-infrared, and blue LED wavelengths for collagen production and acne clearing.",
    tags: ["led-mask", "light-therapy", "anti-aging", "skincare-tech"],
    badge: "HOT",
  },

  // === EXISTING Men's Grooming ===
  {
    id: "philips-oneblade-pro-face-and-body",
    name: "OneBlade Pro 360 Face & Body Trimmer",
    brand: "Philips",
    subcategory: "Men's Grooming",
    sectionId: "mens-grooming-beard",
    sectionTitle: "Men's Grooming & Beard Care",
    description: "Revolutionary dual-sided 360 blade that trims, edges, and shaves any length of hair with digital LED battery display.",
    tags: ["philips", "oneblade", "trimmer", "shaver", "mens-grooming", "bestseller"],
    badge: "BESTSELLER",
    featured: true,
  },
  {
    id: "beardo-godfather-beard-oil",
    name: "Godfather Beard Growth & Nourishing Oil",
    brand: "Beardo",
    subcategory: "Men's Grooming",
    sectionId: "mens-grooming-beard",
    sectionTitle: "Men's Grooming & Beard Care",
    description: "Mineral-rich blend of almond and castor oils with Vitamin E that promotes fuller beard growth and tames flyaways.",
    tags: ["beardo", "beard-oil", "mens-grooming", "beard-care"],
  },
  {
    id: "bombay-shaving-company-precision-safety-razor",
    name: "Precision Metal Safety Razor Kit",
    brand: "Bombay Shaving Company",
    subcategory: "Men's Grooming",
    sectionId: "mens-grooming-beard",
    sectionTitle: "Men's Grooming & Beard Care",
    description: "Heavyweight chrome metal safety razor engineered for single-stroke irritation-free close shaves.",
    tags: ["bombay-shaving-company", "razor", "shaving", "mens-grooming"],
  },
  {
    id: "minimalist-male-skincare-daily-duo",
    name: "Daily Men's Face Wash & SPF Moisturizer Set",
    brand: "Minimalist",
    subcategory: "Men's Grooming",
    sectionId: "mens-grooming-beard",
    sectionTitle: "Men's Grooming & Beard Care",
    description: "Salicylic acid cleanser with oil-free niacinamide sunscreen moisturizer tailored for active men.",
    tags: ["minimalist", "men-skincare", "spf", "face-wash"],
  },

  // === EXISTING Luxury & Gift Sets ===
  {
    id: "charlotte-tilbury-magic-cream",
    name: "Charlotte's Magic Cream Plumping Moisturizer",
    brand: "Charlotte Tilbury",
    subcategory: "Luxury Beauty",
    sectionId: "luxury-beauty-gift-sets",
    sectionTitle: "Luxury Beauty & Gift Sets",
    description: "Award-winning backstage moisturizer with Bionymph Peptide and hyaluronic acid that transforms tired skin in 28 seconds.",
    tags: ["charlotte-tilbury", "magic-cream", "moisturizer", "luxury", "glow"],
    badge: "PREMIUM",
    featured: true,
  },
  {
    id: "estee-lauder-advanced-night-repair-serum",
    name: "Advanced Night Repair Synchronized Multi-Recovery",
    brand: "Estée Lauder",
    subcategory: "Luxury Beauty",
    sectionId: "luxury-beauty-gift-sets",
    sectionTitle: "Luxury Beauty & Gift Sets",
    description: "Chronolux Power Signal Technology night serum that fights multiple signs of aging and delivers 72-hour moisture.",
    tags: ["estee-lauder", "advanced-night-repair", "serum", "luxury", "bestseller"],
    badge: "PREMIUM",
    featured: true,
  },
  {
    id: "jo-malone-english-pear-and-freesia-cologne",
    name: "English Pear & Freesia Cologne",
    brand: "Jo Malone",
    subcategory: "Luxury Beauty",
    sectionId: "luxury-beauty-gift-sets",
    sectionTitle: "Luxury Beauty & Gift Sets",
    description: "Sensuous freshness of just-ripe King William pears wrapped in a bouquet of white freesias and mellowed by amber and patchouli.",
    tags: ["jo-malone", "english-pear", "cologne", "luxury", "gift"],
    badge: "PREMIUM",
  },
  {
    id: "laneige-midnight-minis-lip-mask-set",
    name: "Midnight Minis 5-Piece Lip Sleeping Mask Set",
    brand: "Laneige",
    subcategory: "Gift Sets",
    sectionId: "luxury-beauty-gift-sets",
    sectionTitle: "Luxury Beauty & Gift Sets",
    description: "Holiday limited-edition collection of five travel-size Lip Sleeping Masks including Berry, Gummy Bear, and Sweet Candy.",
    tags: ["laneige", "lip-set", "gift-set", "k-beauty", "minis", "viral"],
    badge: "VIRAL",
    featured: true,
  },
  
  // === NEW Makeup ===
  {
    id: "maybelline-vinyl-ink",
    name: "SuperStay Vinyl Ink Liquid Lipcolor",
    brand: "Maybelline",
    subcategory: "Makeup",
    sectionId: "lip-favorites-oils-tints",
    sectionTitle: "Lip Favorites: Oils, Tints & Plumpers",
    description: "High-shine longwear vinyl lip color with 16-hour fade-proof and transfer-proof formula.",
    tags: ["maybelline", "vinyl-ink", "lipstick", "liquid-lip", "makeup"],
    badge: "POPULAR",
  },
  {
    id: "maybelline-superstay-matte-ink",
    name: "SuperStay Matte Ink Liquid Lipstick",
    brand: "Maybelline",
    subcategory: "Makeup",
    sectionId: "lip-favorites-oils-tints",
    sectionTitle: "Lip Favorites: Oils, Tints & Plumpers",
    description: "Ultra-pigmented 16-hour wear matte liquid lipstick with precision arrow applicator.",
    tags: ["maybelline", "matte-ink", "lipstick", "longwear"],
    badge: "BESTSELLER",
  },
  {
    id: "maybelline-fit-me-foundation",
    name: "Fit Me Matte + Poreless Foundation",
    brand: "Maybelline",
    subcategory: "Makeup",
    sectionId: "makeup-face-base",
    sectionTitle: "Makeup Obsession: Face & Base",
    description: "Lightweight foundation with micro-powders that blur pores and control shine in 40+ shades for Indian skin tones.",
    tags: ["maybelline", "fit-me", "foundation", "matte", "base"],
    badge: "BESTSELLER",
  },
  {
    id: "maybelline-fit-me-concealer",
    name: "Fit Me Liquid Concealer",
    brand: "Maybelline",
    subcategory: "Makeup",
    sectionId: "makeup-face-base",
    sectionTitle: "Makeup Obsession: Face & Base",
    description: "Oil-free concealer providing natural, light-to-medium coverage with a non-cakey finish.",
    tags: ["maybelline", "fit-me", "concealer", "makeup"],
  },
  {
    id: "maybelline-sky-high-mascara",
    name: "Sky High Waterproof Mascara",
    brand: "Maybelline",
    subcategory: "Makeup",
    sectionId: "eye-drama-lashes",
    sectionTitle: "Eye Drama, Brows & Lashes",
    description: "Flex Tower mascara wand with bamboo extract fiber formula for volumized, lengthened lashes.",
    tags: ["maybelline", "mascara", "sky-high", "waterproof", "lashes"],
    badge: "VIRAL",
  },
  {
    id: "maybelline-colossal-kajal",
    name: "The Colossal Kajal 24HR",
    brand: "Maybelline",
    subcategory: "Makeup",
    sectionId: "eye-drama-lashes",
    sectionTitle: "Eye Drama, Brows & Lashes",
    description: "India's iconic 24-hour smudge-proof kajal with intense black pigment.",
    tags: ["maybelline", "kajal", "colossal", "eye", "indian-beauty"],
    badge: "BESTSELLER",
  },
  {
    id: "loreal-infallible-foundation",
    name: "Infallible 24H Fresh Wear Foundation",
    brand: "L'Oréal",
    subcategory: "Makeup",
    sectionId: "makeup-face-base",
    sectionTitle: "Makeup Obsession: Face & Base",
    description: "Breathable full-coverage foundation with 24-hour longwear in waterproof, sweatproof formula.",
    tags: ["loreal", "infallible", "foundation", "full-coverage"],
    badge: "POPULAR",
  },
  {
    id: "loreal-true-match-foundation",
    name: "True Match Super-Blendable Foundation",
    brand: "L'Oréal",
    subcategory: "Makeup",
    sectionId: "makeup-face-base",
    sectionTitle: "Makeup Obsession: Face & Base",
    description: "Skincare-infused foundation with hyaluronic acid matching skin's tone, texture, and undertone.",
    tags: ["loreal", "true-match", "foundation", "hydrating"],
  },
  {
    id: "loreal-panorama-mascara",
    name: "Panorama Volumising Mascara",
    brand: "L'Oréal",
    subcategory: "Makeup",
    sectionId: "eye-drama-lashes",
    sectionTitle: "Eye Drama, Brows & Lashes",
    description: "Panoramic fan-effect brush delivering 360° volume and defined separation to every lash.",
    tags: ["loreal", "panorama", "mascara", "volume", "lashes"],
  },
  {
    id: "loreal-infallible-setting-spray",
    name: "Infallible 3-Second Setting Spray",
    brand: "L'Oréal",
    subcategory: "Makeup",
    sectionId: "makeup-face-base",
    sectionTitle: "Makeup Obsession: Face & Base",
    description: "Micro-fine mist that locks makeup in place all day with a luminous, natural finish.",
    tags: ["loreal", "infallible", "setting-spray", "longwear"],
  },
  {
    id: "lakme-9to5-primer-matte",
    name: "9 to 5 Primer + Matte Foundation",
    brand: "Lakmé",
    subcategory: "Makeup",
    sectionId: "makeup-face-base",
    sectionTitle: "Makeup Obsession: Face & Base",
    description: "Built-in primer foundation with 12-hour oil control and silky matte finish for Indian skin.",
    tags: ["lakme", "9to5", "foundation", "primer", "matte", "indian-beauty"],
    badge: "POPULAR",
  },
  {
    id: "lakme-9to5-mousse",
    name: "9 to 5 Weightless Matte Mousse",
    brand: "Lakmé",
    subcategory: "Makeup",
    sectionId: "makeup-face-base",
    sectionTitle: "Makeup Obsession: Face & Base",
    description: "Ultra-light mousse-based foundation with breathable matte coverage.",
    tags: ["lakme", "mousse", "foundation", "matte"],
  },
  {
    id: "lakme-eyeconic-kajal",
    name: "Eyeconic Waterproof Kajal",
    brand: "Lakmé",
    subcategory: "Makeup",
    sectionId: "eye-drama-lashes",
    sectionTitle: "Eye Drama, Brows & Lashes",
    description: "Dermatologically-tested kajal enriched with Vitamin B3 for intense black definition.",
    tags: ["lakme", "eyeconic", "kajal", "waterproof", "indian-beauty"],
    badge: "BESTSELLER",
  },
  {
    id: "lakme-eyeconic-curling-mascara",
    name: "Eyeconic Curling Mascara",
    brand: "Lakmé",
    subcategory: "Makeup",
    sectionId: "eye-drama-lashes",
    sectionTitle: "Eye Drama, Brows & Lashes",
    description: "Specially curved brush that lifts and curls lashes with smudge-proof formula.",
    tags: ["lakme", "eyeconic", "mascara", "curling"],
  },
  {
    id: "kay-beauty-foundation",
    name: "Hydrating Full Coverage Foundation",
    brand: "Kay Beauty",
    subcategory: "Makeup",
    sectionId: "makeup-face-base",
    sectionTitle: "Makeup Obsession: Face & Base",
    description: "Buildable hydrating foundation with hyaluronic acid tailored for Indian skin tones.",
    tags: ["kay-beauty", "foundation", "hydrating", "indian-beauty"],
  },
  {
    id: "kay-beauty-hd-concealer",
    name: "HD Liquid Concealer",
    brand: "Kay Beauty",
    subcategory: "Makeup",
    sectionId: "makeup-face-base",
    sectionTitle: "Makeup Obsession: Face & Base",
    description: "Lightweight full-coverage concealer with blur technology for flawless undereye coverage.",
    tags: ["kay-beauty", "concealer", "hd", "indian-beauty"],
  },
  {
    id: "kay-beauty-creme-blush",
    name: "Crème Blush Stick",
    brand: "Kay Beauty",
    subcategory: "Makeup",
    sectionId: "makeup-face-base",
    sectionTitle: "Makeup Obsession: Face & Base",
    description: "Creamy multi-use blush stick with vitamin E for a natural dewy flush on cheeks and lips.",
    tags: ["kay-beauty", "blush", "creme", "stick", "indian-beauty"],
    badge: "POPULAR",
  },
  {
    id: "elf-halo-glow",
    name: "Halo Glow Liquid Filter",
    brand: "e.l.f.",
    subcategory: "Makeup",
    sectionId: "makeup-face-base",
    sectionTitle: "Makeup Obsession: Face & Base",
    description: "Complexion booster with squalane and hyaluronic acid for a soft-focus, luminous Hollywood glow.",
    tags: ["elf", "halo-glow", "primer", "luminous", "viral"],
    badge: "VIRAL",
    featured: true,
  },
  {
    id: "elf-camo-concealer",
    name: "16HR Camo Concealer",
    brand: "e.l.f.",
    subcategory: "Makeup",
    sectionId: "makeup-face-base",
    sectionTitle: "Makeup Obsession: Face & Base",
    description: "Ultra-pigmented full-coverage concealer with avocado oil that lasts all day without creasing.",
    tags: ["elf", "camo", "concealer", "full-coverage"],
    badge: "POPULAR",
  },
  {
    id: "elf-power-grip-primer",
    name: "Power Grip Primer",
    brand: "e.l.f.",
    subcategory: "Makeup",
    sectionId: "makeup-face-base",
    sectionTitle: "Makeup Obsession: Face & Base",
    description: "Gel-based gripping primer with 4% Niacinamide that holds makeup in place for 12+ hours.",
    tags: ["elf", "power-grip", "primer", "gel", "viral"],
    badge: "VIRAL",
  },
  {
    id: "rare-beauty-positive-light-highlighter",
    name: "Positive Light Liquid Luminizer",
    brand: "Rare Beauty",
    subcategory: "Makeup",
    sectionId: "makeup-face-base",
    sectionTitle: "Makeup Obsession: Face & Base",
    description: "Weightless buildable liquid highlighter that melts into skin for an ethereal lit-from-within glow.",
    tags: ["rare-beauty", "highlighter", "luminizer", "glow"],
    badge: "VIRAL",
  },
  {
    id: "charlotte-tilbury-pillow-talk-lipstick",
    name: "Matte Revolution Lipstick - Pillow Talk",
    brand: "Charlotte Tilbury",
    subcategory: "Makeup",
    sectionId: "lip-favorites-oils-tints",
    sectionTitle: "Lip Favorites: Oils, Tints & Plumpers",
    description: "Iconic universally flattering nude-pink matte lipstick with 3D lip-plumping pigments.",
    tags: ["charlotte-tilbury", "pillow-talk", "lipstick", "matte", "luxury"],
    badge: "VIRAL",
    featured: true,
  },
  {
    id: "fenty-beauty-pro-filtr-foundation",
    name: "Pro Filt'r Soft Matte Longwear Foundation",
    brand: "Fenty Beauty",
    subcategory: "Makeup",
    sectionId: "makeup-face-base",
    sectionTitle: "Makeup Obsession: Face & Base",
    description: "Climate-adaptive oil-free foundation in 50 shades with pore-diffusing technology and 12-hour wear.",
    tags: ["fenty", "pro-filtr", "foundation", "matte", "inclusive"],
    badge: "POPULAR",
  },
  {
    id: "mac-ruby-woo",
    name: "Retro Matte Lipstick - Ruby Woo",
    brand: "MAC",
    subcategory: "Makeup",
    sectionId: "lip-favorites-oils-tints",
    sectionTitle: "Lip Favorites: Oils, Tints & Plumpers",
    description: "The world's best-selling red lipstick with vivid blue-red pigment and retro matte finish.",
    tags: ["mac", "ruby-woo", "red-lipstick", "matte", "iconic"],
    badge: "BESTSELLER",
    featured: true,
  },
  {
    id: "mac-fix-plus",
    name: "Fix+ Magic Radiance Setting Spray",
    brand: "MAC",
    subcategory: "Makeup",
    sectionId: "makeup-face-base",
    sectionTitle: "Makeup Obsession: Face & Base",
    description: "Lightweight setting mist with vitamins and minerals that refreshes and sets makeup with a radiant finish.",
    tags: ["mac", "fix-plus", "setting-spray", "radiant"],
    badge: "POPULAR",
  },
  {
    id: "huda-beauty-liquid-matte",
    name: "Liquid Matte Lipstick",
    brand: "Huda Beauty",
    subcategory: "Makeup",
    sectionId: "lip-favorites-oils-tints",
    sectionTitle: "Lip Favorites: Oils, Tints & Plumpers",
    description: "Transfer-proof matte liquid lipstick with intense pigmentation and comfortable all-day wear.",
    tags: ["huda-beauty", "liquid-matte", "lipstick", "longwear"],
    badge: "POPULAR",
  },
  {
    id: "nyx-butter-gloss",
    name: "Butter Gloss",
    brand: "NYX",
    subcategory: "Makeup",
    sectionId: "lip-favorites-oils-tints",
    sectionTitle: "Lip Favorites: Oils, Tints & Plumpers",
    description: "Silky-smooth non-sticky lip gloss with sheer-to-medium coverage and delicious buttery vanilla scent.",
    tags: ["nyx", "butter-gloss", "lip-gloss", "affordable"],
    badge: "BESTSELLER",
  },
  {
    id: "nyx-fat-oil-lip-drip",
    name: "Fat Oil Lip Drip",
    brand: "NYX",
    subcategory: "Makeup",
    sectionId: "lip-favorites-oils-tints",
    sectionTitle: "Lip Favorites: Oils, Tints & Plumpers",
    description: "Nourishing lip oil with vegan squalane delivering high-shine and hydrating lip color.",
    tags: ["nyx", "fat-oil", "lip-oil", "hydrating", "viral"],
    badge: "VIRAL",
  },
  {
    id: "benefit-benetint",
    name: "Benetint Rose Lip & Cheek Tint",
    brand: "Benefit",
    subcategory: "Makeup",
    sectionId: "makeup-face-base",
    sectionTitle: "Makeup Obsession: Face & Base",
    description: "Iconic sheer rose-tinted stain for cheeks and lips with buildable natural flush.",
    tags: ["benefit", "benetint", "tint", "cheek", "lip"],
    badge: "POPULAR",
  },
  {
    id: "benefit-roller-lash",
    name: "Roller Lash Curling Mascara",
    brand: "Benefit",
    subcategory: "Makeup",
    sectionId: "eye-drama-lashes",
    sectionTitle: "Eye Drama, Brows & Lashes",
    description: "Hook 'n' Roll brush that grabs, separates, and curls lashes for a super curled lift.",
    tags: ["benefit", "roller-lash", "mascara", "curling"],
    badge: "POPULAR",
  },

  // === NEW Skincare ===
  {
    id: "cerave-moisturizing-cream",
    name: "Moisturizing Cream with Ceramides",
    brand: "CeraVe",
    subcategory: "Skincare",
    sectionId: "skincare-actives-serums",
    sectionTitle: "Skincare Essentials: Actives & Serums",
    description: "Rich moisturizer with 3 essential ceramides and MVE technology for 24-hour hydration.",
    tags: ["cerave", "moisturizer", "ceramides", "hydration"],
    badge: "BESTSELLER",
  },
  {
    id: "cerave-foaming-cleanser",
    name: "Foaming Facial Cleanser",
    brand: "CeraVe",
    subcategory: "Skincare",
    sectionId: "skincare-actives-serums",
    sectionTitle: "Skincare Essentials: Actives & Serums",
    description: "Gel-to-foam cleanser with hyaluronic acid and niacinamide for normal-to-oily skin.",
    tags: ["cerave", "cleanser", "foaming", "oily-skin"],
  },
  {
    id: "cerave-sa-cleanser",
    name: "SA Smoothing Cleanser with Salicylic Acid",
    brand: "CeraVe",
    subcategory: "Skincare",
    sectionId: "skincare-actives-serums",
    sectionTitle: "Skincare Essentials: Actives & Serums",
    description: "Exfoliating cleanser with salicylic acid and ceramides for bumpy and rough skin.",
    tags: ["cerave", "sa", "salicylic-acid", "exfoliant"],
  },
  {
    id: "cetaphil-gentle-cleanser",
    name: "Gentle Skin Cleanser",
    brand: "Cetaphil",
    subcategory: "Skincare",
    sectionId: "skincare-actives-serums",
    sectionTitle: "Skincare Essentials: Actives & Serums",
    description: "Ultra-gentle non-foaming cleanser that removes dirt and makeup without stripping moisture.",
    tags: ["cetaphil", "cleanser", "gentle", "sensitive-skin"],
    badge: "BESTSELLER",
  },
  {
    id: "cetaphil-moisturizing-lotion",
    name: "Daily Hydrating Lotion",
    brand: "Cetaphil",
    subcategory: "Skincare",
    sectionId: "skincare-actives-serums",
    sectionTitle: "Skincare Essentials: Actives & Serums",
    description: "Lightweight daily moisturizer with hyaluronic acid for 48-hour hydration.",
    tags: ["cetaphil", "lotion", "moisturizer", "hydrating"],
  },
  {
    id: "the-ordinary-niacinamide",
    name: "Niacinamide 10% + Zinc 1%",
    brand: "The Ordinary",
    subcategory: "Skincare",
    sectionId: "skincare-actives-serums",
    sectionTitle: "Skincare Essentials: Actives & Serums",
    description: "High-strength niacinamide serum that targets blemishes, uneven skin tone, and enlarged pores.",
    tags: ["the-ordinary", "niacinamide", "serum", "pores", "viral"],
    badge: "VIRAL",
    featured: true,
  },
  {
    id: "the-ordinary-aha-bha-peel",
    name: "AHA 30% + BHA 2% Exfoliating Solution",
    brand: "The Ordinary",
    subcategory: "Skincare",
    sectionId: "skincare-actives-serums",
    sectionTitle: "Skincare Essentials: Actives & Serums",
    description: "10-minute exfoliating treatment for improved skin radiance and textural irregularities.",
    tags: ["the-ordinary", "aha", "bha", "peel", "exfoliant"],
    badge: "POPULAR",
  },
  {
    id: "the-ordinary-hyaluronic-acid",
    name: "Hyaluronic Acid 2% + B5",
    brand: "The Ordinary",
    subcategory: "Skincare",
    sectionId: "skincare-actives-serums",
    sectionTitle: "Skincare Essentials: Actives & Serums",
    description: "Multi-depth hyaluronic acid complex with vitamin B5 for deep hydration at every skin layer.",
    tags: ["the-ordinary", "hyaluronic-acid", "hydration", "serum"],
  },
  {
    id: "minimalist-salicylic-acid-cleanser",
    name: "2% Salicylic Acid Face Wash",
    brand: "Minimalist",
    subcategory: "Skincare",
    sectionId: "skincare-actives-serums",
    sectionTitle: "Skincare Essentials: Actives & Serums",
    description: "Gentle foaming cleanser with LHA that deep cleans pores and controls active acne.",
    tags: ["minimalist", "salicylic-acid", "cleanser", "acne"],
  },
  {
    id: "minimalist-vitamin-c-serum",
    name: "10% Vitamin C + AG5 Brightening Serum",
    brand: "Minimalist",
    subcategory: "Skincare",
    sectionId: "skincare-actives-serums",
    sectionTitle: "Skincare Essentials: Actives & Serums",
    description: "Stable vitamin C serum with 5th-generation vitamin C derivative for brightening and anti-aging.",
    tags: ["minimalist", "vitamin-c", "serum", "brightening", "indian-beauty"],
    badge: "POPULAR",
  },
  {
    id: "dot-key-vitamin-c-serum",
    name: "Vitamin C + E Super Bright Serum",
    brand: "Dot & Key",
    subcategory: "Skincare",
    sectionId: "skincare-actives-serums",
    sectionTitle: "Skincare Essentials: Actives & Serums",
    description: "Ethyl ascorbic acid serum with vitamin E for stubborn dark spots and uneven skin tone.",
    tags: ["dot-and-key", "vitamin-c", "serum", "brightening"],
  },
  {
    id: "dot-key-barrier-repair-cream",
    name: "Barrier Repair Hydrating Cream",
    brand: "Dot & Key",
    subcategory: "Skincare",
    sectionId: "skincare-actives-serums",
    sectionTitle: "Skincare Essentials: Actives & Serums",
    description: "Ceramide-rich barrier repair moisturizer with probiotics for strengthening sensitive skin.",
    tags: ["dot-and-key", "barrier-repair", "cream", "ceramides"],
  },
  {
    id: "plum-niacinamide-serum",
    name: "10% Niacinamide Face Serum",
    brand: "Plum",
    subcategory: "Skincare",
    sectionId: "skincare-actives-serums",
    sectionTitle: "Skincare Essentials: Actives & Serums",
    description: "Vegan niacinamide serum with rice water that reduces pores, blemishes, and oil production.",
    tags: ["plum", "niacinamide", "serum", "vegan", "indian-beauty"],
  },
  {
    id: "plum-vitamin-c-moisturizer",
    name: "Vitamin C Moisturizer with SPF 35",
    brand: "Plum",
    subcategory: "Skincare",
    sectionId: "skincare-actives-serums",
    sectionTitle: "Skincare Essentials: Actives & Serums",
    description: "Brightening moisturizer with UV protection for a daily sun-safe glow routine.",
    tags: ["plum", "vitamin-c", "moisturizer", "spf", "indian-beauty"],
  },
  {
    id: "deconstruct-retinol-serum",
    name: "0.5% Retinol + Peptide Anti-Aging Serum",
    brand: "Deconstruct",
    subcategory: "Skincare",
    sectionId: "skincare-actives-serums",
    sectionTitle: "Skincare Essentials: Actives & Serums",
    description: "Encapsulated retinol with pentapeptides for fine lines without irritation.",
    tags: ["deconstruct", "retinol", "anti-aging", "serum", "indian-beauty"],
  },
  {
    id: "deconstruct-aha-exfoliant",
    name: "5% AHA + 1% BHA Exfoliating Serum",
    brand: "Deconstruct",
    subcategory: "Skincare",
    sectionId: "skincare-actives-serums",
    sectionTitle: "Skincare Essentials: Actives & Serums",
    description: "Chemical exfoliant with glycolic acid and salicylic acid for smoother, brighter skin.",
    tags: ["deconstruct", "aha", "bha", "exfoliant", "indian-beauty"],
  },
  {
    id: "cosrx-bha-blackhead-power-liquid",
    name: "BHA Blackhead Power Liquid",
    brand: "COSRX",
    subcategory: "K-Beauty",
    sectionId: "k-beauty-cult-favorites",
    sectionTitle: "K-Beauty Cult Favorites (COSRX, Laneige, Joseon)",
    description: "Gentle betaine salicylate blackhead solution that clears pores without over-drying sensitive skin.",
    tags: ["cosrx", "bha", "blackhead", "pores", "k-beauty"],
    badge: "POPULAR",
  },
  {
    id: "cosrx-aloe-soothing-sun-cream",
    name: "Aloe Soothing Sun Cream SPF 50+",
    brand: "COSRX",
    subcategory: "Sun Care",
    sectionId: "sun-care-spf-shields",
    sectionTitle: "Sun Care & Daily SPF Shields",
    description: "Calming aloe-infused sunscreen with lightweight texture and no white cast.",
    tags: ["cosrx", "sunscreen", "aloe", "k-beauty"],
  },
  {
    id: "laneige-water-sleeping-mask",
    name: "Water Sleeping Mask",
    brand: "Laneige",
    subcategory: "K-Beauty",
    sectionId: "k-beauty-cult-favorites",
    sectionTitle: "K-Beauty Cult Favorites (COSRX, Laneige, Joseon)",
    description: "Overnight sleeping mask with Sleep-tox purifying technology and CICA for refreshed morning skin.",
    tags: ["laneige", "sleeping-mask", "overnight", "k-beauty", "hydration"],
    badge: "POPULAR",
  },
  {
    id: "clinique-moisture-surge",
    name: "Moisture Surge 100H Auto-Replenishing Hydrator",
    brand: "Clinique",
    subcategory: "Skincare",
    sectionId: "skincare-actives-serums",
    sectionTitle: "Skincare Essentials: Actives & Serums",
    description: "Oil-free gel-cream with aloe bioferment and hyaluronic acid providing 100 hours of hydration.",
    tags: ["clinique", "moisture-surge", "hydrator", "gel-cream", "luxury"],
    badge: "POPULAR",
  },
  {
    id: "clinique-dramatically-different",
    name: "Dramatically Different Moisturizing Lotion+",
    brand: "Clinique",
    subcategory: "Skincare",
    sectionId: "skincare-actives-serums",
    sectionTitle: "Skincare Essentials: Actives & Serums",
    description: "Dermatologist-developed moisturizer that strengthens skin barrier with 8-hour hydration.",
    tags: ["clinique", "moisturizer", "barrier", "classic"],
  },
  {
    id: "estee-lauder-double-wear",
    name: "Double Wear Stay-in-Place Foundation",
    brand: "Estée Lauder",
    subcategory: "Makeup",
    sectionId: "makeup-face-base",
    sectionTitle: "Makeup Obsession: Face & Base",
    description: "24-hour wear buildable medium-to-full coverage foundation that is waterproof and flawless in 60+ shades.",
    tags: ["estee-lauder", "double-wear", "foundation", "longwear", "luxury"],
    badge: "PREMIUM",
  },

  // === NEW Lip Products ===
  {
    id: "dior-lip-maximizer",
    name: "Dior Addict Lip Maximizer Plumping Gloss",
    brand: "Dior",
    subcategory: "Lip Care",
    sectionId: "lip-favorites-oils-tints",
    sectionTitle: "Lip Favorites: Oils, Tints & Plumpers",
    description: "Volumizing lip gloss with hyaluronic acid and marine collagen for instant plumping effect.",
    tags: ["dior", "lip-maximizer", "plumping", "gloss", "luxury"],
    badge: "VIRAL",
    featured: true,
  },
  {
    id: "rhode-peptide-lip-treatment",
    name: "Peptide Lip Treatment",
    brand: "Rhode",
    subcategory: "Lip Care",
    sectionId: "lip-favorites-oils-tints",
    sectionTitle: "Lip Favorites: Oils, Tints & Plumpers",
    description: "Peptide-powered lip treatment with shea butter and babassu providing glossy nourished lips.",
    tags: ["rhode", "peptide", "lip-treatment", "hailey-bieber", "viral"],
    badge: "VIRAL",
    featured: true,
    trending: true,
  },
  {
    id: "summer-fridays-lip-butter-balm",
    name: "Lip Butter Balm",
    brand: "Summer Fridays",
    subcategory: "Lip Care",
    sectionId: "lip-favorites-oils-tints",
    sectionTitle: "Lip Favorites: Oils, Tints & Plumpers",
    description: "Vegan lip balm with shea and murumuru butters for a buttery-soft, glossy, hydrated finish.",
    tags: ["summer-fridays", "lip-butter", "balm", "vegan", "viral"],
    badge: "VIRAL",
  },
  {
    id: "mac-lipstick-velvet-teddy",
    name: "Matte Lipstick - Velvet Teddy",
    brand: "MAC",
    subcategory: "Makeup",
    sectionId: "lip-favorites-oils-tints",
    sectionTitle: "Lip Favorites: Oils, Tints & Plumpers",
    description: "Deep-tone beige matte lipstick that flatters every skin tone with comfortable wear.",
    tags: ["mac", "velvet-teddy", "nude", "matte", "lipstick"],
    badge: "BESTSELLER",
  },
  {
    id: "rare-beauty-soft-pinch-lip-oil",
    name: "Soft Pinch Tinted Lip Oil",
    brand: "Rare Beauty",
    subcategory: "Lip Care",
    sectionId: "lip-favorites-oils-tints",
    sectionTitle: "Lip Favorites: Oils, Tints & Plumpers",
    description: "Hydrating tinted lip oil with a glossy finish that adds a hint of color and shine.",
    tags: ["rare-beauty", "lip-oil", "tinted", "hydrating"],
    badge: "NEW",
  },
  {
    id: "huda-beauty-lip-liner",
    name: "Lip Contour 2.0 Lip Liner",
    brand: "Huda Beauty",
    subcategory: "Makeup",
    sectionId: "lip-favorites-oils-tints",
    sectionTitle: "Lip Favorites: Oils, Tints & Plumpers",
    description: "Creamy matte lip liner with built-in sharpener for precise definition and overlined lips.",
    tags: ["huda-beauty", "lip-liner", "contour", "matte"],
  },

  // === NEW Haircare ===
  {
    id: "revlon-one-step-volumizer",
    name: "One-Step Volumizer PLUS 2.0 Hair Dryer Brush",
    brand: "Revlon",
    subcategory: "Hair Tools",
    sectionId: "hair-styling-tools",
    sectionTitle: "Hair Styling Tools (Dyson, Shark, Philips)",
    description: "Hot air brush that dries and volumizes in one step with ionic technology for reduced frizz.",
    tags: ["revlon", "one-step", "blow-dry-brush", "volumizer"],
    badge: "POPULAR",
  },
  {
    id: "ghd-platinum-plus-straightener",
    name: "Platinum+ Smart Styler Straightener",
    brand: "GHD",
    subcategory: "Hair Tools",
    sectionId: "hair-styling-tools",
    sectionTitle: "Hair Styling Tools (Dyson, Shark, Philips)",
    description: "Predictive ultra-zone technology that recognizes hair needs and adapts heat for healthier styling.",
    tags: ["ghd", "straightener", "flat-iron", "smart", "premium"],
    badge: "PREMIUM",
  },
  {
    id: "ghd-curve-curling-iron",
    name: "Curve Classic Curl Tong",
    brand: "GHD",
    subcategory: "Hair Tools",
    sectionId: "hair-styling-tools",
    sectionTitle: "Hair Styling Tools (Dyson, Shark, Philips)",
    description: "26mm barrel with ultra-zone predictive technology creating bouncy, long-lasting curls.",
    tags: ["ghd", "curling-iron", "tong", "styling"],
  },
  {
    id: "hair-serum-general",
    name: "Anti-Frizz Hair Serum",
    brand: "L'Oréal",
    subcategory: "Haircare",
    sectionId: "haircare-scalp-revival",
    sectionTitle: "Haircare & Scalp Revival",
    description: "Lightweight smoothing serum with argan oil that tames frizz and adds mirror-like shine.",
    tags: ["loreal", "hair-serum", "anti-frizz", "shine"],
  },
  {
    id: "hair-mask-keratin",
    name: "Keratin Smooth Deep Conditioning Hair Mask",
    brand: "TRESemmé",
    subcategory: "Haircare",
    sectionId: "haircare-scalp-revival",
    sectionTitle: "Haircare & Scalp Revival",
    description: "Salon-grade keratin-infused mask that restores damaged hair and controls frizz for 72 hours.",
    tags: ["tresemme", "hair-mask", "keratin", "repair"],
  },
  {
    id: "heat-protectant-spray",
    name: "Heat Protection Spray",
    brand: "TRESemmé",
    subcategory: "Haircare",
    sectionId: "haircare-scalp-revival",
    sectionTitle: "Haircare & Scalp Revival",
    description: "Lightweight heat protectant that shields hair up to 230°C and adds smoothness and shine.",
    tags: ["tresemme", "heat-protectant", "styling", "hair-care"],
  },
  {
    id: "hair-oil-indulekha",
    name: "Bringha Ayurvedic Hair Oil",
    brand: "Indulekha",
    subcategory: "Haircare",
    sectionId: "haircare-scalp-revival",
    sectionTitle: "Haircare & Scalp Revival",
    description: "Ayurvedic heritage oil with selfie comb applicator that reduces hair fall and promotes growth.",
    tags: ["indulekha", "hair-oil", "ayurvedic", "growth", "indian-beauty"],
    badge: "POPULAR",
  },
  {
    id: "hair-styling-cream",
    name: "Defining Curl Cream",
    brand: "Moroccanoil",
    subcategory: "Haircare",
    sectionId: "haircare-scalp-revival",
    sectionTitle: "Haircare & Scalp Revival",
    description: "Activated argan oil curl cream that defines and hydrates curls without crunch.",
    tags: ["moroccanoil", "curl-cream", "styling", "curly-hair"],
  },

  // === NEW Fragrance ===
  {
    id: "bath-body-works-vanilla-mist",
    name: "A Thousand Wishes Body Mist",
    brand: "Bath & Body Works",
    subcategory: "Bath & Body",
    sectionId: "body-mists-bath-indulgence",
    sectionTitle: "Body Mists & Indulgent Bath",
    description: "Sparkling champagne toast with crystal peonies, gilded amber, and almond crème body mist.",
    tags: ["bath-and-body-works", "body-mist", "vanilla", "sweet"],
    badge: "POPULAR",
  },
  {
    id: "victorias-secret-bombshell-mist",
    name: "Bombshell Fragrance Mist",
    brand: "Victoria's Secret",
    subcategory: "Bath & Body",
    sectionId: "body-mists-bath-indulgence",
    sectionTitle: "Body Mists & Indulgent Bath",
    description: "Iconic purple passionfruit, Shangri-la peony, and vanilla orchid fragrance mist.",
    tags: ["victorias-secret", "bombshell", "body-mist", "floral"],
    badge: "POPULAR",
  },
  {
    id: "zara-red-vanilla",
    name: "Red Vanilla Eau de Toilette",
    brand: "Zara",
    subcategory: "Fragrance",
    sectionId: "perfumes-fine-fragrances",
    sectionTitle: "Perfumes & Fine Fragrances",
    description: "Warm and cozy vanilla fragrance with subtle sweetness perfect for everyday wear.",
    tags: ["zara", "red-vanilla", "perfume", "affordable", "vanilla"],
  },
  {
    id: "zara-rich-warm-addictive",
    name: "Rich Warm Addictive Eau de Parfum",
    brand: "Zara",
    subcategory: "Fragrance",
    sectionId: "perfumes-fine-fragrances",
    sectionTitle: "Perfumes & Fine Fragrances",
    description: "Smoky amber and vanilla EDP that rivals designer fragrances at a fraction of the price.",
    tags: ["zara", "perfume", "amber", "vanilla", "affordable"],
    badge: "TRENDING",
  },
  {
    id: "dior-miss-dior-edp",
    name: "Miss Dior Eau de Parfum",
    brand: "Dior",
    subcategory: "Fragrance",
    sectionId: "perfumes-fine-fragrances",
    sectionTitle: "Perfumes & Fine Fragrances",
    description: "Fresh floral fragrance with Centifolia rose absolute, peony, and iris notes.",
    tags: ["dior", "miss-dior", "perfume", "floral", "luxury"],
    badge: "PREMIUM",
  },
  {
    id: "ariana-grande-cloud-edp",
    name: "Cloud Eau de Parfum",
    brand: "Ariana Grande",
    subcategory: "Fragrance",
    sectionId: "perfumes-fine-fragrances",
    sectionTitle: "Perfumes & Fine Fragrances",
    description: "Dreamy lavender blossom, juicy pear, and coconut cloud of musks for a fantasy aura.",
    tags: ["ariana-grande", "cloud", "perfume", "sweet", "celebrity"],
    badge: "POPULAR",
  },
  {
    id: "kayali-eden-juicy-apple",
    name: "Eden | Juicy Apple 01 Eau de Parfum",
    brand: "Kayali",
    subcategory: "Fragrance",
    sectionId: "perfumes-fine-fragrances",
    sectionTitle: "Perfumes & Fine Fragrances",
    description: "Playful fruity fragrance with green apple, white florals, and creamy sandalwood.",
    tags: ["kayali", "eden", "apple", "perfume", "fruity"],
  },
  {
    id: "jo-malone-wood-sage",
    name: "Wood Sage & Sea Salt Cologne",
    brand: "Jo Malone",
    subcategory: "Luxury Beauty",
    sectionId: "luxury-beauty-gift-sets",
    sectionTitle: "Luxury Beauty & Gift Sets",
    description: "Windswept mineral scent with ambrette seeds and sea salt for an escape to the coast.",
    tags: ["jo-malone", "wood-sage", "cologne", "unisex", "luxury"],
    badge: "PREMIUM",
  },

  // === NEW Bodycare ===
  {
    id: "body-lotion-nivea",
    name: "Nourishing Body Lotion",
    brand: "Nivea",
    subcategory: "Bath & Body",
    sectionId: "bodycare-essentials",
    sectionTitle: "Bodycare Essentials",
    description: "Deep moisture body lotion with almond oil for 48-hour hydration and soft, smooth skin.",
    tags: ["nivea", "body-lotion", "moisturizer", "hydration"],
  },
  {
    id: "body-wash-dove",
    name: "Deeply Nourishing Body Wash",
    brand: "Dove",
    subcategory: "Bath & Body",
    sectionId: "bodycare-essentials",
    sectionTitle: "Bodycare Essentials",
    description: "Sulfate-free body wash with NutriumMoisture technology that nourishes skin while cleansing.",
    tags: ["dove", "body-wash", "nourishing", "gentle"],
  },
  {
    id: "body-scrub-mcaffeine",
    name: "Coffee Body Scrub",
    brand: "mCaffeine",
    subcategory: "Bath & Body",
    sectionId: "bodycare-essentials",
    sectionTitle: "Bodycare Essentials",
    description: "Exfoliating coffee scrub with walnut that removes dead skin, tan, and smoothens rough patches.",
    tags: ["mcaffeine", "body-scrub", "coffee", "exfolicating", "indian-beauty"],
    badge: "POPULAR",
  },
  {
    id: "body-oil-nuxe",
    name: "Huile Prodigieuse Multi-Purpose Dry Oil",
    brand: "Nuxe",
    subcategory: "Bath & Body",
    sectionId: "bodycare-essentials",
    sectionTitle: "Bodycare Essentials",
    description: "Luxurious multi-purpose dry oil for face, body, and hair with a signature botanical scent.",
    tags: ["nuxe", "body-oil", "dry-oil", "multi-purpose", "luxury"],
  },
  {
    id: "deodorant-wild-stone",
    name: "Code Chrome Perfume Body Spray",
    brand: "Wild Stone",
    subcategory: "Bath & Body",
    sectionId: "bodycare-essentials",
    sectionTitle: "Bodycare Essentials",
    description: "Long-lasting 150ml fragrance body spray with fresh aquatic notes for all-day freshness.",
    tags: ["wild-stone", "deodorant", "body-spray", "fresh"],
  },
  {
    id: "hand-cream-loccitane",
    name: "Shea Butter Hand Cream",
    brand: "L'Occitane",
    subcategory: "Bath & Body",
    sectionId: "bodycare-essentials",
    sectionTitle: "Bodycare Essentials",
    description: "Intensely nourishing hand cream with 20% shea butter that absorbs quickly without greasiness.",
    tags: ["loccitane", "hand-cream", "shea-butter", "luxury"],
    badge: "BESTSELLER",
  },
  {
    id: "body-mist-nykaa",
    name: "Wanderlust Body Mist",
    brand: "Nykaa",
    subcategory: "Bath & Body",
    sectionId: "bodycare-essentials",
    sectionTitle: "Bodycare Essentials",
    description: "Light, refreshing fragrance body mist for an everyday scent boost.",
    tags: ["nykaa", "body-mist", "fragrance", "affordable", "indian-beauty"],
  },
  {
    id: "sol-de-janeiro-body-wash",
    name: "Brazilian 4 Play Moisturizing Shower Cream-Gel",
    brand: "Sol de Janeiro",
    subcategory: "Bath & Body",
    sectionId: "bodycare-essentials",
    sectionTitle: "Bodycare Essentials",
    description: "Rich shower cream-gel with cupuaçu butter and açaí oil in the addictive Cheirosa '62 scent.",
    tags: ["sol-de-janeiro", "body-wash", "shower", "moisturizing"],
    badge: "POPULAR",
  },

  // === NEW Beauty Tools / Accessories ===
  {
    id: "makeup-brush-set",
    name: "12-Piece Professional Makeup Brush Set",
    brand: "Real Techniques",
    subcategory: "Beauty Tools",
    sectionId: "beauty-tools-accessories",
    sectionTitle: "Beauty Tools & Accessories",
    description: "Complete brush collection with synthetic bristles for foundation, powder, contour, and eye makeup.",
    tags: ["real-techniques", "brushes", "makeup-tools", "set"],
    badge: "POPULAR",
  },
  {
    id: "beauty-blender-original",
    name: "Original Beautyblender Sponge",
    brand: "Beautyblender",
    subcategory: "Beauty Tools",
    sectionId: "beauty-tools-accessories",
    sectionTitle: "Beauty Tools & Accessories",
    description: "The iconic edgeless makeup sponge that bounces and blends for a flawless, airbrushed finish.",
    tags: ["beautyblender", "sponge", "blending", "foundation"],
    badge: "BESTSELLER",
  },
  {
    id: "makeup-organizer-acrylic",
    name: "Acrylic Makeup Organizer",
    brand: "Muji",
    subcategory: "Beauty Tools",
    sectionId: "beauty-tools-accessories",
    sectionTitle: "Beauty Tools & Accessories",
    description: "Clear acrylic multi-tier organizer with drawers and compartments for a clutter-free vanity.",
    tags: ["organizer", "acrylic", "vanity", "storage"],
  },
  {
    id: "vanity-mirror-led",
    name: "Hollywood LED Vanity Mirror",
    brand: "Impressions Vanity",
    subcategory: "Beauty Tools",
    sectionId: "beauty-tools-accessories",
    sectionTitle: "Beauty Tools & Accessories",
    description: "Professional 12-bulb LED lighted vanity mirror with adjustable brightness and 3 color temperatures.",
    tags: ["vanity-mirror", "led", "hollywood", "lighting"],
    badge: "POPULAR",
  },
  {
    id: "makeup-bag-travel",
    name: "Travel Makeup Bag with Compartments",
    brand: "Béis",
    subcategory: "Beauty Tools",
    sectionId: "beauty-tools-accessories",
    sectionTitle: "Beauty Tools & Accessories",
    description: "Water-resistant travel cosmetic bag with removable pouches and brush compartments.",
    tags: ["makeup-bag", "travel", "organizer", "pouch"],
  },
  {
    id: "heatless-curlers",
    name: "Silk Heatless Hair Curler Set",
    brand: "Kitsch",
    subcategory: "Beauty Tools",
    sectionId: "beauty-tools-accessories",
    sectionTitle: "Beauty Tools & Accessories",
    description: "Overnight silk heatless curling ribbon that creates bouncy curls without heat damage.",
    tags: ["heatless-curlers", "silk", "curls", "no-heat", "viral"],
    badge: "VIRAL",
  },
  {
    id: "gua-sha-jade",
    name: "Jade Stone Gua Sha Facial Tool",
    brand: "Mount Lai",
    subcategory: "Beauty Tools",
    sectionId: "beauty-tools-accessories",
    sectionTitle: "Beauty Tools & Accessories",
    description: "Authentic jade stone sculpting tool for lymphatic drainage, jaw tension, and facial contouring.",
    tags: ["gua-sha", "jade", "facial-tool", "sculpting"],
  },
  {
    id: "facial-roller-rose-quartz",
    name: "Rose Quartz Facial Roller",
    brand: "Mount Lai",
    subcategory: "Beauty Tools",
    sectionId: "beauty-tools-accessories",
    sectionTitle: "Beauty Tools & Accessories",
    description: "Dual-ended rose quartz roller for de-puffing under-eyes and boosting serum absorption.",
    tags: ["facial-roller", "rose-quartz", "depuffing", "skincare"],
  },
  {
    id: "skincare-fridge",
    name: "Mini Beauty Fridge 4L",
    brand: "Cooluli",
    subcategory: "Beauty Tools",
    sectionId: "beauty-tools-accessories",
    sectionTitle: "Beauty Tools & Accessories",
    description: "Compact thermoelectric cooler that keeps serums, sheet masks, and eye creams perfectly chilled.",
    tags: ["skincare-fridge", "mini-fridge", "beauty", "storage"],
    badge: "TRENDING",
  },
  {
    id: "nail-kit-gel",
    name: "At-Home Gel Manicure Kit",
    brand: "OPI",
    subcategory: "Beauty Tools",
    sectionId: "beauty-tools-accessories",
    sectionTitle: "Beauty Tools & Accessories",
    description: "Complete gel nail kit with LED lamp, base coat, top coat, and 4 popular gel colors.",
    tags: ["gel-nails", "manicure", "opi", "nail-kit"],
    badge: "POPULAR",
  },
  {
    id: "hair-brush-wet",
    name: "The Original Detangling Hair Brush",
    brand: "Tangle Teezer",
    subcategory: "Beauty Tools",
    sectionId: "beauty-tools-accessories",
    sectionTitle: "Beauty Tools & Accessories",
    description: "Two-tiered teeth technology that flexes and detangles wet or dry hair pain-free.",
    tags: ["tangle-teezer", "hair-brush", "detangling", "gentle"],
    badge: "POPULAR",
  },
  {
    id: "at-home-manicure-set",
    name: "Manicure & Pedicure 10-Piece Kit",
    brand: "Tweezerman",
    subcategory: "Beauty Tools",
    sectionId: "beauty-tools-accessories",
    sectionTitle: "Beauty Tools & Accessories",
    description: "Professional-grade stainless steel nail care kit with cuticle pusher, clippers, and glass file.",
    tags: ["tweezerman", "manicure", "pedicure", "nails", "kit"],
  },

  // === NEW Premium / Aspirational ===
  {
    id: "rhode-glazing-milk",
    name: "Glazing Milk",
    brand: "Rhode",
    subcategory: "Skincare",
    sectionId: "premium-aspirational",
    sectionTitle: "Premium & Aspirational Beauty",
    description: "Lightweight milky essence with niacinamide and peptides for a dewy glass-skin glow.",
    tags: ["rhode", "glazing-milk", "essence", "glass-skin", "viral"],
    badge: "VIRAL",
    featured: true,
  },
  {
    id: "dior-backstage-face-body",
    name: "Backstage Face & Body Foundation",
    brand: "Dior",
    subcategory: "Makeup",
    sectionId: "premium-aspirational",
    sectionTitle: "Premium & Aspirational Beauty",
    description: "Professional-grade buildable water-based foundation in 40 shades for a natural skin-like finish.",
    tags: ["dior", "backstage", "foundation", "luxury", "professional"],
    badge: "PREMIUM",
  },
  {
    id: "laneige-cream-skin-toner",
    name: "Cream Skin Cerapeptide Toner & Moisturizer",
    brand: "Laneige",
    subcategory: "K-Beauty",
    sectionId: "premium-aspirational",
    sectionTitle: "Premium & Aspirational Beauty",
    description: "2-in-1 toner and moisturizer with Ceramide-peptide complex for skin barrier strengthening.",
    tags: ["laneige", "cream-skin", "toner", "moisturizer", "k-beauty"],
    badge: "POPULAR",
  },
  {
    id: "ysl-touche-eclat",
    name: "Touche Éclat All-Over Brightening Concealer Pen",
    brand: "YSL",
    subcategory: "Makeup",
    sectionId: "premium-aspirational",
    sectionTitle: "Premium & Aspirational Beauty",
    description: "Iconic click-pen concealer and highlighter that erases signs of fatigue with luminous finish.",
    tags: ["ysl", "touche-eclat", "concealer", "brightening", "luxury"],
    badge: "PREMIUM",
    featured: true,
  },
  {
    id: "clinique-take-the-day-off",
    name: "Take The Day Off Cleansing Balm",
    brand: "Clinique",
    subcategory: "Skincare",
    sectionId: "premium-aspirational",
    sectionTitle: "Premium & Aspirational Beauty",
    description: "Lightweight balm that dissolves even long-wearing makeup and sunscreen in one gentle step.",
    tags: ["clinique", "cleansing-balm", "makeup-remover", "luxury"],
    badge: "POPULAR",
  },
  {
    id: "sol-de-janeiro-bom-dia-cream",
    name: "Bom Dia Bright Body Cream",
    brand: "Sol de Janeiro",
    subcategory: "Bath & Body",
    sectionId: "premium-aspirational",
    sectionTitle: "Premium & Aspirational Beauty",
    description: "AHA-infused body cream with Brazilian Cupuaçu butter that smooths and brightens skin with the addictive Bom Dia scent.",
    tags: ["sol-de-janeiro", "bom-dia", "body-cream", "brightening", "viral"],
    badge: "VIRAL",
  }
];

/**
 * Return all Beauty products with resolved image URLs and display orders.
 */
export function getFullBeautyCatalog(): BeautyProduct[] {
  return RAW_BEAUTY_PRODUCTS.map((p, idx) => ({
    id: p.id,
    name: p.name,
    brand: p.brand,
    category: "Beauty",
    subcategory: p.subcategory,
    sectionId: p.sectionId,
    sectionTitle: p.sectionTitle,
    imageUrl: getBeautyProductImage(p.id),
    description: p.description,
    tags: p.tags,
    badge: p.badge,
    featured: Boolean(p.featured),
    trending: Boolean(p.trending),
    displayOrder: idx,
  }));
}

/**
 * Get distinct subcategories for beauty navigation
 */
export function getBeautySubcategories(): Array<{ name: string; count: number }> {
  const map = new Map<string, number>();
  for (const item of RAW_BEAUTY_PRODUCTS) {
    map.set(item.subcategory, (map.get(item.subcategory) || 0) + 1);
  }
  return Array.from(map.entries()).map(([name, count]) => ({ name, count }));
}
