export const NICHES = [
  { name: "Founder", emoji: "🚀" },
  { name: "Builder", emoji: "🔨" },
  { name: "Developer", emoji: "💻" },
  { name: "Designer", emoji: "🎨" },
  { name: "Indie Hacker", emoji: "⚡" },
  { name: "AI", emoji: "🤖" },
  { name: "Marketer", emoji: "📈" },
  { name: "Writer", emoji: "✍️" },
  { name: "Creator", emoji: "🎬" },
  { name: "Investor", emoji: "💰" },
  { name: "Crypto", emoji: "🪙" },
  { name: "Trader", emoji: "📊" },
  { name: "SaaS", emoji: "📦" },
  { name: "Agency", emoji: "🏢" },
  { name: "Freelancer", emoji: "🧳" },
  { name: "Engineer", emoji: "⚙️" },
  { name: "Product Manager", emoji: "🗂️" },
  { name: "Data & Analytics", emoji: "🔍" },
  { name: "Cybersecurity", emoji: "🔒" },
  { name: "DevOps", emoji: "🖥️" },
  { name: "Finance", emoji: "💵" },
  { name: "Healthcare", emoji: "🏥" },
  { name: "Legal", emoji: "⚖️" },
  { name: "Education", emoji: "🎓" },
  { name: "Student", emoji: "📚" },
  { name: "Podcaster", emoji: "🎙️" },
  { name: "Artist", emoji: "🎨" },
  { name: "Tech", emoji: "💡" },
  { name: "Consultant", emoji: "🤝" },
  { name: "Researcher", emoji: "🔬" },
  { name: "Journalist", emoji: "📰" },
  { name: "Photographer", emoji: "📷" },
  { name: "Filmmaker", emoji: "🎥" },
  { name: "Architect", emoji: "🏗️" },
  { name: "HR & Recruiting", emoji: "👥" },
  { name: "Sales", emoji: "💼" },
  { name: "Operations", emoji: "🔧" },
  { name: "Supply Chain", emoji: "🚢" },
  { name: "Real Estate", emoji: "🏠" },
  { name: "E-commerce", emoji: "🛒" },
  { name: "Gaming", emoji: "🎮" },
  { name: "Sports & Fitness", emoji: "🏋️" },
  { name: "Nonprofit", emoji: "❤️" },
  { name: "Government", emoji: "🏛️" },
  { name: "Other", emoji: "➕" },
];
