import { 
  Rocket, 
  Hammer, 
  Laptop, 
  Palette, 
  Zap, 
  Bot, 
  TrendingUp, 
  Pen, 
  Clapperboard, 
  DollarSign, 
  Coins, 
  BarChart2, 
  Cloud, 
  Building2, 
  Briefcase, 
  Settings, 
  ClipboardList, 
  Search, 
  Lock, 
  Terminal, 
  Heart, 
  Scale, 
  GraduationCap, 
  Book, 
  Mic, 
  Lightbulb, 
  Users, 
  Newspaper, 
  Camera, 
  Video, 
  Building, 
  Wrench, 
  Truck, 
  Home, 
  ShoppingCart, 
  Gamepad2, 
  Dumbbell, 
  Plus
} from "lucide-react";

export const NICHES = [
  { name: "Founder", icon: Rocket },
  { name: "Builder", icon: Hammer },
  { name: "Developer", icon: Laptop },
  { name: "Designer", icon: Palette },
  { name: "Indie Hacker", icon: Zap },
  { name: "AI", icon: Bot },
  { name: "Marketer", icon: TrendingUp },
  { name: "Writer", icon: Pen },
  { name: "Creator", icon: Clapperboard },
  { name: "Investor", icon: DollarSign },
  { name: "Crypto", icon: Coins },
  { name: "Trader", icon: BarChart2 },
  { name: "SaaS", icon: Cloud },
  { name: "Agency", icon: Building2 },
  { name: "Freelancer", icon: Briefcase },
  { name: "Engineer", icon: Settings },
  { name: "Product Manager", icon: ClipboardList },
  { name: "Data & Analytics", icon: Search },
  { name: "Cybersecurity", icon: Lock },
  { name: "DevOps", icon: Terminal },
  { name: "Finance", icon: DollarSign },
  { name: "Healthcare", icon: Heart },
  { name: "Legal", icon: Scale },
  { name: "Education", icon: GraduationCap },
  { name: "Student", icon: Book },
  { name: "Podcaster", icon: Mic },
  { name: "Artist", icon: Palette },
  { name: "Tech", icon: Lightbulb },
  { name: "Consultant", icon: Users },
  { name: "Researcher", icon: Search },
  { name: "Journalist", icon: Newspaper },
  { name: "Photographer", icon: Camera },
  { name: "Filmmaker", icon: Video },
  { name: "Architect", icon: Building },
  { name: "HR & Recruiting", icon: Users },
  { name: "Sales", icon: Briefcase },
  { name: "Operations", icon: Wrench },
  { name: "Supply Chain", icon: Truck },
  { name: "Real Estate", icon: Home },
  { name: "E-commerce", icon: ShoppingCart },
  { name: "Gaming", icon: Gamepad2 },
  { name: "Sports & Fitness", icon: Dumbbell },
  { name: "Nonprofit", icon: Heart },
  { name: "Government", icon: Building },
  { name: "Other", icon: Plus },
];

export const FOLLOWERS_RANGES = [
  "0-100", "100-500", "500-1K", "1K-2K", "2K-5K", "5K-10K", "10K-25K", "25K-50K", "50K-100K", "100K+"
];
