export interface CountryCode {
  name: string;
  dialCode: string;
  code: string;
}

export function getFlagEmoji(countryCode: string): string {
  const codePoints = countryCode
    .toUpperCase()
    .split("")
    .map(char => 127397 + char.charCodeAt(0));
  try {
    return String.fromCodePoint(...codePoints);
  } catch {
    return "🌐";
  }
}

export const COUNTRY_CODES: CountryCode[] = [
  { name: "Afghanistan", dialCode: "+93", code: "AF" },
  { name: "Albania", dialCode: "+355", code: "AL" },
  { name: "Algeria", dialCode: "+213", code: "DZ" },
  { name: "Angola", dialCode: "+244", code: "AO" },
  { name: "Argentina", dialCode: "+54", code: "AR" },
  { name: "Armenia", dialCode: "+374", code: "AM" },
  { name: "Australia", dialCode: "+61", code: "AU" },
  { name: "Austria", dialCode: "+43", code: "AT" },
  { name: "Azerbaijan", dialCode: "+994", code: "AZ" },
  { name: "Bahrain", dialCode: "+973", code: "BH" },
  { name: "Bangladesh", dialCode: "+880", code: "BD" },
  { name: "Belarus", dialCode: "+375", code: "BY" },
  { name: "Belgium", dialCode: "+32", code: "BE" },
  { name: "Benin", dialCode: "+229", code: "BJ" },
  { name: "Bolivia", dialCode: "+591", code: "BO" },
  { name: "Bosnia and Herzegovina", dialCode: "+387", code: "BA" },
  { name: "Botswana", dialCode: "+267", code: "BW" },
  { name: "Brazil", dialCode: "+55", code: "BR" },
  { name: "Bulgaria", dialCode: "+359", code: "BG" },
  { name: "Burkina Faso", dialCode: "+226", code: "BF" },
  { name: "Cambodia", dialCode: "+855", code: "KH" },
  { name: "Cameroon", dialCode: "+237", code: "CM" },
  { name: "Canada", dialCode: "+1", code: "CA" },
  { name: "Chile", dialCode: "+56", code: "CL" },
  { name: "China", dialCode: "+86", code: "CN" },
  { name: "Colombia", dialCode: "+57", code: "CO" },
  { name: "Costa Rica", dialCode: "+506", code: "CR" },
  { name: "Croatia", dialCode: "+385", code: "HR" },
  { name: "Cyprus", dialCode: "+357", code: "CY" },
  { name: "Czech Republic", dialCode: "+420", code: "CZ" },
  { name: "Denmark", dialCode: "+45", code: "DK" },
  { name: "Dominican Republic", dialCode: "+1", code: "DO" },
  { name: "Ecuador", dialCode: "+593", code: "EC" },
  { name: "Egypt", dialCode: "+20", code: "EG" },
  { name: "El Salvador", dialCode: "+503", code: "SV" },
  { name: "Estonia", dialCode: "+372", code: "EE" },
  { name: "Ethiopia", dialCode: "+251", code: "ET" },
  { name: "Finland", dialCode: "+358", code: "FI" },
  { name: "France", dialCode: "+33", code: "FR" },
  { name: "Georgia", dialCode: "+995", code: "GE" },
  { name: "Germany", dialCode: "+49", code: "DE" },
  { name: "Ghana", dialCode: "+233", code: "GH" },
  { name: "Greece", dialCode: "+30", code: "GR" },
  { name: "Guatemala", dialCode: "+502", code: "GT" },
  { name: "Honduras", dialCode: "+504", code: "HN" },
  { name: "Hong Kong", dialCode: "+852", code: "HK" },
  { name: "Hungary", dialCode: "+36", code: "HU" },
  { name: "Iceland", dialCode: "+354", code: "IS" },
  { name: "India", dialCode: "+91", code: "IN" },
  { name: "Indonesia", dialCode: "+62", code: "ID" },
  { name: "Iraq", dialCode: "+964", code: "IQ" },
  { name: "Ireland", dialCode: "+353", code: "IE" },
  { name: "Israel", dialCode: "+972", code: "IL" },
  { name: "Italy", dialCode: "+39", code: "IT" },
  { name: "Ivory Coast", dialCode: "+225", code: "CI" },
  { name: "Jamaica", dialCode: "+1", code: "JM" },
  { name: "Japan", dialCode: "+81", code: "JP" },
  { name: "Jordan", dialCode: "+962", code: "JO" },
  { name: "Kazakhstan", dialCode: "+7", code: "KZ" },
  { name: "Kenya", dialCode: "+254", code: "KE" },
  { name: "Kosovo", dialCode: "+383", code: "XK" },
  { name: "Kuwait", dialCode: "+965", code: "KW" },
  { name: "Kyrgyzstan", dialCode: "+996", code: "KG" },
  { name: "Latvia", dialCode: "+371", code: "LV" },
  { name: "Lebanon", dialCode: "+961", code: "LB" },
  { name: "Libya", dialCode: "+218", code: "LY" },
  { name: "Lithuania", dialCode: "+370", code: "LT" },
  { name: "Luxembourg", dialCode: "+352", code: "LU" },
  { name: "Malaysia", dialCode: "+60", code: "MY" },
  { name: "Mali", dialCode: "+223", code: "ML" },
  { name: "Malta", dialCode: "+356", code: "MT" },
  { name: "Mexico", dialCode: "+52", code: "MX" },
  { name: "Moldova", dialCode: "+373", code: "MD" },
  { name: "Mongolia", dialCode: "+976", code: "MN" },
  { name: "Morocco", dialCode: "+212", code: "MA" },
  { name: "Mozambique", dialCode: "+258", code: "MZ" },
  { name: "Myanmar", dialCode: "+95", code: "MM" },
  { name: "Namibia", dialCode: "+264", code: "NA" },
  { name: "Nepal", dialCode: "+977", code: "NP" },
  { name: "Netherlands", dialCode: "+31", code: "NL" },
  { name: "New Zealand", dialCode: "+64", code: "NZ" },
  { name: "Nicaragua", dialCode: "+505", code: "NI" },
  { name: "Niger", dialCode: "+227", code: "NE" },
  { name: "Nigeria", dialCode: "+234", code: "NG" },
  { name: "North Macedonia", dialCode: "+389", code: "MK" },
  { name: "Norway", dialCode: "+47", code: "NO" },
  { name: "Oman", dialCode: "+968", code: "OM" },
  { name: "Pakistan", dialCode: "+92", code: "PK" },
  { name: "Palestine", dialCode: "+970", code: "PS" },
  { name: "Panama", dialCode: "+507", code: "PA" },
  { name: "Paraguay", dialCode: "+595", code: "PY" },
  { name: "Peru", dialCode: "+51", code: "PE" },
  { name: "Philippines", dialCode: "+63", code: "PH" },
  { name: "Poland", dialCode: "+48", code: "PL" },
  { name: "Portugal", dialCode: "+351", code: "PT" },
  { name: "Qatar", dialCode: "+974", code: "QA" },
  { name: "Romania", dialCode: "+40", code: "RO" },
  { name: "Russia", dialCode: "+7", code: "RU" },
  { name: "Rwanda", dialCode: "+250", code: "RW" },
  { name: "Saudi Arabia", dialCode: "+966", code: "SA" },
  { name: "Senegal", dialCode: "+221", code: "SN" },
  { name: "Serbia", dialCode: "+381", code: "RS" },
  { name: "Sierra Leone", dialCode: "+232", code: "SL" },
  { name: "Singapore", dialCode: "+65", code: "SG" },
  { name: "Slovakia", dialCode: "+421", code: "SK" },
  { name: "Slovenia", dialCode: "+386", code: "SI" },
  { name: "South Africa", dialCode: "+27", code: "ZA" },
  { name: "South Korea", dialCode: "+82", code: "KR" },
  { name: "Spain", dialCode: "+34", code: "ES" },
  { name: "Sri Lanka", dialCode: "+94", code: "LK" },
  { name: "Sweden", dialCode: "+46", code: "SE" },
  { name: "Switzerland", dialCode: "+41", code: "CH" },
  { name: "Taiwan", dialCode: "+886", code: "TW" },
  { name: "Tajikistan", dialCode: "+992", code: "TJ" },
  { name: "Tanzania", dialCode: "+255", code: "TZ" },
  { name: "Thailand", dialCode: "+66", code: "TH" },
  { name: "Tunisia", dialCode: "+216", code: "TN" },
  { name: "Turkey", dialCode: "+90", code: "TR" },
  { name: "Turkmenistan", dialCode: "+993", code: "TM" },
  { name: "Uganda", dialCode: "+256", code: "UG" },
  { name: "Ukraine", dialCode: "+380", code: "UA" },
  { name: "United Arab Emirates", dialCode: "+971", code: "AE" },
  { name: "United Kingdom", dialCode: "+44", code: "GB" },
  { name: "United States", dialCode: "+1", code: "US" },
  { name: "Uruguay", dialCode: "+598", code: "UY" },
  { name: "Uzbekistan", dialCode: "+998", code: "UZ" },
  { name: "Venezuela", dialCode: "+58", code: "VE" },
  { name: "Vietnam", dialCode: "+84", code: "VN" },
  { name: "Yemen", dialCode: "+967", code: "YE" },
  { name: "Zambia", dialCode: "+260", code: "ZM" },
  { name: "Zimbabwe", dialCode: "+263", code: "ZW" }
];
