export interface PlaybookLesson {
  id: string;
  number: string;
  title: string;
}

export interface PlaybookModule {
  id: string;
  number: string;
  title: string;
  description: string;
  lessons: PlaybookLesson[];
}

export const DATING_PLAYBOOK_MODULES: PlaybookModule[] = [
  {
    id: "module-01",
    number: "01",
    title: "The Psychology of Attraction",
    description:
      "Start with the underlying psychology. Understand how attraction develops, what influences romantic interest, and why attraction cannot be reduced to a universal formula.",
    lessons: [
      { id: "01-1", number: "1.1", title: "The Anatomy of Romantic Attraction" },
      { id: "01-2", number: "1.2", title: "Physical Attraction, Personality & Emotional Connection" },
      { id: "01-3", number: "1.3", title: "First Impressions and the Formation of Interest" },
      { id: "01-4", number: "1.4", title: "Confidence, Competence & Social Presence" },
      { id: "01-5", number: "1.5", title: "The Difference Between Attraction, Chemistry & Compatibility" },
      { id: "01-6", number: "1.6", title: "Why Being Nice Is Not the Same as Being Romantically Attractive" },
      { id: "01-7", number: "1.7", title: "Desire, Validation & the Psychology of Approval" },
      { id: "01-8", number: "1.8", title: "Individual Preferences and What Women Find Attractive" },
      { id: "01-9", number: "1.9", title: "The Myths, Misconceptions & Pseudoscience of Dating" },
      { id: "01-10", number: "1.10", title: "What Creates Attraction—and What Remains Outside Your Control" },
      { id: "01-11", number: "1.11", title: "Understanding Romantic Interest Without Treating People Like Formulas" },
      { id: "01-12", number: "1.12", title: "The Principles That Will Guide the Entire Playbook" },
    ],
  },
  {
    id: "module-02",
    number: "02",
    title: "Becoming the Man",
    description:
      "Before trying to attract someone else, build a life and identity you genuinely respect through real improvements in appearance, lifestyle, confidence, and personal direction.",
    lessons: [
      { id: "02-1", number: "2.1", title: "Define the Man You Intend to Become" },
      { id: "02-2", number: "2.2", title: "Grooming, Hygiene & Personal Presentation" },
      { id: "02-3", number: "2.3", title: "Style, Clothing & Developing Your Own Look" },
      { id: "02-4", number: "2.4", title: "Fitness, Health, Sleep & Physical Energy" },
      { id: "02-5", number: "2.5", title: "Building a Life That Does Not Revolve Around Women" },
      { id: "02-6", number: "2.6", title: "Ambition, Purpose & Personal Direction" },
      { id: "02-7", number: "2.7", title: "Hobbies, Interests & Becoming More Socially Engaged" },
      { id: "02-8", number: "2.8", title: "Confidence as a Consequence of Action" },
      { id: "02-9", number: "2.9", title: "Body Language, Eye Contact & Physical Presence" },
      { id: "02-10", number: "2.10", title: "Overcoming Insecurity, Comparison & Self-Doubt" },
      { id: "02-11", number: "2.11", title: "Emotional Stability Without Emotional Suppression" },
      { id: "02-12", number: "2.12", title: "Independence, Self-Respect & Personal Boundaries" },
      { id: "02-13", number: "2.13", title: "Becoming Socially Comfortable Outside Your Comfort Zone" },
      { id: "02-14", number: "2.14", title: "Authenticity: Improving Yourself Without Becoming Someone Else" },
      { id: "02-15", number: "2.15", title: "Building Your Personal Development System" },
    ],
  },
  {
    id: "module-03",
    number: "03",
    title: "The Art of Social Connection",
    description:
      "Learn how to connect with people in real life, hold engaging conversations, participate naturally in social environments, and create opportunities to meet compatible women.",
    lessons: [
      { id: "03-1", number: "3.1", title: "Building a Social Life That Creates Opportunities" },
      { id: "03-2", number: "3.2", title: "Expanding Your Social Circle and Meeting New People" },
      { id: "03-3", number: "3.3", title: "Where to Meet Women Who Share Your Interests" },
      { id: "03-4", number: "3.4", title: "Becoming Comfortable in Unfamiliar Social Settings" },
      { id: "03-5", number: "3.5", title: "Starting Conversations Without Rehearsed Scripts" },
      { id: "03-6", number: "3.6", title: "The Anatomy of a Natural Conversation" },
      { id: "03-7", number: "3.7", title: "Moving Beyond Small Talk" },
      { id: "03-8", number: "3.8", title: "Asking Better Questions Without Interrogating Someone" },
      { id: "03-9", number: "3.9", title: "Active Listening, Curiosity & Conversational Flow" },
      { id: "03-10", number: "3.10", title: "Storytelling, Humor & Sharing Your Personality" },
      { id: "03-11", number: "3.11", title: "Reading the Social Environment and Nonverbal Cues" },
      { id: "03-12", number: "3.12", title: "Handling Awkward Silences and Conversational Dead Ends" },
      { id: "03-13", number: "3.13", title: "Approaching Women With Awareness and Respect" },
      { id: "03-14", number: "3.14", title: "Recognizing Disinterest and Respecting Boundaries" },
      { id: "03-15", number: "3.15", title: "Turning a Good Interaction Into an Opportunity to Reconnect" },
    ],
  },
  {
    id: "module-04",
    number: "04",
    title: "Flirtation, Chemistry & Desire",
    description:
      "Communicate romantic interest, introduce playfulness, express your personality, recognize reciprocity, and develop genuine chemistry without manipulative tactics.",
    lessons: [
      { id: "04-1", number: "4.1", title: "From Friendly Interaction to Romantic Interest" },
      { id: "04-2", number: "4.2", title: "The Principles of Natural Flirtation" },
      { id: "04-3", number: "4.3", title: "Playfulness, Humor & Light Teasing" },
      { id: "04-4", number: "4.4", title: "Expressing Interest Without Overpursuing" },
      { id: "04-5", number: "4.5", title: "Compliments, Appreciation & Genuine Attraction" },
      { id: "04-6", number: "4.6", title: "Creating Conversational Tension Without Manipulation" },
      { id: "04-7", number: "4.7", title: "Emotional Engagement and Memorable Interactions" },
      { id: "04-8", number: "4.8", title: "Confidence, Calmness & Handling Nervousness" },
      { id: "04-9", number: "4.9", title: "Reading Reciprocity Instead of Imagining It" },
      { id: "04-10", number: "4.10", title: "Understanding Body Language Without Overinterpreting It" },
      { id: "04-11", number: "4.11", title: "Verbal and Nonverbal Communication" },
      { id: "04-12", number: "4.12", title: "Making Your Intentions Clear Without Creating Pressure" },
      { id: "04-13", number: "4.13", title: "When to Escalate the Conversation—and When to Stop" },
      { id: "04-14", number: "4.14", title: "Common Flirting Mistakes and Why They Fail" },
      { id: "04-15", number: "4.15", title: "Developing a Flirting Style That Feels Like You" },
    ],
  },
  {
    id: "module-05",
    number: "05",
    title: "Modern Dating: Profiles, Texting & Momentum",
    description:
      "Master dating apps, social media, DMs, texting, and the transition from digital conversations to real-life dates with clarity, momentum, and confidence.",
    lessons: [
      { id: "05-1", number: "5.1", title: "Understanding the Modern Dating Landscape" },
      { id: "05-2", number: "5.2", title: "Choosing the Right Dating Platforms" },
      { id: "05-3", number: "5.3", title: "Building an Authentic and Attractive Dating Profile" },
      { id: "05-4", number: "5.4", title: "Photography, Presentation & Profile Positioning" },
      { id: "05-5", number: "5.5", title: "Writing a Bio That Communicates Personality" },
      { id: "05-6", number: "5.6", title: "Starting Conversations Through DMs and Dating Apps" },
      { id: "05-7", number: "5.7", title: "Opening Messages That Create a Natural Conversation" },
      { id: "05-8", number: "5.8", title: "Texting With Personality, Humor & Intent" },
      { id: "05-9", number: "5.9", title: "Creating Momentum Without Forcing the Conversation" },
      { id: "05-10", number: "5.10", title: "Asking Questions and Sharing About Yourself" },
      { id: "05-11", number: "5.11", title: "Reply Timing, Double Texting & Communication Differences" },
      { id: "05-12", number: "5.12", title: "Understanding Slow Replies, Inconsistency & Low Interest" },
      { id: "05-13", number: "5.13", title: "Avoiding Overanalysis and Texting Anxiety" },
      { id: "05-14", number: "5.14", title: "Transitioning From Digital Conversation to a Date" },
      { id: "05-15", number: "5.15", title: "Asking Her Out With Clarity and Confidence" },
      { id: "05-16", number: "5.16", title: "Online Dating Safety, Privacy & Scam Awareness" },
    ],
  },
  {
    id: "module-06",
    number: "06",
    title: "The Psychology of Dating",
    description:
      "Navigate dates with confidence, create genuine emotional and physical connection, communicate romantic intentions, respect boundaries, and assess mutual interest.",
    lessons: [
      { id: "06-1", number: "6.1", title: "The Purpose of a First Date" },
      { id: "06-2", number: "6.2", title: "Planning an Experience That Encourages Connection" },
      { id: "06-3", number: "6.3", title: "Choosing the Right Setting for a Date" },
      { id: "06-4", number: "6.4", title: "Managing First-Date Anxiety and Expectations" },
      { id: "06-5", number: "6.5", title: "Creating Comfort Without Losing Romantic Intent" },
      { id: "06-6", number: "6.6", title: "Conversation, Humor & Emotional Engagement on Dates" },
      { id: "06-7", number: "6.7", title: "Showing Interest Without Turning the Date Into an Interview" },
      { id: "06-8", number: "6.8", title: "Being Present Instead of Constantly Evaluating Yourself" },
      { id: "06-9", number: "6.9", title: "Understanding Mutual Interest During a Date" },
      { id: "06-10", number: "6.10", title: "Communicating Romantic Intentions Naturally" },
      { id: "06-11", number: "6.11", title: "Consent, Boundaries & Respectful Physical Intimacy" },
      { id: "06-12", number: "6.12", title: "Kissing, Physical Affection & Mutual Readiness" },
      { id: "06-13", number: "6.13", title: "Navigating Different Comfort Levels and Expectations" },
      { id: "06-14", number: "6.14", title: "Ending the Date and Communicating Your Interest" },
      { id: "06-15", number: "6.15", title: "Following Up After a Date" },
      { id: "06-16", number: "6.16", title: "Planning Subsequent Dates and Building Continuity" },
      { id: "06-17", number: "6.17", title: "Recognizing When Chemistry Is Not Mutual" },
      { id: "06-18", number: "6.18", title: "Evaluating the Experience Without Overanalyzing It" },
    ],
  },
  {
    id: "module-07",
    number: "07",
    title: "Emotional Mastery & the Realities of Dating",
    description:
      "Navigate rejection, inconsistency, disappointment, and emotional investment without becoming resentful, obsessive, or dependent on external validation.",
    lessons: [
      { id: "07-1", number: "7.1", title: "Rejection as Part of the Dating Process" },
      { id: "07-2", number: "7.2", title: "Separating Romantic Outcomes From Self-Worth" },
      { id: "07-3", number: "7.3", title: "Responding to Rejection With Dignity" },
      { id: "07-4", number: "7.4", title: "Understanding Ghosting and Unanswered Messages" },
      { id: "07-5", number: "7.5", title: "Mixed Signals, Ambiguity & Uncertainty" },
      { id: "07-6", number: "7.6", title: "Consistency, Reciprocity & Unequal Investment" },
      { id: "07-7", number: "7.7", title: "Knowing When to Continue and When to Walk Away" },
      { id: "07-8", number: "7.8", title: "Managing Anxiety, Jealousy & Comparison" },
      { id: "07-9", number: "7.9", title: "Attachment Patterns and Their Influence on Dating" },
      { id: "07-10", number: "7.10", title: "Recognizing Neediness and Emotional Overdependence" },
      { id: "07-11", number: "7.11", title: "Recovering From Unrequited Feelings" },
      { id: "07-12", number: "7.12", title: "Handling Disappointment Without Becoming Cynical" },
      { id: "07-13", number: "7.13", title: "Maintaining Standards Without Developing Entitlement" },
      { id: "07-14", number: "7.14", title: "Emotional Regulation During Romantic Uncertainty" },
      { id: "07-15", number: "7.15", title: "Learning From Repeated Dating Patterns" },
      { id: "07-16", number: "7.16", title: "Building Resilience Without Losing Your Capacity for Connection" },
    ],
  },
  {
    id: "module-08",
    number: "08",
    title: "Choosing Her: Compatibility, Standards & Commitment",
    description:
      "Move beyond attraction to assess compatibility, clarify relationship intentions, uphold healthy standards, and make intentional decisions about commitment.",
    lessons: [
      { id: "08-1", number: "8.1", title: "Attraction Is Not the Same as Compatibility" },
      { id: "08-2", number: "8.2", title: "Defining the Relationship You Actually Want" },
      { id: "08-3", number: "8.3", title: "Identifying Your Core Values and Non-Negotiables" },
      { id: "08-4", number: "8.4", title: "Understanding Her Values, Character & Relationship Goals" },
      { id: "08-5", number: "8.5", title: "Distinguishing Genuine Compatibility From Infatuation" },
      { id: "08-6", number: "8.6", title: "Casual Dating, Exclusivity & Long-Term Intentions" },
      { id: "08-7", number: "8.7", title: "Recognizing Reciprocity and Balanced Investment" },
      { id: "08-8", number: "8.8", title: "Green Flags: Signs of a Healthy Connection" },
      { id: "08-9", number: "8.9", title: "Red Flags: Patterns You Should Not Ignore" },
      { id: "08-10", number: "8.10", title: "Standards, Preferences & Unrealistic Expectations" },
      { id: "08-11", number: "8.11", title: "Communicating Your Intentions Honestly" },
      { id: "08-12", number: "8.12", title: "Discussing Exclusivity Without Games" },
      { id: "08-13", number: "8.13", title: "Boundaries, Expectations & Relationship Agreements" },
      { id: "08-14", number: "8.14", title: "Recognizing Incompatibility Before Becoming Deeply Invested" },
      { id: "08-15", number: "8.15", title: "Making the Decision to Commit" },
      { id: "08-16", number: "8.16", title: "Transitioning From Dating to a Relationship" },
      { id: "08-17", number: "8.17", title: "When Walking Away Is the Healthier Choice" },
    ],
  },
  {
    id: "module-09",
    number: "09",
    title: "The Architecture of a Lasting Relationship",
    description:
      "Develop the skills to sustain a healthy, fulfilling partnership over time through communication, trust, emotional intimacy, conflict resolution, and mutual effort.",
    lessons: [
      { id: "09-1", number: "9.1", title: "What Sustains a Healthy Relationship" },
      { id: "09-2", number: "9.2", title: "Emotional Availability and Genuine Vulnerability" },
      { id: "09-3", number: "9.3", title: "Communicating Needs Without Blame or Defensiveness" },
      { id: "09-4", number: "9.4", title: "Listening to Understand Rather Than to Win" },
      { id: "09-5", number: "9.5", title: "Trust, Reliability & Consistent Behavior" },
      { id: "09-6", number: "9.6", title: "Navigating Disagreements Without Escalating Conflict" },
      { id: "09-7", number: "9.7", title: "Apologies, Accountability & Relationship Repair" },
      { id: "09-8", number: "9.8", title: "Managing Jealousy and Insecurity Within a Relationship" },
      { id: "09-9", number: "9.9", title: "Maintaining Attraction Without Manipulation" },
      { id: "09-10", number: "9.10", title: "Physical Intimacy, Affection & Ongoing Consent" },
      { id: "09-11", number: "9.11", title: "Balancing Independence With Emotional Closeness" },
      { id: "09-12", number: "9.12", title: "Personal Space, Friends & Individual Identity" },
      { id: "09-13", number: "9.13", title: "Discussing Money, Lifestyle, Family & Future Plans" },
      { id: "09-14", number: "9.14", title: "Navigating Different Needs and Communication Styles" },
      { id: "09-15", number: "9.15", title: "Recognizing Unhealthy Patterns and Repeated Conflict" },
      { id: "09-16", number: "9.16", title: "Supporting Each Other Through Difficult Periods" },
      { id: "09-17", number: "9.17", title: "Keeping the Relationship Connected and Intentional" },
      { id: "09-18", number: "9.18", title: "Repairing a Relationship—or Recognizing When to Leave" },
    ],
  },
  {
    id: "module-10",
    number: "10",
    title: "The Man's Dating Framework",
    description:
      "Bring the entire playbook together into a coherent, practical personal system for dating and relationships that fits your personality and long-term goals.",
    lessons: [
      { id: "10-1", number: "10.1", title: "The Complete Journey: From First Impression to Commitment" },
      { id: "10-2", number: "10.2", title: "Identifying Your Current Dating Strengths and Weaknesses" },
      { id: "10-3", number: "10.3", title: "Building a Social Life That Supports Your Goals" },
      { id: "10-4", number: "10.4", title: "Your Personal Standards, Preferences & Boundaries" },
      { id: "10-5", number: "10.5", title: "Applying Attraction Psychology in Real Situations" },
      { id: "10-6", number: "10.6", title: "Developing Your Own Conversational and Flirting Style" },
      { id: "10-7", number: "10.7", title: "Evaluating Dates Without Overanalyzing Every Detail" },
      { id: "10-8", number: "10.8", title: "Recognizing and Correcting Repeating Patterns" },
      { id: "10-9", number: "10.9", title: "Balancing Dating With Ambition, Friends & Personal Well-Being" },
      { id: "10-10", number: "10.10", title: "Making Decisions Based on Reciprocity and Compatibility" },
      { id: "10-11", number: "10.11", title: "Remaining Confident Without Depending on Validation" },
      { id: "10-12", number: "10.12", title: "Choosing Between Casual Dating and a Serious Relationship" },
      { id: "10-13", number: "10.13", title: "Your Personal Dating Action Plan" },
      { id: "10-14", number: "10.14", title: "The Principles to Carry Into Every Future Relationship" },
    ],
  },
];

export const TOTAL_MODULES_COUNT = DATING_PLAYBOOK_MODULES.length;
export const TOTAL_LESSONS_COUNT = DATING_PLAYBOOK_MODULES.reduce(
  (sum, mod) => sum + mod.lessons.length,
  0
);
