/**
 * Drinks Catalog Data Definition for Plugd
 * 
 * Exactly the 18 specified drinks products with zero descriptions and zero prices.
 */

import { getDrinksProductImage, DEFAULT_DRINKS_IMAGE } from "./product-images";

export interface DrinksProduct {
  id: string;
  name: string;
  brand: string;
  category: "Drinks";
  subcategory: string;
  sectionId: string;
  sectionTitle: string;
  imageUrl: string;
  description: string;
  tags: string[];
  badge?: "HOT" | "TRENDING" | "VIRAL" | "NEW" | "POPULAR" | "PREMIUM" | "BESTSELLER";
  featured?: boolean;
  trending?: boolean;
  displayOrder: number;
}

export interface DrinksSection {
  id: string;
  title: string;
  subtitle: string;
  badge?: string;
  displayOrder: number;
  productIds: string[];
}

export const DRINKS_SECTIONS: DrinksSection[] = [
  {
    id: "all-drinks",
    title: "All Drinks",
    subtitle: "Beverages, refreshments, energy drinks, and dairy sips",
    badge: "🥤 Drinks",
    displayOrder: 1,
    productIds: [
      "diet-coke",
      "red-bull-energy-drink",
      "monster-energy-drink",
      "monster-ultra-energy-drink",
      "gatorade-energy-drink",
      "amul-masti-spiced-buttermilk",
      "bisleri-water-bottle",
      "minute-maid-pulpy-orange",
      "hell-energy-drink",
      "coca-cola-zero-sugar-pet",
      "smooth-chocolate-milk-drink",
      "coca-cola-zero-sugar-can",
      "soft-soya-milk-drink",
      "coolberg-cranberry-non-alcoholic-beer",
      "amul-protein-shake-blueberry",
      "sprite-zero",
      "thums-up",
      "pepsi",
      "pepsi-zero-sugar-soft-drink",
    ],
  },
];

export const RAW_DRINKS_PRODUCTS: Array<{
  id: string;
  name: string;
  brand: string;
  subcategory: string;
  sectionId: string;
  sectionTitle: string;
  description: string;
  tags: string[];
  badge?: "HOT" | "TRENDING" | "VIRAL" | "NEW" | "POPULAR" | "PREMIUM" | "BESTSELLER";
  featured?: boolean;
  trending?: boolean;
}> = [
  {
    id: "diet-coke",
    name: "Diet Coke",
    brand: "Coca-Cola",
    subcategory: "Soft Drinks",
    sectionId: "all-drinks",
    sectionTitle: "All Drinks",
    description: "",
    tags: ["coke", "diet", "soda", "sugar-free"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "red-bull-energy-drink",
    name: "Red Bull Energy Drink",
    brand: "Red Bull",
    subcategory: "Energy Drinks",
    sectionId: "all-drinks",
    sectionTitle: "All Drinks",
    description: "",
    tags: ["red-bull", "energy-drink", "caffeine"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "monster-energy-drink",
    name: "Monster Energy Drink",
    brand: "Monster",
    subcategory: "Energy Drinks",
    sectionId: "all-drinks",
    sectionTitle: "All Drinks",
    description: "",
    tags: ["monster", "energy-drink", "caffeine"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "monster-ultra-energy-drink",
    name: "Monster Ultra Energy Drink",
    brand: "Monster",
    subcategory: "Energy Drinks",
    sectionId: "all-drinks",
    sectionTitle: "All Drinks",
    description: "",
    tags: ["monster", "energy-drink", "caffeine", "sugar-free", "ultra"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "gatorade-energy-drink",
    name: "Gatorade Energy Drink",
    brand: "Gatorade",
    subcategory: "Sports Drinks",
    sectionId: "all-drinks",
    sectionTitle: "All Drinks",
    description: "",
    tags: ["gatorade", "sports-drink", "electrolytes"],
    badge: "POPULAR",
  },
  {
    id: "amul-masti-spiced-buttermilk",
    name: "Amul Masti Spiced Buttermilk",
    brand: "Amul",
    subcategory: "Dairy",
    sectionId: "all-drinks",
    sectionTitle: "All Drinks",
    description: "",
    tags: ["amul", "buttermilk", "chaas", "dairy"],
    badge: "BESTSELLER",
  },
  {
    id: "bisleri-water-bottle",
    name: "Bisleri Water Bottle",
    brand: "Bisleri",
    subcategory: "Water",
    sectionId: "all-drinks",
    sectionTitle: "All Drinks",
    description: "",
    tags: ["bisleri", "water", "mineral-water"],
    badge: "BESTSELLER",
  },
  {
    id: "minute-maid-pulpy-orange",
    name: "Minute Maid Pulpy Orange",
    brand: "Minute Maid",
    subcategory: "Juices",
    sectionId: "all-drinks",
    sectionTitle: "All Drinks",
    description: "",
    tags: ["minute-maid", "orange", "juice"],
    badge: "POPULAR",
  },
  {
    id: "hell-energy-drink",
    name: "Hell Energy Drink",
    brand: "Hell",
    subcategory: "Energy Drinks",
    sectionId: "all-drinks",
    sectionTitle: "All Drinks",
    description: "",
    tags: ["hell", "energy-drink", "caffeine"],
  },
  {
    id: "coca-cola-zero-sugar-pet",
    name: "Coca Cola Zero Sugar PET",
    brand: "Coca-Cola",
    subcategory: "Soft Drinks",
    sectionId: "all-drinks",
    sectionTitle: "All Drinks",
    description: "",
    tags: ["coca-cola", "zero-sugar", "soda"],
    badge: "POPULAR",
  },
  {
    id: "smooth-chocolate-milk-drink",
    name: "Smooth Chocolate Milk Drink",
    brand: "Amul",
    subcategory: "Dairy",
    sectionId: "all-drinks",
    sectionTitle: "All Drinks",
    description: "",
    tags: ["chocolate-milk", "amul", "dairy"],
  },
  {
    id: "coca-cola-zero-sugar-can",
    name: "Coca Cola Zero Sugar Can",
    brand: "Coca-Cola",
    subcategory: "Soft Drinks",
    sectionId: "all-drinks",
    sectionTitle: "All Drinks",
    description: "",
    tags: ["coca-cola", "zero-sugar", "can", "soda"],
  },
  {
    id: "soft-soya-milk-drink",
    name: "Soft Soya Milk Drink",
    brand: "Sofit",
    subcategory: "Dairy Alternatives",
    sectionId: "all-drinks",
    sectionTitle: "All Drinks",
    description: "",
    tags: ["soya-milk", "vegan", "dairy-free"],
  },
  {
    id: "coolberg-cranberry-non-alcoholic-beer",
    name: "Coolberg Cranberry Non Alcoholic Beer",
    brand: "Coolberg",
    subcategory: "Non-Alcoholic",
    sectionId: "all-drinks",
    sectionTitle: "All Drinks",
    description: "",
    tags: ["coolberg", "cranberry", "beer", "non-alcoholic"],
    badge: "TRENDING",
  },
  {
    id: "amul-protein-shake-blueberry",
    name: "Amul Protein Shake Blueberry",
    brand: "Amul",
    subcategory: "Protein Drinks",
    sectionId: "all-drinks",
    sectionTitle: "All Drinks",
    description: "",
    tags: ["amul", "protein", "shake", "blueberry"],
    badge: "HOT",
  },
  {
    id: "sprite-zero",
    name: "Sprite Zero",
    brand: "Sprite",
    subcategory: "Soft Drinks",
    sectionId: "all-drinks",
    sectionTitle: "All Drinks",
    description: "",
    tags: ["sprite", "zero-sugar", "lime", "soda"],
  },
  {
    id: "thums-up",
    name: "Thums Up",
    brand: "Thums Up",
    subcategory: "Soft Drinks",
    sectionId: "all-drinks",
    sectionTitle: "All Drinks",
    description: "",
    tags: ["thums-up", "cola", "indian-soft-drink"],
    badge: "BESTSELLER",
  },
  {
    id: "pepsi",
    name: "Pepsi",
    brand: "Pepsi",
    subcategory: "Soft Drinks",
    sectionId: "all-drinks",
    sectionTitle: "All Drinks",
    description: "",
    tags: ["pepsi", "cola", "soda"],
  },
  {
    id: "pepsi-zero-sugar-soft-drink",
    name: "Pepsi Zero Sugar Soft Drink",
    brand: "Pepsi",
    subcategory: "Soft Drinks",
    sectionId: "all-drinks",
    sectionTitle: "All Drinks",
    description: "",
    tags: ["pepsi", "zero-sugar", "soda"],
  },

  // === COFFEE (15 items) ===
  {
    id: "nescafe-classic-instant-coffee",
    name: "Nescafé Classic Instant Coffee",
    brand: "Nescafé",
    subcategory: "Coffee",
    sectionId: "coffee",
    sectionTitle: "Coffee",
    description: "",
    tags: ["coffee", "instant-coffee", "nescafe"],
  },
  {
    id: "nescafe-sunrise-instant-coffee",
    name: "Nescafé Sunrise Instant Coffee",
    brand: "Nescafé",
    subcategory: "Coffee",
    sectionId: "coffee",
    sectionTitle: "Coffee",
    description: "",
    tags: ["coffee", "instant-coffee", "nescafe"],
  },
  {
    id: "bru-instant-coffee",
    name: "Bru Instant Coffee",
    brand: "Bru",
    subcategory: "Coffee",
    sectionId: "coffee",
    sectionTitle: "Coffee",
    description: "",
    tags: ["coffee", "instant-coffee", "bru"],
  },
  {
    id: "bru-gold-instant-coffee",
    name: "Bru Gold Instant Coffee",
    brand: "Bru",
    subcategory: "Coffee",
    sectionId: "coffee",
    sectionTitle: "Coffee",
    description: "",
    tags: ["coffee", "instant-coffee", "bru"],
  },
  {
    id: "continental-xtra-coffee",
    name: "Continental Xtra Coffee",
    brand: "Continental",
    subcategory: "Coffee",
    sectionId: "coffee",
    sectionTitle: "Coffee",
    description: "",
    tags: ["coffee", "instant-coffee", "continental"],
  },
  {
    id: "tata-coffee-grand",
    name: "Tata Coffee Grand",
    brand: "Tata",
    subcategory: "Coffee",
    sectionId: "coffee",
    sectionTitle: "Coffee",
    description: "",
    tags: ["coffee", "instant-coffee", "tata"],
  },
  {
    id: "starbucks-premium-instant-coffee",
    name: "Starbucks Premium Instant Coffee",
    brand: "Starbucks",
    subcategory: "Coffee",
    sectionId: "coffee",
    sectionTitle: "Coffee",
    description: "",
    tags: ["coffee", "instant-coffee", "starbucks"],
  },
  {
    id: "starbucks-frappuccino-coffee",
    name: "Starbucks Frappuccino Coffee",
    brand: "Starbucks",
    subcategory: "Coffee",
    sectionId: "coffee",
    sectionTitle: "Coffee",
    description: "",
    tags: ["coffee", "cold-coffee", "frappuccino", "starbucks"],
  },
  {
    id: "rage-coffee",
    name: "Rage Coffee",
    brand: "Rage Coffee",
    subcategory: "Coffee",
    sectionId: "coffee",
    sectionTitle: "Coffee",
    description: "",
    tags: ["coffee", "instant-coffee", "rage"],
  },
  {
    id: "sleepy-owl-cold-coffee",
    name: "Sleepy Owl Cold Coffee",
    brand: "Sleepy Owl",
    subcategory: "Coffee",
    sectionId: "coffee",
    sectionTitle: "Coffee",
    description: "",
    tags: ["coffee", "cold-coffee", "sleepy-owl"],
  },
  {
    id: "bevzilla-instant-coffee",
    name: "Bevzilla Instant Coffee",
    brand: "Bevzilla",
    subcategory: "Coffee",
    sectionId: "coffee",
    sectionTitle: "Coffee",
    description: "",
    tags: ["coffee", "instant-coffee", "bevzilla"],
  },
  {
    id: "country-bean-vanilla-coffee",
    name: "Country Bean Vanilla Coffee",
    brand: "Country Bean",
    subcategory: "Coffee",
    sectionId: "coffee",
    sectionTitle: "Coffee",
    description: "",
    tags: ["coffee", "instant-coffee", "country-bean"],
  },
  {
    id: "blue-tokai-coffee",
    name: "Blue Tokai Coffee",
    brand: "Blue Tokai",
    subcategory: "Coffee",
    sectionId: "coffee",
    sectionTitle: "Coffee",
    description: "",
    tags: ["coffee", "blue-tokai", "ground-coffee"],
  },
  {
    id: "third-wave-coffee",
    name: "Third Wave Coffee",
    brand: "Third Wave",
    subcategory: "Coffee",
    sectionId: "coffee",
    sectionTitle: "Coffee",
    description: "",
    tags: ["coffee", "third-wave", "roast"],
  },
  {
    id: "nescafe-gold",
    name: "Nescafé Gold",
    brand: "Nescafé",
    subcategory: "Coffee",
    sectionId: "coffee",
    sectionTitle: "Coffee",
    description: "",
    tags: ["coffee", "nescafe", "gold"],
  },

  // === COLD DRINKS & JUICES (25 items) ===
  {
    id: "frooti",
    name: "Frooti",
    brand: "Parle Agro",
    subcategory: "Cold Drinks & Juices",
    sectionId: "cold-drinks-juices",
    sectionTitle: "Cold Drinks & Juices",
    description: "",
    tags: ["frooti", "mango", "juice"],
  },
  {
    id: "maaza",
    name: "Maaza",
    brand: "Coca-Cola",
    subcategory: "Cold Drinks & Juices",
    sectionId: "cold-drinks-juices",
    sectionTitle: "Cold Drinks & Juices",
    description: "",
    tags: ["maaza", "mango", "juice"],
  },
  {
    id: "appy-fizz",
    name: "Appy Fizz",
    brand: "Parle Agro",
    subcategory: "Cold Drinks & Juices",
    sectionId: "cold-drinks-juices",
    sectionTitle: "Cold Drinks & Juices",
    description: "",
    tags: ["appy-fizz", "apple", "sparkling"],
  },
  {
    id: "slice",
    name: "Slice",
    brand: "PepsiCo",
    subcategory: "Cold Drinks & Juices",
    sectionId: "cold-drinks-juices",
    sectionTitle: "Cold Drinks & Juices",
    description: "",
    tags: ["slice", "mango", "juice"],
  },
  {
    id: "paper-boat-aamras",
    name: "Paper Boat Aamras",
    brand: "Paper Boat",
    subcategory: "Cold Drinks & Juices",
    sectionId: "cold-drinks-juices",
    sectionTitle: "Cold Drinks & Juices",
    description: "",
    tags: ["paper-boat", "aamras", "mango"],
  },
  {
    id: "paper-boat-coconut-water",
    name: "Paper Boat Coconut Water",
    brand: "Paper Boat",
    subcategory: "Cold Drinks & Juices",
    sectionId: "cold-drinks-juices",
    sectionTitle: "Cold Drinks & Juices",
    description: "",
    tags: ["paper-boat", "coconut-water"],
  },
  {
    id: "real-fruit-power-orange",
    name: "Real Fruit Power Orange",
    brand: "Real",
    subcategory: "Cold Drinks & Juices",
    sectionId: "cold-drinks-juices",
    sectionTitle: "Cold Drinks & Juices",
    description: "",
    tags: ["real", "orange", "juice"],
  },
  {
    id: "real-fruit-power-mixed-fruit",
    name: "Real Fruit Power Mixed Fruit",
    brand: "Real",
    subcategory: "Cold Drinks & Juices",
    sectionId: "cold-drinks-juices",
    sectionTitle: "Cold Drinks & Juices",
    description: "",
    tags: ["real", "mixed-fruit", "juice"],
  },
  {
    id: "tropicana-orange-juice",
    name: "Tropicana Orange Juice",
    brand: "Tropicana",
    subcategory: "Cold Drinks & Juices",
    sectionId: "cold-drinks-juices",
    sectionTitle: "Cold Drinks & Juices",
    description: "",
    tags: ["tropicana", "orange", "juice"],
  },
  {
    id: "tropicana-apple-juice",
    name: "Tropicana Apple Juice",
    brand: "Tropicana",
    subcategory: "Cold Drinks & Juices",
    sectionId: "cold-drinks-juices",
    sectionTitle: "Cold Drinks & Juices",
    description: "",
    tags: ["tropicana", "apple", "juice"],
  },
  {
    id: "b-natural-mixed-fruit",
    name: "B Natural Mixed Fruit",
    brand: "B Natural",
    subcategory: "Cold Drinks & Juices",
    sectionId: "cold-drinks-juices",
    sectionTitle: "Cold Drinks & Juices",
    description: "",
    tags: ["b-natural", "mixed-fruit", "juice"],
  },
  {
    id: "b-natural-orange-juice",
    name: "B Natural Orange Juice",
    brand: "B Natural",
    subcategory: "Cold Drinks & Juices",
    sectionId: "cold-drinks-juices",
    sectionTitle: "Cold Drinks & Juices",
    description: "",
    tags: ["b-natural", "orange", "juice"],
  },
  {
    id: "paper-boat-aam-panna",
    name: "Paper Boat Aam Panna",
    brand: "Paper Boat",
    subcategory: "Cold Drinks & Juices",
    sectionId: "cold-drinks-juices",
    sectionTitle: "Cold Drinks & Juices",
    description: "",
    tags: ["paper-boat", "aam-panna"],
  },
  {
    id: "paper-boat-jaljeera",
    name: "Paper Boat Jaljeera",
    brand: "Paper Boat",
    subcategory: "Cold Drinks & Juices",
    sectionId: "cold-drinks-juices",
    sectionTitle: "Cold Drinks & Juices",
    description: "",
    tags: ["paper-boat", "jaljeera"],
  },
  {
    id: "coconut-water",
    name: "Coconut Water",
    brand: "Fresh",
    subcategory: "Cold Drinks & Juices",
    sectionId: "cold-drinks-juices",
    sectionTitle: "Cold Drinks & Juices",
    description: "",
    tags: ["coconut-water", "hydration"],
  },
  {
    id: "limca",
    name: "Limca",
    brand: "Coca-Cola",
    subcategory: "Cold Drinks & Juices",
    sectionId: "cold-drinks-juices",
    sectionTitle: "Cold Drinks & Juices",
    description: "",
    tags: ["limca", "lime", "lemon", "soft-drink"],
  },
  {
    id: "7up",
    name: "7UP",
    brand: "PepsiCo",
    subcategory: "Cold Drinks & Juices",
    sectionId: "cold-drinks-juices",
    sectionTitle: "Cold Drinks & Juices",
    description: "",
    tags: ["7up", "lime", "soda"],
  },
  {
    id: "mirinda",
    name: "Mirinda",
    brand: "PepsiCo",
    subcategory: "Cold Drinks & Juices",
    sectionId: "cold-drinks-juices",
    sectionTitle: "Cold Drinks & Juices",
    description: "",
    tags: ["mirinda", "orange", "soda"],
  },
  {
    id: "mountain-dew",
    name: "Mountain Dew",
    brand: "PepsiCo",
    subcategory: "Cold Drinks & Juices",
    sectionId: "cold-drinks-juices",
    sectionTitle: "Cold Drinks & Juices",
    description: "",
    tags: ["mountain-dew", "soda"],
  },
  {
    id: "sting-energy-drink",
    name: "Sting Energy Drink",
    brand: "PepsiCo",
    subcategory: "Cold Drinks & Juices",
    sectionId: "cold-drinks-juices",
    sectionTitle: "Cold Drinks & Juices",
    description: "",
    tags: ["sting", "energy-drink"],
  },
  {
    id: "kinley-soda",
    name: "Kinley Soda",
    brand: "Coca-Cola",
    subcategory: "Cold Drinks & Juices",
    sectionId: "cold-drinks-juices",
    sectionTitle: "Cold Drinks & Juices",
    description: "",
    tags: ["kinley", "soda", "mixer"],
  },
  {
    id: "schweppes-tonic-water",
    name: "Schweppes Tonic Water",
    brand: "Schweppes",
    subcategory: "Cold Drinks & Juices",
    sectionId: "cold-drinks-juices",
    sectionTitle: "Cold Drinks & Juices",
    description: "",
    tags: ["schweppes", "tonic-water", "mixer"],
  },
  {
    id: "nestea-lemon-iced-tea",
    name: "Nestea Lemon Iced Tea",
    brand: "Nestlé",
    subcategory: "Cold Drinks & Juices",
    sectionId: "cold-drinks-juices",
    sectionTitle: "Cold Drinks & Juices",
    description: "",
    tags: ["nestea", "iced-tea", "lemon"],
  },
  {
    id: "paper-boat-neer-more",
    name: "Paper Boat Neer More",
    brand: "Paper Boat",
    subcategory: "Cold Drinks & Juices",
    sectionId: "cold-drinks-juices",
    sectionTitle: "Cold Drinks & Juices",
    description: "",
    tags: ["paper-boat", "neer-more", "buttermilk"],
  },
  {
    id: "raw-pressery-cold-pressed-orange-juice",
    name: "Raw Pressery Cold-Pressed Orange Juice",
    brand: "RAW Pressery",
    subcategory: "Cold Drinks & Juices",
    sectionId: "cold-drinks-juices",
    sectionTitle: "Cold Drinks & Juices",
    description: "",
    tags: ["raw-pressery", "orange", "cold-pressed", "juice"],
  },
];

export function getFullDrinksCatalog(): DrinksProduct[] {
  return RAW_DRINKS_PRODUCTS.map((p, idx) => ({
    id: p.id,
    name: p.name,
    brand: p.brand,
    category: "Drinks",
    subcategory: p.subcategory,
    sectionId: p.sectionId,
    sectionTitle: p.sectionTitle,
    imageUrl: getDrinksProductImage(p.id) || DEFAULT_DRINKS_IMAGE,
    description: "",
    tags: p.tags,
    badge: p.badge,
    featured: Boolean(p.featured),
    trending: Boolean(p.trending),
    displayOrder: idx,
  }));
}

export const DRINKS_STARTING_COUNTS: Record<string, number> = {};

