/**
 * Curated Electronics Catalog Data Definition for Plugd
 * 
 * EXACTLY the 11 specified subcategories:
 * 1. Mobile (24 products)
 * 2. Laptops (25 products)
 * 3. Audio (23 products)
 * 4. Gaming (17 products)
 * 5. Keyboards & Mice (12 products)
 * 6. Cameras & Streaming (11 products)
 * 7. Storage & Computing (10 products)
 * 8. Displays & Projectors (7 products)
 * 9. Smart Home (10 products)
 * 10. Watches (8 products)
 * 11. Other (10 products)
 * 
 * Total: 157 products, all with authentic supplied image URLs.
 */

import { getElectronicsProductImage, DEFAULT_ELECTRONICS_IMAGE } from "./product-images";

export interface ElectronicsProduct {
  id: string;
  name: string;
  brand: string;
  category: "Electronics";
  subcategory: string;
  subgroup?: string;
  sectionId: string;
  sectionTitle: string;
  imageUrl: string;
  description: string;
  tags: string[];
  featured?: boolean;
  trending?: boolean;
  displayOrder: number;
}

export interface ElectronicsSection {
  id: string;
  title: string;
  subtitle: string;
  badge?: string;
  displayOrder: number;
  productIds: string[];
}

export const ELECTRONICS_TOP_PICKS_SLUGS: string[] = [
  "iphone-duo",
  "iphone-18-pro-max",
  "iphone-18-pro-max-burgundy",
  "iphone-18-pro",
  "iphone-17-pro-max",
  "iphone-17-pro",
  "samsung-galaxy-s26-ultra",
  "samsung-galaxy-z-fold8-ultra",
  "google-pixel-11-pro-xl",
  "ipad-pro",
  "macbook-pro-14",
  "macbook-pro-16",
  "macbook-air-13",
  "macbook-air-15",
  "airpods-pro",
  "airpods-max",
  "sony-wh-1000xm5",
  "playstation-5",
  "playstation-5-console-standard",
  "dualsense-wireless-controller-white",
  "logitech-g502-hero-high-performance-gaming-mouse",
  "amazon-echo-show-8",
  "apple-watch",
  "apple-watch-ultra"
];

export const RAW_ELECTRONICS_PRODUCTS: Array<{
  id: string;
  name: string;
  brand: string;
  subcategory: string;
  imageUrl: string;
  tags: string[];
  featured?: boolean;
  trending?: boolean;
}> = [
  {
    id: "iphone-duo",
    name: "iPhone Duo",
    brand: "Apple",
    subcategory: "Mobile",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRt-Py_mtnnO9Wx2oMpAm_6MlBM8Ts8Y5l4GHL_ZZiFA&s=10",
    tags: ["apple","mobile","iphone","duo"],
    featured: true,
  },
  {
    id: "iphone-18-pro-max",
    name: "iPhone 18 Pro Max (Black)",
    brand: "Apple",
    subcategory: "Mobile",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjjpBwTXJjm8C0bFEFG__PRqxwUokGeq-XZ01MXVgIXV15nwWvNIycsEZC&s=10",
    tags: ["apple","mobile","iphone","18","pro","max","black"],
    featured: true,
  },
  {
    id: "iphone-18-pro-max-burgundy",
    name: "iPhone 18 Pro Max (Burgundy)",
    brand: "Apple",
    subcategory: "Mobile",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiFWSx1IUTIylE_EDVo-tI_zIwfb5dJD2zIVz5TF8KHw&s=10",
    tags: ["apple","mobile","iphone","18","pro","max","burgundy"],
    featured: true,
  },
  {
    id: "iphone-18-pro",
    name: "iPhone 18 Pro",
    brand: "Apple",
    subcategory: "Mobile",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScWhJuGRg-lc4Edazc7Y-wpw2-vCCTmbO9R0Ih6BrF8g&s=10",
    tags: ["apple","mobile","iphone","18","pro"],
    featured: true,
  },
  {
    id: "iphone-17-pro-max",
    name: "iPhone 17 Pro Max",
    brand: "Apple",
    subcategory: "Mobile",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7T0QVTazqX6Ub2Z-hfyRuY3O5ZafA-8YBpu-TQBEC55fJdUDrKFwjBySO&s=10",
    tags: ["apple","mobile","iphone","17","pro","max"],
    featured: true,
  },
  {
    id: "iphone-17-pro",
    name: "iPhone 17 Pro",
    brand: "Apple",
    subcategory: "Mobile",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQB7MBW8XJb9nXA-K9zfML1nFC0-MDPLr0MbKNaIwuQRhqciGVLIYErP0rC&s=10",
    tags: ["apple","mobile","iphone","17","pro"],
    featured: true,
  },
  {
    id: "iphone-17",
    name: "iPhone 17",
    brand: "Apple",
    subcategory: "Mobile",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCo2xgLwt3YdBN4wa94lcegC8IdTtSxyURyCnV1z4hHVbtB8UyutnVAiNw&s=10",
    tags: ["apple","mobile","iphone","17"],
  },
  {
    id: "iphone-air",
    name: "iPhone Air",
    brand: "Apple",
    subcategory: "Mobile",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsKB0_WWwHoh8zHPmxe9jqBxDg4hLF4lZNEDKSKVgA9w&s=10",
    tags: ["apple","mobile","iphone","air"],
  },
  {
    id: "samsung-galaxy-s26-ultra",
    name: "Samsung Galaxy S26 Ultra",
    brand: "Samsung",
    subcategory: "Mobile",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSV4NfcaCn-7pYsN6ffwWnBTOaUaqYGYTFDhlp9MP1uawSwDRMrh6oFI0Q&s=10",
    tags: ["samsung","mobile","galaxy","s26","ultra"],
    featured: true,
  },
  {
    id: "samsung-galaxy-s26",
    name: "Samsung Galaxy S26",
    brand: "Samsung",
    subcategory: "Mobile",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwEWdPDdxwU80fAdkqaFezr_WngzB5AFTUlOOwEjuSAQ&s=10",
    tags: ["samsung","mobile","galaxy","s26"],
  },
  {
    id: "samsung-galaxy-z-fold8-ultra",
    name: "Samsung Galaxy Z Fold8 Ultra",
    brand: "Samsung",
    subcategory: "Mobile",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_po2gyE4o-kIboEJLG2ycd0zoJLiGizJH5PiiTaxVOE1RKN-kwDChMEfa&s=10",
    tags: ["samsung","mobile","galaxy","z","fold8","ultra"],
    featured: true,
  },
  {
    id: "samsung-galaxy-z-fold8",
    name: "Samsung Galaxy Z Fold8",
    brand: "Samsung",
    subcategory: "Mobile",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJFuGZ_uo-3uO9pohaLYyhAzUNnKbtcDRJnL5VlROKShzjUEjrIpWp6cBF&s=10",
    tags: ["samsung","mobile","galaxy","z","fold8"],
  },
  {
    id: "google-pixel-11-pro-xl",
    name: "Google Pixel 11 Pro XL",
    brand: "Google",
    subcategory: "Mobile",
    imageUrl: "https://media-ik.croma.com/Croma%20Assets/Communication/Mobiles/Images/325392_0_fI1oSY8Vf.png?updatedAt=1786601024435&tr=w-600",
    tags: ["google","mobile","pixel","11","pro","xl"],
    featured: true,
  },
  {
    id: "google-pixel-11-pro",
    name: "Google Pixel 11 Pro",
    brand: "Google",
    subcategory: "Mobile",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRguaqYpQ3klgGaA3ck2tIuhlpK5mdF6L8SEw3P1MnzDZ6Y5vnwbxODASgn&s=10",
    tags: ["google","mobile","pixel","11","pro"],
  },
  {
    id: "google-pixel-11-pro-fold",
    name: "Google Pixel 11 Pro Fold",
    brand: "Google",
    subcategory: "Mobile",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxz_x6UiUZ6H2aJPKDUzx1mqeS4eQTFcEBYlYqvRRy6rpV0gNxX5cp888&s=10",
    tags: ["google","mobile","pixel","11","pro","fold"],
  },
  {
    id: "google-pixel-11",
    name: "Google Pixel 11",
    brand: "Google",
    subcategory: "Mobile",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTk7ovV0Gaq0-YJcS5bNbkwuArh9LUToNiqyZzXzS_sT-_f3hDFZbj0x3ur&s=10",
    tags: ["google","mobile","pixel","11"],
  },
  {
    id: "nothing-phone-4a",
    name: "Nothing Phone (4a)",
    brand: "Nothing",
    subcategory: "Mobile",
    imageUrl: "https://www.myg.in/images/thumbnails/300/300/detailed/131/Nothing-phone-4a-5g-black-12gb-256gb-Back-View__1_.webp.png",
    tags: ["nothing","mobile","phone","4a"],
  },
  {
    id: "nothing-phone-4a-pro",
    name: "Nothing Phone (4a) Pro",
    brand: "Nothing",
    subcategory: "Mobile",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiFWtPH_ApPB_hrr02wPVB5wnKhw01XpMXIhysMieAiA&s",
    tags: ["nothing","mobile","phone","4a","pro"],
  },
  {
    id: "nothing-phone-4b",
    name: "Nothing Phone (4b)",
    brand: "Nothing",
    subcategory: "Mobile",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbge3-Wirm8f0cuxUgwTxSIqla9ijnOmFKDY4pvFKMS7aNdyWmIDSWEsk&s=10",
    tags: ["nothing","mobile","phone","4b"],
  },
  {
    id: "nothing-phone-3",
    name: "Nothing Phone (3)",
    brand: "Nothing",
    subcategory: "Mobile",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT58xI9T6wwZQWR4eQR-ZvLG42J36KQUgDCDLtGPZ3HnRG4jpZVfQt5u05Y&s=10",
    tags: ["nothing","mobile","phone","3"],
  },
  {
    id: "nothing-phone-3a-pro",
    name: "Nothing Phone (3a) Pro",
    brand: "Nothing",
    subcategory: "Mobile",
    imageUrl: "https://cdn.shopify.com/s/files/1/0586/3270/0077/files/ArcPro1352x1352-Black-Glyphon.png?v=1740649967",
    tags: ["nothing","mobile","phone","3a","pro"],
  },
  {
    id: "nothing-phone-3a",
    name: "Nothing Phone (3a)",
    brand: "Nothing",
    subcategory: "Mobile",
    imageUrl: "https://cdn.shopify.com/s/files/1/0586/3270/0077/files/Arc1352x1352-Black-Glyphon_4677e90c-2628-407c-b286-e6b96238dedf.png?v=1740649954",
    tags: ["nothing","mobile","phone","3a"],
  },
  {
    id: "ipad-pro",
    name: "iPad Pro",
    brand: "Apple",
    subcategory: "Mobile",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEm5aYxF1PdMkzHdKLawFuRJqmzLGVsmi999GGtTkQrw&s=10",
    tags: ["apple","mobile","ipad","pro"],
    featured: true,
  },
  {
    id: "ipad-air",
    name: "iPad Air",
    brand: "Apple",
    subcategory: "Mobile",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlHykL_BQuML6hT5PG8TIIvh3qLtoTbG8cJCqqRJfqVQ&s=10",
    tags: ["apple","mobile","ipad","air"],
  },
  {
    id: "ipad",
    name: "iPad",
    brand: "Apple",
    subcategory: "Mobile",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbRnwaY_Kp1LKyKFGBjyThFMOBABn4rySGYp00qgeKnw&s=10",
    tags: ["apple","mobile","ipad"],
  },
  {
    id: "macbook-pro-14",
    name: "MacBook Pro 14\"",
    brand: "Apple",
    subcategory: "Laptops",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgRdG_AlB3AL1ikG4LCKqSyyqGu77kaIxVupZhXUaBKhpIQN_L105A6wI&s=10",
    tags: ["apple","laptops","macbook","pro","14"],
    featured: true,
  },
  {
    id: "macbook-pro-16",
    name: "MacBook Pro 16\"",
    brand: "Apple",
    subcategory: "Laptops",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwkDHiWMemHQdQsD43c7WLYyweCOQ9t1HB2rhpt_p4E7vPAQ0MXRyHM8c&s=10",
    tags: ["apple","laptops","macbook","pro","16"],
    featured: true,
  },
  {
    id: "macbook-air-13",
    name: "MacBook Air 13\"",
    brand: "Apple",
    subcategory: "Laptops",
    imageUrl: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/macbook-air-size-select-202601-13inch_FMT_WHH?wid=690&hei=720&fmt=jpeg&qlt=90&.v=1767638906961",
    tags: ["apple","laptops","macbook","air","13"],
    featured: true,
  },
  {
    id: "macbook-air-15",
    name: "MacBook Air 15\"",
    brand: "Apple",
    subcategory: "Laptops",
    imageUrl: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/macbook-air-size-select-202601-15inch_FMT_WHH?wid=690&hei=720&fmt=p-jpg&qlt=80&.v=YTFkSnBPS2tMZFdhaFNRRkx6VnJZZ0dOZysray9HQ25xUFBjc1l1SVBQRG5WazRSZDNzTjJDN0R4MnByYUd0N3hqT1k5MlJQRXZIWm56SHJna3BlQjdZc3g4ZkhUVEc0bFNFL1l3MHJZd1d2ZVJqR3ZtdzFQWlFSUElOTnpGUkk&traceId=1",
    tags: ["apple","laptops","macbook","air","15"],
    featured: true,
  },
  {
    id: "macbook-neo",
    name: "MacBook Neo",
    brand: "Apple",
    subcategory: "Laptops",
    imageUrl: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/macbook-neo-color-unselect-202603-gallery-1_FMT_WHH?wid=690&hei=720&fmt=p-jpg&qlt=80&.v=TytZbDBUUnRqRElRcFlBSHpmZVVDK3BoR2lIdGdhMDNQSUZrOHIycWd6Vk5EdTEzMnhDNnFqUTNLSW9SdzdIN1RXdm1tTmFzNjBGQmdSRVIyOXZjeGM2c3NSYUM4YjA0RTQxLytvRzE4M0F1d1cwdVFFUmlqTVkxb0FUYmd6QzluUjhtbEpESTNWUVNxQ1UzUkRHZWZB&traceId=1",
    tags: ["apple","laptops","macbook","neo"],
  },
  {
    id: "mac-mini",
    name: "Mac Mini",
    brand: "Apple",
    subcategory: "Laptops",
    imageUrl: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/mac-mini-chip-unselect-202608-gallery-1_FMT_WHH?wid=690&hei=720&fmt=p-jpg&qlt=80&.v=d1pXNGRPZVVoYmlPOFhNR3g4R2wxRXR2WVdiVFJadS9sN05uYmNBWEpHY2JLeEpwTVdId3c2M0IzMUdUQVhQaXNQSmo4S3Y2K1lXWjJLUjd2dkU2MDJ5aFM4QSthSG1nSUl6WXJQME1SZ2xDMWVkeVhwejgra0VIR1dwYS83bjNoNG5zaDVpV0hVYUV5eVFvejlsM2J3&traceId=1",
    tags: ["apple","laptops","mac","mini"],
  },
  {
    id: "mac-studio",
    name: "Mac Studio",
    brand: "Apple",
    subcategory: "Laptops",
    imageUrl: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/mac-studio-chip-unselect-202608-gallery-6_FMT_WHH?wid=690&hei=720&fmt=p-jpg&qlt=80&.v=Q0wvVFlkSnZCd1pNaGQ2aENud1pOd2h5dEROb21tWXk1TTk5REtzUUVvb1k5bjZ6blpHZHViSEYrdHJIRTlYRjA4VVhrakdBdzU2bHF2VEZpM1BtZ2laSE1Qa0haZTFvMWVJTkxjaWwxSnp1ZFJ3blBadlVEM3BXSUNWS3lEKzBzTlNiZXZUN3BsbGxYYldQcTlhaFJB&traceId=1",
    tags: ["apple","laptops","mac","studio"],
  },
  {
    id: "imac",
    name: "iMac",
    brand: "Apple",
    subcategory: "Laptops",
    imageUrl: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/imac-color-unselect-202601-gallery-1_FMT_WHH?wid=690&hei=720&fmt=p-jpg&qlt=80&.v=YUhqSVNUTWk1djNVekVIdjhjMjArWDZwVTFScmpKbWRKUXNHNFhkOTgxUERrUGZyd0l4OW40NURXZjNaZ0VBeEFhYkFDMDMraDRZMENUbDZQbjBoQ0swekI5ZWpRa0o2WWdVYzdzTUdBdFVURXowNXQ3OGpLVDFWRU9qQzExd0w&traceId=1",
    tags: ["apple","laptops","imac"],
  },
  {
    id: "dell-xps-13",
    name: "Dell XPS 13",
    brand: "Dell",
    subcategory: "Laptops",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRiyco_n2vtX7Be9hmxFcIXWFKKMa9LBTNR_kiv0XiGHkUm3UPPRWeJho&s=10",
    tags: ["dell","laptops","xps","13"],
  },
  {
    id: "dell-xps-16",
    name: "Dell XPS 16",
    brand: "Dell",
    subcategory: "Laptops",
    imageUrl: "https://static.hub.91mobiles.com/wp-content/uploads/sites/9/2026/06/Dell-XPS-16-creator-edition-announced.png?tr=q-70",
    tags: ["dell","laptops","xps","16"],
  },
  {
    id: "microsoft-surface-laptop",
    name: "Microsoft Surface Laptop",
    brand: "Microsoft",
    subcategory: "Laptops",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHmgCczSXWw3x5alfRqcydVy4RXz9bPhI8eDytuCV82xKtAsR6GnOPhUw&s=10",
    tags: ["microsoft","laptops","surface","laptop"],
  },
  {
    id: "microsoft-surface-pro",
    name: "Microsoft Surface Pro",
    brand: "Microsoft",
    subcategory: "Laptops",
    imageUrl: "https://media.wired.com/photos/5b22da4d66dc162128d464cf/master/w_2560%2Cc_limit/mircosoft-TAFA.jpg",
    tags: ["microsoft","laptops","surface","pro"],
  },
  {
    id: "lenovo-thinkpad-x1-carbon",
    name: "Lenovo ThinkPad X1 Carbon",
    brand: "Lenovo",
    subcategory: "Laptops",
    imageUrl: "https://m.media-amazon.com/images/I/51TjZ1nza0L.jpg",
    tags: ["lenovo","laptops","thinkpad","x1","carbon"],
  },
  {
    id: "lenovo-yoga-pro",
    name: "Lenovo Yoga Pro",
    brand: "Lenovo",
    subcategory: "Laptops",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSplW2p6Wq1el9k-rvVZgv53FxuFIwWAwtdiOROBV5Z-Q&s=10",
    tags: ["lenovo","laptops","yoga","pro"],
  },
  {
    id: "hp-spectre-x360",
    name: "HP Spectre x360",
    brand: "HP",
    subcategory: "Laptops",
    imageUrl: "https://m.media-amazon.com/images/I/819PtcwCiBL._AC_UF350,350_QL80_.jpg",
    tags: ["hp","laptops","spectre","x360"],
  },
  {
    id: "asus-zenbook",
    name: "ASUS Zenbook",
    brand: "ASUS",
    subcategory: "Laptops",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBBgQiNfZzI01l4K6n9CYzrgYAaF8YAf2V0Pbvruir-Q&s=10",
    tags: ["asus","laptops","zenbook"],
  },
  {
    id: "asus-proart",
    name: "ASUS ProArt",
    brand: "ASUS",
    subcategory: "Laptops",
    imageUrl: "https://m.media-amazon.com/images/I/81CFn-NfutL.jpg",
    tags: ["asus","laptops","proart"],
  },
  {
    id: "acer-swift",
    name: "Acer Swift",
    brand: "Acer",
    subcategory: "Laptops",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRN7mTR9OmA_j22JhO8pQKUrPXu3xVIatynAO7w_q90VY2xULMlRX-Pvei_&s=10",
    tags: ["acer","laptops","swift"],
  },
  {
    id: "razer-blade-16",
    name: "Razer Blade 16",
    brand: "Razer",
    subcategory: "Laptops",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIF5RaWyLzosCXRZElCj1wmpDTMn8-bk6egnPgZ-6Tng&s=10",
    tags: ["razer","laptops","blade","16"],
  },
  {
    id: "asus-rog-strix",
    name: "ASUS ROG Strix",
    brand: "ASUS",
    subcategory: "Laptops",
    imageUrl: "https://in.store.asus.com/media/catalog/product/1/_/1._g614pr-rv032ws__main_g614pr.jpg",
    tags: ["asus","laptops","rog","strix"],
  },
  {
    id: "asus-rog-zephyrus-g14",
    name: "ASUS ROG Zephyrus G14",
    brand: "ASUS",
    subcategory: "Laptops",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwz3OkObwNeGykUjCxMPaguSQ-n5fDCTaKbwKi0iJc8Q&s=10",
    tags: ["asus","laptops","rog","zephyrus","g14"],
  },
  {
    id: "lenovo-legion-pro",
    name: "Lenovo Legion Pro",
    brand: "Lenovo",
    subcategory: "Laptops",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsmYTGqX7F8awcyPnVxz1jQxa5nZTLk2riGIv09HF_jw&s=10",
    tags: ["lenovo","laptops","legion","pro"],
  },
  {
    id: "alienware-gaming-laptop",
    name: "Alienware Gaming Laptop",
    brand: "Alienware",
    subcategory: "Laptops",
    imageUrl: "https://media.wired.com/photos/59e9500c06a2232e82ba9bdd/master/w_2560%2Cc_limit/Dell_TA.jpg",
    tags: ["alienware","laptops","gaming","laptop"],
  },
  {
    id: "msi-raider",
    name: "MSI Raider",
    brand: "MSI",
    subcategory: "Laptops",
    imageUrl: "https://gamingicons.in/wp-content/uploads/2025/07/Raider-18HX.png",
    tags: ["msi","laptops","raider"],
  },
  {
    id: "acer-predator-helios",
    name: "Acer Predator Helios",
    brand: "Acer",
    subcategory: "Laptops",
    imageUrl: "https://m.media-amazon.com/images/I/51q3f4NuyIL.jpg",
    tags: ["acer","laptops","predator","helios"],
  },
  {
    id: "airpods",
    name: "AirPods",
    brand: "Apple",
    subcategory: "Audio",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSc2KGycdwHD2kGO1BU2g296PihHDCrZo7liKuGafMQEm4dGz4MJi2UrtOr&s=10",
    tags: ["apple","audio","airpods"],
  },
  {
    id: "airpods-pro",
    name: "AirPods Pro",
    brand: "Apple",
    subcategory: "Audio",
    imageUrl: "https://www.apple.com/v/airpods-pro/t/images/overview/welcome/hero__b0eal3mn03ua_large.jpg",
    tags: ["apple","audio","airpods","pro"],
    featured: true,
  },
  {
    id: "airpods-max",
    name: "AirPods Max",
    brand: "Apple",
    subcategory: "Audio",
    imageUrl: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/airpods-max-select-202409-midnight_FV1_FMT_WHH?wid=752&hei=636&fmt=jpeg&qlt=90&.v=azQxRkVJKzd6V3J0aGNqWFhLMzBmdmVWNWdHYnp5cHkwMldsSElEOHpyd2ttdW5wTmRBL1NETnlMVldNRXJ0RFZOSzlQRTFSbHNFZCtKQi9Wc2w5b3I2TGhYaGhMVkJpQ2RGWWVURTZNbXphV29iOFBIcjE1bWVvKzVNUlpwYys",
    tags: ["apple","audio","airpods","max"],
    featured: true,
  },
  {
    id: "sony-wf-1000xm6",
    name: "Sony WF-1000XM6",
    brand: "Sony",
    subcategory: "Audio",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEjd6fqEZyPAr6iS5zMG0lqc7RGdYzl48DlRGoRcSvmw&s=10",
    tags: ["sony","audio","wf","1000xm6"],
  },
  {
    id: "sony-wf-1000xm5",
    name: "Sony WF-1000XM5",
    brand: "Sony",
    subcategory: "Audio",
    imageUrl: "https://sony.scene7.com/is/image/sonyglobalsolutions/Primary_image_black?$S7Product$&fmt=png-alpha",
    tags: ["sony","audio","wf","1000xm5"],
  },
  {
    id: "sony-wh-1000xm6",
    name: "Sony WH-1000XM6",
    brand: "Sony",
    subcategory: "Audio",
    imageUrl: "https://sony.scene7.com/is/image/sonyglobalsolutions/WH1000XM6_Product_intro_18_M?$productIntroPlatemobile$&fmt=png-alpha",
    tags: ["sony","audio","wh","1000xm6"],
  },
  {
    id: "sony-wh-1000xm5",
    name: "Sony WH-1000XM5",
    brand: "Sony",
    subcategory: "Audio",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmRsKZhTjZ3TAT4aF2-mI3gYs2V0yq-PT62EJRRToT9A&s=10",
    tags: ["sony","audio","wh","1000xm5"],
    featured: true,
  },
  {
    id: "samsung-galaxy-buds4-pro",
    name: "Samsung Galaxy Buds4 Pro",
    brand: "Samsung",
    subcategory: "Audio",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTetNev18RL42vUApoNBVTLRLHLVaBhcy7E2pqHCuauBB_YYlt61GJh2Z9H&s=10",
    tags: ["samsung","audio","galaxy","buds4","pro"],
  },
  {
    id: "galaxy-buds4",
    name: "Galaxy Buds4",
    brand: "Samsung",
    subcategory: "Audio",
    imageUrl: "https://media-ik.croma.com/Croma%20Assets/Communication/Headphones%20And%20Earphones/Images/321820_0_YRfxDInen.png?updatedAt=1772191270627",
    tags: ["samsung","audio","galaxy","buds4"],
  },
  {
    id: "galaxy-buds3-pro",
    name: "Galaxy Buds3 Pro",
    brand: "Samsung",
    subcategory: "Audio",
    imageUrl: "https://www.samsungplaza.com.np/public/files/0F1497BDC3A7FBB-009-galaxy-buds3pro-silver-case-top-open-combination.jpg",
    tags: ["samsung","audio","galaxy","buds3","pro"],
  },
  {
    id: "galaxy-buds3",
    name: "Galaxy Buds3",
    brand: "Samsung",
    subcategory: "Audio",
    imageUrl: "https://cdn.jiostore.online/v2/jmd-asp/jdprod/wrkr/products/pictures/item/free/resize-w:460/samsung/494623997/0/OwxiIOK1Tt-hPpH1QnUdeF-Samsung-Galaxy-Buds3-FE-Earbuds-494623997-i-1-1200Wx1200H.jpeg",
    tags: ["samsung","audio","galaxy","buds3"],
  },
  {
    id: "pixel-buds-pro-2",
    name: "Pixel Buds Pro 2",
    brand: "Google",
    subcategory: "Audio",
    imageUrl: "https://lh3.googleusercontent.com/MP4ymmRItYWpJsY0cjGQfkR38WYCvrqGWv8PF-sOJQwK0A9oM2u0sr-BKD2kq_SxImwincyudgTwJRiNF5UofQwXT0IljAXKq-Zm=rw-e365-w1200-rj-sc0xffffffff",
    tags: ["google","audio","pixel","buds","pro","2"],
  },
  {
    id: "pixel-buds-2a",
    name: "Pixel Buds 2a",
    brand: "Google",
    subcategory: "Audio",
    imageUrl: "https://m.media-amazon.com/images/I/51+UqZz0uTL.jpg_BO30,255,255,255_UF750,750_SR1910,1000,0,C_QL100_.jpg",
    tags: ["google","audio","pixel","buds","2a"],
  },
  {
    id: "cmf-headphone-pro",
    name: "CMF Headphone Pro",
    brand: "CMF by Nothing",
    subcategory: "Audio",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEmEIuHJT4pP-ptxMymlmIYX1JqDyRNB_cFJLjXXGSpK4HYxMBn4UAPcc&s=10",
    tags: ["cmf by nothing","audio","cmf","headphone","pro"],
  },
  {
    id: "cmf-buds-2-plus",
    name: "CMF Buds 2 Plus",
    brand: "CMF by Nothing",
    subcategory: "Audio",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxJUvo1DvwTbmKv440YvrkNwpyZFRy4cRlp0n-9zSYXg&s=10",
    tags: ["cmf by nothing","audio","cmf","buds","2","plus"],
  },
  {
    id: "cmf-buds-pro-2",
    name: "CMF Buds Pro 2",
    brand: "CMF by Nothing",
    subcategory: "Audio",
    imageUrl: "https://cdn.shopify.com/s/files/1/0586/3270/0077/files/CMF-Buds-Pro-2_Dark-Grey_1.png?v=1745489690",
    tags: ["cmf by nothing","audio","cmf","buds","pro","2"],
  },
  {
    id: "marshall-headphones",
    name: "Marshall Headphones",
    brand: "Marshall",
    subcategory: "Audio",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYbkFWg0hXFcdcl6OVh9GlC-O5ZuPTBBj9IIhD0ffKrJutwyHcuXQLNyM&s=10",
    tags: ["marshall","audio","headphones"],
  },
  {
    id: "marshall-earbuds",
    name: "Marshall Earbuds",
    brand: "Marshall",
    subcategory: "Audio",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtzN4v9t5q80XKvAOpVejHhhnx9CGMYOyKkPyoL66RnOFPVkUmkboqwjQR&s=10",
    tags: ["marshall","audio","earbuds"],
  },
  {
    id: "bose-quietcomfort-ultra",
    name: "Bose QuietComfort Ultra",
    brand: "Bose",
    subcategory: "Audio",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4fPhoq51h3V4hSGtSsdmFMLYsVKiZn999jQIa-3Ti6g&s",
    tags: ["bose","audio","quietcomfort","ultra"],
  },
  {
    id: "bose-quietcomfort-headphones",
    name: "Bose QuietComfort Headphones",
    brand: "Bose",
    subcategory: "Audio",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSSOr0KB0JI9WGsU3V5qvB_Xc15c9aEQqCcfJ7mkv6ZVdurGXomf3F_C9d&s=10",
    tags: ["bose","audio","quietcomfort","headphones"],
  },
  {
    id: "sennheiser-momentum-4",
    name: "Sennheiser Momentum 4",
    brand: "Sennheiser",
    subcategory: "Audio",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQL_-zyQQNH7rXmaZdNorJdVfxuqmGm9TKy_O5_cj9JXwFDrZVKp62gUHXQ&s=10",
    tags: ["sennheiser","audio","momentum","4"],
  },
  {
    id: "sennheiser-hd-600",
    name: "Sennheiser HD 600",
    brand: "Sennheiser",
    subcategory: "Audio",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUS3hjt_QesfF37fgeLqT477E4vwUWBueHo8qi3z3e5R2-NamnPVqmqdly&s=10",
    tags: ["sennheiser","audio","hd","600"],
  },
  {
    id: "audio-technica-ath-m50x",
    name: "Audio-Technica ATH-M50x",
    brand: "Audio-Technica",
    subcategory: "Audio",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjw5u9-CvVa25hWqAQPiV91AUvc1MnClke7xO9z2ob-YfbAw4Dasx0rV0&s=10",
    tags: ["audio-technica","audio","technica","ath","m50x"],
  },
  {
    id: "playstation-5",
    name: "PlayStation 5",
    brand: "PlayStation",
    subcategory: "Gaming",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTo--qhjhrtlrD0V1gSSLixfoZjmiqjUCrBU6ez_65HMw&s=10",
    tags: ["playstation","gaming","5"],
    featured: true,
  },
  {
    id: "playstation-5-pro",
    name: "PlayStation 5 Pro",
    brand: "PlayStation",
    subcategory: "Gaming",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGsdEMkU73pp6JyVBWbWz5RlUmUZYr0LboOJlXZKRKIUfkuvlexTHpndc&s=10",
    tags: ["playstation","gaming","5","pro"],
  },
  {
    id: "playstation-5-console-standard",
    name: "PlayStation 5 Console Standard",
    brand: "PlayStation",
    subcategory: "Gaming",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYr_nHPnNucwy2bucX-nHGiKxQt8NMZWoQ4GQXizFrbG3TPICQZNjrpd_B&s=10",
    tags: ["playstation","gaming","5","console","standard"],
    featured: true,
  },
  {
    id: "playstation-5-console-digital",
    name: "PlayStation 5 Console Digital",
    brand: "PlayStation",
    subcategory: "Gaming",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsewg2LSVteJUOGbCQm173wGlrUR27F2Igf_uqFJ2ClA&s=10",
    tags: ["playstation","gaming","5","console","digital"],
  },
  {
    id: "xbox-series-x",
    name: "Xbox Series X",
    brand: "Xbox",
    subcategory: "Gaming",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQf8flGa7u29C1R53DBFmu-ms7hartCjaoM8LUyD0QR-sqb0O6zNAzkt-Y&s=10",
    tags: ["xbox","gaming","series","x"],
  },
  {
    id: "nintendo-switch-2",
    name: "Nintendo Switch 2",
    brand: "Nintendo",
    subcategory: "Gaming",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqJ67Zxbtz6Esoq-rmyGtjt4xMvh2GVSfGqP3oJAAV_3PbP493APouBIwj&s=10",
    tags: ["nintendo","gaming","switch","2"],
  },
  {
    id: "asus-rog-ally-x",
    name: "ASUS ROG Ally X",
    brand: "ASUS",
    subcategory: "Gaming",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgkcOe7AKl2kbXE0rPB_ya3Eekv2QpU4_B_HbDLG-tmrPT2F__e7wWcFQ3&s=10",
    tags: ["asus","gaming","rog","ally","x"],
  },
  {
    id: "steam-deck-oled",
    name: "Steam Deck OLED",
    brand: "Valve",
    subcategory: "Gaming",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIedD7BmUHk_hA-h-uoAIcENKeVc7C4uZ4QlNo7968UhXt0Zgzj7GqMiO1&s=10",
    tags: ["valve","gaming","steam","deck","oled"],
  },
  {
    id: "meta-quest-3",
    name: "Meta Quest 3",
    brand: "Meta",
    subcategory: "Gaming",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3XRDSct3HRdbwpKj2drNDr5GMNPQBqAZDUux8snZ5SA&s=10",
    tags: ["meta","gaming","quest","3"],
  },
  {
    id: "apple-vision-pro",
    name: "Apple Vision Pro",
    brand: "Apple",
    subcategory: "Gaming",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3QkdlXuOTLchu2P8rVXOJIEK7Kj_RQ9KBgipwtHPwU_63DnQIogIwWpHk&s=10",
    tags: ["apple","gaming","vision","pro"],
  },
  {
    id: "dualsense-wireless-controller-white",
    name: "DualSense Wireless Controller White",
    brand: "PlayStation",
    subcategory: "Gaming",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHCsWRlHap9IkPM3DKF9AVxbwGx3Ya07Wt3GrJQCg-1Q&s=10",
    tags: ["playstation","gaming","dualsense","wireless","controller","white"],
    featured: true,
  },
  {
    id: "logitech-g502-hero-high-performance-gaming-mouse",
    name: "Logitech G502 HERO High Performance Gaming Mouse",
    brand: "Logitech",
    subcategory: "Gaming",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTn0OtGL2srDfAk6nmspWcJvWZPw7uhQvnU9UF3xlVEMw&s=10",
    tags: ["logitech","gaming","g502","hero","high","performance","mouse"],
    featured: true,
  },
  {
    id: "logitech-g402-hyperion-fury-usb-wired-gaming-mouse",
    name: "Logitech G402 Hyperion Fury USB Wired Gaming Mouse",
    brand: "Logitech",
    subcategory: "Gaming",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQP03UpRuG65UGneeNUhb7SSykxQQW_k8ymjxJcsXfGhp4m2JH5kOBsi5xo&s=10",
    tags: ["logitech","gaming","g402","hyperion","fury","usb","wired","mouse"],
  },
  {
    id: "nvidia-geforce-rtx-5090",
    name: "NVIDIA GeForce RTX 5090",
    brand: "NVIDIA",
    subcategory: "Gaming",
    imageUrl: "https://www.nvidia.com/content/dam/en-zz/Solutions/geforce/graphic-cards/50-series/rtx-5090/geforce-rtx-5090-learn-more-og-1200x630.jpg",
    tags: ["nvidia","gaming","geforce","rtx","5090"],
  },
  {
    id: "nvidia-geforce-rtx-5080",
    name: "NVIDIA GeForce RTX 5080",
    brand: "NVIDIA",
    subcategory: "Gaming",
    imageUrl: "https://www.nvidia.com/content/dam/en-zz/Solutions/geforce/graphic-cards/50-series/rtx-5080/geforce-rtx-5080-og-1200x630.jpg",
    tags: ["nvidia","gaming","geforce","rtx","5080"],
  },
  {
    id: "nvidia-geforce-rtx-5070-ti",
    name: "NVIDIA GeForce RTX 5070 Ti",
    brand: "NVIDIA",
    subcategory: "Gaming",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSm269ixAgfX4LoZFS-m6ceh00l8uEVCIXA5slre7zp0A&s=10",
    tags: ["nvidia","gaming","geforce","rtx","5070","ti"],
  },
  {
    id: "samsung-odyssey-oled-g9",
    name: "Samsung Odyssey OLED G9",
    brand: "Samsung",
    subcategory: "Gaming",
    imageUrl: "https://images.samsung.com/is/image/samsung/p6pim/in/ls49dg910swxxl/gallery/in-odyssey-oled-g9-g91sd-ls49dg910swxxl-545396504?$1164_776_PNG$",
    tags: ["samsung","gaming","odyssey","oled","g9"],
  },
  {
    id: "logitech-pebble-keys-2-k380s",
    name: "Logitech Pebble Keys 2 K380S",
    brand: "Logitech",
    subcategory: "Keyboards & Mice",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNNmIcTE-CcraXOcAC7qyiYGkMbpLyjlDtf3CAAohDCA&s=10",
    tags: ["logitech","keyboards & mice","pebble","keys","2","k380s"],
  },
  {
    id: "logitech-mk240-nano-wireless-usb-keyboard",
    name: "Logitech MK240 Nano Wireless USB Keyboard",
    brand: "Logitech",
    subcategory: "Keyboards & Mice",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvGfgoxYTcWYDBRiFdHfftKZVzNYGyFG-0vkTJT7RerQ&s=10",
    tags: ["logitech","keyboards & mice","mk240","nano","wireless","usb","keyboard"],
  },
  {
    id: "logitech-g502-hero",
    name: "Logitech G502 HERO",
    brand: "Logitech",
    subcategory: "Keyboards & Mice",
    imageUrl: "https://rukmini1.flixcart.com/image/1500/1500/xif0q/mouse/7/n/t/g502-hero-logitech-enriched-transparent-original-imag3d4qhpdjr9tj.png?q=70",
    tags: ["logitech","keyboards & mice","g502","hero"],
  },
  {
    id: "logitech-g402-hyperion-fury",
    name: "Logitech G402 Hyperion Fury",
    brand: "Logitech",
    subcategory: "Keyboards & Mice",
    imageUrl: "https://resource.logitechg.com/w_544,h_466,ar_7:6,c_pad,q_auto,f_auto,dpr_1.0/d_transparent.gif/content/dam/gaming/en/products/g402/gallery-1.png",
    tags: ["logitech","keyboards & mice","g402","hyperion","fury"],
  },
  {
    id: "zebronics-companion-201",
    name: "Zebronics Companion 201",
    brand: "Zebronics",
    subcategory: "Keyboards & Mice",
    imageUrl: "https://shop.zebronics.com/cdn/shop/files/Zeb-companion-201-black-pic1_23abc4a1-00aa-4953-acd5-8a76e2b41436.jpg?v=1726742666&width=1200",
    tags: ["zebronics","keyboards & mice","companion","201"],
  },
  {
    id: "zebronics-shark-lite",
    name: "Zebronics Shark Lite",
    brand: "Zebronics",
    subcategory: "Keyboards & Mice",
    imageUrl: "https://cdn.grofers.com/da/cms-assets/cms/product/rc-upload-1781780707276-183.jpg",
    tags: ["zebronics","keyboards & mice","shark","lite"],
  },
  {
    id: "zebronics-war-m",
    name: "Zebronics War M",
    brand: "Zebronics",
    subcategory: "Keyboards & Mice",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCunwIqzf8NtNTC3M20eHDULMX2MRTLVahe_PNgKnHMJJ9SUQe4qQLrBgV&s=10",
    tags: ["zebronics","keyboards & mice","war","m"],
  },
  {
    id: "rapoo-e9050l",
    name: "Rapoo E9050L",
    brand: "Rapoo",
    subcategory: "Keyboards & Mice",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSm3HF3jA_yHDBWlnkkNaazEAzbIWaHki5A4wb0LJRXFtwWGOELCC5H_Oo&s=10",
    tags: ["rapoo","keyboards & mice","e9050l"],
  },
  {
    id: "evofox-katana-x2-tkl",
    name: "EvoFox Katana X2 TKL",
    brand: "EvoFox",
    subcategory: "Keyboards & Mice",
    imageUrl: "https://m.media-amazon.com/images/I/61cvMO-HeeL.jpg",
    tags: ["evofox","keyboards & mice","katana","x2","tkl"],
  },
  {
    id: "evofox-banshee-tri-mode",
    name: "EvoFox Banshee Tri-Mode",
    brand: "EvoFox",
    subcategory: "Keyboards & Mice",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQyrFzQfcFLmN2t3o7iOoc3eav9jHWMXnIry0sbz8iXtiIdLwz9y1rQ-sc&s=10",
    tags: ["evofox","keyboards & mice","banshee","tri","mode"],
  },
  {
    id: "potronics-wireless-keyboard",
    name: "Potronics Wireless Keyboard",
    brand: "Portronics",
    subcategory: "Keyboards & Mice",
    imageUrl: "https://rukminim3.flixcart.com/image/480/640/xif0q/keyboard/laptop-keyboard/7/x/p/por-2113-portronics-enriched-transparent-original-imahce2zyfyxhbsf.png?q=20",
    tags: ["portronics","keyboards & mice","potronics","wireless","keyboard"],
  },
  {
    id: "potronics-toad-8",
    name: "Potronics Toad 8",
    brand: "Portronics",
    subcategory: "Keyboards & Mice",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0aApkbUNDuK-ZBSc2J-sYZwM1EHUbY0qTnXE6MAQ1yY8CeElmo3oUbnI&s=10",
    tags: ["portronics","keyboards & mice","potronics","toad","8"],
  },
  {
    id: "mirrorless-camera",
    name: "Mirrorless Camera",
    brand: "Plugd",
    subcategory: "Cameras & Streaming",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQreXW9PhcBbJfJu_355JjJaudDHbOCeU9O6qpZLsu8mNeNyoMx1VRlA7W4&s=10",
    tags: ["plugd","cameras & streaming","mirrorless","camera"],
  },
  {
    id: "dslr-camera",
    name: "DSLR Camera",
    brand: "Plugd",
    subcategory: "Cameras & Streaming",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0qcaVpzfYApiNOADfPts_7jG0ffjFxn7c81PVlUVpN8YFJ9OPmEDqyMM&s=10",
    tags: ["plugd","cameras & streaming","dslr","camera"],
  },
  {
    id: "action-camera",
    name: "Action Camera",
    brand: "Plugd",
    subcategory: "Cameras & Streaming",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3XV5-icefp5rFZLC-YzXNPwWHCS0hySsYc1f-wt8j-w&s=10",
    tags: ["plugd","cameras & streaming","action","camera"],
  },
  {
    id: "gopro",
    name: "GoPro",
    brand: "GoPro",
    subcategory: "Cameras & Streaming",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLnzWs6hQvHbjZF3y8O8lBzY9MeHHjKreMcHSHRqP4kA&s=10",
    tags: ["gopro","cameras & streaming"],
  },
  {
    id: "4k-stream-webcam",
    name: "4K Stream Webcam",
    brand: "Plugd",
    subcategory: "Cameras & Streaming",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkes7UOdgO_acSTUgKD03nX5Kzf01hVm2I6hzrmVZaDg&s=10",
    tags: ["plugd","cameras & streaming","4k","stream","webcam"],
  },
  {
    id: "streaming-microphone",
    name: "Streaming Microphone",
    brand: "Plugd",
    subcategory: "Cameras & Streaming",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6OnEqAvg0_0wtLWNbyWnYthLnCQWqkgvw2AT-jhE5SQ&s=10",
    tags: ["plugd","cameras & streaming","streaming","microphone"],
  },
  {
    id: "audio-interface",
    name: "Audio Interface",
    brand: "Plugd",
    subcategory: "Cameras & Streaming",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsx3jiW5tMfan8FTaLft6qRKpKlOa58bEM-lKYFhRhhQ&s=10",
    tags: ["plugd","cameras & streaming","audio","interface"],
  },
  {
    id: "ring-light",
    name: "Ring Light",
    brand: "Plugd",
    subcategory: "Cameras & Streaming",
    imageUrl: "https://cdn.mos.cms.futurecdn.net/ncw7awS6MDUgaRrmLbw3aP-1200-80.jpg",
    tags: ["plugd","cameras & streaming","ring","light"],
  },
  {
    id: "capture-card",
    name: "Capture Card",
    brand: "Plugd",
    subcategory: "Cameras & Streaming",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxQPH4x-e1VYMSJUe3v46xuN09ubwnuDrG4itSiv8gIp0kSHzpQr7BzAf7&s=10",
    tags: ["plugd","cameras & streaming","capture","card"],
  },
  {
    id: "tripod",
    name: "Tripod",
    brand: "Plugd",
    subcategory: "Cameras & Streaming",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShtCq24EagQ1TypyO3Bh9RNQQeVp2TULkxA0dhVhX8-MtSTKDJbek5oGU&s=10",
    tags: ["plugd","cameras & streaming","tripod"],
  },
  {
    id: "camera-gimbal",
    name: "Camera Gimbal",
    brand: "Plugd",
    subcategory: "Cameras & Streaming",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfchMZvsmHeuMNksxyHhWMgtK287bPrkBJ9zn2ZP4VgmrCwjg5nII6Qnc&s=10",
    tags: ["plugd","cameras & streaming","camera","gimbal"],
  },
  {
    id: "external-ssd",
    name: "External SSD",
    brand: "Plugd",
    subcategory: "Storage & Computing",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQN6b90Mj_e3TJzWRihcPt4cyzy6vyeE2hhy4ie8ZpMMvCoL7eI9vdx1-M&s=10",
    tags: ["plugd","storage & computing","external","ssd"],
  },
  {
    id: "external-hdd",
    name: "External HDD",
    brand: "Plugd",
    subcategory: "Storage & Computing",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyrgaVtAsDKRcmhkmcTcOsc3X_KA9ZuXip9ILYfrmxZaIYf0tsqRr-6rvU&s=10",
    tags: ["plugd","storage & computing","external","hdd"],
  },
  {
    id: "usb-flash-drive",
    name: "USB Flash Drive",
    brand: "Plugd",
    subcategory: "Storage & Computing",
    imageUrl: "https://cdn.ewshopping.com/uploads/product/bcf1aebe-6f84-44ef-a1da-0833b5d5041f.webp",
    tags: ["plugd","storage & computing","usb","flash","drive"],
  },
  {
    id: "portable-ssd",
    name: "Portable SSD",
    brand: "Plugd",
    subcategory: "Storage & Computing",
    imageUrl: "https://fotocentreindia.com/wp-content/uploads/SanDisk-SSD-Extreme-USB-3.2-Type-C-Online-Buy-Mumbai-India_5.jpg",
    tags: ["plugd","storage & computing","portable","ssd"],
  },
  {
    id: "nas-storage",
    name: "NAS Storage",
    brand: "Plugd",
    subcategory: "Storage & Computing",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSH_cUWxxffV8GADnYGtc9jv9bUMaCmSyufNIT-yHxfRykM49DJusCLKsLb&s=10",
    tags: ["plugd","storage & computing","nas","storage"],
  },
  {
    id: "power-bank",
    name: "Power Bank",
    brand: "Plugd",
    subcategory: "Storage & Computing",
    imageUrl: "https://www.stuffcool.com/cdn/shop/files/Click_10_Orange_216aea36-93d3-4b8b-a576-a46b19f3d260.jpg?v=1771219042&width=1200",
    tags: ["plugd","storage & computing","power","bank"],
  },
  {
    id: "usb-c-hub",
    name: "USB-C Hub",
    brand: "Plugd",
    subcategory: "Storage & Computing",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTU8GSCOEpLwdWnn51dUVvCVc-ro_uxA-p6XHRFmOqRhDqlD5ZTIJT2ck0&s=10",
    tags: ["plugd","storage & computing","usb","c","hub"],
  },
  {
    id: "thunderbolt-dock",
    name: "Thunderbolt Dock",
    brand: "Plugd",
    subcategory: "Storage & Computing",
    imageUrl: "https://mm.digikey.com/Volume0/opasdata/d220001/medias/images/8880/MFG_215N-TB5USB4DOCK.jpg",
    tags: ["plugd","storage & computing","thunderbolt","dock"],
  },
  {
    id: "wireless-charger",
    name: "Wireless Charger",
    brand: "Plugd",
    subcategory: "Storage & Computing",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTibuX5suae41r8pmurJDk8_eWDk8qWONjv8BO7mqFRBKBKFRrJQ8sBoI4&s=10",
    tags: ["plugd","storage & computing","wireless","charger"],
  },
  {
    id: "magsafe-charger",
    name: "MagSafe Charger",
    brand: "Plugd",
    subcategory: "Storage & Computing",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8HARoqJQkG4GdMj-SV-oXZjuvRmoVnE3nEsOzXq6LmQ&s=10",
    tags: ["plugd","storage & computing","magsafe","charger"],
  },
  {
    id: "gaming-monitor",
    name: "Gaming Monitor",
    brand: "Plugd",
    subcategory: "Displays & Projectors",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5aTSGBTYpaHaOj7Xfot6OIzDLutNJaW5OxUyOYEROPA&s=10",
    tags: ["plugd","displays & projectors","gaming","monitor"],
  },
  {
    id: "4k-monitor",
    name: "4K Monitor",
    brand: "Plugd",
    subcategory: "Displays & Projectors",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVhFO77Q7gd0Lxa2U-lOJTHNCcetAGqk3GJYtI7YFpRhsJGWnXOfoijLe2&s=10",
    tags: ["plugd","displays & projectors","4k","monitor"],
  },
  {
    id: "ultrawide-monitor",
    name: "Ultrawide Monitor",
    brand: "Plugd",
    subcategory: "Displays & Projectors",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcgUnmQOcNZgcIjbw1H4QS2NDG6nS60xmkFxJnjtI0Hw&s=10",
    tags: ["plugd","displays & projectors","ultrawide","monitor"],
  },
  {
    id: "smart-projector",
    name: "Smart Projector",
    brand: "Plugd",
    subcategory: "Displays & Projectors",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRVUmEB_qjS8lp_abV6DGwae90Whswq3Z5CySGx5iGVeU72R5h-itiVgLn&s=10",
    tags: ["plugd","displays & projectors","smart","projector"],
  },
  {
    id: "4k-projector",
    name: "4K Projector",
    brand: "Plugd",
    subcategory: "Displays & Projectors",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxqLtwVx6efq2JLPWVZUJk6jPJQR4WbKi9RFMhOIdtFCdXjm000DRLRY4&s=10",
    tags: ["plugd","displays & projectors","4k","projector"],
  },
  {
    id: "portable-projector",
    name: "Portable Projector",
    brand: "Plugd",
    subcategory: "Displays & Projectors",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPT5x-BkkZatjSVYzcqH2i5AESrpiuUvitt-tlBlAcR9RlmHCqdbMd-zv0&s=10",
    tags: ["plugd","displays & projectors","portable","projector"],
  },
  {
    id: "4k-smart-tv",
    name: "4K Smart TV",
    brand: "Plugd",
    subcategory: "Displays & Projectors",
    imageUrl: "https://wiscon.in/cdn/shop/files/1_1cdb0f9f-cb73-44a9-b520-984067d09633.jpg?v=1779533881",
    tags: ["plugd","displays & projectors","4k","smart","tv"],
  },
  {
    id: "amazon-echo-show-8",
    name: "Amazon Echo Show 8",
    brand: "Amazon",
    subcategory: "Smart Home",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMdoYoiXcfLz2VdXUYifqLA80o8Wh_4OJMPqnDfAZCzax6QBa-yQtmVdv8&s=10",
    tags: ["amazon","smart home","echo","show","8"],
    featured: true,
  },
  {
    id: "amazon-echo-4th-gen",
    name: "Amazon Echo 4th Gen",
    brand: "Amazon",
    subcategory: "Smart Home",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQs3Fc4nQgNl6Fhzf74oVePkMKMzNJvfCeItyOoVEpLN6XoHNaNU-wBRcoi&s=10",
    tags: ["amazon","smart home","echo","4th","gen"],
  },
  {
    id: "google-nest-hub",
    name: "Google Nest Hub",
    brand: "Google",
    subcategory: "Smart Home",
    imageUrl: "https://lh3.googleusercontent.com/UK8aHGzoF23BZUEl7tDJoUga4_fsPUMDAvCFXUPChxkC8zO2TYEE22XmDHN_i2JujblITT18WzKdmOOb8zTUoCR05pRU4FRYoaM8=c0xffffff-rj-sc0xffffffff",
    tags: ["google","smart home","nest","hub"],
  },
  {
    id: "apple-homepod",
    name: "Apple HomePod",
    brand: "Apple",
    subcategory: "Smart Home",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1JDDcpJXcdEytDWuogeN-XWidwrD70D6mLT5RiIP_rQ&s=10",
    tags: ["apple","smart home","homepod"],
  },
  {
    id: "smart-light",
    name: "Smart Light",
    brand: "Plugd",
    subcategory: "Smart Home",
    imageUrl: "https://cdn.shopify.com/s/files/1/0648/5478/6148/files/Image_2.jpg?v=1722579278&quality=50",
    tags: ["plugd","smart home","smart","light"],
  },
  {
    id: "smart-led-strip",
    name: "Smart LED Strip",
    brand: "Plugd",
    subcategory: "Smart Home",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCEtbkV-a9c1KPPFBhtwE_MTHv5dcUIu_9Fp_njpu2J-1ab4cupUDuwJ8&s=10",
    tags: ["plugd","smart home","smart","led","strip"],
  },
  {
    id: "smart-plug",
    name: "Smart Plug",
    brand: "Plugd",
    subcategory: "Smart Home",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8hpRjGJGFI5SCbBLERgDOoCTppsXynwXdVZqWTLZbwmymvjEYOD9Aa7I&s=10",
    tags: ["plugd","smart home","smart","plug"],
  },
  {
    id: "smart-doorbell",
    name: "Smart Doorbell",
    brand: "Plugd",
    subcategory: "Smart Home",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0jwn3ajtYJWlr0qljUNvmFRgFoduSWhFJEhjoQ-2ls3i7qui0mp2LoPE&s=10",
    tags: ["plugd","smart home","smart","doorbell"],
  },
  {
    id: "security-camera",
    name: "Security Camera",
    brand: "Plugd",
    subcategory: "Smart Home",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcST79dHhCMTGr18r_s6pDzO2xodtdZdYFoS-n2AiCTVpgV1nLIAPhHeRio&s=10",
    tags: ["plugd","smart home","security","camera"],
  },
  {
    id: "robot-vacuum",
    name: "Robot Vacuum",
    brand: "Plugd",
    subcategory: "Smart Home",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKBUD-wxaFVjEAUiqxD02VHRynrhywgbbhXxL1G6tqtDPfLD4ICd03tJRw&s=10",
    tags: ["plugd","smart home","robot","vacuum"],
  },
  {
    id: "apple-watch",
    name: "Apple Watch",
    brand: "Apple",
    subcategory: "Watches",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYyeVtulEyXSJMQIdatdSOo1GeXCjhJ0MNdFGVn3VF7lcsB7aywgkx-8il&s=10",
    tags: ["apple","watches","watch"],
    featured: true,
  },
  {
    id: "apple-watch-ultra",
    name: "Apple Watch Ultra",
    brand: "Apple",
    subcategory: "Watches",
    imageUrl: "https://cdn.jiostore.online/v2/jmd-asp/jdprod/wrkr/products/pictures/item/free/resize-w:460/apple/494741952/0/DaGz0qvUE4-FTupXW1TNf-Apple-Watch-Ultra-3-494741952-i-1-1200Wx1200H.jpeg",
    tags: ["apple","watches","watch","ultra"],
    featured: true,
  },
  {
    id: "samsung-galaxy-watch",
    name: "Samsung Galaxy Watch",
    brand: "Samsung",
    subcategory: "Watches",
    imageUrl: "https://images.samsung.com/is/image/samsung/p6pim/in/f2607/gallery/in-galaxy-watch-ultra2-l710-sm-l715fzsains-553717152?$1164_776_PNG$",
    tags: ["samsung","watches","galaxy","watch"],
  },
  {
    id: "google-pixel-watch",
    name: "Google Pixel Watch",
    brand: "Google",
    subcategory: "Watches",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2z6X6npp8VHK_dG9Ug4_ROPpS2Nhpn3CpZ4_UI-OWDQ&s=10",
    tags: ["google","watches","pixel","watch"],
  },
  {
    id: "garmin-forerunner",
    name: "Garmin Forerunner",
    brand: "Garmin",
    subcategory: "Watches",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2XdLFK7sHHk6GOuvRSUz2KlJCodfXT9ESpsnYRGPV5Q&s=10",
    tags: ["garmin","watches","forerunner"],
  },
  {
    id: "garmin-fenix",
    name: "Garmin Fenix",
    brand: "Garmin",
    subcategory: "Watches",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLuNbTXNfliwOTSRuLPkQ-QcJqa1192jQtiRnEmX0A_ECy8Gepe0Icbqg&s=10",
    tags: ["garmin","watches","fenix"],
  },
  {
    id: "fitbit-charge",
    name: "Fitbit Charge",
    brand: "Fitbit",
    subcategory: "Watches",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqb1szcjCHolHJOwDwvVqUz8hZVAgU1qJqeUalmJYNzwdvCrDPlRaVFYEO&s=10",
    tags: ["fitbit","watches","charge"],
  },
  {
    id: "xiaomi-smart-band",
    name: "Xiaomi Smart Band",
    brand: "Xiaomi",
    subcategory: "Watches",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqkeAZcujBeduvstuhF_gUM1FMu2aEa2veZxiBv0xlQw&s",
    tags: ["xiaomi","watches","smart","band"],
  },
  {
    id: "standing-desk",
    name: "Standing Desk",
    brand: "Plugd",
    subcategory: "Other",
    imageUrl: "https://m.media-amazon.com/images/I/6102Pz3rqbL._AC_UF894,1000_QL80_.jpg",
    tags: ["plugd","other","standing","desk"],
  },
  {
    id: "mechanical-keyboard",
    name: "Mechanical Keyboard",
    brand: "Plugd",
    subcategory: "Other",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDEMvUmgxTjXN-lhZNtyqqg_OgDnGfwTzKuggCit7hrXjDpaUqyiPDE164&s=10",
    tags: ["plugd","other","mechanical","keyboard"],
  },
  {
    id: "gaming-chair",
    name: "Gaming Chair",
    brand: "Plugd",
    subcategory: "Other",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT96Le_pgY6TtmSpr1yTVeTHtiMIr8XK6pKGN4IaPm77gDI0QMSiNqvVoo&s=10",
    tags: ["plugd","other","gaming","chair"],
  },
  {
    id: "desk-lamp",
    name: "Desk Lamp",
    brand: "Plugd",
    subcategory: "Other",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQniBEBa3RDoQfPZM_9AwWeRFyYXg0PM4gPhIKoVHYbb_xAkiWyqOY49UDn&s=10",
    tags: ["plugd","other","desk","lamp"],
  },
  {
    id: "electric-toothbrush",
    name: "Electric Toothbrush",
    brand: "Plugd",
    subcategory: "Other",
    imageUrl: "https://www.waterpik.com/products/images/sensonic-electric-toothbrush-stw-03w020.jpg",
    tags: ["plugd","other","electric","toothbrush"],
  },
  {
    id: "electric-shaver",
    name: "Electric Shaver",
    brand: "Plugd",
    subcategory: "Other",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQx62vEclkXCPOAy7_DKT48ZDBVAlvNxb0xY2tHTZ-Eog&s",
    tags: ["plugd","other","electric","shaver"],
  },
  {
    id: "hair-dryer",
    name: "Hair Dryer",
    brand: "Plugd",
    subcategory: "Other",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_kzWR30zrEvtzR3CVgxRHfIp9_cbIIJlhw3slbIQOTDDEfrtUdHN9eACP&s=10",
    tags: ["plugd","other","hair","dryer"],
  },
  {
    id: "air-purifier",
    name: "Air Purifier",
    brand: "Plugd",
    subcategory: "Other",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTH4IDRAHKkce5fqqoq_-GGlHmO7qr0gdxW3ebxZyr2wo0Z2EQZYxQ3eJE&s=10",
    tags: ["plugd","other","air","purifier"],
  },
  {
    id: "portable-fan",
    name: "Portable Fan",
    brand: "Plugd",
    subcategory: "Other",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI4xqjNYF3zdqToOvgx57e_PtJyxoGbGl3SOgGdkZQjip79XO3yPZz7Cz5&s=10",
    tags: ["plugd","other","portable","fan"],
  },
  {
    id: "digital-alarm-clock",
    name: "Digital Alarm Clock",
    brand: "Plugd",
    subcategory: "Other",
    imageUrl: "https://rukminim3.flixcart.com/image/480/640/xif0q/table-clock/1/u/h/smart-night-light-digital-alarm-clock-with-date-amp-indoor-original-imahkuhpfjcehz5z.jpeg?q=80",
    tags: ["plugd","other","digital","alarm","clock"],
  },
];

export function getFullElectronicsCatalog(): ElectronicsProduct[] {
  return RAW_ELECTRONICS_PRODUCTS.map((p, idx) => ({
    id: p.id,
    name: p.name,
    brand: p.brand,
    category: "Electronics",
    subcategory: p.subcategory,
    sectionId: p.subcategory.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
    sectionTitle: p.subcategory,
    imageUrl: getElectronicsProductImage(p.id) || p.imageUrl || DEFAULT_ELECTRONICS_IMAGE,
    description: "",
    tags: p.tags,
    featured: Boolean(p.featured),
    trending: Boolean(p.trending),
    displayOrder: idx,
  }));
}

export function getElectronicsSubcategories(): Array<{ name: string; count: number }> {
  const map = new Map<string, number>();
  for (const item of RAW_ELECTRONICS_PRODUCTS) {
    map.set(item.subcategory, (map.get(item.subcategory) || 0) + 1);
  }
  return Array.from(map.entries()).map(([name, count]) => ({
    name,
    count,
  }));
}

export const ELECTRONICS_SECTIONS: ElectronicsSection[] = [
  {
    id: "mobile",
    title: "Mobile",
    subtitle: "Flagship smartphones, pro tablets, and next-gen mobile tech",
    badge: "📱 Mobile",
    displayOrder: 1,
    productIds: RAW_ELECTRONICS_PRODUCTS.filter((p) => p.subcategory === "Mobile").map((p) => p.id),
  },
  {
    id: "laptops",
    title: "Laptops",
    subtitle: "High-performance laptops and pro workstations",
    badge: "💻 Laptops",
    displayOrder: 2,
    productIds: RAW_ELECTRONICS_PRODUCTS.filter((p) => p.subcategory === "Laptops").map((p) => p.id),
  },
  {
    id: "audio",
    title: "Audio",
    subtitle: "Premium headphones, wireless earbuds, and studio monitors",
    badge: "🎧 Audio",
    displayOrder: 3,
    productIds: RAW_ELECTRONICS_PRODUCTS.filter((p) => p.subcategory === "Audio").map((p) => p.id),
  },
  {
    id: "gaming",
    title: "Gaming",
    subtitle: "Consoles, handhelds, GPUs, and performance gear",
    badge: "🎮 Gaming",
    displayOrder: 4,
    productIds: RAW_ELECTRONICS_PRODUCTS.filter((p) => p.subcategory === "Gaming").map((p) => p.id),
  },
  {
    id: "keyboards-mice",
    title: "Keyboards & Mice",
    subtitle: "Mechanical keyboards, ergonomic mice, and desk controllers",
    badge: "⌨️ Keyboards & Mice",
    displayOrder: 5,
    productIds: RAW_ELECTRONICS_PRODUCTS.filter((p) => p.subcategory === "Keyboards & Mice").map((p) => p.id),
  },
  {
    id: "cameras-streaming",
    title: "Cameras & Streaming",
    subtitle: "Mirrorless cameras, action cams, mics, and creator tools",
    badge: "📷 Cameras & Streaming",
    displayOrder: 6,
    productIds: RAW_ELECTRONICS_PRODUCTS.filter((p) => p.subcategory === "Cameras & Streaming").map((p) => p.id),
  },
  {
    id: "storage-computing",
    title: "Storage & Computing",
    subtitle: "Fast SSDs, external storage, hubs, and docks",
    badge: "💾 Storage & Computing",
    displayOrder: 7,
    productIds: RAW_ELECTRONICS_PRODUCTS.filter((p) => p.subcategory === "Storage & Computing").map((p) => p.id),
  },
  {
    id: "displays-projectors",
    title: "Displays & Projectors",
    subtitle: "Pro monitors, 4K displays, and portable projectors",
    badge: "🖥️ Displays & Projectors",
    displayOrder: 8,
    productIds: RAW_ELECTRONICS_PRODUCTS.filter((p) => p.subcategory === "Displays & Projectors").map((p) => p.id),
  },
  {
    id: "smart-home",
    title: "Smart Home",
    subtitle: "Smart speakers, displays, cameras, and automated lighting",
    badge: "🏠 Smart Home",
    displayOrder: 9,
    productIds: RAW_ELECTRONICS_PRODUCTS.filter((p) => p.subcategory === "Smart Home").map((p) => p.id),
  },
  {
    id: "watches",
    title: "Watches",
    subtitle: "Connected smartwatches and fitness trackers",
    badge: "⌚ Watches",
    displayOrder: 10,
    productIds: RAW_ELECTRONICS_PRODUCTS.filter((p) => p.subcategory === "Watches").map((p) => p.id),
  },
  {
    id: "other",
    title: "Other",
    subtitle: "Desks, lifestyle electronics, and accessories",
    badge: "✨ Other",
    displayOrder: 11,
    productIds: RAW_ELECTRONICS_PRODUCTS.filter((p) => p.subcategory === "Other").map((p) => p.id),
  },
];

export const ELECTRONICS_STARTING_COUNTS: Record<string, number> = {
  // LAPTOPS (25)
  "macbook-pro-14": 2100, // 2.1K
  "macbook-pro-16": 1800, // 1.8K
  "macbook-air-13": 1500, // 1.5K
  "macbook-air-15": 1300, // 1.3K
  "macbook-neo": 1000, // 1K
  "mac-mini": 880,
  "mac-studio": 1100, // 1.1K
  "imac": 1300, // 1.3K
  "dell-xps-13": 282,
  "dell-xps-16": 321,
  "microsoft-surface-laptop": 210,
  "microsoft-surface-pro": 541,
  "lenovo-thinkpad-x1-carbon": 1400, // 1.4K
  "lenovo-yoga-pro": 402,
  "hp-spectre-x360": 391,
  "asus-zenbook": 211,
  "asus-proart": 101,
  "acer-swift": 132,
  "razer-blade-16": 320,
  "asus-rog-strix": 356,
  "asus-rog-zephyrus-g14": 432,
  "lenovo-legion-pro": 561,
  "alienware-gaming-laptop": 693,
  "msi-raider": 485,
  "acer-predator-helios": 347,

  // AUDIO (23)
  "airpods": 1100, // 1.1K
  "airpods-pro": 2800, // 2.8K
  "airpods-max": 2400, // 2.4K
  "sony-wf-1000xm6": 1400, // 1.4K
  "sony-wf-1000xm5": 742,
  "sony-wh-1000xm6": 1200, // 1.2K
  "sony-wh-1000xm5": 480,
  "samsung-galaxy-buds4-pro": 245,
  "galaxy-buds4": 609,
  "galaxy-buds3-pro": 428,
  "galaxy-buds3": 321,
  "pixel-buds-pro-2": 210,
  "pixel-buds-2a": 143,
  "cmf-headphone-pro": 430,
  "cmf-buds-2-plus": 382,
  "cmf-buds-pro-2": 212,
  "marshall-headphones": 589,
  "marshall-earbuds": 921,
  "bose-quietcomfort-ultra": 354,
  "bose-quietcomfort-headphones": 430,
  "sennheiser-momentum-4": 139,
  "sennheiser-hd-600": 123,
  "audio-technica-ath-m50x": 459,

  // GAMING (17)
  "playstation-5": 1200, // 1.2K
  "playstation-5-pro": 1600, // 1.6K
  "playstation-5-console-standard": 1100, // 1.1K
  "playstation-5-console-digital": 1200, // 1.2K
  "xbox-series-x": 1100, // 1.1K
  "nintendo-switch-2": 648,
  "asus-rog-ally-x": 532,
  "steam-deck-oled": 498,
  "meta-quest-3": 610,
  "apple-vision-pro": 732,
  "dualsense-wireless-controller-white": 523,
  "logitech-g502-hero-high-performance-gaming-mouse": 372,
  "logitech-g402-hyperion-fury-usb-wired-gaming-mouse": 290,
  "nvidia-geforce-rtx-5090": 3500, // 3.5K
  "nvidia-geforce-rtx-5080": 2300, // 2.3K
  "nvidia-geforce-rtx-5070-ti": 1500, // 1.5K
  "samsung-odyssey-oled-g9": 834,

  // KEYBOARDS & MOUSE (12)
  "logitech-pebble-keys-2-k380s": 349,
  "logitech-mk240-nano-wireless-usb-keyboard": 432,
  "logitech-g502-hero": 483,
  "logitech-g402-hyperion-fury": 367,
  "zebronics-companion-201": 301,
  "zebronics-shark-lite": 392,
  "zebronics-war-m": 340,
  "rapoo-e9050l": 298,
  "evofox-katana-x2-tkl": 540,
  "evofox-banshee-tri-mode": 501,
  "potronics-wireless-keyboard": 219,
  "potronics-toad-8": 184,

  // CAMERAS & STREAMING (11)
  "mirrorless-camera": 234,
  "dslr-camera": 569,
  "action-camera": 354,
  "gopro": 809,
  "4k-stream-webcam": 476,
  "streaming-microphone": 381,
  "audio-interface": 298,
  "ring-light": 903,
  "capture-card": 310,
  "tripod": 693,
  "camera-gimbal": 311,

  // STORAGE & COMPUTING (10)
  "external-ssd": 113,
  "external-hdd": 87,
  "usb-flash-drive": 145,
  "portable-ssd": 56,
  "nas-storage": 45,
  "power-bank": 153,
  "usb-c-hub": 50,
  "thunderbolt-dock": 32,
  "wireless-charger": 98,
  "magsafe-charger": 71,

  // DISPLAYS & PROJECTORS (7)
  "gaming-monitor": 345,
  "4k-monitor": 201,
  "ultrawide-monitor": 198,
  "smart-projector": 143,
  "4k-projector": 183,
  "portable-projector": 222,
  "4k-smart-tv": 310,

  // SMART HOME (10)
  "amazon-echo-show-8": 92,
  "amazon-echo-4th-gen": 83,
  "google-nest-hub": 73,
  "apple-homepod": 81,
  "smart-light": 22,
  "smart-led-strip": 54,
  "smart-plug": 31,
  "smart-doorbell": 12,
  "security-camera": 9,
  "robot-vacuum": 56,

  // WATCHES (8)
  "apple-watch": 732,
  "apple-watch-ultra": 1200, // 1.2K
  "samsung-galaxy-watch": 325,
  "google-pixel-watch": 210,
  "garmin-forerunner": 185,
  "garmin-fenix": 57,
  "fitbit-charge": 118,
  "xiaomi-smart-band": 34,

  // OTHER (10)
  "standing-desk": 301,
  "mechanical-keyboard": 126,
  "gaming-chair": 1200, // 1.2K
  "desk-lamp": 333,
  "electric-toothbrush": 120,
  "electric-shaver": 209,
  "hair-dryer": 154,
  "air-purifier": 91,
  "portable-fan": 561,
  "digital-alarm-clock": 241,
};

