/**
 * Comprehensive Electronics Catalog Data Definition for Plugd
 * 
 * EXACTLY the 5 specified subcategories:
 * 1. Mobile (exact same 21 products from mobiles-catalog)
 * 2. Laptops (exact 7 products)
 * 3. Audio (exact 22 products)
 * 4. Gaming & Entertainment (Console Controllers: 6, Games: 10, Keyboards: 6, Mouse: 6, Speakers: 8)
 * 5. Watches (empty / ready-to-expand)
 * 
 * ZERO descriptions, ZERO prices.
 */

import { getElectronicsProductImage, DEFAULT_ELECTRONICS_IMAGE } from "./product-images";
import { RAW_MOBILE_PRODUCTS } from "./mobiles-catalog";

export interface ElectronicsProduct {
  id: string;
  name: string;
  brand: string;
  category: "Electronics";
  subcategory: "Mobile" | "Laptops" | "Audio" | "Gaming & Entertainment" | "Watches";
  subgroup?: string;
  sectionId: string;
  sectionTitle: string;
  imageUrl: string;
  description: string;
  tags: string[];
  featured?: boolean;
  trending?: boolean;
  displayOrder: number;
}

export interface ElectronicsSection {
  id: string;
  title: string;
  subtitle: string;
  badge?: string;
  displayOrder: number;
  productIds: string[];
}

export const ELECTRONICS_SECTIONS: ElectronicsSection[] = [
  {
    id: "mobiles-section",
    title: "Mobile",
    subtitle: "Next-gen flagship smartphones and pro tablets",
    badge: "📱 Mobile",
    displayOrder: 1,
    productIds: RAW_MOBILE_PRODUCTS.map((p) => p.id),
  },
  {
    id: "laptops-section",
    title: "Laptops",
    subtitle: "High performance laptops and creator workstations",
    badge: "💻 Laptops",
    displayOrder: 2,
    productIds: [
      "macbook-pro",
      "macbook-air",
      "macbook-neo",
      "lenovo-thinkpad",
      "lenovo-laptop",
      "hp-laptop",
      "dell-laptop",
    ],
  },
  {
    id: "audio-section",
    title: "Audio",
    subtitle: "Pro headphones, true wireless earbuds, and studio monitors",
    badge: "🎧 Audio",
    displayOrder: 3,
    productIds: [
      "airpods",
      "airpods-pro",
      "airpods-max",
      "sony-wf-1000xm6",
      "sony-wf-1000xm5",
      "sony-wh-1000xm6",
      "sony-wh-1000xm5",
      "samsung-galaxy-buds4-pro",
      "galaxy-buds4",
      "galaxy-buds3-pro",
      "galaxy-buds3",
      "pixel-buds-pro-2",
      "pixel-buds-2a",
      "headphone-1",
      "ear-open",
      "cmf-headphone-pro",
      "ear",
      "ear-a",
      "cmf-buds-2-plus",
      "cmf-buds-pro-2",
      "marshall-headphones",
      "marshall-earbuds",
    ],
  },
  {
    id: "gaming-entertainment-section",
    title: "Gaming & Entertainment",
    subtitle: "Controllers, games, keyboards, mouse, and audio speakers",
    badge: "🎮 Gaming",
    displayOrder: 4,
    productIds: [
      // Controllers
      "dualsense-wireless-controller-white",
      "zebronics-max-fury-wired-gamepad",
      "playstation-5-console-standard",
      "playstation-5-console-digital",
      "evofox-deck-2-smartphone-wireless-gaming-controller",
      "zebronics-zeb-max-link-plus-wireless-gamepad",
      // Games
      "sony-ps5-ghost-of-yotei",
      "sony-ps5-marvels-spider-man-miles-morales",
      "sony-ps5-the-last-of-us-part-ii-remastered",
      "sony-ps5-marvel-tokon-fighting-souls",
      "sony-ps5-astro-bot",
      "playstation-god-of-war-ragnarok",
      "sony-gran-turismo-2",
      "sony-ps5-spider-man-2",
      "sony-ghost-of-tsushima",
      "sony-uncharted-legacy-of-thieves-collection",
      // Keyboards
      "logitech-pebble-keys-2-k380s-graphite",
      "zebronics-companion-201-24ghz-wireless-keyboard",
      "rapoo-e9050l-bluetooth-wireless-multi-device-keyboard",
      "evofox-katana-x2-tkl-wired-mechanical-gaming-keyboard",
      "logitech-mk240-nano-wireless-usb-keyboard",
      "portronics-wireless-keyboard",
      // Mouse
      "logitech-g502-hero-high-performance-gaming-mouse",
      "logitech-g402-hyperion-fury-usb-wired-gaming-mouse",
      "zebronics-shark-lite-gaming-mouse",
      "evofox-banshee-tri-mode-wireless-gaming-mouse",
      "portronics-toad-8-transparent-wireless-bluetooth-mouse",
      "zebronics-war-m-wired-gaming-mouse",
      // Speakers
      "sony-new-sa-d40m2-speaker",
      "amazon-echo-show-8",
      "amazon-echo-4th-gen",
      "jbl-cinema-sb150-200w-soundbar",
      "sony-srs-xb100-wireless-bluetooth-speaker",
      "jbl-go-4-wireless-bluetooth-speaker",
      "philips-tax2208-party-speaker",
      "boat-partypal-65-pro",
    ],
  },
  {
    id: "watches-section",
    title: "Watches",
    subtitle: "Connected wearables and digital timepieces (ready-to-expand)",
    badge: "⌚ Watches",
    displayOrder: 5,
    productIds: [],
  },
];

export const RAW_ELECTRONICS_PRODUCTS: Array<{
  id: string;
  name: string;
  brand: string;
  subcategory: "Mobile" | "Laptops" | "Audio" | "Gaming & Entertainment" | "Watches";
  subgroup?: string;
  sectionId: string;
  sectionTitle: string;
  description: string;
  tags: string[];
  featured?: boolean;
  trending?: boolean;
}> = [
  // 1. MOBILE (Exact 21 products from mobiles catalog)
  ...RAW_MOBILE_PRODUCTS.map((m) => ({
    id: m.id,
    name: m.name,
    brand: m.brand,
    subcategory: "Mobile" as const,
    sectionId: "mobiles-section",
    sectionTitle: "Mobile",
    description: "",
    tags: m.tags,
    featured: m.featured,
    trending: m.trending,
  })),

  // 2. LAPTOPS (Exact 7 products)
  {
    id: "macbook-pro",
    name: "MacBook Pro",
    brand: "Apple",
    subcategory: "Laptops",
    sectionId: "laptops-section",
    sectionTitle: "Laptops",
    description: "",
    tags: ["apple", "macbook", "laptop", "pro"],
    featured: true,
  },
  {
    id: "macbook-air",
    name: "MacBook Air",
    brand: "Apple",
    subcategory: "Laptops",
    sectionId: "laptops-section",
    sectionTitle: "Laptops",
    description: "",
    tags: ["apple", "macbook", "air", "laptop"],
    featured: true,
  },
  {
    id: "macbook-neo",
    name: "MacBook Neo",
    brand: "Apple",
    subcategory: "Laptops",
    sectionId: "laptops-section",
    sectionTitle: "Laptops",
    description: "",
    tags: ["apple", "macbook", "neo"],
  },
  {
    id: "lenovo-thinkpad",
    name: "Lenovo ThinkPad",
    brand: "Lenovo",
    subcategory: "Laptops",
    sectionId: "laptops-section",
    sectionTitle: "Laptops",
    description: "",
    tags: ["lenovo", "thinkpad", "laptop"],
  },
  {
    id: "lenovo-laptop",
    name: "Lenovo Laptop",
    brand: "Lenovo",
    subcategory: "Laptops",
    sectionId: "laptops-section",
    sectionTitle: "Laptops",
    description: "",
    tags: ["lenovo", "laptop"],
  },
  {
    id: "hp-laptop",
    name: "HP Laptop",
    brand: "HP",
    subcategory: "Laptops",
    sectionId: "laptops-section",
    sectionTitle: "Laptops",
    description: "",
    tags: ["hp", "laptop"],
  },
  {
    id: "dell-laptop",
    name: "Dell Laptop",
    brand: "Dell",
    subcategory: "Laptops",
    sectionId: "laptops-section",
    sectionTitle: "Laptops",
    description: "",
    tags: ["dell", "laptop"],
  },

  // 3. AUDIO (Exact 22 products)
  {
    id: "airpods",
    name: "AirPods",
    brand: "Apple",
    subcategory: "Audio",
    sectionId: "audio-section",
    sectionTitle: "Audio",
    description: "",
    tags: ["apple", "airpods", "earbuds"],
  },
  {
    id: "airpods-pro",
    name: "AirPods Pro",
    brand: "Apple",
    subcategory: "Audio",
    sectionId: "audio-section",
    sectionTitle: "Audio",
    description: "",
    tags: ["apple", "airpods", "pro", "anc"],
    featured: true,
  },
  {
    id: "airpods-max",
    name: "AirPods Max",
    brand: "Apple",
    subcategory: "Audio",
    sectionId: "audio-section",
    sectionTitle: "Audio",
    description: "",
    tags: ["apple", "headphones", "airpods-max"],
    featured: true,
  },
  {
    id: "sony-wf-1000xm6",
    name: "Sony WF-1000XM6",
    brand: "Sony",
    subcategory: "Audio",
    sectionId: "audio-section",
    sectionTitle: "Audio",
    description: "",
    tags: ["sony", "earbuds", "anc"],
  },
  {
    id: "sony-wf-1000xm5",
    name: "Sony WF-1000XM5",
    brand: "Sony",
    subcategory: "Audio",
    sectionId: "audio-section",
    sectionTitle: "Audio",
    description: "",
    tags: ["sony", "earbuds", "anc"],
  },
  {
    id: "sony-wh-1000xm6",
    name: "Sony WH-1000XM6",
    brand: "Sony",
    subcategory: "Audio",
    sectionId: "audio-section",
    sectionTitle: "Audio",
    description: "",
    tags: ["sony", "headphones", "anc"],
  },
  {
    id: "sony-wh-1000xm5",
    name: "Sony WH-1000XM5",
    brand: "Sony",
    subcategory: "Audio",
    sectionId: "audio-section",
    sectionTitle: "Audio",
    description: "",
    tags: ["sony", "headphones", "anc"],
    featured: true,
  },
  {
    id: "samsung-galaxy-buds4-pro",
    name: "Samsung Galaxy Buds4 Pro",
    brand: "Samsung",
    subcategory: "Audio",
    sectionId: "audio-section",
    sectionTitle: "Audio",
    description: "",
    tags: ["samsung", "galaxy", "buds", "anc"],
  },
  {
    id: "galaxy-buds4",
    name: "Galaxy Buds4",
    brand: "Samsung",
    subcategory: "Audio",
    sectionId: "audio-section",
    sectionTitle: "Audio",
    description: "",
    tags: ["samsung", "galaxy", "buds"],
  },
  {
    id: "galaxy-buds3-pro",
    name: "Galaxy Buds3 Pro",
    brand: "Samsung",
    subcategory: "Audio",
    sectionId: "audio-section",
    sectionTitle: "Audio",
    description: "",
    tags: ["samsung", "galaxy", "buds3", "pro"],
  },
  {
    id: "galaxy-buds3",
    name: "Galaxy Buds3",
    brand: "Samsung",
    subcategory: "Audio",
    sectionId: "audio-section",
    sectionTitle: "Audio",
    description: "",
    tags: ["samsung", "galaxy", "buds3"],
  },
  {
    id: "pixel-buds-pro-2",
    name: "Pixel Buds Pro 2",
    brand: "Google",
    subcategory: "Audio",
    sectionId: "audio-section",
    sectionTitle: "Audio",
    description: "",
    tags: ["google", "pixel-buds", "pro"],
  },
  {
    id: "pixel-buds-2a",
    name: "Pixel Buds 2a",
    brand: "Google",
    subcategory: "Audio",
    sectionId: "audio-section",
    sectionTitle: "Audio",
    description: "",
    tags: ["google", "pixel-buds"],
  },
  {
    id: "headphone-1",
    name: "Headphone (1)",
    brand: "Nothing",
    subcategory: "Audio",
    sectionId: "audio-section",
    sectionTitle: "Audio",
    description: "",
    tags: ["nothing", "headphone"],
  },
  {
    id: "ear-open",
    name: "Ear (open)",
    brand: "Nothing",
    subcategory: "Audio",
    sectionId: "audio-section",
    sectionTitle: "Audio",
    description: "",
    tags: ["nothing", "ear-open", "earbuds"],
  },
  {
    id: "cmf-headphone-pro",
    name: "CMF Headphone Pro",
    brand: "CMF by Nothing",
    subcategory: "Audio",
    sectionId: "audio-section",
    sectionTitle: "Audio",
    description: "",
    tags: ["cmf", "headphones"],
  },
  {
    id: "ear",
    name: "Ear",
    brand: "Nothing",
    subcategory: "Audio",
    sectionId: "audio-section",
    sectionTitle: "Audio",
    description: "",
    tags: ["nothing", "ear", "earbuds"],
  },
  {
    id: "ear-a",
    name: "Ear (a)",
    brand: "Nothing",
    subcategory: "Audio",
    sectionId: "audio-section",
    sectionTitle: "Audio",
    description: "",
    tags: ["nothing", "ear-a", "earbuds"],
  },
  {
    id: "cmf-buds-2-plus",
    name: "CMF Buds 2 Plus",
    brand: "CMF by Nothing",
    subcategory: "Audio",
    sectionId: "audio-section",
    sectionTitle: "Audio",
    description: "",
    tags: ["cmf", "buds", "earbuds"],
  },
  {
    id: "cmf-buds-pro-2",
    name: "CMF Buds Pro 2",
    brand: "CMF by Nothing",
    subcategory: "Audio",
    sectionId: "audio-section",
    sectionTitle: "Audio",
    description: "",
    tags: ["cmf", "buds-pro", "earbuds"],
  },
  {
    id: "marshall-headphones",
    name: "Marshall Headphones",
    brand: "Marshall",
    subcategory: "Audio",
    sectionId: "audio-section",
    sectionTitle: "Audio",
    description: "",
    tags: ["marshall", "headphones", "major"],
  },
  {
    id: "marshall-earbuds",
    name: "Marshall Earbuds",
    brand: "Marshall",
    subcategory: "Audio",
    sectionId: "audio-section",
    sectionTitle: "Audio",
    description: "",
    tags: ["marshall", "earbuds", "motif"],
  },

  // 4. GAMING & ENTERTAINMENT
  // Console Controllers
  {
    id: "dualsense-wireless-controller-white",
    name: "DualSense Wireless Controller White",
    brand: "PlayStation",
    subcategory: "Gaming & Entertainment",
    subgroup: "Console Controllers",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["playstation", "ps5", "controller", "dualsense"],
    featured: true,
  },
  {
    id: "zebronics-max-fury-wired-gamepad",
    name: "Zebronics MAX FURY Wired Gamepad",
    brand: "Zebronics",
    subcategory: "Gaming & Entertainment",
    subgroup: "Console Controllers",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["zebronics", "gamepad", "gaming"],
  },
  {
    id: "playstation-5-console-standard",
    name: "PlayStation 5 Console Standard",
    brand: "PlayStation",
    subcategory: "Gaming & Entertainment",
    subgroup: "Console Controllers",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["playstation", "ps5", "console"],
    featured: true,
  },
  {
    id: "playstation-5-console-digital",
    name: "PlayStation 5 Console Digital",
    brand: "PlayStation",
    subcategory: "Gaming & Entertainment",
    subgroup: "Console Controllers",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["playstation", "ps5", "digital"],
  },
  {
    id: "evofox-deck-2-smartphone-wireless-gaming-controller",
    name: "EvoFox Deck 2 Smartphone Wireless Gaming Controller",
    brand: "EvoFox",
    subcategory: "Gaming & Entertainment",
    subgroup: "Console Controllers",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["evofox", "mobile-controller", "gaming"],
  },
  {
    id: "zebronics-zeb-max-link-plus-wireless-gamepad",
    name: "Zebronics Zeb Max Link Plus Wireless Gamepad",
    brand: "Zebronics",
    subcategory: "Gaming & Entertainment",
    subgroup: "Console Controllers",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["zebronics", "gamepad", "wireless"],
  },

  // Games
  {
    id: "sony-ps5-ghost-of-yotei",
    name: "Sony PS5 Ghost of Yotei",
    brand: "PlayStation",
    subcategory: "Gaming & Entertainment",
    subgroup: "Games",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["ps5", "game", "ghost-of-yotei"],
    featured: true,
  },
  {
    id: "sony-ps5-marvels-spider-man-miles-morales",
    name: "Sony PS5 Marvel's Spider-Man: Miles Morales",
    brand: "PlayStation",
    subcategory: "Gaming & Entertainment",
    subgroup: "Games",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["ps5", "spiderman", "game"],
  },
  {
    id: "sony-ps5-the-last-of-us-part-ii-remastered",
    name: "Sony PS5 The Last of Us Part II Remastered",
    brand: "PlayStation",
    subcategory: "Gaming & Entertainment",
    subgroup: "Games",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["ps5", "last-of-us", "game"],
  },
  {
    id: "sony-ps5-marvel-tokon-fighting-souls",
    name: "Sony PS5 Marvel Tōkon: Fighting Souls",
    brand: "PlayStation",
    subcategory: "Gaming & Entertainment",
    subgroup: "Games",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["ps5", "marvel", "game"],
  },
  {
    id: "sony-ps5-astro-bot",
    name: "Sony PS5 Astro Bot",
    brand: "PlayStation",
    subcategory: "Gaming & Entertainment",
    subgroup: "Games",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["ps5", "astro-bot", "game"],
  },
  {
    id: "playstation-god-of-war-ragnarok",
    name: "PlayStation God of War Ragnarök",
    brand: "PlayStation",
    subcategory: "Gaming & Entertainment",
    subgroup: "Games",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["ps5", "god-of-war", "game"],
  },
  {
    id: "sony-gran-turismo-2",
    name: "Sony Gran Turismo 2",
    brand: "PlayStation",
    subcategory: "Gaming & Entertainment",
    subgroup: "Games",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["ps5", "gran-turismo", "racing"],
  },
  {
    id: "sony-ps5-spider-man-2",
    name: "Sony PS5 Spider-Man 2",
    brand: "PlayStation",
    subcategory: "Gaming & Entertainment",
    subgroup: "Games",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["ps5", "spiderman-2", "game"],
  },
  {
    id: "sony-ghost-of-tsushima",
    name: "Sony Ghost of Tsushima",
    brand: "PlayStation",
    subcategory: "Gaming & Entertainment",
    subgroup: "Games",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["ps5", "ghost-of-tsushima", "game"],
  },
  {
    id: "sony-uncharted-legacy-of-thieves-collection",
    name: "Sony Uncharted: Legacy of Thieves Collection",
    brand: "PlayStation",
    subcategory: "Gaming & Entertainment",
    subgroup: "Games",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["ps5", "uncharted", "game"],
  },

  // Keyboards
  {
    id: "logitech-pebble-keys-2-k380s-graphite",
    name: "Logitech Pebble Keys 2 K380S - Graphite",
    brand: "Logitech",
    subcategory: "Gaming & Entertainment",
    subgroup: "Keyboards",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["logitech", "keyboard", "pebble"],
  },
  {
    id: "zebronics-companion-201-24ghz-wireless-keyboard",
    name: "Zebronics Companion 201 2.4GHz Wireless Keyboard",
    brand: "Zebronics",
    subcategory: "Gaming & Entertainment",
    subgroup: "Keyboards",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["zebronics", "keyboard", "wireless"],
  },
  {
    id: "rapoo-e9050l-bluetooth-wireless-multi-device-keyboard",
    name: "Rapoo E9050L Bluetooth Wireless Multi-Device Keyboard",
    brand: "Rapoo",
    subcategory: "Gaming & Entertainment",
    subgroup: "Keyboards",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["rapoo", "keyboard", "bluetooth"],
  },
  {
    id: "evofox-katana-x2-tkl-wired-mechanical-gaming-keyboard",
    name: "EvoFox Katana X2 TKL Wired Mechanical Gaming Keyboard",
    brand: "EvoFox",
    subcategory: "Gaming & Entertainment",
    subgroup: "Keyboards",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["evofox", "mechanical-keyboard", "gaming"],
  },
  {
    id: "logitech-mk240-nano-wireless-usb-keyboard",
    name: "Logitech MK240 Nano Wireless USB Keyboard",
    brand: "Logitech",
    subcategory: "Gaming & Entertainment",
    subgroup: "Keyboards",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["logitech", "keyboard"],
  },
  {
    id: "portronics-wireless-keyboard",
    name: "Portronics Wireless Keyboard",
    brand: "Portronics",
    subcategory: "Gaming & Entertainment",
    subgroup: "Keyboards",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["portronics", "keyboard"],
  },

  // Mouse
  {
    id: "logitech-g502-hero-high-performance-gaming-mouse",
    name: "Logitech G502 HERO High Performance Gaming Mouse",
    brand: "Logitech",
    subcategory: "Gaming & Entertainment",
    subgroup: "Mouse",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["logitech", "g502", "gaming-mouse"],
    featured: true,
  },
  {
    id: "logitech-g402-hyperion-fury-usb-wired-gaming-mouse",
    name: "Logitech G402 Hyperion Fury USB Wired Gaming Mouse",
    brand: "Logitech",
    subcategory: "Gaming & Entertainment",
    subgroup: "Mouse",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["logitech", "g402", "mouse"],
  },
  {
    id: "zebronics-shark-lite-gaming-mouse",
    name: "Zebronics Shark Lite Gaming Mouse",
    brand: "Zebronics",
    subcategory: "Gaming & Entertainment",
    subgroup: "Mouse",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["zebronics", "mouse", "gaming"],
  },
  {
    id: "evofox-banshee-tri-mode-wireless-gaming-mouse",
    name: "EvoFox Banshee Tri-Mode Wireless Gaming Mouse",
    brand: "EvoFox",
    subcategory: "Gaming & Entertainment",
    subgroup: "Mouse",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["evofox", "mouse", "wireless"],
  },
  {
    id: "portronics-toad-8-transparent-wireless-bluetooth-mouse",
    name: "Portronics Toad 8 Transparent Wireless Bluetooth Mouse",
    brand: "Portronics",
    subcategory: "Gaming & Entertainment",
    subgroup: "Mouse",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["portronics", "mouse", "transparent"],
  },
  {
    id: "zebronics-war-m-wired-gaming-mouse",
    name: "Zebronics War M Wired Gaming Mouse",
    brand: "Zebronics",
    subcategory: "Gaming & Entertainment",
    subgroup: "Mouse",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["zebronics", "mouse"],
  },

  // Speakers
  {
    id: "sony-new-sa-d40m2-speaker",
    name: "Sony New SA-D40M2 Speaker",
    brand: "Sony",
    subcategory: "Gaming & Entertainment",
    subgroup: "Speakers",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["sony", "speaker", "sound-system"],
  },
  {
    id: "amazon-echo-show-8",
    name: "Amazon Echo Show 8",
    brand: "Amazon",
    subcategory: "Gaming & Entertainment",
    subgroup: "Speakers",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["amazon", "echo-show", "smart-speaker"],
    featured: true,
  },
  {
    id: "amazon-echo-4th-gen",
    name: "Amazon Echo (4th Gen)",
    brand: "Amazon",
    subcategory: "Gaming & Entertainment",
    subgroup: "Speakers",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["amazon", "echo", "alexa"],
  },
  {
    id: "jbl-cinema-sb150-200w-soundbar",
    name: "JBL Cinema SB150 200W Soundbar",
    brand: "JBL",
    subcategory: "Gaming & Entertainment",
    subgroup: "Speakers",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["jbl", "soundbar", "cinema"],
  },
  {
    id: "sony-srs-xb100-wireless-bluetooth-speaker",
    name: "Sony SRS-XB100 Wireless Bluetooth Speaker",
    brand: "Sony",
    subcategory: "Gaming & Entertainment",
    subgroup: "Speakers",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["sony", "bluetooth-speaker", "portable"],
  },
  {
    id: "jbl-go-4-wireless-bluetooth-speaker",
    name: "JBL Go 4 Wireless Bluetooth Speaker",
    brand: "JBL",
    subcategory: "Gaming & Entertainment",
    subgroup: "Speakers",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["jbl", "go4", "portable-speaker"],
  },
  {
    id: "philips-tax2208-party-speaker",
    name: "Philips TAX2208 Party Speaker",
    brand: "Philips",
    subcategory: "Gaming & Entertainment",
    subgroup: "Speakers",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["philips", "party-speaker"],
  },
  {
    id: "boat-partypal-65-pro",
    name: "boAt PartyPal 65 Pro",
    brand: "boAt",
    subcategory: "Gaming & Entertainment",
    subgroup: "Speakers",
    sectionId: "gaming-entertainment-section",
    sectionTitle: "Gaming & Entertainment",
    description: "",
    tags: ["boat", "partypal", "speaker"],
  },

  // 5. WATCHES (empty / ready-to-expand)
];

export function getFullElectronicsCatalog(): ElectronicsProduct[] {
  return RAW_ELECTRONICS_PRODUCTS.map((p, idx) => ({
    id: p.id,
    name: p.name,
    brand: p.brand,
    category: "Electronics",
    subcategory: p.subcategory,
    subgroup: p.subgroup,
    sectionId: p.sectionId,
    sectionTitle: p.sectionTitle,
    imageUrl: getElectronicsProductImage(p.id) || DEFAULT_ELECTRONICS_IMAGE,
    description: "",
    tags: p.tags,
    featured: Boolean(p.featured),
    trending: Boolean(p.trending),
    displayOrder: idx,
  }));
}

export function getElectronicsSubcategories(): Array<{ name: string; count: number }> {
  const subcategories: Array<"Mobile" | "Laptops" | "Audio" | "Gaming & Entertainment" | "Watches"> = [
    "Mobile",
    "Laptops",
    "Audio",
    "Gaming & Entertainment",
    "Watches",
  ];
  const map = new Map<string, number>();
  for (const item of RAW_ELECTRONICS_PRODUCTS) {
    map.set(item.subcategory, (map.get(item.subcategory) || 0) + 1);
  }
  return subcategories.map((name) => ({
    name,
    count: map.get(name) || 0,
  }));
}
