/**
 * Comprehensive Electronics Catalog Data Definition for Plugd
 * 
 * Scalable product catalog with zero prices, remote CDN image URLs,
 * brand indexing, subcategory organization, and 14 distinct discovery sections.
 */

import { getElectronicsProductImage } from "./product-images";

export interface ElectronicsProduct {
  id: string;
  name: string;
  brand: string;
  category: "Electronics";
  subcategory: string;
  sectionId: string;
  sectionTitle: string;
  imageUrl: string;
  description: string;
  tags: string[];
  featured?: boolean;
  trending?: boolean;
  displayOrder: number;
}

export interface ElectronicsSection {
  id: string;
  title: string;
  subtitle: string;
  badge?: string;
  displayOrder: number;
  productIds: string[];
}

export const ELECTRONICS_SECTIONS: ElectronicsSection[] = [
  {
    id: "trending",
    title: "Trending Now",
    subtitle: "Highly desired hardware for creators, developers, gamers, and internet culture",
    badge: "🔥 Hot",
    displayOrder: 1,
    productIds: [
      "macbook-pro",
      "macbook-air",
      "iphone-17-pro",
      "iphone-17",
      "samsung-galaxy-s26-ultra",
      "google-pixel-10-pro",
      "sony-wh-1000xm5",
      "airpods-pro",
      "airpods-max",
      "playstation-5",
      "playstation-5-pro",
      "nintendo-switch-2",
      "xbox-series-x",
      "nvidia-geforce-rtx-5090",
      "nvidia-geforce-rtx-5080",
      "nvidia-geforce-rtx-5070-ti",
      "asus-rog-ally-x",
      "steam-deck-oled",
      "meta-quest-3",
      "apple-vision-pro",
      "samsung-odyssey-oled-g9",
    ],
  },
  {
    id: "laptops-computers",
    title: "Laptops & Computers",
    subtitle: "Flagship MacBooks, Windows ultrabooks, and extreme performance gaming rigs",
    badge: "💻 Computing",
    displayOrder: 2,
    productIds: [
      "macbook-pro-14",
      "macbook-pro-16",
      "macbook-air-13",
      "macbook-air-15",
      "mac-mini",
      "mac-studio",
      "imac",
      "ipad-pro",
      "dell-xps-13",
      "dell-xps-16",
      "microsoft-surface-laptop",
      "microsoft-surface-pro",
      "lenovo-thinkpad-x1-carbon",
      "lenovo-yoga-pro",
      "hp-spectre-x360",
      "asus-zenbook",
      "asus-proart",
      "acer-swift",
      "razer-blade-16",
      "asus-rog-strix",
      "asus-rog-zephyrus-g14",
      "lenovo-legion-pro",
      "alienware-gaming-laptop",
      "msi-raider",
      "acer-predator-helios",
    ],
  },
  {
    id: "audio-store",
    title: "Audio Store",
    subtitle: "Audiophile headphones, noise-cancelling earbuds, and spatial room speakers",
    badge: "🎧 Sound",
    displayOrder: 3,
    productIds: [
      "sony-wh-1000xm5",
      "sony-wh-1000xm6",
      "bose-quietcomfort-ultra",
      "bose-quietcomfort-headphones",
      "apple-airpods-max",
      "sennheiser-momentum-4",
      "sennheiser-hd-600",
      "audio-technica-ath-m50x",
      "beyerdynamic-dt-770-pro",
      "beyerdynamic-dt-990-pro",
      "airpods-pro",
      "airpods",
      "sony-wf-1000xm5",
      "bose-quietcomfort-ultra-earbuds",
      "samsung-galaxy-buds3-pro",
      "nothing-ear",
      "sennheiser-momentum-true-wireless",
      "sonos-era-100",
      "sonos-era-300",
      "sonos-arc",
      "jbl-charge",
      "jbl-flip",
      "marshall-stanmore",
      "marshall-acton",
      "bose-soundlink",
    ],
  },
  {
    id: "gaming",
    title: "Gaming",
    subtitle: "Next-gen consoles, handheld PCs, pro controllers, and competitive esports gear",
    badge: "🎮 Play",
    displayOrder: 4,
    productIds: [
      "playstation-5",
      "playstation-5-pro",
      "xbox-series-x",
      "xbox-series-s",
      "nintendo-switch-2",
      "steam-deck-oled",
      "asus-rog-ally-x",
      "lenovo-legion-go",
      "playstation-portal",
      "meta-quest-3",
      "meta-quest-3s",
      "dualsense-edge",
      "xbox-elite-wireless-controller",
      "nintendo-switch-pro-controller",
      "logitech-g-pro-x-superlight",
      "razer-deathadder-v3",
      "razer-blackshark-v2",
      "steelseries-arctis-nova-pro",
      "elgato-stream-deck",
      "elgato-stream-deck-xl",
    ],
  },
  {
    id: "monitors-displays",
    title: "Monitors & Displays",
    subtitle: "Ultrawide OLED canvases, 5K studio panels, and competitive high-refresh screens",
    badge: "🖥️ Displays",
    displayOrder: 5,
    productIds: [
      "samsung-odyssey-oled-g9",
      "samsung-odyssey-oled-g8",
      "lg-ultragear-oled",
      "lg-ultrafine",
      "apple-studio-display",
      "apple-pro-display-xdr",
      "dell-ultrasharp-4k",
      "asus-proart-display",
      "asus-rog-swift-oled",
      "benq-pd-series",
      "gigabyte-aorus-gaming-monitor",
      "gaming-monitor",
    ],
  },
  {
    id: "nvidia-hardware",
    title: "NVIDIA & PC Hardware",
    subtitle: "Cutting-edge Blackwell GPUs, powerhouse processors, and ultra-fast Gen5 storage",
    badge: "⚡ Power",
    displayOrder: 6,
    productIds: [
      "nvidia-geforce-rtx-5090",
      "nvidia-geforce-rtx-5080",
      "nvidia-geforce-rtx-5070-ti",
      "nvidia-geforce-rtx-5070",
      "nvidia-geforce-rtx-5060-ti",
      "nvidia-geforce-rtx-5060",
      "nvidia-rtx-6000-ada",
      "nvidia-jetson-orin",
      "amd-ryzen-9",
      "intel-core-ultra-9",
      "amd-radeon-rx-9070-xt",
      "samsung-nvme-ssd",
      "wd-black-nvme-ssd",
      "crucial-pro-ssd",
      "corsair-vengeance-ram",
      "gskill-trident-z-ram",
    ],
  },
  {
    id: "cameras-photography",
    title: "Cameras & Photography",
    subtitle: "Hybrid full-frame bodies, cinematic 4K vlogging tools, drones, and action cams",
    badge: "📷 Visual",
    displayOrder: 7,
    productIds: [
      "sony-alpha-a7-iv",
      "sony-alpha-a7-v",
      "sony-alpha-a7r-v",
      "sony-alpha-a6700",
      "canon-eos-r6-mark-ii",
      "canon-eos-r5",
      "nikon-z6-iii",
      "fujifilm-x-t5",
      "fujifilm-x100vi",
      "leica-q3",
      "gopro-hero",
      "dji-osmo-pocket",
      "dji-action",
      "dji-mini",
      "insta360-x-series",
      "mirrorless-camera",
    ],
  },
  {
    id: "creator-streaming",
    title: "Creator & Streaming",
    subtitle: "Broadcast dynamic mics, studio audio interfaces, key lights, and 4K stream cams",
    badge: "🎙️ Studio",
    displayOrder: 8,
    productIds: [
      "shure-sm7b",
      "shure-mv7",
      "rode-podmic",
      "rode-nt1",
      "rode-wireless-pro",
      "dji-mic",
      "elgato-wave-3",
      "elgato-wave-dx",
      "focusrite-scarlett-2i2",
      "focusrite-scarlett-4i4",
      "universal-audio-volt",
      "elgato-key-light",
      "elgato-facecam",
      "logitech-mx-brio",
      "sony-zv-e10",
      "sony-zv-1-ii",
      "canon-powershot-v10",
      "4k-stream-webcam",
      "streaming-microphone",
      "audio-interface",
    ],
  },
  {
    id: "storage-backup",
    title: "Storage & Backup",
    subtitle: "High-speed portable NVMe drives, creative NAS vaults, and pro SD media cards",
    badge: "💾 Backup",
    displayOrder: 9,
    productIds: [
      "samsung-t7-ssd",
      "samsung-t9-ssd",
      "sandisk-extreme-portable-ssd",
      "wd-my-passport",
      "wd-black-sn850x",
      "crucial-t500",
      "synology-nas",
      "qnap-nas",
      "sandisk-extreme-pro-sd-card",
      "samsung-pro-plus-microsd",
      "external-ssd",
    ],
  },
  {
    id: "desk-setup",
    title: "Keyboards, Mice & Desk Setup",
    subtitle: "Custom mechanical boards, ergonomic seating, dual-motor desks, and clean accessories",
    badge: "⌨️ Workstation",
    displayOrder: 10,
    productIds: [
      "keychron-q-series",
      "keychron-k-series",
      "logitech-mx-mechanical",
      "logitech-mx-keys",
      "logitech-mx-master-3s",
      "logitech-g-pro-x-keyboard",
      "razer-blackwidow",
      "razer-huntsman",
      "steelseries-apex-pro",
      "wooting-80he",
      "apple-magic-keyboard",
      "apple-magic-mouse",
      "herman-miller-embody",
      "herman-miller-aeron",
      "secretlab-titan-evo",
      "standing-desk",
      "monitor-arm",
      "desk-mat",
      "laptop-stand",
      "mechanical-keyboard",
    ],
  },
  {
    id: "networking-smarthome",
    title: "Networking & Smart Home",
    subtitle: "Enterprise Wi-Fi 7 routers, computational home audio, and adaptive smart lighting",
    badge: "🌐 Connected",
    displayOrder: 11,
    productIds: [
      "ubiquiti-unifi-dream-machine",
      "ubiquiti-unifi-access-point",
      "tp-link-wi-fi-7-router",
      "asus-wi-fi-7-router",
      "google-nest-wifi-pro",
      "amazon-echo",
      "google-nest-hub",
      "apple-homepod",
      "philips-hue-starter-kit",
      "nanoleaf-panels",
      "smart-led-light-strip",
    ],
  },
  {
    id: "accessories-power",
    title: "Accessories & Power",
    subtitle: "High-wattage GaN power banks, MagSafe chargers, Thunderbolt docks, and cabling",
    badge: "🔋 Essential",
    displayOrder: 12,
    productIds: [
      "anker-power-bank",
      "anker-prime-power-bank",
      "magsafe-battery-pack",
      "anker-gan-charger",
      "apple-35w-dual-usb-c-charger",
      "apple-70w-usb-c-charger",
      "ugreen-gan-charger",
      "usb-c-hub",
      "thunderbolt-dock",
      "magsafe-charger",
      "apple-watch-charger",
      "usb-c-cable",
      "hdmi-21-cable",
      "laptop-cooling-pad",
      "cable-management-kit",
    ],
  },
  {
    id: "wearables-future-tech",
    title: "Wearables & Future Tech",
    subtitle: "Spatial computing headsets, smart camera glasses, titanium rings, and health smartwatches",
    badge: "🥽 Next-Gen",
    displayOrder: 13,
    productIds: [
      "apple-watch",
      "apple-watch-ultra",
      "samsung-galaxy-watch",
      "google-pixel-watch",
      "garmin-fenix",
      "oura-ring",
      "ray-ban-meta-smart-glasses",
      "meta-quest-3",
      "apple-vision-pro",
      "dji-goggles",
    ],
  },
  {
    id: "smart-lifestyle",
    title: "Smart & Lifestyle Electronics",
    subtitle: "Intelligent hair care, smart espresso makers, 4K laser projectors, and robotic vacuums",
    badge: "✨ Lifestyle",
    displayOrder: 14,
    productIds: [
      "dyson-airwrap",
      "dyson-supersonic",
      "dyson-air-purifier",
      "philips-air-fryer",
      "philips-sonicare",
      "oral-b-io",
      "kindle",
      "kobo-libra",
      "digital-photo-frame",
      "smart-projector",
      "portable-projector",
      "robot-vacuum",
      "smart-coffee-machine",
    ],
  },
];

/** Full list of Electronics products */
export const RAW_ELECTRONICS_PRODUCTS: Array<{
  id: string;
  name: string;
  brand: string;
  subcategory: string;
  sectionId: string;
  sectionTitle: string;
  description: string;
  tags: string[];
  featured?: boolean;
  trending?: boolean;
}> = [
  // === Original 14 Preserved Items ===
  {
    id: "macbook-pro",
    name: "MacBook Pro",
    brand: "Apple",
    subcategory: "Laptops",
    sectionId: "trending",
    sectionTitle: "Trending Now",
    description: "The ultimate creative powerhouse laptop with Liquid Retina XDR display and M-series Silicon.",
    tags: ["apple", "laptop", "macbook", "creator", "coding", "editing", "trending"],
    featured: true,
    trending: true,
  },
  {
    id: "macbook-air",
    name: "MacBook Air",
    brand: "Apple",
    subcategory: "Laptops",
    sectionId: "trending",
    sectionTitle: "Trending Now",
    description: "Ultra-thin, silent, and incredibly fast daily laptop built for mobility and battery life.",
    tags: ["apple", "macbook", "air", "ultrabook", "lightweight", "trending"],
    featured: true,
    trending: true,
  },
  {
    id: "airpods-pro",
    name: "AirPods Pro",
    brand: "Apple",
    subcategory: "Earbuds",
    sectionId: "trending",
    sectionTitle: "Trending Now",
    description: "Active Noise Cancellation, Transparency mode, and personalized Spatial Audio for daily focus.",
    tags: ["apple", "airpods", "audio", "earbuds", "anc", "trending"],
    featured: true,
    trending: true,
  },
  {
    id: "sony-wh-1000xm5",
    name: "Sony WH-1000XM5",
    brand: "Sony",
    subcategory: "Headphones",
    sectionId: "trending",
    sectionTitle: "Trending Now",
    description: "Industry-leading noise cancelling wireless headphones with 30-hour battery and exceptional clarity.",
    tags: ["sony", "headphones", "anc", "audio", "music", "trending"],
    featured: true,
    trending: true,
  },
  {
    id: "ipad-pro",
    name: "iPad Pro",
    brand: "Apple",
    subcategory: "Tablets",
    sectionId: "laptops-computers",
    sectionTitle: "Laptops & Computers",
    description: "Tandem OLED Ultra Retina XDR display with Apple Pencil Pro precision for sketching and workflows.",
    tags: ["apple", "ipad", "tablet", "drawing", "design"],
    featured: true,
  },
  {
    id: "mirrorless-camera",
    name: "Mirrorless Camera",
    brand: "Sony",
    subcategory: "Cameras",
    sectionId: "cameras-photography",
    sectionTitle: "Cameras & Photography",
    description: "Full-frame 4K hybrid mirrorless camera for cinematic YouTube videos, reels, and editorial stills.",
    tags: ["camera", "sony", "photo", "video", "youtube", "creator"],
    featured: true,
  },
  {
    id: "gaming-monitor",
    name: "Gaming Monitor",
    brand: "LG",
    subcategory: "Monitors",
    sectionId: "monitors-displays",
    sectionTitle: "Monitors & Displays",
    description: "High refresh rate UltraGear gaming monitor with ultra-low latency response for work and competitive play.",
    tags: ["monitor", "gaming", "screen", "display", "high-refresh"],
    featured: true,
  },
  {
    id: "mechanical-keyboard",
    name: "Mechanical Keyboard",
    brand: "Keychron",
    subcategory: "Desk Setup",
    sectionId: "desk-setup",
    sectionTitle: "Keyboards, Mice & Desk Setup",
    description: "Hot-swappable custom mechanical keyboard with tactile switches and custom CNC aluminum frame.",
    tags: ["keyboard", "mechanical", "keychron", "desk", "setup"],
    featured: true,
  },
  {
    id: "streaming-microphone",
    name: "Streaming Microphone",
    brand: "Shure",
    subcategory: "Creator Gear",
    sectionId: "creator-streaming",
    sectionTitle: "Creator & Streaming",
    description: "Studio broadcast dynamic microphone engineered for rich podcasting, streaming, and vocal capture.",
    tags: ["mic", "microphone", "shure", "streaming", "podcast", "audio"],
    featured: true,
  },
  {
    id: "external-ssd",
    name: "External SSD",
    brand: "Samsung",
    subcategory: "Storage",
    sectionId: "storage-backup",
    sectionTitle: "Storage & Backup",
    description: "Blazing-fast rugged USB 3.2 Gen 2 portable solid state drive for video footage and heavy projects.",
    tags: ["ssd", "storage", "samsung", "backup", "drive"],
    featured: true,
  },
  {
    id: "standing-desk",
    name: "Standing Desk",
    brand: "Autonomous",
    subcategory: "Desk Setup",
    sectionId: "desk-setup",
    sectionTitle: "Keyboards, Mice & Desk Setup",
    description: "Dual-motor motorized height adjustable sit-stand desk for healthier, energized creative workdays.",
    tags: ["desk", "standing-desk", "ergonomics", "workspace", "furniture"],
    featured: true,
  },
  {
    id: "smart-projector",
    name: "Smart Projector",
    brand: "XGIMI",
    subcategory: "Smart Electronics",
    sectionId: "smart-lifestyle",
    sectionTitle: "Smart & Lifestyle Electronics",
    description: "4K smart laser home theater projector with Harman Kardon sound and auto-keystone correction.",
    tags: ["projector", "cinema", "movie", "home-theater", "4k"],
    featured: true,
  },
  {
    id: "audio-interface",
    name: "Audio Interface",
    brand: "Focusrite",
    subcategory: "Creator Gear",
    sectionId: "creator-streaming",
    sectionTitle: "Creator & Streaming",
    description: "High-fidelity USB studio audio interface with ultra-low noise preamps and Auto-Gain.",
    tags: ["audio", "interface", "focusrite", "studio", "sound", "recording"],
    featured: true,
  },
  {
    id: "4k-stream-webcam",
    name: "4K Stream Webcam",
    brand: "Elgato",
    subcategory: "Creator Gear",
    sectionId: "creator-streaming",
    sectionTitle: "Creator & Streaming",
    description: "Sony STARVIS sensor uncompressed 4K60 HDR streaming webcam for pristine creator broadcast visuals.",
    tags: ["webcam", "camera", "4k", "elgato", "streaming", "zoom"],
    featured: true,
  },

  // === Section 1 Extra Trending Items ===
  {
    id: "iphone-17-pro",
    name: "iPhone 17 Pro",
    brand: "Apple",
    subcategory: "Phones",
    sectionId: "trending",
    sectionTitle: "Trending Now",
    description: "Next-generation titanium flagship with pro camera system and Apple Intelligence.",
    tags: ["apple", "iphone", "phone", "mobile", "trending", "camera"],
    trending: true,
  },
  {
    id: "iphone-17",
    name: "iPhone 17",
    brand: "Apple",
    subcategory: "Phones",
    sectionId: "trending",
    sectionTitle: "Trending Now",
    description: "Sleek all-day iPhone with vivid Super Retina display and ultra-fast performance.",
    tags: ["apple", "iphone", "mobile", "trending"],
    trending: true,
  },
  {
    id: "samsung-galaxy-s26-ultra",
    name: "Samsung Galaxy S26 Ultra",
    brand: "Samsung",
    subcategory: "Phones",
    sectionId: "trending",
    sectionTitle: "Trending Now",
    description: "Android titan with integrated S-Pen, quad telephoto zoom cameras, and massive AMOLED display.",
    tags: ["samsung", "galaxy", "ultra", "android", "phone", "trending"],
    trending: true,
  },
  {
    id: "google-pixel-10-pro",
    name: "Google Pixel 10 Pro",
    brand: "Google",
    subcategory: "Phones",
    sectionId: "trending",
    sectionTitle: "Trending Now",
    description: "Google Tensor-powered photography master with pure Android and computational camera chops.",
    tags: ["google", "pixel", "android", "phone", "camera", "trending"],
    trending: true,
  },
  {
    id: "airpods-max",
    name: "AirPods Max",
    brand: "Apple",
    subcategory: "Headphones",
    sectionId: "trending",
    sectionTitle: "Trending Now",
    description: "High-fidelity over-ear headphones with custom acoustic design and computational audio.",
    tags: ["apple", "airpods", "headphones", "audio", "premium", "trending"],
    trending: true,
  },
  {
    id: "playstation-5",
    name: "PlayStation 5",
    brand: "Sony",
    subcategory: "Consoles",
    sectionId: "trending",
    sectionTitle: "Trending Now",
    description: "Next-generation 4K gaming console with ultra-fast custom SSD and DualSense haptic feedback.",
    tags: ["sony", "playstation", "ps5", "gaming", "console", "trending"],
    trending: true,
  },
  {
    id: "playstation-5-pro",
    name: "PlayStation 5 Pro",
    brand: "Sony",
    subcategory: "Consoles",
    sectionId: "trending",
    sectionTitle: "Trending Now",
    description: "Enhanced GPU with advanced ray tracing and PlayStation Spectral Super Resolution AI upscaling.",
    tags: ["sony", "playstation", "ps5-pro", "gaming", "console", "trending"],
    trending: true,
  },
  {
    id: "nintendo-switch-2",
    name: "Nintendo Switch 2",
    brand: "Nintendo",
    subcategory: "Consoles",
    sectionId: "trending",
    sectionTitle: "Trending Now",
    description: "Next-gen hybrid console for home and handheld play with richer graphics and bigger display.",
    tags: ["nintendo", "switch", "gaming", "handheld", "console", "trending"],
    trending: true,
  },
  {
    id: "xbox-series-x",
    name: "Xbox Series X",
    brand: "Microsoft",
    subcategory: "Consoles",
    sectionId: "trending",
    sectionTitle: "Trending Now",
    description: "The fastest, most powerful Xbox ever with 12 teraflops of raw graphical processing power.",
    tags: ["microsoft", "xbox", "gaming", "console", "gamepass", "trending"],
    trending: true,
  },
  {
    id: "nvidia-geforce-rtx-5090",
    name: "NVIDIA GeForce RTX 5090",
    brand: "NVIDIA",
    subcategory: "GPU & PC Hardware",
    sectionId: "trending",
    sectionTitle: "Trending Now",
    description: "The apex Blackwell architecture graphics card for extreme 4K gaming, AI compute, and rendering.",
    tags: ["nvidia", "rtx", "5090", "gpu", "hardware", "gaming", "ai", "trending"],
    trending: true,
  },
  {
    id: "nvidia-geforce-rtx-5080",
    name: "NVIDIA GeForce RTX 5080",
    brand: "NVIDIA",
    subcategory: "GPU & PC Hardware",
    sectionId: "trending",
    sectionTitle: "Trending Now",
    description: "Enthusiast-grade Blackwell graphics card delivering massive ray tracing and DLSS 4 performance.",
    tags: ["nvidia", "rtx", "5080", "gpu", "hardware", "gaming", "trending"],
    trending: true,
  },
  {
    id: "nvidia-geforce-rtx-5070-ti",
    name: "NVIDIA GeForce RTX 5070 Ti",
    brand: "NVIDIA",
    subcategory: "GPU & PC Hardware",
    sectionId: "trending",
    sectionTitle: "Trending Now",
    description: "High-performance GPU engineered for 1440p and 4K creative workstations and high-FPS gaming.",
    tags: ["nvidia", "rtx", "5070ti", "gpu", "hardware", "trending"],
    trending: true,
  },
  {
    id: "asus-rog-ally-x",
    name: "ASUS ROG Ally X",
    brand: "ASUS",
    subcategory: "Gaming",
    sectionId: "trending",
    sectionTitle: "Trending Now",
    description: "Windows handheld gaming beast with AMD Ryzen Z1 Extreme, 24GB RAM, and huge 80Wh battery.",
    tags: ["asus", "rog", "handheld", "gaming", "pc", "trending"],
    trending: true,
  },
  {
    id: "steam-deck-oled",
    name: "Steam Deck OLED",
    brand: "Valve",
    subcategory: "Gaming",
    sectionId: "trending",
    sectionTitle: "Trending Now",
    description: "HDR OLED screen, longer battery life, and faster Wi-Fi 6E for portable Steam library gaming.",
    tags: ["valve", "steam", "steamdeck", "oled", "handheld", "gaming", "trending"],
    trending: true,
  },
  {
    id: "meta-quest-3",
    name: "Meta Quest 3",
    brand: "Meta",
    subcategory: "Gaming",
    sectionId: "trending",
    sectionTitle: "Trending Now",
    description: "Breakthrough mixed reality headset with high-resolution full-color passthrough and spatial audio.",
    tags: ["meta", "quest", "vr", "mixed-reality", "gaming", "trending"],
    trending: true,
  },
  {
    id: "apple-vision-pro",
    name: "Apple Vision Pro",
    brand: "Apple",
    subcategory: "Wearables & Future Tech",
    sectionId: "trending",
    sectionTitle: "Trending Now",
    description: "Revolutionary spatial computer that seamlessly blends digital media with your physical world.",
    tags: ["apple", "vision-pro", "spatial", "vr", "ar", "future", "trending"],
    trending: true,
  },
  {
    id: "samsung-odyssey-oled-g9",
    name: "Samsung Odyssey OLED G9",
    brand: "Samsung",
    subcategory: "Monitors",
    sectionId: "trending",
    sectionTitle: "Trending Now",
    description: "49-inch dual QHD curved OLED gaming monitor with 240Hz refresh rate and 0.03ms response time.",
    tags: ["samsung", "odyssey", "oled", "monitor", "ultrawide", "gaming", "trending"],
    trending: true,
  },

  // === Section 2: Laptops & Computers ===
  {
    id: "macbook-pro-14",
    name: "MacBook Pro 14\"",
    brand: "Apple",
    subcategory: "Laptops",
    sectionId: "laptops-computers",
    sectionTitle: "Laptops & Computers",
    description: "Pro performance in a portable 14-inch form factor with Liquid Retina XDR screen.",
    tags: ["apple", "macbook", "pro", "laptop", "14inch"],
  },
  {
    id: "macbook-pro-16",
    name: "MacBook Pro 16\"",
    brand: "Apple",
    subcategory: "Laptops",
    sectionId: "laptops-computers",
    sectionTitle: "Laptops & Computers",
    description: "Maximum screen real estate, sustained peak M-series power, and industry-leading battery longevity.",
    tags: ["apple", "macbook", "pro", "laptop", "16inch"],
  },
  {
    id: "macbook-air-13",
    name: "MacBook Air 13\"",
    brand: "Apple",
    subcategory: "Laptops",
    sectionId: "laptops-computers",
    sectionTitle: "Laptops & Computers",
    description: "The world's favorite ultrabook, ultra-thin and whisper-silent fanless design.",
    tags: ["apple", "macbook", "air", "13inch"],
  },
  {
    id: "macbook-air-15",
    name: "MacBook Air 15\"",
    brand: "Apple",
    subcategory: "Laptops",
    sectionId: "laptops-computers",
    sectionTitle: "Laptops & Computers",
    description: "Expansive 15.3-inch Liquid Retina display in an impossibly thin aluminum unibody.",
    tags: ["apple", "macbook", "air", "15inch"],
  },
  {
    id: "mac-mini",
    name: "Mac Mini",
    brand: "Apple",
    subcategory: "Desktops",
    sectionId: "laptops-computers",
    sectionTitle: "Laptops & Computers",
    description: "Compact desktop powerhouse that fits anywhere and punches way above its weight class.",
    tags: ["apple", "mac", "mini", "desktop", "silicon"],
  },
  {
    id: "mac-studio",
    name: "Mac Studio",
    brand: "Apple",
    subcategory: "Desktops",
    sectionId: "laptops-computers",
    sectionTitle: "Laptops & Computers",
    description: "Studio-grade desktop workstation engineered for massive 3D renders, video timelines, and code compilation.",
    tags: ["apple", "mac", "studio", "workstation", "creative"],
  },
  {
    id: "imac",
    name: "iMac",
    brand: "Apple",
    subcategory: "Desktops",
    sectionId: "laptops-computers",
    sectionTitle: "Laptops & Computers",
    description: "All-in-one desktop marvel with stunning 24-inch 4.5K Retina display in bold color finishes.",
    tags: ["apple", "imac", "all-in-one", "desktop"],
  },
  {
    id: "dell-xps-13",
    name: "Dell XPS 13",
    brand: "Dell",
    subcategory: "Laptops",
    sectionId: "laptops-computers",
    sectionTitle: "Laptops & Computers",
    description: "Iconic minimalist Windows ultrabook with edge-to-edge InfinityEdge glass.",
    tags: ["dell", "xps", "windows", "ultrabook", "laptop"],
  },
  {
    id: "dell-xps-16",
    name: "Dell XPS 16",
    brand: "Dell",
    subcategory: "Laptops",
    sectionId: "laptops-computers",
    sectionTitle: "Laptops & Computers",
    description: "Premium large-screen creator laptop with dedicated RTX graphics and OLED display options.",
    tags: ["dell", "xps", "creator", "laptop", "16inch"],
  },
  {
    id: "microsoft-surface-laptop",
    name: "Microsoft Surface Laptop",
    brand: "Microsoft",
    subcategory: "Laptops",
    sectionId: "laptops-computers",
    sectionTitle: "Laptops & Computers",
    description: "Copilot+ PC with Snapdragon X Elite silicon, PixelSense touchscreen, and incredible battery life.",
    tags: ["microsoft", "surface", "laptop", "copilot", "windows"],
  },
  {
    id: "microsoft-surface-pro",
    name: "Microsoft Surface Pro",
    brand: "Microsoft",
    subcategory: "Laptops",
    sectionId: "laptops-computers",
    sectionTitle: "Laptops & Computers",
    description: "The most versatile 2-in-1 tablet PC with detachable Flex keyboard and precision Slim Pen.",
    tags: ["microsoft", "surface", "tablet", "2in1"],
  },
  {
    id: "lenovo-thinkpad-x1-carbon",
    name: "Lenovo ThinkPad X1 Carbon",
    brand: "Lenovo",
    subcategory: "Laptops",
    sectionId: "laptops-computers",
    sectionTitle: "Laptops & Computers",
    description: "The legendary executive lightweight business machine with mil-spec durability and world-class keyboard.",
    tags: ["lenovo", "thinkpad", "x1", "carbon", "business", "laptop"],
  },
  {
    id: "lenovo-yoga-pro",
    name: "Lenovo Yoga Pro",
    brand: "Lenovo",
    subcategory: "Laptops",
    sectionId: "laptops-computers",
    sectionTitle: "Laptops & Computers",
    description: "Creator-tuned laptop with PureSight Pro calibrated color display and NVIDIA RTX acceleration.",
    tags: ["lenovo", "yoga", "creator", "laptop"],
  },
  {
    id: "hp-spectre-x360",
    name: "HP Spectre x360",
    brand: "HP",
    subcategory: "Laptops",
    sectionId: "laptops-computers",
    sectionTitle: "Laptops & Computers",
    description: "Gem-cut precision 2-in-1 convertible laptop with OLED touch and AI audio enhancement.",
    tags: ["hp", "spectre", "convertible", "laptop"],
  },
  {
    id: "asus-zenbook",
    name: "ASUS Zenbook",
    brand: "ASUS",
    subcategory: "Laptops",
    sectionId: "laptops-computers",
    sectionTitle: "Laptops & Computers",
    description: "Ultra-slim Lumina OLED laptop built with innovative Ceraluminum aerospace material.",
    tags: ["asus", "zenbook", "oled", "laptop"],
  },
  {
    id: "asus-proart",
    name: "ASUS ProArt",
    brand: "ASUS",
    subcategory: "Laptops",
    sectionId: "laptops-computers",
    sectionTitle: "Laptops & Computers",
    description: "Dedicated workstation laptop with physical ASUS DialPad for Adobe and video workflows.",
    tags: ["asus", "proart", "creator", "design", "workstation"],
  },
  {
    id: "acer-swift",
    name: "Acer Swift",
    brand: "Acer",
    subcategory: "Laptops",
    sectionId: "laptops-computers",
    sectionTitle: "Laptops & Computers",
    description: "Featherlight everyday laptop with high-refresh OLED panel and long battery longevity.",
    tags: ["acer", "swift", "laptop", "lightweight"],
  },
  {
    id: "razer-blade-16",
    name: "Razer Blade 16",
    brand: "Razer",
    subcategory: "Gaming Laptops",
    sectionId: "laptops-computers",
    sectionTitle: "Laptops & Computers",
    description: "CNC anodized aluminum gaming laptop featuring dual-mode Mini-LED/OLED display and RTX 4090.",
    tags: ["razer", "blade", "gaming", "laptop", "rgb"],
  },
  {
    id: "asus-rog-strix",
    name: "ASUS ROG Strix",
    brand: "ASUS",
    subcategory: "Gaming Laptops",
    sectionId: "laptops-computers",
    sectionTitle: "Laptops & Computers",
    description: "Maxed-out cooling and flagship processor gaming laptop for tournament-level FPS performance.",
    tags: ["asus", "rog", "strix", "gaming", "laptop"],
  },
  {
    id: "asus-rog-zephyrus-g14",
    name: "ASUS ROG Zephyrus G14",
    brand: "ASUS",
    subcategory: "Gaming Laptops",
    sectionId: "laptops-computers",
    sectionTitle: "Laptops & Computers",
    description: "The gold standard compact 14-inch gaming laptop with ROG Nebula OLED screen.",
    tags: ["asus", "zephyrus", "g14", "gaming", "laptop"],
  },
  {
    id: "lenovo-legion-pro",
    name: "Lenovo Legion Pro",
    brand: "Lenovo",
    subcategory: "Gaming Laptops",
    sectionId: "laptops-computers",
    sectionTitle: "Laptops & Computers",
    description: "AI-tuned gaming powerhouse with Legion Coldfront vapor chamber cooling system.",
    tags: ["lenovo", "legion", "gaming", "laptop"],
  },
  {
    id: "alienware-gaming-laptop",
    name: "Alienware Gaming Laptop",
    brand: "Alienware",
    subcategory: "Gaming Laptops",
    sectionId: "laptops-computers",
    sectionTitle: "Laptops & Computers",
    description: "Legendary sci-fi aesthetic chassis with Cryo-tech cooling and CherryMX mechanical keyboard.",
    tags: ["alienware", "dell", "gaming", "laptop"],
  },
  {
    id: "msi-raider",
    name: "MSI Raider",
    brand: "MSI",
    subcategory: "Gaming Laptops",
    sectionId: "laptops-computers",
    sectionTitle: "Laptops & Computers",
    description: "Uncompromised desktop replacement laptop with matrix lightbar and extreme overclocking support.",
    tags: ["msi", "raider", "gaming", "laptop"],
  },
  {
    id: "acer-predator-helios",
    name: "Acer Predator Helios",
    brand: "Acer",
    subcategory: "Gaming Laptops",
    sectionId: "laptops-computers",
    sectionTitle: "Laptops & Computers",
    description: "High-wattage performance with 5th Gen AeroBlade 3D fan technology and per-key RGB.",
    tags: ["acer", "predator", "helios", "gaming", "laptop"],
  },

  // === Section 3: Audio Store ===
  {
    id: "sony-wh-1000xm6",
    name: "Sony WH-1000XM6",
    brand: "Sony",
    subcategory: "Headphones",
    sectionId: "audio-store",
    sectionTitle: "Audio Store",
    description: "Next-generation noise cancellation flagship with refined acoustic chamber and multi-point LDAC.",
    tags: ["sony", "headphones", "anc", "audio", "bluetooth"],
  },
  {
    id: "bose-quietcomfort-ultra",
    name: "Bose QuietComfort Ultra",
    brand: "Bose",
    subcategory: "Headphones",
    sectionId: "audio-store",
    sectionTitle: "Audio Store",
    description: "World-class noise cancellation with Bose Immersive Audio spatial soundstage.",
    tags: ["bose", "quietcomfort", "headphones", "anc", "audio"],
  },
  {
    id: "bose-quietcomfort-headphones",
    name: "Bose QuietComfort Headphones",
    brand: "Bose",
    subcategory: "Headphones",
    sectionId: "audio-store",
    sectionTitle: "Audio Store",
    description: "Legendary comfort and signature Bose acoustic tuning for all-day listening.",
    tags: ["bose", "headphones", "anc", "audio"],
  },
  {
    id: "apple-airpods-max",
    name: "Apple AirPods Max",
    brand: "Apple",
    subcategory: "Headphones",
    sectionId: "audio-store",
    sectionTitle: "Audio Store",
    description: "Anodized aluminum earcups, knit mesh canopy, and high-fidelity computational audio.",
    tags: ["apple", "airpods", "max", "headphones", "audio"],
  },
  {
    id: "sennheiser-momentum-4",
    name: "Sennheiser Momentum 4",
    brand: "Sennheiser",
    subcategory: "Headphones",
    sectionId: "audio-store",
    sectionTitle: "Audio Store",
    description: "Signature audiophile acoustic performance backed by an unbeatable 60-hour battery life.",
    tags: ["sennheiser", "momentum", "headphones", "audiophile"],
  },
  {
    id: "sennheiser-hd-600",
    name: "Sennheiser HD 600",
    brand: "Sennheiser",
    subcategory: "Headphones",
    sectionId: "audio-store",
    sectionTitle: "Audio Store",
    description: "The gold-standard open-back reference studio headphones revered by sound engineers worldwide.",
    tags: ["sennheiser", "hd600", "openback", "studio", "audiophile"],
  },
  {
    id: "audio-technica-ath-m50x",
    name: "Audio-Technica ATH-M50x",
    brand: "Audio-Technica",
    subcategory: "Headphones",
    sectionId: "audio-store",
    sectionTitle: "Audio Store",
    description: "Professional studio monitor headphones praised by top audio pros and content creators.",
    tags: ["audiotechnica", "m50x", "studio", "headphones", "monitoring"],
  },
  {
    id: "beyerdynamic-dt-770-pro",
    name: "Beyerdynamic DT 770 Pro",
    brand: "Beyerdynamic",
    subcategory: "Headphones",
    sectionId: "audio-store",
    sectionTitle: "Audio Store",
    description: "Closed-back studio headphones offering remarkable acoustic isolation and deep bass reproduction.",
    tags: ["beyerdynamic", "dt770", "studio", "headphones"],
  },
  {
    id: "beyerdynamic-dt-990-pro",
    name: "Beyerdynamic DT 990 Pro",
    brand: "Beyerdynamic",
    subcategory: "Headphones",
    sectionId: "audio-store",
    sectionTitle: "Audio Store",
    description: "Open-back studio reference headphones delivering incredible three-dimensional soundstage.",
    tags: ["beyerdynamic", "dt990", "openback", "studio", "headphones"],
  },
  {
    id: "airpods",
    name: "AirPods",
    brand: "Apple",
    subcategory: "Earbuds",
    sectionId: "audio-store",
    sectionTitle: "Audio Store",
    description: "Open-ear wireless convenience with USB-C case and instant Apple ecosystem pairing.",
    tags: ["apple", "airpods", "earbuds", "wireless"],
  },
  {
    id: "sony-wf-1000xm5",
    name: "Sony WF-1000XM5",
    brand: "Sony",
    subcategory: "Earbuds",
    sectionId: "audio-store",
    sectionTitle: "Audio Store",
    description: "Pocketable flagship noise cancelling earbuds with dual feedback microphones and Dynamic Driver X.",
    tags: ["sony", "earbuds", "anc", "audio", "wireless"],
  },
  {
    id: "bose-quietcomfort-ultra-earbuds",
    name: "Bose QuietComfort Ultra Earbuds",
    brand: "Bose",
    subcategory: "Earbuds",
    sectionId: "audio-store",
    sectionTitle: "Audio Store",
    description: "World-leading in-ear noise cancellation paired with CustomTune personalized audio.",
    tags: ["bose", "quietcomfort", "earbuds", "anc"],
  },
  {
    id: "samsung-galaxy-buds3-pro",
    name: "Samsung Galaxy Buds3 Pro",
    brand: "Samsung",
    subcategory: "Earbuds",
    sectionId: "audio-store",
    sectionTitle: "Audio Store",
    description: "Blade design with adaptive noise control and 24-bit Hi-Fi sound processing.",
    tags: ["samsung", "galaxy", "buds", "earbuds", "wireless"],
  },
  {
    id: "nothing-ear",
    name: "Nothing Ear",
    brand: "Nothing",
    subcategory: "Earbuds",
    sectionId: "audio-store",
    sectionTitle: "Audio Store",
    description: "Transparent design icon featuring custom ceramic driver and advanced ChatGPT voice integration.",
    tags: ["nothing", "earbuds", "transparent", "design", "audio"],
  },
  {
    id: "sennheiser-momentum-true-wireless",
    name: "Sennheiser Momentum True Wireless",
    brand: "Sennheiser",
    subcategory: "Earbuds",
    sectionId: "audio-store",
    sectionTitle: "Audio Store",
    description: "Audiophile-grade TrueResponse transducer system with lossless audio and Auracast support.",
    tags: ["sennheiser", "momentum", "earbuds", "audiophile"],
  },
  {
    id: "sonos-era-100",
    name: "Sonos Era 100",
    brand: "Sonos",
    subcategory: "Speakers",
    sectionId: "audio-store",
    sectionTitle: "Audio Store",
    description: "Next-gen smart speaker featuring stereo sound, deep bass, and Trueplay tuning.",
    tags: ["sonos", "speaker", "smarthome", "audio", "wifi"],
  },
  {
    id: "sonos-era-300",
    name: "Sonos Era 300",
    brand: "Sonos",
    subcategory: "Speakers",
    sectionId: "audio-store",
    sectionTitle: "Audio Store",
    description: "Revolutionary spatial audio speaker with Dolby Atmos drivers firing in all directions.",
    tags: ["sonos", "speaker", "dolbyatmos", "spatial", "audio"],
  },
  {
    id: "sonos-arc",
    name: "Sonos Arc",
    brand: "Sonos",
    subcategory: "Speakers",
    sectionId: "audio-store",
    sectionTitle: "Audio Store",
    description: "Premium smart soundbar bringing cinema-grade Dolby Atmos 3D audio to your living room.",
    tags: ["sonos", "soundbar", "cinema", "dolbyatmos", "tv"],
  },
  {
    id: "jbl-charge",
    name: "JBL Charge",
    brand: "JBL",
    subcategory: "Speakers",
    sectionId: "audio-store",
    sectionTitle: "Audio Store",
    description: "Rugged waterproof portable Bluetooth speaker with built-in power bank for all-day jams.",
    tags: ["jbl", "charge", "speaker", "bluetooth", "portable", "waterproof"],
  },
  {
    id: "jbl-flip",
    name: "JBL Flip",
    brand: "JBL",
    subcategory: "Speakers",
    sectionId: "audio-store",
    sectionTitle: "Audio Store",
    description: "Ultra-compact grab-and-go waterproof Bluetooth speaker with bold JBL Original Pro Sound.",
    tags: ["jbl", "flip", "speaker", "bluetooth", "portable"],
  },
  {
    id: "marshall-stanmore",
    name: "Marshall Stanmore",
    brand: "Marshall",
    subcategory: "Speakers",
    sectionId: "audio-store",
    sectionTitle: "Audio Store",
    description: "Vintage rock 'n' roll aesthetic home Bluetooth speaker with re-engineered wider soundstage.",
    tags: ["marshall", "stanmore", "speaker", "vintage", "audio"],
  },
  {
    id: "marshall-acton",
    name: "Marshall Acton",
    brand: "Marshall",
    subcategory: "Speakers",
    sectionId: "audio-store",
    sectionTitle: "Audio Store",
    description: "Compact home speaker with brass details, analogue interaction knobs, and room-filling sound.",
    tags: ["marshall", "acton", "speaker", "vintage", "bluetooth"],
  },
  {
    id: "bose-soundlink",
    name: "Bose SoundLink",
    brand: "Bose",
    subcategory: "Speakers",
    sectionId: "audio-store",
    sectionTitle: "Audio Store",
    description: "Portable 360-degree wireless Bluetooth speaker engineered for consistent uniform sound coverage.",
    tags: ["bose", "soundlink", "speaker", "bluetooth", "portable"],
  },

  // === Section 4: Gaming ===
  {
    id: "xbox-series-s",
    name: "Xbox Series S",
    brand: "Microsoft",
    subcategory: "Consoles",
    sectionId: "gaming",
    sectionTitle: "Gaming",
    description: "All-digital compact next-gen Xbox console offering 1440p gaming up to 120fps.",
    tags: ["microsoft", "xbox", "series-s", "gaming", "console"],
  },
  {
    id: "lenovo-legion-go",
    name: "Lenovo Legion Go",
    brand: "Lenovo",
    subcategory: "Handheld Gaming",
    sectionId: "gaming",
    sectionTitle: "Gaming",
    description: "Handheld PC with massive 8.8-inch QHD+ display and detachable TrueStrike controllers with FPS mode.",
    tags: ["lenovo", "legion", "handheld", "gaming", "pc"],
  },
  {
    id: "playstation-portal",
    name: "PlayStation Portal",
    brand: "Sony",
    subcategory: "Remote Play",
    sectionId: "gaming",
    sectionTitle: "Gaming",
    description: "Dedicated PS5 remote player featuring 8-inch 1080p 60fps screen and DualSense adaptive triggers.",
    tags: ["sony", "playstation", "portal", "remoteplay", "handheld"],
  },
  {
    id: "meta-quest-3s",
    name: "Meta Quest 3S",
    brand: "Meta",
    subcategory: "VR Headsets",
    sectionId: "gaming",
    sectionTitle: "Gaming",
    description: "Accessible mixed reality headset powered by Snapdragon XR2 Gen 2 for spatial immersion.",
    tags: ["meta", "quest3s", "vr", "mr", "gaming"],
  },
  {
    id: "dualsense-edge",
    name: "DualSense Edge",
    brand: "Sony",
    subcategory: "Controllers",
    sectionId: "gaming",
    sectionTitle: "Gaming",
    description: "Ultra-customizable PlayStation controller with swappable stick modules and mappable back buttons.",
    tags: ["sony", "playstation", "dualsense", "controller", "pro"],
  },
  {
    id: "xbox-elite-wireless-controller",
    name: "Xbox Elite Wireless Controller",
    brand: "Microsoft",
    subcategory: "Controllers",
    sectionId: "gaming",
    sectionTitle: "Gaming",
    description: "Adjustable-tension thumbsticks, wrap-around rubberized grip, and shorter hair trigger locks.",
    tags: ["microsoft", "xbox", "elite", "controller", "pro"],
  },
  {
    id: "nintendo-switch-pro-controller",
    name: "Nintendo Switch Pro Controller",
    brand: "Nintendo",
    subcategory: "Controllers",
    sectionId: "gaming",
    sectionTitle: "Gaming",
    description: "Premium ergonomic gamepad with HD rumble, motion controls, and built-in amiibo NFC reader.",
    tags: ["nintendo", "switch", "controller", "pro"],
  },
  {
    id: "logitech-g-pro-x-superlight",
    name: "Logitech G Pro X Superlight",
    brand: "Logitech",
    subcategory: "Gaming Mice",
    sectionId: "gaming",
    sectionTitle: "Gaming",
    description: "Sub-60g ultra-lightweight esports wireless gaming mouse with HERO 2 sensor and LIGHTSPEED tech.",
    tags: ["logitech", "mouse", "esports", "gaming", "wireless"],
  },
  {
    id: "razer-deathadder-v3",
    name: "Razer DeathAdder V3",
    brand: "Razer",
    subcategory: "Gaming Mice",
    sectionId: "gaming",
    sectionTitle: "Gaming",
    description: "Ergonomic esports mouse with Focus Pro 30K optical sensor and optical Gen-3 switches.",
    tags: ["razer", "deathadder", "mouse", "gaming", "esports"],
  },
  {
    id: "razer-blackshark-v2",
    name: "Razer BlackShark V2",
    brand: "Razer",
    subcategory: "Gaming Headsets",
    sectionId: "gaming",
    sectionTitle: "Gaming",
    description: "Esports headset with TriForce Titanium 50mm drivers and HyperClear supercardioid mic.",
    tags: ["razer", "blackshark", "headset", "gaming", "audio"],
  },
  {
    id: "steelseries-arctis-nova-pro",
    name: "SteelSeries Arctis Nova Pro",
    brand: "SteelSeries",
    subcategory: "Gaming Headsets",
    sectionId: "gaming",
    sectionTitle: "Gaming",
    description: "Flagship wireless gaming headset with Multi-System Connect, active noise cancellation, and hot-swap batteries.",
    tags: ["steelseries", "arctis", "headset", "gaming", "anc"],
  },
  {
    id: "elgato-stream-deck",
    name: "Elgato Stream Deck",
    brand: "Elgato",
    subcategory: "Stream Controllers",
    sectionId: "gaming",
    sectionTitle: "Gaming",
    description: "15 customizable LCD keys to trigger studio actions, switch scenes, and control smart workflows.",
    tags: ["elgato", "streamdeck", "streaming", "creator", "shortcuts"],
  },
  {
    id: "elgato-stream-deck-xl",
    name: "Elgato Stream Deck XL",
    brand: "Elgato",
    subcategory: "Stream Controllers",
    sectionId: "gaming",
    sectionTitle: "Gaming",
    description: "32 customizable LCD keys giving broadcast power users and streamers complete tactile command.",
    tags: ["elgato", "streamdeck", "xl", "streaming", "creator"],
  },

  // === Section 5: Monitors & Displays ===
  {
    id: "samsung-odyssey-oled-g8",
    name: "Samsung Odyssey OLED G8",
    brand: "Samsung",
    subcategory: "Monitors",
    sectionId: "monitors-displays",
    sectionTitle: "Monitors & Displays",
    description: "34-inch ultra-fast OLED curved display with Neo Quantum Processor and Smart TV hub.",
    tags: ["samsung", "odyssey", "oled", "monitor", "curved"],
  },
  {
    id: "lg-ultragear-oled",
    name: "LG UltraGear OLED",
    brand: "LG",
    subcategory: "Monitors",
    sectionId: "monitors-displays",
    sectionTitle: "Monitors & Displays",
    description: "Lightning-fast 240Hz OLED gaming monitor with 0.03ms GtG response and DCI-P3 98.5% color.",
    tags: ["lg", "ultragear", "oled", "monitor", "gaming"],
  },
  {
    id: "lg-ultrafine",
    name: "LG UltraFine",
    brand: "LG",
    subcategory: "Monitors",
    sectionId: "monitors-displays",
    sectionTitle: "Monitors & Displays",
    description: "5K resolution macOS companion monitor with Thunderbolt 3 connectivity and P3 wide color gamut.",
    tags: ["lg", "ultrafine", "5k", "monitor", "mac"],
  },
  {
    id: "apple-studio-display",
    name: "Apple Studio Display",
    brand: "Apple",
    subcategory: "Monitors",
    sectionId: "monitors-displays",
    sectionTitle: "Monitors & Displays",
    description: "27-inch 5K Retina display with 12MP Ultra Wide camera with Center Stage and 6-speaker sound.",
    tags: ["apple", "studio-display", "5k", "monitor", "mac"],
  },
  {
    id: "apple-pro-display-xdr",
    name: "Apple Pro Display XDR",
    brand: "Apple",
    subcategory: "Monitors",
    sectionId: "monitors-displays",
    sectionTitle: "Monitors & Displays",
    description: "32-inch 6K reference display with 1,000,000:1 contrast ratio and 1600 nits peak HDR brightness.",
    tags: ["apple", "pro-display-xdr", "6k", "hdr", "color-grading"],
  },
  {
    id: "dell-ultrasharp-4k",
    name: "Dell UltraSharp 4K",
    brand: "Dell",
    subcategory: "Monitors",
    sectionId: "monitors-displays",
    sectionTitle: "Monitors & Displays",
    description: "Color-accurate IPS Black monitor with Thunderbolt 4 hub and integrated KVM switch.",
    tags: ["dell", "ultrasharp", "4k", "monitor", "productivity"],
  },
  {
    id: "asus-proart-display",
    name: "ASUS ProArt Display",
    brand: "ASUS",
    subcategory: "Monitors",
    sectionId: "monitors-displays",
    sectionTitle: "Monitors & Displays",
    description: "Calman Verified factory calibrated display engineered for colorists, animators, and photographers.",
    tags: ["asus", "proart", "color-grading", "monitor", "designer"],
  },
  {
    id: "asus-rog-swift-oled",
    name: "ASUS ROG Swift OLED",
    brand: "ASUS",
    subcategory: "Monitors",
    sectionId: "monitors-displays",
    sectionTitle: "Monitors & Displays",
    description: "Cutting-edge ROG gaming monitor with custom heatsink cooling and anti-reflective micro-texture.",
    tags: ["asus", "rog", "swift", "oled", "monitor", "gaming"],
  },
  {
    id: "benq-pd-series",
    name: "BenQ PD Series",
    brand: "BenQ",
    subcategory: "Monitors",
    sectionId: "monitors-displays",
    sectionTitle: "Monitors & Displays",
    description: "Designer monitor with M-Book mode for seamless Mac color matching and Hotkey Puck controller.",
    tags: ["benq", "designer", "monitor", "4k", "color"],
  },
  {
    id: "gigabyte-aorus-gaming-monitor",
    name: "Gigabyte AORUS Gaming Monitor",
    brand: "Gigabyte",
    subcategory: "Monitors",
    sectionId: "monitors-displays",
    sectionTitle: "Monitors & Displays",
    description: "Tactical gaming display with Aim Stabilizer Sync and built-in Black Equalizer.",
    tags: ["gigabyte", "aorus", "gaming", "monitor"],
  },

  // === Section 6: NVIDIA & PC Hardware ===
  {
    id: "nvidia-geforce-rtx-5070",
    name: "NVIDIA GeForce RTX 5070",
    brand: "NVIDIA",
    subcategory: "PC Hardware",
    sectionId: "nvidia-hardware",
    sectionTitle: "NVIDIA & PC Hardware",
    description: "Next-gen Blackwell gaming graphics card delivering fluid high-frame-rate 1440p gaming.",
    tags: ["nvidia", "rtx", "5070", "gpu", "hardware"],
  },
  {
    id: "nvidia-geforce-rtx-5060-ti",
    name: "NVIDIA GeForce RTX 5060 Ti",
    brand: "NVIDIA",
    subcategory: "PC Hardware",
    sectionId: "nvidia-hardware",
    sectionTitle: "NVIDIA & PC Hardware",
    description: "High-efficiency 1080p and 1440p gaming graphics card with dedicated Tensor cores.",
    tags: ["nvidia", "rtx", "5060ti", "gpu", "hardware"],
  },
  {
    id: "nvidia-geforce-rtx-5060",
    name: "NVIDIA GeForce RTX 5060",
    brand: "NVIDIA",
    subcategory: "PC Hardware",
    sectionId: "nvidia-hardware",
    sectionTitle: "NVIDIA & PC Hardware",
    description: "Accessible ray tracing and DLSS 4 gaming card with low power draw and quiet acoustics.",
    tags: ["nvidia", "rtx", "5060", "gpu", "hardware"],
  },
  {
    id: "nvidia-rtx-6000-ada",
    name: "NVIDIA RTX 6000 Ada",
    brand: "NVIDIA",
    subcategory: "PC Hardware",
    sectionId: "nvidia-hardware",
    sectionTitle: "NVIDIA & PC Hardware",
    description: "Workstation monster with 48GB GDDR6 ECC memory built for generative AI and scientific visual computing.",
    tags: ["nvidia", "rtx6000", "ai", "workstation", "gpu", "llm"],
  },
  {
    id: "nvidia-jetson-orin",
    name: "NVIDIA Jetson Orin",
    brand: "NVIDIA",
    subcategory: "PC Hardware",
    sectionId: "nvidia-hardware",
    sectionTitle: "NVIDIA & PC Hardware",
    description: "Edge AI developer supercomputer capable of up to 275 TOPS for robotics and intelligent machines.",
    tags: ["nvidia", "jetson", "orin", "ai", "robotics", "embedded"],
  },
  {
    id: "amd-ryzen-9",
    name: "AMD Ryzen 9",
    brand: "AMD",
    subcategory: "PC Hardware",
    sectionId: "nvidia-hardware",
    sectionTitle: "NVIDIA & PC Hardware",
    description: "16-core 32-thread Zen 5 processor engineered for ultra-fast rendering, compiling, and gaming.",
    tags: ["amd", "ryzen", "cpu", "processor", "hardware"],
  },
  {
    id: "intel-core-ultra-9",
    name: "Intel Core Ultra 9",
    brand: "Intel",
    subcategory: "PC Hardware",
    sectionId: "nvidia-hardware",
    sectionTitle: "NVIDIA & PC Hardware",
    description: "Arrow Lake desktop processor with dedicated NPU for on-device AI and extreme single-core clocks.",
    tags: ["intel", "cpu", "ultra9", "processor", "hardware"],
  },
  {
    id: "amd-radeon-rx-9070-xt",
    name: "AMD Radeon RX 9070 XT",
    brand: "AMD",
    subcategory: "PC Hardware",
    sectionId: "nvidia-hardware",
    sectionTitle: "NVIDIA & PC Hardware",
    description: "RDNA 4 graphics card with large VRAM buffer and FSR 4 frame generation.",
    tags: ["amd", "radeon", "gpu", "graphics", "gaming"],
  },
  {
    id: "samsung-nvme-ssd",
    name: "Samsung NVMe SSD",
    brand: "Samsung",
    subcategory: "PC Hardware",
    sectionId: "nvidia-hardware",
    sectionTitle: "NVIDIA & PC Hardware",
    description: "990 PRO PCIe 4.0/5.0 NVMe M.2 internal SSD with read speeds up to 7450 MB/s.",
    tags: ["samsung", "nvme", "ssd", "storage", "pcie"],
  },
  {
    id: "wd-black-nvme-ssd",
    name: "WD Black NVMe SSD",
    brand: "Western Digital",
    subcategory: "PC Hardware",
    sectionId: "nvidia-hardware",
    sectionTitle: "NVIDIA & PC Hardware",
    description: "SN850X gaming NVMe internal SSD built for instantaneous game load times and DirectStorage.",
    tags: ["wd", "wdblack", "nvme", "ssd", "gaming"],
  },
  {
    id: "crucial-pro-ssd",
    name: "Crucial Pro SSD",
    brand: "Crucial",
    subcategory: "PC Hardware",
    sectionId: "nvidia-hardware",
    sectionTitle: "NVIDIA & PC Hardware",
    description: "High-end Gen5 internal SSD delivering mind-boggling transfer speeds up to 12,400 MB/s.",
    tags: ["crucial", "ssd", "gen5", "nvme", "storage"],
  },
  {
    id: "corsair-vengeance-ram",
    name: "Corsair Vengeance RAM",
    brand: "Corsair",
    subcategory: "PC Hardware",
    sectionId: "nvidia-hardware",
    sectionTitle: "NVIDIA & PC Hardware",
    description: "High-performance DDR5 desktop memory module kit optimized for Intel XMP and AMD EXPO.",
    tags: ["corsair", "ram", "ddr5", "memory", "hardware"],
  },
  {
    id: "gskill-trident-z-ram",
    name: "G.Skill Trident Z RAM",
    brand: "G.Skill",
    subcategory: "PC Hardware",
    sectionId: "nvidia-hardware",
    sectionTitle: "NVIDIA & PC Hardware",
    description: "Flagship RGB DDR5 memory designed for extreme overclocking and dazzling desk aesthetics.",
    tags: ["gskill", "ram", "ddr5", "rgb", "overclocking"],
  },

  // === Section 7: Cameras & Photography ===
  {
    id: "sony-alpha-a7-iv",
    name: "Sony Alpha a7 IV",
    brand: "Sony",
    subcategory: "Cameras",
    sectionId: "cameras-photography",
    sectionTitle: "Cameras & Photography",
    description: "33MP full-frame Exmor R sensor, 4K60p video, and real-time eye autofocus for creators.",
    tags: ["sony", "a7iv", "camera", "mirrorless", "fullframe"],
  },
  {
    id: "sony-alpha-a7-v",
    name: "Sony Alpha a7 V",
    brand: "Sony",
    subcategory: "Cameras",
    sectionId: "cameras-photography",
    sectionTitle: "Cameras & Photography",
    description: "Next-generation full-frame hybrid camera with dedicated AI subject tracking processor.",
    tags: ["sony", "a7v", "camera", "mirrorless", "photography"],
  },
  {
    id: "sony-alpha-a7r-v",
    name: "Sony Alpha a7R V",
    brand: "Sony",
    subcategory: "Cameras",
    sectionId: "cameras-photography",
    sectionTitle: "Cameras & Photography",
    description: "61MP ultra-high resolution camera with AI deep learning autofocus and 8-stop image stabilization.",
    tags: ["sony", "a7rv", "camera", "high-res", "photography"],
  },
  {
    id: "sony-alpha-a6700",
    name: "Sony Alpha a6700",
    brand: "Sony",
    subcategory: "Cameras",
    sectionId: "cameras-photography",
    sectionTitle: "Cameras & Photography",
    description: "Compact APS-C creator powerhouse with 4K120p, AI framing, and cinematic S-Cinetone color profile.",
    tags: ["sony", "a6700", "camera", "apsc", "video", "creator"],
  },
  {
    id: "canon-eos-r6-mark-ii",
    name: "Canon EOS R6 Mark II",
    brand: "Canon",
    subcategory: "Cameras",
    sectionId: "cameras-photography",
    sectionTitle: "Cameras & Photography",
    description: "40 fps electronic burst shooting, 6K oversampled 4K60p, and Dual Pixel CMOS AF II.",
    tags: ["canon", "eos", "r6markii", "camera", "fullframe"],
  },
  {
    id: "canon-eos-r5",
    name: "Canon EOS R5",
    brand: "Canon",
    subcategory: "Cameras",
    sectionId: "cameras-photography",
    sectionTitle: "Cameras & Photography",
    description: "45MP full-frame sensor capable of 8K RAW video capture and 100% frame autofocus coverage.",
    tags: ["canon", "r5", "camera", "8k", "cinema", "photography"],
  },
  {
    id: "nikon-z6-iii",
    name: "Nikon Z6 III",
    brand: "Nikon",
    subcategory: "Cameras",
    sectionId: "cameras-photography",
    sectionTitle: "Cameras & Photography",
    description: "Partially-stacked CMOS sensor with 6K N-RAW internal recording and bright 4000-nit EVF.",
    tags: ["nikon", "z6iii", "camera", "raw", "video"],
  },
  {
    id: "fujifilm-x-t5",
    name: "Fujifilm X-T5",
    brand: "Fujifilm",
    subcategory: "Cameras",
    sectionId: "cameras-photography",
    sectionTitle: "Cameras & Photography",
    description: "40MP X-Trans sensor, classic mechanical dials, and iconic analog Film Simulations.",
    tags: ["fujifilm", "xt5", "camera", "film-simulation", "photography"],
  },
  {
    id: "fujifilm-x100vi",
    name: "Fujifilm X100VI",
    brand: "Fujifilm",
    subcategory: "Cameras",
    sectionId: "cameras-photography",
    sectionTitle: "Cameras & Photography",
    description: "The viral fixed-lens compact rangefinder camera with 40MP sensor and in-body stabilization.",
    tags: ["fujifilm", "x100vi", "compact", "camera", "street-photography"],
  },
  {
    id: "leica-q3",
    name: "Leica Q3",
    brand: "Leica",
    subcategory: "Cameras",
    sectionId: "cameras-photography",
    sectionTitle: "Cameras & Photography",
    description: "Summilux 28mm f/1.7 ASPH lens, 60MP full-frame sensor, and timeless German craftsmanship.",
    tags: ["leica", "q3", "luxury", "camera", "fullframe"],
  },
  {
    id: "gopro-hero",
    name: "GoPro HERO",
    brand: "GoPro",
    subcategory: "Action Cameras",
    sectionId: "cameras-photography",
    sectionTitle: "Cameras & Photography",
    description: "Rugged waterproof 5.3K action camera with HyperSmooth 6.0 stabilization and horizon lock.",
    tags: ["gopro", "hero", "action-cam", "waterproof", "adventure"],
  },
  {
    id: "dji-osmo-pocket",
    name: "DJI Osmo Pocket",
    brand: "DJI",
    subcategory: "Cameras",
    sectionId: "cameras-photography",
    sectionTitle: "Cameras & Photography",
    description: "Pocket-sized 1-inch CMOS sensor gimbal camera with rotating 2-inch OLED touchscreen.",
    tags: ["dji", "osmo", "pocket", "vlog", "camera", "gimbal"],
  },
  {
    id: "dji-action",
    name: "DJI Action",
    brand: "DJI",
    subcategory: "Action Cameras",
    sectionId: "cameras-photography",
    sectionTitle: "Cameras & Photography",
    description: "Magnetic quick-release 4K120 action camera with extreme temperature battery tolerance.",
    tags: ["dji", "action", "camera", "adventure", "sports"],
  },
  {
    id: "dji-mini",
    name: "DJI Mini",
    brand: "DJI",
    subcategory: "Drones",
    sectionId: "cameras-photography",
    sectionTitle: "Cameras & Photography",
    description: "Under-249g ultralight foldable drone with 4K HDR True Vertical Shooting for social reels.",
    tags: ["dji", "mini", "drone", "aerial", "4k", "reels"],
  },
  {
    id: "insta360-x-series",
    name: "Insta360 X Series",
    brand: "Insta360",
    subcategory: "Action Cameras",
    sectionId: "cameras-photography",
    sectionTitle: "Cameras & Photography",
    description: "8K 360-degree action camera with Invisible Selfie Stick effect and AI reframing tools.",
    tags: ["insta360", "360cam", "action", "vr", "video"],
  },

  // === Section 8: Creator & Streaming ===
  {
    id: "shure-sm7b",
    name: "Shure SM7B",
    brand: "Shure",
    subcategory: "Microphones",
    sectionId: "creator-streaming",
    sectionTitle: "Creator & Streaming",
    description: "The iconic studio broadcast vocal microphone used by Joe Rogan, top artists, and creators.",
    tags: ["shure", "sm7b", "mic", "podcast", "broadcast", "studio"],
  },
  {
    id: "shure-mv7",
    name: "Shure MV7",
    brand: "Shure",
    subcategory: "Microphones",
    sectionId: "creator-streaming",
    sectionTitle: "Creator & Streaming",
    description: "Hybrid USB/XLR dynamic microphone with Voice Isolation Technology and auto-level mode.",
    tags: ["shure", "mv7", "usb-mic", "streaming", "podcast"],
  },
  {
    id: "rode-podmic",
    name: "Rode PodMic",
    brand: "Rode",
    subcategory: "Microphones",
    sectionId: "creator-streaming",
    sectionTitle: "Creator & Streaming",
    description: "Broadcast-grade dynamic microphone optimized for podcasting with integrated internal pop filter.",
    tags: ["rode", "podmic", "microphone", "podcast"],
  },
  {
    id: "rode-nt1",
    name: "Rode NT1",
    brand: "Rode",
    subcategory: "Microphones",
    sectionId: "creator-streaming",
    sectionTitle: "Creator & Streaming",
    description: "Ultra-low noise large-diaphragm studio condenser microphone with 32-bit float digital recording.",
    tags: ["rode", "nt1", "condenser", "studio", "mic", "vocals"],
  },
  {
    id: "rode-wireless-pro",
    name: "Rode Wireless PRO",
    brand: "Rode",
    subcategory: "Wireless Audio",
    sectionId: "creator-streaming",
    sectionTitle: "Creator & Streaming",
    description: "Dual-channel wireless microphone system with 32-bit float on-board recording and timecode.",
    tags: ["rode", "wireless", "mic", "lavalier", "creator"],
  },
  {
    id: "dji-mic",
    name: "DJI Mic",
    brand: "DJI",
    subcategory: "Wireless Audio",
    sectionId: "creator-streaming",
    sectionTitle: "Creator & Streaming",
    description: "All-in-one wireless microphone system with compact charging case and 250m transmission range.",
    tags: ["dji", "mic", "wireless", "vlog", "creator"],
  },
  {
    id: "elgato-wave-3",
    name: "Elgato Wave:3",
    brand: "Elgato",
    subcategory: "Microphones",
    sectionId: "creator-streaming",
    sectionTitle: "Creator & Streaming",
    description: "Premium USB condenser mic with Clipguard anti-distortion and Wave Link digital mixing suite.",
    tags: ["elgato", "wave3", "mic", "streaming", "usb"],
  },
  {
    id: "elgato-wave-dx",
    name: "Elgato Wave DX",
    brand: "Elgato",
    subcategory: "Microphones",
    sectionId: "creator-streaming",
    sectionTitle: "Creator & Streaming",
    description: "Dynamic XLR vocal microphone tuned for speech clarity and background noise rejection.",
    tags: ["elgato", "wavedx", "xlr", "mic", "studio"],
  },
  {
    id: "focusrite-scarlett-2i2",
    name: "Focusrite Scarlett 2i2",
    brand: "Focusrite",
    subcategory: "Audio Interfaces",
    sectionId: "creator-streaming",
    sectionTitle: "Creator & Streaming",
    description: "The world's best-selling 2-in/2-out USB audio interface with Air Mode and 120dB dynamic range.",
    tags: ["focusrite", "scarlett", "audio-interface", "music", "podcast"],
  },
  {
    id: "focusrite-scarlett-4i4",
    name: "Focusrite Scarlett 4i4",
    brand: "Focusrite",
    subcategory: "Audio Interfaces",
    sectionId: "creator-streaming",
    sectionTitle: "Creator & Streaming",
    description: "Expanded 4-input studio audio interface with MIDI I/O and loopback routing for streams.",
    tags: ["focusrite", "4i4", "interface", "studio"],
  },
  {
    id: "universal-audio-volt",
    name: "Universal Audio Volt",
    brand: "Universal Audio",
    subcategory: "Audio Interfaces",
    sectionId: "creator-streaming",
    sectionTitle: "Creator & Streaming",
    description: "Studio USB interface with built-in vintage tube preamp emulation and 1176-style analog compressor.",
    tags: ["universalaudio", "volt", "interface", "compressor", "studio"],
  },
  {
    id: "elgato-key-light",
    name: "Elgato Key Light",
    brand: "Elgato",
    subcategory: "Studio Lighting",
    sectionId: "creator-streaming",
    sectionTitle: "Creator & Streaming",
    description: "Desk-clamped 2800-lumen Wi-Fi LED studio light panel with edge-lit diffusion.",
    tags: ["elgato", "keylight", "lighting", "streaming", "studio"],
  },
  {
    id: "elgato-facecam",
    name: "Elgato Facecam",
    brand: "Elgato",
    subcategory: "Webcams",
    sectionId: "creator-streaming",
    sectionTitle: "Creator & Streaming",
    description: "Full HD 60fps uncompressed studio webcam with prime lens and Camera Hub manual controls.",
    tags: ["elgato", "facecam", "webcam", "streaming", "zoom"],
  },
  {
    id: "logitech-mx-brio",
    name: "Logitech MX Brio",
    brand: "Logitech",
    subcategory: "Webcams",
    sectionId: "creator-streaming",
    sectionTitle: "Creator & Streaming",
    description: "Ultra HD 4K webcam with Sony sensor, Show Mode desk tilt, and dual beamforming microphones.",
    tags: ["logitech", "mxbrio", "webcam", "4k", "zoom"],
  },
  {
    id: "sony-zv-e10",
    name: "Sony ZV-E10",
    brand: "Sony",
    subcategory: "Vlog Cameras",
    sectionId: "creator-streaming",
    sectionTitle: "Creator & Streaming",
    description: "Interchangeable lens vlog camera with Product Showcase setting and background defocus switch.",
    tags: ["sony", "zve10", "vlog", "camera", "youtube"],
  },
  {
    id: "sony-zv-1-ii",
    name: "Sony ZV-1 II",
    brand: "Sony",
    subcategory: "Vlog Cameras",
    sectionId: "creator-streaming",
    sectionTitle: "Creator & Streaming",
    description: "All-in-one pocket vlog camera with ultra-wide 18-50mm zoom lens and directional 3-capsule mic.",
    tags: ["sony", "zv1", "vlog", "camera", "reels"],
  },
  {
    id: "canon-powershot-v10",
    name: "Canon PowerShot V10",
    brand: "Canon",
    subcategory: "Vlog Cameras",
    sectionId: "creator-streaming",
    sectionTitle: "Creator & Streaming",
    description: "Pocket-sized vertical vlogging camera with built-in multi-position stand and wide 19mm lens.",
    tags: ["canon", "v10", "vlog", "pocket-camera", "tiktok"],
  },

  // === Section 9: Storage & Backup ===
  {
    id: "samsung-t7-ssd",
    name: "Samsung T7 SSD",
    brand: "Samsung",
    subcategory: "Storage",
    sectionId: "storage-backup",
    sectionTitle: "Storage & Backup",
    description: "Sleek pocket-sized portable SSD with 1050 MB/s transfer speeds and shock resistance.",
    tags: ["samsung", "t7", "ssd", "portable", "storage"],
  },
  {
    id: "samsung-t9-ssd",
    name: "Samsung T9 SSD",
    brand: "Samsung",
    subcategory: "Storage",
    sectionId: "storage-backup",
    sectionTitle: "Storage & Backup",
    description: "Rugged high-speed USB 3.2 Gen 2x2 portable SSD delivering up to 2,000 MB/s performance.",
    tags: ["samsung", "t9", "ssd", "fast", "storage"],
  },
  {
    id: "sandisk-extreme-portable-ssd",
    name: "SanDisk Extreme Portable SSD",
    brand: "SanDisk",
    subcategory: "Storage",
    sectionId: "storage-backup",
    sectionTitle: "Storage & Backup",
    description: "IP65 water and dust resistant rugged portable SSD with handy carabiner loop for travel shoots.",
    tags: ["sandisk", "extreme", "ssd", "rugged", "travel"],
  },
  {
    id: "wd-my-passport",
    name: "WD My Passport",
    brand: "Western Digital",
    subcategory: "Storage",
    sectionId: "storage-backup",
    sectionTitle: "Storage & Backup",
    description: "High-capacity portable hard drive for continuous system backups and archiving archives.",
    tags: ["wd", "mypassport", "harddrive", "backup", "storage"],
  },
  {
    id: "wd-black-sn850x",
    name: "WD Black SN850X",
    brand: "Western Digital",
    subcategory: "Storage",
    sectionId: "storage-backup",
    sectionTitle: "Storage & Backup",
    description: "Internal PCIe Gen4 NVMe drive with heatsink option designed for PS5 and high-end gaming desktops.",
    tags: ["wd", "sn850x", "nvme", "ps5-ssd", "storage"],
  },
  {
    id: "crucial-t500",
    name: "Crucial T500",
    brand: "Crucial",
    subcategory: "Storage",
    sectionId: "storage-backup",
    sectionTitle: "Storage & Backup",
    description: "PCIe 4.0 NVMe SSD engineered with 232-layer TLC NAND for rapid game and app launching.",
    tags: ["crucial", "t500", "nvme", "ssd"],
  },
  {
    id: "synology-nas",
    name: "Synology NAS",
    brand: "Synology",
    subcategory: "Network Storage",
    sectionId: "storage-backup",
    sectionTitle: "Storage & Backup",
    description: "DiskStation multi-bay network attached storage for automated creator backups and private cloud.",
    tags: ["synology", "nas", "cloud", "backup", "storage", "server"],
  },
  {
    id: "qnap-nas",
    name: "QNAP NAS",
    brand: "QNAP",
    subcategory: "Network Storage",
    sectionId: "storage-backup",
    sectionTitle: "Storage & Backup",
    description: "High-speed 2.5GbE network attached storage with multi-media streaming and virtualization.",
    tags: ["qnap", "nas", "server", "backup"],
  },
  {
    id: "sandisk-extreme-pro-sd-card",
    name: "SanDisk Extreme Pro SD Card",
    brand: "SanDisk",
    subcategory: "Memory Cards",
    sectionId: "storage-backup",
    sectionTitle: "Storage & Backup",
    description: "UHS-II V90 SDXC memory card engineered for flawless 8K and high-bitrate video capture.",
    tags: ["sandisk", "sdcard", "v90", "camera-memory"],
  },
  {
    id: "samsung-pro-plus-microsd",
    name: "Samsung PRO Plus microSD",
    brand: "Samsung",
    subcategory: "Memory Cards",
    sectionId: "storage-backup",
    sectionTitle: "Storage & Backup",
    description: "Fast microSD card with adapter for Nintendo Switch, drones, action cameras, and smartphones.",
    tags: ["samsung", "microsd", "switch-memory", "drone-storage"],
  },

  // === Section 10: Keyboards, Mice & Desk Setup ===
  {
    id: "keychron-q-series",
    name: "Keychron Q Series",
    brand: "Keychron",
    subcategory: "Keyboards",
    sectionId: "desk-setup",
    sectionTitle: "Keyboards, Mice & Desk Setup",
    description: "Full CNC machined aluminum body custom mechanical keyboard with double-gasket design and QMK/VIA.",
    tags: ["keychron", "q-series", "keyboard", "mechanical", "custom"],
  },
  {
    id: "keychron-k-series",
    name: "Keychron K Series",
    brand: "Keychron",
    subcategory: "Keyboards",
    sectionId: "desk-setup",
    sectionTitle: "Keyboards, Mice & Desk Setup",
    description: "Wireless mechanical keyboard featuring Bluetooth multi-device switching and macOS layout keys.",
    tags: ["keychron", "k-series", "wireless", "keyboard", "mac"],
  },
  {
    id: "logitech-mx-mechanical",
    name: "Logitech MX Mechanical",
    brand: "Logitech",
    subcategory: "Keyboards",
    sectionId: "desk-setup",
    sectionTitle: "Keyboards, Mice & Desk Setup",
    description: "Low-profile tactile mechanical keyboard with smart illumination and multi-device Flow pairing.",
    tags: ["logitech", "mx", "keyboard", "mechanical", "productivity"],
  },
  {
    id: "logitech-mx-keys",
    name: "Logitech MX Keys",
    brand: "Logitech",
    subcategory: "Keyboards",
    sectionId: "desk-setup",
    sectionTitle: "Keyboards, Mice & Desk Setup",
    description: "Spherically dished keys designed for fingertips, solid build, and quiet productivity typing.",
    tags: ["logitech", "mxkeys", "keyboard", "wireless"],
  },
  {
    id: "logitech-mx-master-3s",
    name: "Logitech MX Master 3S",
    brand: "Logitech",
    subcategory: "Mice",
    sectionId: "desk-setup",
    sectionTitle: "Keyboards, Mice & Desk Setup",
    description: "The quintessential creator mouse with 8K DPI any-surface tracking and MagSpeed electromagnetic scroll wheel.",
    tags: ["logitech", "mxmaster", "mouse", "ergonomic", "productivity"],
  },
  {
    id: "logitech-g-pro-x-keyboard",
    name: "Logitech G Pro X Keyboard",
    brand: "Logitech",
    subcategory: "Keyboards",
    sectionId: "desk-setup",
    sectionTitle: "Keyboards, Mice & Desk Setup",
    description: "Compact tenkeyless gaming keyboard with swappable pro-grade mechanical switches and LIGHTSYNC.",
    tags: ["logitech", "gprox", "tkl", "keyboard", "gaming"],
  },
  {
    id: "razer-blackwidow",
    name: "Razer BlackWidow",
    brand: "Razer",
    subcategory: "Keyboards",
    sectionId: "desk-setup",
    sectionTitle: "Keyboards, Mice & Desk Setup",
    description: "Iconic mechanical gaming keyboard equipped with clicky Green switches and Razer Chroma RGB.",
    tags: ["razer", "blackwidow", "keyboard", "gaming", "rgb"],
  },
  {
    id: "razer-huntsman",
    name: "Razer Huntsman",
    brand: "Razer",
    subcategory: "Keyboards",
    sectionId: "desk-setup",
    sectionTitle: "Keyboards, Mice & Desk Setup",
    description: "Optical gaming keyboard delivering near-zero debounce delay and Gen-2 linear switches.",
    tags: ["razer", "huntsman", "optical", "keyboard", "gaming"],
  },
  {
    id: "steelseries-apex-pro",
    name: "SteelSeries Apex Pro",
    brand: "SteelSeries",
    subcategory: "Keyboards",
    sectionId: "desk-setup",
    sectionTitle: "Keyboards, Mice & Desk Setup",
    description: "OmniPoint 3.0 adjustable magnetic switches with Rapid Trigger functionality and OLED smart display.",
    tags: ["steelseries", "apexpro", "rapid-trigger", "keyboard"],
  },
  {
    id: "wooting-80he",
    name: "Wooting 80HE",
    brand: "Wooting",
    subcategory: "Keyboards",
    sectionId: "desk-setup",
    sectionTitle: "Keyboards, Mice & Desk Setup",
    description: "The competitive FPS king with 0.1mm adjustable actuation, true Rapid Trigger, and analog sensing.",
    tags: ["wooting", "80he", "hall-effect", "keyboard", "esports"],
  },
  {
    id: "apple-magic-keyboard",
    name: "Apple Magic Keyboard",
    brand: "Apple",
    subcategory: "Keyboards",
    sectionId: "desk-setup",
    sectionTitle: "Keyboards, Mice & Desk Setup",
    description: "Slim wireless keyboard with built-in Touch ID sensor for fast, secure logins and Apple Pay.",
    tags: ["apple", "magickeyboard", "touchid", "mac"],
  },
  {
    id: "apple-magic-mouse",
    name: "Apple Magic Mouse",
    brand: "Apple",
    subcategory: "Mice",
    sectionId: "desk-setup",
    sectionTitle: "Keyboards, Mice & Desk Setup",
    description: "Multi-Touch surface mouse supporting intuitive swipe gestures across macOS and iPadOS.",
    tags: ["apple", "magicmouse", "mouse", "mac"],
  },
  {
    id: "herman-miller-embody",
    name: "Herman Miller Embody",
    brand: "Herman Miller",
    subcategory: "Desk Setup",
    sectionId: "desk-setup",
    sectionTitle: "Keyboards, Mice & Desk Setup",
    description: "The holy grail of ergonomic seating with dynamic pixel matrix backing designed to reduce pressure.",
    tags: ["hermanmiller", "embody", "chair", "ergonomic", "desk-setup"],
  },
  {
    id: "herman-miller-aeron",
    name: "Herman Miller Aeron",
    brand: "Herman Miller",
    subcategory: "Desk Setup",
    sectionId: "desk-setup",
    sectionTitle: "Keyboards, Mice & Desk Setup",
    description: "The timeless benchmark in ergonomic task chairs with Pellicle breathable mesh suspension.",
    tags: ["hermanmiller", "aeron", "chair", "ergonomic", "classic"],
  },
  {
    id: "secretlab-titan-evo",
    name: "Secretlab Titan Evo",
    brand: "Secretlab",
    subcategory: "Desk Setup",
    sectionId: "desk-setup",
    sectionTitle: "Keyboards, Mice & Desk Setup",
    description: "Award-winning gaming and productivity chair with 4-way L-ADAPT lumbar support and magnetic memory foam pillow.",
    tags: ["secretlab", "titan", "chair", "gaming", "desk-setup"],
  },
  {
    id: "monitor-arm",
    name: "Monitor Arm",
    brand: "Ergotron",
    subcategory: "Desk Setup",
    sectionId: "desk-setup",
    sectionTitle: "Keyboards, Mice & Desk Setup",
    description: "Heavy-duty aluminum gas spring monitor arm for effortless height, swivel, and tilt repositioning.",
    tags: ["ergotron", "monitorarm", "desk-setup", "ergonomics"],
  },
  {
    id: "desk-mat",
    name: "Desk Mat",
    brand: "Grovemade",
    subcategory: "Desk Setup",
    sectionId: "desk-setup",
    sectionTitle: "Keyboards, Mice & Desk Setup",
    description: "Premium merino wool felt and matte leather desk pad to elevate workstation aesthetics.",
    tags: ["grovemade", "deskmat", "desk-setup", "leather", "wool"],
  },
  {
    id: "laptop-stand",
    name: "Laptop Stand",
    brand: "Rain Design",
    subcategory: "Desk Setup",
    sectionId: "desk-setup",
    sectionTitle: "Keyboards, Mice & Desk Setup",
    description: "Anodized aluminum laptop elevator stand for ergonomic eye-level posture and airflow.",
    tags: ["raindesign", "stand", "laptop", "desk-setup"],
  },

  // === Section 11: Networking & Smart Home ===
  {
    id: "ubiquiti-unifi-dream-machine",
    name: "Ubiquiti UniFi Dream Machine",
    brand: "Ubiquiti",
    subcategory: "Networking",
    sectionId: "networking-smarthome",
    sectionTitle: "Networking & Smart Home",
    description: "Enterprise-grade all-in-one gateway console with IDS/IPS threat management and gigabit routing.",
    tags: ["ubiquiti", "unifi", "router", "networking", "homelab"],
  },
  {
    id: "ubiquiti-unifi-access-point",
    name: "Ubiquiti UniFi Access Point",
    brand: "Ubiquiti",
    subcategory: "Networking",
    sectionId: "networking-smarthome",
    sectionTitle: "Networking & Smart Home",
    description: "High-density Wi-Fi 7 ceiling access point supporting gigabit wireless across dozens of devices.",
    tags: ["ubiquiti", "unifi", "wifi7", "access-point", "networking"],
  },
  {
    id: "tp-link-wi-fi-7-router",
    name: "TP-Link Wi-Fi 7 Router",
    brand: "TP-Link",
    subcategory: "Networking",
    sectionId: "networking-smarthome",
    sectionTitle: "Networking & Smart Home",
    description: "Tri-Band Archer Wi-Fi 7 router with 10Gbps ports and Multi-Link Operation for zero-lag streaming.",
    tags: ["tplink", "wifi7", "router", "networking"],
  },
  {
    id: "asus-wi-fi-7-router",
    name: "ASUS Wi-Fi 7 Router",
    brand: "ASUS",
    subcategory: "Networking",
    sectionId: "networking-smarthome",
    sectionTitle: "Networking & Smart Home",
    description: "ROG Rapture high-performance gaming router with mobile game boost and AiMesh network expansion.",
    tags: ["asus", "rog", "wifi7", "router", "gaming"],
  },
  {
    id: "google-nest-wifi-pro",
    name: "Google Nest WiFi Pro",
    brand: "Google",
    subcategory: "Networking",
    sectionId: "networking-smarthome",
    sectionTitle: "Networking & Smart Home",
    description: "Tri-band Wi-Fi 6E mesh system providing reliable whole-home coverage and Matter smart hub support.",
    tags: ["google", "nest", "wifi", "mesh", "networking"],
  },
  {
    id: "amazon-echo",
    name: "Amazon Echo",
    brand: "Amazon",
    subcategory: "Smart Home",
    sectionId: "networking-smarthome",
    sectionTitle: "Networking & Smart Home",
    description: "Spherical smart speaker with room-filling Dolby audio and Alexa smart assistant automation.",
    tags: ["amazon", "echo", "alexa", "smarthome", "speaker"],
  },
  {
    id: "google-nest-hub",
    name: "Google Nest Hub",
    brand: "Google",
    subcategory: "Smart Home",
    sectionId: "networking-smarthome",
    sectionTitle: "Networking & Smart Home",
    description: "Smart display with Google Assistant, sleep sensing radar, and central smart home dashboard.",
    tags: ["google", "nesthub", "smarthome", "display"],
  },
  {
    id: "apple-homepod",
    name: "Apple HomePod",
    brand: "Apple",
    subcategory: "Smart Home",
    sectionId: "networking-smarthome",
    sectionTitle: "Networking & Smart Home",
    description: "High-excursion woofer smart speaker with spatial audio room sensing and Siri HomeKit control.",
    tags: ["apple", "homepod", "speaker", "homekit", "spatial"],
  },
  {
    id: "philips-hue-starter-kit",
    name: "Philips Hue Starter Kit",
    brand: "Philips",
    subcategory: "Smart Home",
    sectionId: "networking-smarthome",
    sectionTitle: "Networking & Smart Home",
    description: "Smart color ambiance bulbs and Zigbee Hue Bridge for customizable studio and room lighting scenes.",
    tags: ["philips", "hue", "smartlights", "lighting", "smarthome"],
  },
  {
    id: "nanoleaf-panels",
    name: "Nanoleaf Panels",
    brand: "Nanoleaf",
    subcategory: "Smart Home",
    sectionId: "networking-smarthome",
    sectionTitle: "Networking & Smart Home",
    description: "Modular RGB smart wall light panels with Rhythm music visualizer and screen mirror.",
    tags: ["nanoleaf", "rgb", "wall-lights", "decor", "gaming-setup"],
  },
  {
    id: "smart-led-light-strip",
    name: "Smart LED Light Strip",
    brand: "Govee",
    subcategory: "Smart Home",
    sectionId: "networking-smarthome",
    sectionTitle: "Networking & Smart Home",
    description: "RGBIC addressable gradient LED light strip for immersive desk bias lighting and studio backdrops.",
    tags: ["govee", "led", "lightstrip", "rgb", "desk-setup"],
  },

  // === Section 12: Accessories & Power ===
  {
    id: "anker-power-bank",
    name: "Anker Power Bank",
    brand: "Anker",
    subcategory: "Power",
    sectionId: "accessories-power",
    sectionTitle: "Accessories & Power",
    description: "High-capacity 24,000mAh portable charger with smart digital display and PowerIQ 3.0.",
    tags: ["anker", "powerbank", "battery", "charging"],
  },
  {
    id: "anker-prime-power-bank",
    name: "Anker Prime Power Bank",
    brand: "Anker",
    subcategory: "Power",
    sectionId: "accessories-power",
    sectionTitle: "Accessories & Power",
    description: "250W multi-port high-output power bank capable of fast-charging two MacBooks simultaneously.",
    tags: ["anker", "prime", "powerbank", "fastcharge", "250w"],
  },
  {
    id: "magsafe-battery-pack",
    name: "MagSafe Battery Pack",
    brand: "Apple",
    subcategory: "Power",
    sectionId: "accessories-power",
    sectionTitle: "Accessories & Power",
    description: "Snaps on magnetically to the back of iPhone for wireless power on the move.",
    tags: ["apple", "magsafe", "battery", "iphone"],
  },
  {
    id: "anker-gan-charger",
    name: "Anker GaN Charger",
    brand: "Anker",
    subcategory: "Power",
    sectionId: "accessories-power",
    sectionTitle: "Accessories & Power",
    description: "Compact 100W GaN wall charger with foldable prongs and temperature monitoring.",
    tags: ["anker", "gan", "charger", "fastcharging"],
  },
  {
    id: "apple-35w-dual-usb-c-charger",
    name: "Apple 35W Dual USB-C Charger",
    brand: "Apple",
    subcategory: "Power",
    sectionId: "accessories-power",
    sectionTitle: "Accessories & Power",
    description: "Compact power adapter with dual USB-C ports to charge iPhone and Apple Watch together.",
    tags: ["apple", "charger", "usbc", "dualport"],
  },
  {
    id: "apple-70w-usb-c-charger",
    name: "Apple 70W USB-C Charger",
    brand: "Apple",
    subcategory: "Power",
    sectionId: "accessories-power",
    sectionTitle: "Accessories & Power",
    description: "Fast-charging power adapter for 13-inch and 15-inch MacBook Air and MacBook Pro.",
    tags: ["apple", "70w", "charger", "macbook"],
  },
  {
    id: "ugreen-gan-charger",
    name: "UGREEN GaN Charger",
    brand: "UGREEN",
    subcategory: "Power",
    sectionId: "accessories-power",
    sectionTitle: "Accessories & Power",
    description: "Nexode 100W 4-port desktop GaN charging station powering all your workstation devices.",
    tags: ["ugreen", "gan", "charger", "nexode", "power"],
  },
  {
    id: "usb-c-hub",
    name: "USB-C Hub",
    brand: "CalDigit",
    subcategory: "Accessories",
    sectionId: "accessories-power",
    sectionTitle: "Accessories & Power",
    description: "Aluminum multi-port adapter expanding USB-C to 4K HDMI, Gigabit Ethernet, SD card, and USB-A.",
    tags: ["caldigit", "usbc", "hub", "dongle", "adapter"],
  },
  {
    id: "thunderbolt-dock",
    name: "Thunderbolt Dock",
    brand: "CalDigit",
    subcategory: "Accessories",
    sectionId: "accessories-power",
    sectionTitle: "Accessories & Power",
    description: "TS4 18-port Thunderbolt 4 desktop dock with 98W host charging and dual 6K display support.",
    tags: ["caldigit", "ts4", "thunderbolt", "dock", "workstation"],
  },
  {
    id: "magsafe-charger",
    name: "MagSafe Charger",
    brand: "Apple",
    subcategory: "Power",
    sectionId: "accessories-power",
    sectionTitle: "Accessories & Power",
    description: "Aligned magnetic wireless charging puck delivering up to 25W fast wireless power.",
    tags: ["apple", "magsafe", "wireless-charging"],
  },
  {
    id: "apple-watch-charger",
    name: "Apple Watch Charger",
    brand: "Apple",
    subcategory: "Power",
    sectionId: "accessories-power",
    sectionTitle: "Accessories & Power",
    description: "Fast magnetic charging cable with woven USB-C cable for quick top-ups.",
    tags: ["apple", "applewatch", "charger"],
  },
  {
    id: "usb-c-cable",
    name: "USB-C Cable",
    brand: "Anker",
    subcategory: "Accessories",
    sectionId: "accessories-power",
    sectionTitle: "Accessories & Power",
    description: "240W bio-braided heavy duty USB-C to USB-C charging and 40Gbps data cable.",
    tags: ["anker", "cable", "usbc", "braided"],
  },
  {
    id: "hdmi-21-cable",
    name: "HDMI 2.1 Cable",
    brand: "Belkin",
    subcategory: "Accessories",
    sectionId: "accessories-power",
    sectionTitle: "Accessories & Power",
    description: "Ultra High Speed 48Gbps HDMI 2.1 cable supporting 4K 120Hz, 8K 60Hz, and Dolby Vision.",
    tags: ["belkin", "hdmi", "hdmi21", "cable", "4k120"],
  },
  {
    id: "laptop-cooling-pad",
    name: "Laptop Cooling Pad",
    brand: "IETS",
    subcategory: "Accessories",
    sectionId: "accessories-power",
    sectionTitle: "Accessories & Power",
    description: "High-pressure sealed vacuum turbofan cooling pad drastically lowering laptop thermal throttling.",
    tags: ["iets", "coolingpad", "laptop", "gaming"],
  },
  {
    id: "cable-management-kit",
    name: "Cable Management Kit",
    brand: "D-Line",
    subcategory: "Accessories",
    sectionId: "accessories-power",
    sectionTitle: "Accessories & Power",
    description: "Under-desk cable raceways, magnetic ties, and cable clips for a clean wire-free setup aesthetic.",
    tags: ["cablemanagement", "desk-setup", "clean", "organizer"],
  },

  // === Section 13: Wearables & Future Tech ===
  {
    id: "apple-watch",
    name: "Apple Watch",
    brand: "Apple",
    subcategory: "Wearables",
    sectionId: "wearables-future-tech",
    sectionTitle: "Wearables & Future Tech",
    description: "Series 10 with wide-angle OLED display, sleep apnea detection, and all-day health tracking.",
    tags: ["apple", "applewatch", "smartwatch", "fitness", "health"],
  },
  {
    id: "apple-watch-ultra",
    name: "Apple Watch Ultra",
    brand: "Apple",
    subcategory: "Wearables",
    sectionId: "wearables-future-tech",
    sectionTitle: "Wearables & Future Tech",
    description: "Rugged 49mm titanium smartwatch with precision dual-frequency GPS, siren, and 3000 nits display.",
    tags: ["apple", "watch-ultra", "titanium", "fitness", "adventure"],
  },
  {
    id: "samsung-galaxy-watch",
    name: "Samsung Galaxy Watch",
    brand: "Samsung",
    subcategory: "Wearables",
    sectionId: "wearables-future-tech",
    sectionTitle: "Wearables & Future Tech",
    description: "BioActive sensor smartwatch with body composition BIA analysis and Wear OS ecosystem.",
    tags: ["samsung", "galaxywatch", "smartwatch", "health"],
  },
  {
    id: "google-pixel-watch",
    name: "Google Pixel Watch",
    brand: "Google",
    subcategory: "Wearables",
    sectionId: "wearables-future-tech",
    sectionTitle: "Wearables & Future Tech",
    description: "Circular dome glass smartwatch with deepest Fitbit fitness integration and Google AI.",
    tags: ["google", "pixelwatch", "smartwatch", "fitbit"],
  },
  {
    id: "garmin-fenix",
    name: "Garmin Fenix",
    brand: "Garmin",
    subcategory: "Wearables",
    sectionId: "wearables-future-tech",
    sectionTitle: "Wearables & Future Tech",
    description: "Multisport solar GPS smartwatch with weeks of battery life and topographic mapping.",
    tags: ["garmin", "fenix", "multisport", "gps", "endurance"],
  },
  {
    id: "oura-ring",
    name: "Oura Ring",
    brand: "Oura",
    subcategory: "Wearables",
    sectionId: "wearables-future-tech",
    sectionTitle: "Wearables & Future Tech",
    description: "Ultralight titanium smart ring tracking sleep stages, heart rate variability, and readiness scores.",
    tags: ["oura", "ring", "health", "sleep", "biohacking"],
  },
  {
    id: "ray-ban-meta-smart-glasses",
    name: "Ray-Ban Meta Smart Glasses",
    brand: "Ray-Ban",
    subcategory: "Wearables",
    sectionId: "wearables-future-tech",
    sectionTitle: "Wearables & Future Tech",
    description: "Iconic Wayfarer frames with ultra-wide 12MP POV camera, open-ear audio, and Meta AI assistant.",
    tags: ["rayban", "meta", "smartglasses", "ai", "camera", "pov"],
  },
  {
    id: "dji-goggles",
    name: "DJI Goggles",
    brand: "DJI",
    subcategory: "Wearables",
    sectionId: "wearables-future-tech",
    sectionTitle: "Wearables & Future Tech",
    description: "Micro-OLED FPV drone goggles providing ultra-low latency high-definition first-person flight views.",
    tags: ["dji", "goggles", "fpv", "drone", "flight"],
  },

  // === Section 14: Smart & Lifestyle Electronics ===
  {
    id: "dyson-airwrap",
    name: "Dyson Airwrap",
    brand: "Dyson",
    subcategory: "Lifestyle",
    sectionId: "smart-lifestyle",
    sectionTitle: "Smart & Lifestyle Electronics",
    description: "Multi-styler using the Coanda aerodynamic effect to curl, shape, and hide flyaways with zero extreme heat.",
    tags: ["dyson", "airwrap", "haircare", "beauty", "luxury"],
  },
  {
    id: "dyson-supersonic",
    name: "Dyson Supersonic",
    brand: "Dyson",
    subcategory: "Lifestyle",
    sectionId: "smart-lifestyle",
    sectionTitle: "Smart & Lifestyle Electronics",
    description: "Intelligent heat control hair dryer powered by the V9 digital motor for fast drying and hair shine.",
    tags: ["dyson", "supersonic", "hairdryer", "lifestyle"],
  },
  {
    id: "dyson-air-purifier",
    name: "Dyson Air Purifier",
    brand: "Dyson",
    subcategory: "Smart Home",
    sectionId: "smart-lifestyle",
    sectionTitle: "Smart & Lifestyle Electronics",
    description: "Purifier Hot+Cool with HEPA H13 filtration capturing 99.95% of ultrafine particles and formaldehyde.",
    tags: ["dyson", "purifier", "cleanair", "home", "smart"],
  },
  {
    id: "philips-air-fryer",
    name: "Philips Air Fryer",
    brand: "Philips",
    subcategory: "Lifestyle",
    sectionId: "smart-lifestyle",
    sectionTitle: "Smart & Lifestyle Electronics",
    description: "Rapid Air technology digital air fryer for crispy healthy cooking with 90% less fat.",
    tags: ["philips", "airfryer", "kitchen", "cooking", "lifestyle"],
  },
  {
    id: "philips-sonicare",
    name: "Philips Sonicare",
    brand: "Philips",
    subcategory: "Lifestyle",
    sectionId: "smart-lifestyle",
    sectionTitle: "Smart & Lifestyle Electronics",
    description: "DiamondClean smart sonic electric toothbrush with personalized app feedback and charging glass.",
    tags: ["philips", "sonicare", "toothbrush", "dental", "lifestyle"],
  },
  {
    id: "oral-b-io",
    name: "Oral-B iO",
    brand: "Oral-B",
    subcategory: "Lifestyle",
    sectionId: "smart-lifestyle",
    sectionTitle: "Smart & Lifestyle Electronics",
    description: "Revolutionary magnetic iO technology with micro-vibrating bristles and interactive OLED display.",
    tags: ["oralb", "electric-toothbrush", "dental", "smart"],
  },
  {
    id: "kindle",
    name: "Kindle",
    brand: "Amazon",
    subcategory: "Lifestyle",
    sectionId: "smart-lifestyle",
    sectionTitle: "Smart & Lifestyle Electronics",
    description: "Paperwhite glare-free 300 ppi display with adjustable warm light and weeks of battery life.",
    tags: ["amazon", "kindle", "paperwhite", "books", "reading", "ereader"],
  },
  {
    id: "kobo-libra",
    name: "Kobo Libra",
    brand: "Kobo",
    subcategory: "Lifestyle",
    sectionId: "smart-lifestyle",
    sectionTitle: "Smart & Lifestyle Electronics",
    description: "Color E-Ink waterproof e-reader with physical page-turn buttons and stylus note-taking.",
    tags: ["kobo", "libra", "ereader", "color-eink", "books"],
  },
  {
    id: "digital-photo-frame",
    name: "Digital Photo Frame",
    brand: "Aura",
    subcategory: "Lifestyle",
    sectionId: "smart-lifestyle",
    sectionTitle: "Smart & Lifestyle Electronics",
    description: "Wi-Fi connected HD smart photo frame allowing friends and family to instantly share pictures.",
    tags: ["aura", "photoframe", "digital", "home", "display"],
  },
  {
    id: "portable-projector",
    name: "Portable Projector",
    brand: "Anker",
    subcategory: "Smart Electronics",
    sectionId: "smart-lifestyle",
    sectionTitle: "Smart & Lifestyle Electronics",
    description: "Nebula Capsule soda-can sized smart projector with built-in battery and 360-degree speaker.",
    tags: ["anker", "nebula", "projector", "portable", "outdoors"],
  },
  {
    id: "robot-vacuum",
    name: "Robot Vacuum",
    brand: "Roborock",
    subcategory: "Smart Home",
    sectionId: "smart-lifestyle",
    sectionTitle: "Smart & Lifestyle Electronics",
    description: "LiDAR mapping robotic vacuum and sonic mop with all-in-one auto-emptying and washing dock.",
    tags: ["roborock", "vacuum", "robot", "smarthome", "clean"],
  },
  {
    id: "smart-coffee-machine",
    name: "Smart Coffee Machine",
    brand: "Breville",
    subcategory: "Lifestyle",
    sectionId: "smart-lifestyle",
    sectionTitle: "Smart & Lifestyle Electronics",
    description: "Barista Touch automated espresso machine with precision PID temperature control and microfoam wand.",
    tags: ["breville", "coffee", "espresso", "barista", "kitchen"],
  },
];

/**
 * Return all Electronics products with resolved image URLs and display orders.
 */
export function getFullElectronicsCatalog(): ElectronicsProduct[] {
  return RAW_ELECTRONICS_PRODUCTS.map((p, idx) => ({
    id: p.id,
    name: p.name,
    brand: p.brand,
    category: "Electronics",
    subcategory: p.subcategory,
    sectionId: p.sectionId,
    sectionTitle: p.sectionTitle,
    imageUrl: getElectronicsProductImage(p.id),
    description: p.description,
    tags: p.tags,
    featured: Boolean(p.featured),
    trending: Boolean(p.trending),
    displayOrder: idx,
  }));
}

/**
 * Get distinct subcategories for navigation
 */
export function getElectronicsSubcategories(): Array<{ name: string; count: number }> {
  const map = new Map<string, number>();
  for (const item of RAW_ELECTRONICS_PRODUCTS) {
    map.set(item.subcategory, (map.get(item.subcategory) || 0) + 1);
  }
  return Array.from(map.entries()).map(([name, count]) => ({ name, count }));
}
