/**
 * Comprehensive Fashion Catalog Data Definition for Plugd
 * 
 * Expansive, creator-ready fashion catalog covering Streetwear, Sneakers,
 * Men's, Women's, Unisex, Ethnic Wear, Watches, Bags, Jewellery, Sportswear,
 * Luxury, and Accessories for the Indian market.
 */

import { getFashionProductImage } from "./product-images";

export interface FashionProduct {
  id: string;
  name: string;
  brand: string;
  category: "Fashion";
  subcategory: string;
  sectionId: string;
  sectionTitle: string;
  imageUrl: string;
  description: string;
  tags: string[];
  badge?: "HOT" | "TRENDING" | "NEW" | "POPULAR" | "PREMIUM" | "BESTSELLER";
  featured?: boolean;
  trending?: boolean;
  displayOrder: number;
}

export interface FashionSection {
  id: string;
  title: string;
  subtitle: string;
  badge?: string;
  displayOrder: number;
  productIds: string[];
}

export const FASHION_SECTIONS: FashionSection[] = [
  {
    id: "trending-fashion",
    title: "Trending Fashion",
    subtitle: "Most desired sneakers, oversized street layers, iconic timepieces, and creator wardrobe staples",
    badge: "🔥 Hot",
    displayOrder: 1,
    productIds: [
      "nike-air-jordan-1-retro-high",
      "adidas-samba-og",
      "heavyweight-oversized-graphic-tee",
      "casio-vintage-digital-a168",
      "new-balance-550",
      "boxy-drop-shoulder-hoodie",
      "relaxed-fit-utilitarian-cargo-pants",
      "waterproof-urban-laptop-backpack",
      "vintage-retro-tinted-sunglasses",
      "asics-gel-kayano-14",
      "handloom-banarasi-silk-saree",
      "tissot-prx-powermatic-80",
      "minimalist-leather-crossbody-sling",
      "satin-slip-midi-dress",
      "birkenstock-boston-clog",
    ],
  },
  {
    id: "sneaker-culture",
    title: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    subtitle: "Hype retros, skate icons, terrace classics, and everyday lifestyle runners",
    badge: "👟 Sneakers",
    displayOrder: 2,
    productIds: [
      "nike-air-jordan-1-retro-high",
      "air-jordan-1",
      "nike-dunk-low-retro",
      "adidas-samba-og",
      "adidas-gazelle-indoor",
      "adidas-originals-campus-00s",
      "adidas-originals",
      "new-balance-550",
      "new-balance-9060",
      "new-balance-1906r",
      "asics-gel-kayano-14",
      "asics-gel-nyc",
      "puma-palermo-leather",
      "puma-suede-classic",
      "converse-chuck-70-vintage",
      "vans-old-skool-classic",
      "on-cloudmonster-2",
      "sneakers",
    ],
  },
  {
    id: "streetwear-creator-fits",
    title: "Streetwear & Creator Fits",
    subtitle: "Boxy silhouettes, drop shoulders, utilitarian details, and visual statement pieces for content creators",
    badge: "🛹 Streetwear",
    displayOrder: 3,
    productIds: [
      "heavyweight-oversized-graphic-tee",
      "boxy-drop-shoulder-hoodie",
      "oversized-hoodie",
      "varsity-bomber-jacket",
      "statement-jacket",
      "relaxed-fit-utilitarian-cargo-pants",
      "baggy-90s-skater-jeans",
      "vintage-washed-denim-jacket",
      "cuban-link-stainless-steel-chain",
      "unstructured-dad-cap",
      "minimalist-leather-crossbody-sling",
      "birkenstock-boston-clog",
    ],
  },
  {
    id: "mens-style-essentials",
    title: "Men's Style & Everyday Essentials",
    subtitle: "Refined polos, breathable linen shirts, tailored chinos, selvedge denim, and versatile loafers",
    badge: "👔 Men's Edit",
    displayOrder: 4,
    productIds: [
      "pure-linen-resort-shirt",
      "tailored-oxford-cotton-shirt",
      "pima-cotton-polo-shirt",
      "levis-501-original-straight-jeans",
      "pleated-tailored-smart-trousers",
      "slim-tapered-stretch-chinos",
      "suede-penny-loafers",
      "chelsea-leather-boots",
      "full-grain-leather-pin-buckle-belt",
      "seiko-5-sports-automatic-watch",
      "basic-heavyweight-t-shirt",
    ],
  },
  {
    id: "womens-contemporary-edit",
    title: "Women's Edit & Contemporary Silhouettes",
    subtitle: "Fluid midi dresses, tailored wide-leg trousers, structured blazers, and versatile capsule staples",
    badge: "✨ Women's Edit",
    displayOrder: 5,
    productIds: [
      "satin-slip-midi-dress",
      "fluid-linen-summer-maxi-dress",
      "oversized-structured-blazer",
      "ribbed-knit-seamless-crop-top",
      "wide-leg-high-waist-trousers",
      "floral-wrap-mini-dress",
      "cotton-poplin-oversized-shirt",
      "leather-structure-shoulder-handbag",
      "strappy-block-heels",
      "chunky-platform-loafers",
    ],
  },
  {
    id: "indian-ethnic-festive",
    title: "Indian & Festive Ethnic Wear",
    subtitle: "Handloom Banarasi sarees, embroidered kurtas, raw silk Nehru jackets, and handcrafted mojaris",
    badge: "🥻 Indian Festive",
    displayOrder: 6,
    productIds: [
      "handloom-banarasi-silk-saree",
      "chikankari-embroidered-cotton-kurta",
      "chanderi-silk-anarkali-suit-set",
      "raw-silk-festive-nehru-jacket",
      "designer-embroidered-lehenga-choli",
      "mens-silk-blend-kurta-pajama-set",
      "traditional-bandhgala-suit",
      "handcrafted-kolhapuri-mojaris",
    ],
  },
  {
    id: "timepieces-watches",
    title: "Timepieces & Iconic Watches",
    subtitle: "Retro digital classics, rugged G-Shocks, Swiss automatics, and smart wearable essentials",
    badge: "⌚ Watches",
    displayOrder: 7,
    productIds: [
      "casio-vintage-digital-a168",
      "casio-g-shock-ga-2100-casioak",
      "titan-edge-ceramic-slim-watch",
      "seiko-5-sports-automatic-watch",
      "tissot-prx-powermatic-80",
      "apple-watch-ultra-2",
      "fossil-grant-chronograph-leather-watch",
      "designer-watch",
    ],
  },
  {
    id: "bags-backpacks-carry",
    title: "Bags, Backpacks & Everyday Carry",
    subtitle: "Waterproof tech bags, commuter backpacks, heavy canvas totes, and leather crossbody slings",
    badge: "🎒 Bags & Carry",
    displayOrder: 8,
    productIds: [
      "waterproof-urban-laptop-backpack",
      "travel-backpack",
      "minimalist-leather-crossbody-sling",
      "heavy-canvas-work-tote-bag",
      "leather-structure-shoulder-handbag",
      "cordura-gym-weekend-duffle-bag",
      "slim-leather-rfid-cardholder-wallet",
    ],
  },
  {
    id: "activewear-sportswear",
    title: "Activewear & Sportswear",
    subtitle: "High-performance moisture-wicking tees, training joggers, marathon running shoes, and gym gear",
    badge: "🏃 Sportswear",
    displayOrder: 9,
    productIds: [
      "nike-dri-fit-training-t-shirt",
      "adidas-tiro-training-track-pants",
      "nike-air-max-plus",
      "nike-running-shoes",
      "adidas-ultraboost-light",
      "on-cloudmonster-2",
      "under-armour-heatgear-compression-top",
      "puma-drycell-running-shorts",
      "cordura-gym-weekend-duffle-bag",
    ],
  },
  {
    id: "premium-luxury-statements",
    title: "Premium & Luxury Statements",
    subtitle: "Heritage tailoring, premium leather goods, virgin wool blazers, and iconic designer silhouettes",
    badge: "👑 Luxury",
    displayOrder: 10,
    productIds: [
      "ralph-lauren-custom-fit-oxford",
      "tommy-hilfiger-yacht-bomber-jacket",
      "coach-leather-tabby-shoulder-bag",
      "hugo-boss-virgin-wool-blazer",
      "calvin-klein-minimalist-monogram-tee",
      "tissot-prx-powermatic-80",
      "traditional-bandhgala-suit",
    ],
  },
  {
    id: "footwear-beyond-sneakers",
    title: "Footwear Beyond Sneakers",
    subtitle: "Suede penny loafers, leather Chelsea boots, handcrafted mojaris, and elevated clogs",
    badge: "👞 Footwear",
    displayOrder: 11,
    productIds: [
      "suede-penny-loafers",
      "chelsea-leather-boots",
      "birkenstock-boston-clog",
      "crocs-classic-clog",
      "chunky-platform-loafers",
      "strappy-block-heels",
      "handcrafted-kolhapuri-mojaris",
    ],
  },
  {
    id: "jewellery-accessories",
    title: "Statement Jewellery & Accessories",
    subtitle: "Cuban link chains, signet rings, tinted sunglasses, baseball caps, and full-grain leather belts",
    badge: "💍 Accessories",
    displayOrder: 12,
    productIds: [
      "vintage-retro-tinted-sunglasses",
      "sunglasses",
      "cuban-link-stainless-steel-chain",
      "minimalist-silver-signet-ring",
      "unstructured-dad-cap",
      "full-grain-leather-pin-buckle-belt",
      "slim-leather-rfid-cardholder-wallet",
    ],
  },
  {
    id: "tops-hoodies-layers",
    title: "Casual Tops, Hoodies & Layers",
    subtitle: "Heavyweight tees, relaxed flannels, corduroy overshirts, and zip hoodies",
    badge: "👕 Tops & Layers",
    displayOrder: 13,
    productIds: [
      "heavyweight-oversized-graphic-tee",
      "boxy-drop-shoulder-hoodie",
      "oversized-hoodie",
      "flannel-plaid-overshirt",
      "corduroy-zip-overshirt",
      "crewneck-minimalist-sweatshirt",
      "knit-boxy-cardigan",
      "basic-heavyweight-t-shirt",
    ],
  },
  {
    id: "bottoms-cargos-denims",
    title: "Bottoms: Cargos, Denims & Relaxed Fits",
    subtitle: "Baggy 90s skater cuts, selvedge straight leg jeans, utilitarian cargos, and tailored pleats",
    badge: "👖 Bottoms",
    displayOrder: 14,
    productIds: [
      "relaxed-fit-utilitarian-cargo-pants",
      "levis-501-original-straight-jeans",
      "baggy-90s-skater-jeans",
      "pleated-tailored-smart-trousers",
      "wide-leg-high-waist-trousers",
      "slim-tapered-stretch-chinos",
      "everyday-cotton-drawstring-shorts",
    ],
  },
  {
    id: "budget-wardrobe-essentials",
    title: "Student & Budget Wardrobe Essentials",
    subtitle: "High-value foundational basics, everyday canvas kicks, durable backpacks, and classic tees",
    badge: "💰 Budget Picks",
    displayOrder: 15,
    productIds: [
      "basic-heavyweight-t-shirt",
      "converse-chuck-70-vintage",
      "vans-old-skool-classic",
      "everyday-cotton-drawstring-shorts",
      "casio-vintage-digital-a168",
      "heavy-canvas-work-tote-bag",
      "unstructured-dad-cap",
    ],
  },
  {
    id: "creator-aesthetic",
    title: "Creator Aesthetic (Signature Looks)",
    subtitle: "Curated statement pieces for creators building a distinctive on-camera and street persona",
    badge: "📸 Creator Style",
    displayOrder: 16,
    productIds: [
      "vintage-retro-tinted-sunglasses",
      "varsity-bomber-jacket",
      "statement-jacket",
      "boxy-drop-shoulder-hoodie",
      "adidas-samba-og",
      "nike-air-jordan-1-retro-high",
      "tissot-prx-powermatic-80",
      "minimalist-leather-crossbody-sling",
      "cuban-link-stainless-steel-chain",
    ],
  },
];

/** Full list of Fashion products */
export const RAW_FASHION_PRODUCTS: Array<{
  id: string;
  name: string;
  brand: string;
  subcategory: string;
  sectionId: string;
  sectionTitle: string;
  description: string;
  tags: string[];
  badge?: "HOT" | "TRENDING" | "NEW" | "POPULAR" | "PREMIUM" | "BESTSELLER";
  featured?: boolean;
  trending?: boolean;
}> = [
  // === Sneakers ===
  {
    id: "nike-air-jordan-1-retro-high",
    name: "Air Jordan 1 Retro High OG",
    brand: "Jordan",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "The timeless hardwood icon with premium leather upper, encapsulated Air-Sole cushioning, and signature Wings logo.",
    tags: ["nike", "jordan", "aj1", "sneakers", "streetwear", "high-top", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "air-jordan-1",
    name: "Air Jordan 1",
    brand: "Jordan",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "Classic high-top silhouette crafted with durable leather panels and heritage court traction.",
    tags: ["jordan", "sneakers", "lifestyle"],
  },
  {
    id: "nike-dunk-low-retro",
    name: "Nike Dunk Low Retro 'Panda'",
    brand: "Nike",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "Unmistakable monochromatic colorblocking with padded collar, foam midsole, and durable rubber outsole.",
    tags: ["nike", "dunk", "panda", "sneakers", "streetwear", "bestseller"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "nike-air-force-1-07",
    name: "Nike Air Force 1 '07",
    brand: "Nike",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "Crisp all-white leather upper with stitched overlays, perforations on the toe, and classic Nike Air cushioning.",
    tags: ["nike", "af1", "air-force", "sneakers", "white-sneakers", "essential"],
    badge: "BESTSELLER",
  },
  {
    id: "nike-air-max-plus",
    name: "Nike Air Max Plus TN",
    brand: "Nike",
    subcategory: "Sneakers",
    sectionId: "activewear-sportswear",
    sectionTitle: "Activewear & Sportswear",
    description: "Prominent arch inspired by a whale's tail with breathable gradient mesh and revolutionary Tuned Air units.",
    tags: ["nike", "air-max", "tn", "running", "sportswear"],
    badge: "TRENDING",
  },
  {
    id: "nike-running-shoes",
    name: "Nike Running Shoes",
    brand: "Nike",
    subcategory: "Footwear",
    sectionId: "activewear-sportswear",
    sectionTitle: "Activewear & Sportswear",
    description: "Responsive everyday performance running footwear engineered for breathability and energy return.",
    tags: ["nike", "running", "shoes", "sportswear"],
  },
  {
    id: "adidas-samba-og",
    name: "Adidas Samba OG",
    brand: "Adidas",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "The global terrace trendsetter featuring low-profile leather upper, suede T-toe overlay, and iconic gum rubber sole.",
    tags: ["adidas", "samba", "terrace", "sneakers", "streetwear", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "adidas-gazelle-indoor",
    name: "Adidas Gazelle Indoor",
    brand: "Adidas",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "Vintage indoor training shoe with rich suede construction, translucent gum wrap sole, and gold-foil Gazelle branding.",
    tags: ["adidas", "gazelle", "suede", "sneakers"],
    badge: "POPULAR",
  },
  {
    id: "adidas-originals-campus-00s",
    name: "Adidas Originals Campus 00s",
    brand: "Adidas",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "Chunky Y2K skate proportions with plush padded tongue, fat laces, and soft suede upper.",
    tags: ["adidas", "campus", "y2k", "skate", "sneakers"],
    badge: "TRENDING",
  },
  {
    id: "adidas-originals",
    name: "Adidas Originals",
    brand: "Adidas",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "Heritage sportswear kicks carrying the iconic 3-Stripes legacy for easy streetwear styling.",
    tags: ["adidas", "originals", "sneakers"],
  },
  {
    id: "adidas-ultraboost-light",
    name: "Adidas Ultraboost Light",
    brand: "Adidas",
    subcategory: "Sportswear",
    sectionId: "activewear-sportswear",
    sectionTitle: "Activewear & Sportswear",
    description: "30% lighter Light BOOST cushioning with Primeknit+ upper for supreme comfort on long days and runs.",
    tags: ["adidas", "ultraboost", "running", "comfort", "sportswear"],
  },
  {
    id: "new-balance-550",
    name: "New Balance 550",
    brand: "New Balance",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "Retro 1989 basketball low-top with clean streamlined leather construction and vintage aesthetic.",
    tags: ["new-balance", "nb550", "sneakers", "retro", "streetwear"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "new-balance-9060",
    name: "New Balance 9060",
    brand: "New Balance",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "Futuristic sculpted silhouette combining 990-series heritage with Y2K exaggerated ABZORB pods.",
    tags: ["new-balance", "nb9060", "chunky", "sneakers", "trending"],
    badge: "HOT",
  },
  {
    id: "new-balance-1906r",
    name: "New Balance 1906R",
    brand: "New Balance",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "Technical runner aesthetic with N-ergy shock absorption and Stability Web arch support.",
    tags: ["new-balance", "1906r", "gorpcore", "runner", "sneakers"],
  },
  {
    id: "asics-gel-kayano-14",
    name: "ASICS GEL-Kayano 14",
    brand: "Asics",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "Late 2000s technical runner with metallic synthetic overlays, open mesh, and signature GEL cushioning.",
    tags: ["asics", "gel-kayano", "metallic", "running", "streetwear", "trending"],
    badge: "HOT",
    featured: true,
  },
  {
    id: "asics-gel-nyc",
    name: "ASICS GEL-NYC",
    brand: "Asics",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "Heritage fusion borrowing from GEL-NIMBUS 3 and MC-PLUS V with ultra-cushioned midsole.",
    tags: ["asics", "gel-nyc", "lifestyle", "sneakers"],
  },
  {
    id: "puma-palermo-leather",
    name: "Puma Palermo Leather",
    brand: "Puma",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "Iconic 80s terrace shoe with signature signature Formstrip and gold Puma Palermo tag.",
    tags: ["puma", "palermo", "terrace", "sneakers"],
    badge: "NEW",
  },
  {
    id: "puma-suede-classic",
    name: "Puma Suede Classic XXI",
    brand: "Puma",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "Full suede upper with comfortable sockliner and clean street-ready profile.",
    tags: ["puma", "suede", "classic", "sneakers"],
  },
  {
    id: "converse-chuck-70-vintage",
    name: "Converse Chuck 70 Vintage Canvas",
    brand: "Converse",
    subcategory: "Sneakers",
    sectionId: "budget-wardrobe-essentials",
    sectionTitle: "Student & Budget Wardrobe Essentials",
    description: "Heavier 12oz canvas, higher rubber foxing, and cushioned OrthoLite insole for all-day comfort.",
    tags: ["converse", "chuck70", "high-top", "canvas", "classic", "budget"],
    badge: "POPULAR",
  },
  {
    id: "vans-old-skool-classic",
    name: "Vans Old Skool Classic Skate Shoes",
    brand: "Vans",
    subcategory: "Sneakers",
    sectionId: "budget-wardrobe-essentials",
    sectionTitle: "Student & Budget Wardrobe Essentials",
    description: "Durable suede and canvas uppers with the timeless Vans side stripe and signature waffle outsole.",
    tags: ["vans", "old-skool", "skate", "sneakers", "budget"],
  },
  {
    id: "on-cloudmonster-2",
    name: "On Cloudmonster 2",
    brand: "On",
    subcategory: "Sportswear",
    sectionId: "activewear-sportswear",
    sectionTitle: "Activewear & Sportswear",
    description: "Monster-level CloudTec cushioning with Helion superfoam and explosive Speedboard propulsion.",
    tags: ["on", "cloudmonster", "running", "cushioning", "premium"],
    badge: "NEW",
  },
  {
    id: "sneakers",
    name: "Sneakers",
    brand: "Plugd Footwear",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "A fresh pair of lifestyle sneakers curated for daily wear and modern outfits.",
    tags: ["sneakers", "footwear", "streetwear"],
  },

  // === Footwear (Non-Sneaker) ===
  {
    id: "birkenstock-boston-clog",
    name: "Birkenstock Boston Suede Leather Clogs",
    brand: "Birkenstock",
    subcategory: "Footwear",
    sectionId: "footwear-beyond-sneakers",
    sectionTitle: "Footwear Beyond Sneakers (Loafers, Boots, Mojaris)",
    description: "Velvety suede upper with anatomically shaped cork-latex footbed and adjustable metal pin buckle.",
    tags: ["birkenstock", "boston", "clog", "suede", "comfortable", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "crocs-classic-clog",
    name: "Crocs Classic Clog",
    brand: "Crocs",
    subcategory: "Footwear",
    sectionId: "footwear-beyond-sneakers",
    sectionTitle: "Footwear Beyond Sneakers (Loafers, Boots, Mojaris)",
    description: "Lightweight Croslite construction with ventilation ports and pivoting heel straps.",
    tags: ["crocs", "clogs", "slides", "casual", "waterproof"],
  },
  {
    id: "chelsea-leather-boots",
    name: "Full-Grain Leather Chelsea Boots",
    brand: "Clarks",
    subcategory: "Footwear",
    sectionId: "footwear-beyond-sneakers",
    sectionTitle: "Footwear Beyond Sneakers (Loafers, Boots, Mojaris)",
    description: "Handcrafted burnished leather with elastic side gussets, pull tabs, and Goodyear welted sole.",
    tags: ["boots", "chelsea", "leather", "formal", "menswear"],
    badge: "POPULAR",
  },
  {
    id: "suede-penny-loafers",
    name: "Italian Suede Penny Loafers",
    brand: "Massimo Dutti",
    subcategory: "Footwear",
    sectionId: "footwear-beyond-sneakers",
    sectionTitle: "Footwear Beyond Sneakers (Loafers, Boots, Mojaris)",
    description: "Supple suede slip-on loafers with saddle strap detail and leather-wrapped insole.",
    tags: ["loafers", "suede", "menswear", "smart-casual"],
  },
  {
    id: "chunky-platform-loafers",
    name: "Chunky Lug-Sole Platform Loafers",
    brand: "Zara",
    subcategory: "Footwear",
    sectionId: "footwear-beyond-sneakers",
    sectionTitle: "Footwear Beyond Sneakers (Loafers, Boots, Mojaris)",
    description: "Statement platform sole with polished upper and horsebit metallic hardware.",
    tags: ["loafers", "platform", "womens", "chunky", "trending"],
  },
  {
    id: "strappy-block-heels",
    name: "Minimalist Strappy Block Heels",
    brand: "Mango",
    subcategory: "Footwear",
    sectionId: "footwear-beyond-sneakers",
    sectionTitle: "Footwear Beyond Sneakers (Loafers, Boots, Mojaris)",
    description: "Square-toe silhouette with slender ankle straps and stable mid-height block heel.",
    tags: ["heels", "block-heels", "sandals", "womens", "party"],
  },
  {
    id: "handcrafted-kolhapuri-mojaris",
    name: "Handcrafted Leather Kolhapuri Mojaris",
    brand: "FabIndia",
    subcategory: "Ethnic Wear",
    sectionId: "indian-ethnic-festive",
    sectionTitle: "Indian & Festive Ethnic Wear",
    description: "Authentic vegetable-tanned leather traditional Indian juttis with braided embellishments.",
    tags: ["kolhapuri", "mojari", "juttis", "ethnic-footwear", "festive"],
    badge: "POPULAR",
  },

  // === Streetwear & Creator Tops ===
  {
    id: "heavyweight-oversized-graphic-tee",
    name: "240 GSM Heavyweight Oversized Graphic Tee",
    brand: "H&M",
    subcategory: "T-Shirts",
    sectionId: "streetwear-creator-fits",
    sectionTitle: "Streetwear & Creator Fits",
    description: "Dense 100% combed cotton jersey with dropped shoulders, ribbed crewneck, and vintage wash screenprint.",
    tags: ["t-shirt", "oversized", "graphic-tee", "streetwear", "heavyweight", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "boxy-drop-shoulder-hoodie",
    name: "400 GSM Boxy Drop-Shoulder Fleece Hoodie",
    brand: "Zara",
    subcategory: "Streetwear",
    sectionId: "streetwear-creator-fits",
    sectionTitle: "Streetwear & Creator Fits",
    description: "Ultra-heavy French terry cotton with double-layered hood, hidden kangaroo pocket, and relaxed cropped hem.",
    tags: ["hoodie", "fleece", "oversized", "streetwear", "creator-fit"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "oversized-hoodie",
    name: "Oversized Hoodie",
    brand: "Plugd Street",
    subcategory: "Streetwear",
    sectionId: "streetwear-creator-fits",
    sectionTitle: "Streetwear & Creator Fits",
    description: "Comfort-first wardrobe essential hoodie tailored with relaxed drop shoulders.",
    tags: ["hoodie", "oversized", "comfort"],
  },
  {
    id: "varsity-bomber-jacket",
    name: "Retro Wool-Blend Varsity Bomber Jacket",
    brand: "Tommy Hilfiger",
    subcategory: "Streetwear",
    sectionId: "streetwear-creator-fits",
    sectionTitle: "Streetwear & Creator Fits",
    description: "Classic collegiate aesthetic with contrast vegan leather sleeves, chenille chest patch, and striped ribbed trims.",
    tags: ["varsity", "jacket", "bomber", "streetwear", "creator-style"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "statement-jacket",
    name: "Statement Jacket",
    brand: "Plugd Outerwear",
    subcategory: "Streetwear",
    sectionId: "streetwear-creator-fits",
    sectionTitle: "Streetwear & Creator Fits",
    description: "A bold layer for content creation, travel, and signature outfit building.",
    tags: ["jacket", "outerwear", "statement"],
  },
  {
    id: "flannel-plaid-overshirt",
    name: "Brushed Cotton Plaid Flannel Overshirt",
    brand: "Uniqlo",
    subcategory: "Shirts",
    sectionId: "tops-hoodies-layers",
    sectionTitle: "Casual Tops, Hoodies & Layers",
    description: "Thick double-brushed cotton in a heritage buffalo check pattern, perfect for open layering over tees.",
    tags: ["flannel", "overshirt", "plaid", "layering", "autumn"],
  },
  {
    id: "vintage-washed-denim-jacket",
    name: "Levi's Trucker Denim Jacket",
    brand: "Levi's",
    subcategory: "Streetwear",
    sectionId: "streetwear-creator-fits",
    sectionTitle: "Streetwear & Creator Fits",
    description: "Original 1967 silhouette in rugged non-stretch cotton denim with button-flap chest pockets and side waist adjusters.",
    tags: ["levis", "denim-jacket", "trucker", "streetwear", "classic"],
    badge: "BESTSELLER",
  },
  {
    id: "corduroy-zip-overshirt",
    name: "Fine Wale Corduroy Zip Overshirt",
    brand: "Mango",
    subcategory: "Shirts",
    sectionId: "tops-hoodies-layers",
    sectionTitle: "Casual Tops, Hoodies & Layers",
    description: "Tactile textured corduroy with silver two-way zipper and clean spread collar.",
    tags: ["corduroy", "overshirt", "jacket", "smart-casual"],
  },
  {
    id: "crewneck-minimalist-sweatshirt",
    name: "Minimalist Loopback Cotton Crewneck",
    brand: "Uniqlo",
    subcategory: "Tops",
    sectionId: "tops-hoodies-layers",
    sectionTitle: "Casual Tops, Hoodies & Layers",
    description: "Clean silhouette in premium Japanese loopback terry cotton for effortless daily layering.",
    tags: ["sweatshirt", "crewneck", "minimalist", "basics"],
  },
  {
    id: "knit-boxy-cardigan",
    name: "Textured Knit Boxy Button Cardigan",
    brand: "Zara",
    subcategory: "Tops",
    sectionId: "tops-hoodies-layers",
    sectionTitle: "Casual Tops, Hoodies & Layers",
    description: "Chunky knit ribbed structure with tortoiseshell buttons and contemporary drop-shoulder fit.",
    tags: ["cardigan", "knitwear", "vintage", "autumn"],
  },
  {
    id: "basic-heavyweight-t-shirt",
    name: "Supima Cotton Heavyweight Crewneck Tee",
    brand: "Uniqlo",
    subcategory: "T-Shirts",
    sectionId: "budget-wardrobe-essentials",
    sectionTitle: "Student & Budget Wardrobe Essentials",
    description: "100% extra-long staple Supima cotton providing silky smoothness and shape retention wash after wash.",
    tags: ["t-shirt", "supima", "basics", "essential", "budget"],
    badge: "BESTSELLER",
  },
  {
    id: "pima-cotton-polo-shirt",
    name: "Tailored Pima Cotton Polo Shirt",
    brand: "Lacoste",
    subcategory: "T-Shirts",
    sectionId: "mens-style-essentials",
    sectionTitle: "Men's Style & Everyday Essentials",
    description: "Breathable petit piqué cotton with ribbed collar, mother-of-pearl buttons, and embroidered crocodile logo.",
    tags: ["polo", "lacoste", "smart-casual", "menswear"],
    badge: "POPULAR",
  },
  {
    id: "pure-linen-resort-shirt",
    name: "Pure European Linen Resort Collar Shirt",
    brand: "Westside",
    subcategory: "Shirts",
    sectionId: "mens-style-essentials",
    sectionTitle: "Men's Style & Everyday Essentials",
    description: "Lightweight, airy linen tailored with a modern Cuban camp collar for warm-weather styling.",
    tags: ["linen", "shirt", "cuban-collar", "resort", "summer"],
    badge: "POPULAR",
  },
  {
    id: "tailored-oxford-cotton-shirt",
    name: "Classic Oxford Cloth Button-Down Shirt",
    brand: "Ralph Lauren",
    subcategory: "Shirts",
    sectionId: "mens-style-essentials",
    sectionTitle: "Men's Style & Everyday Essentials",
    description: "Durable basketweave Oxford cotton with button-down collar and box pleat for timeless smart dressing.",
    tags: ["oxford", "shirt", "button-down", "formal", "smart"],
  },

  // === Bottoms ===
  {
    id: "relaxed-fit-utilitarian-cargo-pants",
    name: "Multi-Pocket Utilitarian Relaxed Cargo Pants",
    brand: "H&M",
    subcategory: "Trousers",
    sectionId: "streetwear-creator-fits",
    sectionTitle: "Streetwear & Creator Fits",
    description: "Durable cotton twill with deep 3D bellows pockets, reinforced knee stitching, and adjustable drawstring ankle cuffs.",
    tags: ["cargos", "pants", "streetwear", "utilitarian", "gorpcore", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "levis-501-original-straight-jeans",
    name: "Levi's 501 Original Straight Fit Jeans",
    brand: "Levi's",
    subcategory: "Jeans",
    sectionId: "mens-style-essentials",
    sectionTitle: "Men's Style & Everyday Essentials",
    description: "The original blueprint denim featuring iconic button fly, straight leg, and authentic raw selvedge finish.",
    tags: ["levis", "501", "jeans", "denim", "straight-leg", "bestseller"],
    badge: "BESTSELLER",
    featured: true,
  },
  {
    id: "baggy-90s-skater-jeans",
    name: "90s Baggy Wide-Leg Skater Jeans",
    brand: "Zara",
    subcategory: "Jeans",
    sectionId: "bottoms-cargos-denims",
    sectionTitle: "Bottoms: Cargos, Denims & Relaxed Fits",
    description: "Generous loose cut through the seat and thigh with vintage stone wash effect stacking perfectly on sneakers.",
    tags: ["jeans", "baggy", "90s", "skate", "streetwear"],
    badge: "POPULAR",
  },
  {
    id: "pleated-tailored-smart-trousers",
    name: "Double-Pleated Tailored Wide Trousers",
    brand: "Mango",
    subcategory: "Trousers",
    sectionId: "mens-style-essentials",
    sectionTitle: "Men's Style & Everyday Essentials",
    description: "Draped wool-blend fabric with clean front double pleats, concealed hook fastening, and fluid drape.",
    tags: ["trousers", "pleated", "tailored", "old-money", "smart-casual"],
    badge: "POPULAR",
  },
  {
    id: "wide-leg-high-waist-trousers",
    name: "High-Waist Fluid Wide-Leg Trousers",
    brand: "Zara",
    subcategory: "Trousers",
    sectionId: "womens-contemporary-edit",
    sectionTitle: "Women's Edit & Contemporary Silhouettes",
    description: "High-rise tailored waistband flowing into a floor-skimming wide-leg silhouette with front pressed creases.",
    tags: ["trousers", "wide-leg", "high-waist", "womens", "elegant"],
  },
  {
    id: "slim-tapered-stretch-chinos",
    name: "Stretch Cotton Slim Tapered Chinos",
    brand: "Uniqlo",
    subcategory: "Trousers",
    sectionId: "mens-style-essentials",
    sectionTitle: "Men's Style & Everyday Essentials",
    description: "High-density twill with 2-way stretch providing all-day comfort for work and evening wear.",
    tags: ["chinos", "trousers", "stretch", "workwear"],
  },
  {
    id: "everyday-cotton-drawstring-shorts",
    name: "Relaxed French Terry Drawstring Shorts",
    brand: "H&M",
    subcategory: "Trousers",
    sectionId: "bottoms-cargos-denims",
    sectionTitle: "Bottoms: Cargos, Denims & Relaxed Fits",
    description: "Comfort-stretch elasticated waist with custom drawcords and side welt pockets.",
    tags: ["shorts", "cotton", "casual", "summer", "lounge"],
  },

  // === Women's Edit ===
  {
    id: "satin-slip-midi-dress",
    name: "Bias-Cut Silk-Satin Slip Midi Dress",
    brand: "Mango",
    subcategory: "Dresses",
    sectionId: "womens-contemporary-edit",
    sectionTitle: "Women's Edit & Contemporary Silhouettes",
    description: "Fluid bias-cut satin draping naturally along body contours with delicate adjustable spaghetti straps.",
    tags: ["dress", "slip-dress", "satin", "midi", "evening", "party", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "fluid-linen-summer-maxi-dress",
    name: "Tiered Pure Linen Summer Maxi Dress",
    brand: "Westside",
    subcategory: "Dresses",
    sectionId: "womens-contemporary-edit",
    sectionTitle: "Women's Edit & Contemporary Silhouettes",
    description: "Airy pure linen with tiered skirt volume, sweetheart neckline, and smocked back detailing.",
    tags: ["dress", "maxi", "linen", "summer", "vacation"],
    badge: "POPULAR",
  },
  {
    id: "oversized-structured-blazer",
    name: "Oversized Double-Breasted Tailored Blazer",
    brand: "Zara",
    subcategory: "Tops",
    sectionId: "womens-contemporary-edit",
    sectionTitle: "Women's Edit & Contemporary Silhouettes",
    description: "Structured shoulder pads, peak lapels, and tortoiseshell double-breasted buttons for power dressing.",
    tags: ["blazer", "tailored", "oversized", "workwear", "streetwear"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "ribbed-knit-seamless-crop-top",
    name: "Seamless Ribbed High-Neck Crop Top",
    brand: "H&M",
    subcategory: "Tops",
    sectionId: "womens-contemporary-edit",
    sectionTitle: "Women's Edit & Contemporary Silhouettes",
    description: "Form-fitting four-way stretch ribbed knit with high cutaway neckline.",
    tags: ["crop-top", "ribbed", "seamless", "basics", "layering"],
  },
  {
    id: "floral-wrap-mini-dress",
    name: "Printed Crepe Floral Wrap Mini Dress",
    brand: "Zara",
    subcategory: "Dresses",
    sectionId: "womens-contemporary-edit",
    sectionTitle: "Women's Edit & Contemporary Silhouettes",
    description: "Flattering adjustable side tie with ruffle hemline and V-neckline.",
    tags: ["dress", "wrap-dress", "floral", "mini", "party"],
  },
  {
    id: "cotton-poplin-oversized-shirt",
    name: "Crisp Cotton Poplin Oversized Boyfriend Shirt",
    brand: "Mango",
    subcategory: "Shirts",
    sectionId: "womens-contemporary-edit",
    sectionTitle: "Women's Edit & Contemporary Silhouettes",
    description: "Generous boyfriend cut in crisp poplin cotton with curved high-low hem.",
    tags: ["shirt", "poplin", "oversized", "capsule-wardrobe"],
  },

  // === Indian & Festive Ethnic Wear ===
  {
    id: "handloom-banarasi-silk-saree",
    name: "Handloom Pure Katan Banarasi Silk Saree",
    brand: "FabIndia",
    subcategory: "Ethnic Wear",
    sectionId: "indian-ethnic-festive",
    sectionTitle: "Indian & Festive Ethnic Wear",
    description: "Heirloom-grade handwoven Banarasi silk with intricate golden Zari floral Kadwa motifs and rich pallu.",
    tags: ["saree", "banarasi", "silk", "handloom", "ethnic", "wedding", "festive", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "chikankari-embroidered-cotton-kurta",
    name: "Handcrafted Lucknowi Chikankari Kurta",
    brand: "FabIndia",
    subcategory: "Ethnic Wear",
    sectionId: "indian-ethnic-festive",
    sectionTitle: "Indian & Festive Ethnic Wear",
    description: "Breezy mulmul cotton adorned with delicate handcrafted Bakhiya and Phanda thread embroidery.",
    tags: ["kurta", "chikankari", "cotton", "ethnic", "summer", "bestseller"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "chanderi-silk-anarkali-suit-set",
    name: "Chanderi Silk Anarkali Kurta Set with Dupatta",
    brand: "FabIndia",
    subcategory: "Ethnic Wear",
    sectionId: "indian-ethnic-festive",
    sectionTitle: "Indian & Festive Ethnic Wear",
    description: "Flared Kalidar Anarkali silhouette with Gota Patti trims, straight pants, and lightweight organza dupatta.",
    tags: ["anarkali", "kurta-set", "chanderi", "ethnic", "festive"],
    badge: "POPULAR",
  },
  {
    id: "raw-silk-festive-nehru-jacket",
    name: "Woven Raw Silk Tailored Nehru Jacket",
    brand: "Manyavar",
    subcategory: "Ethnic Wear",
    sectionId: "indian-ethnic-festive",
    sectionTitle: "Indian & Festive Ethnic Wear",
    description: "Structured mandarin collar sleeveless bandhgala jacket with metallic buttons and welt pocket.",
    tags: ["nehru-jacket", "bandhgala", "ethnic", "menswear", "festive"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "designer-embroidered-lehenga-choli",
    name: "Raw Silk Embroidered Bridal Lehenga Set",
    brand: "Manyavar",
    subcategory: "Ethnic Wear",
    sectionId: "indian-ethnic-festive",
    sectionTitle: "Indian & Festive Ethnic Wear",
    description: "Voluminous flared skirt with heavy Zardozi hand-embroidery, padded blouse, and netted dupatta.",
    tags: ["lehenga", "bridal", "festive", "ethnic", "luxury"],
    badge: "PREMIUM",
  },
  {
    id: "mens-silk-blend-kurta-pajama-set",
    name: "Jacquard Silk Blend Festive Kurta Pajama",
    brand: "Manyavar",
    subcategory: "Ethnic Wear",
    sectionId: "indian-ethnic-festive",
    sectionTitle: "Indian & Festive Ethnic Wear",
    description: "Rich woven jacquard pattern kurta with mandarin collar and churidar pajama.",
    tags: ["kurta", "kurta-set", "ethnic", "menswear", "diwali"],
  },
  {
    id: "traditional-bandhgala-suit",
    name: "Bespoke Royal Bandhgala Jodhpuri Suit",
    brand: "Manyavar",
    subcategory: "Ethnic Wear",
    sectionId: "indian-ethnic-festive",
    sectionTitle: "Indian & Festive Ethnic Wear",
    description: "Impeccably tailored closed-collar jacket with tonal trousers for formal royal heritage occasions.",
    tags: ["bandhgala", "jodhpuri", "suit", "ethnic", "luxury"],
    badge: "PREMIUM",
  },

  // === Watches & Timepieces ===
  {
    id: "casio-vintage-digital-a168",
    name: "Casio Vintage Digital A168WA-1",
    brand: "Casio",
    subcategory: "Watches",
    sectionId: "timepieces-watches",
    sectionTitle: "Timepieces & Iconic Watches",
    description: "The retro cultural icon featuring stainless steel band, EL backlight, 1/100s stopwatch, and daily alarm.",
    tags: ["casio", "vintage", "digital-watch", "stainless-steel", "retro", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "casio-g-shock-ga-2100-casioak",
    name: "Casio G-Shock GA-2100 'CasiOak'",
    brand: "G-Shock",
    subcategory: "Watches",
    sectionId: "timepieces-watches",
    sectionTitle: "Timepieces & Iconic Watches",
    description: "Slim octagonal bezel with Carbon Core Guard structure, 200m water resistance, and shockproof durability.",
    tags: ["casio", "g-shock", "casioak", "sports-watch", "rugged", "bestseller"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "titan-edge-ceramic-slim-watch",
    name: "Titan Edge Ceramic Ultra-Slim Watch",
    brand: "Titan",
    subcategory: "Watches",
    sectionId: "timepieces-watches",
    sectionTitle: "Timepieces & Iconic Watches",
    description: "India's engineering marvel measuring just 4.4mm thin with scratch-resistant ceramic case and sapphire crystal.",
    tags: ["titan", "titan-edge", "ceramic", "slim-watch", "dress-watch", "luxury"],
    badge: "PREMIUM",
    featured: true,
  },
  {
    id: "seiko-5-sports-automatic-watch",
    name: "Seiko 5 Sports Automatic SRPD55K1",
    brand: "Seiko",
    subcategory: "Watches",
    sectionId: "timepieces-watches",
    sectionTitle: "Timepieces & Iconic Watches",
    description: "Iconic Japanese mechanical automatic movement with 41-hour power reserve, diver-style unidirectional bezel, and exhibition caseback.",
    tags: ["seiko", "seiko-5", "automatic-watch", "diver", "mechanical"],
    badge: "POPULAR",
  },
  {
    id: "tissot-prx-powermatic-80",
    name: "Tissot PRX Powermatic 80 Automatic",
    brand: "Tissot",
    subcategory: "Watches",
    sectionId: "timepieces-watches",
    sectionTitle: "Timepieces & Iconic Watches",
    description: "1978 integrated bracelet icon with 80-hour power reserve, Nivachron balance spring, and waffle dial.",
    tags: ["tissot", "prx", "swiss-watch", "automatic", "luxury", "trending"],
    badge: "HOT",
    featured: true,
  },
  {
    id: "apple-watch-ultra-2",
    name: "Apple Watch Ultra 2 Titanium",
    brand: "Apple",
    subcategory: "Watches",
    sectionId: "timepieces-watches",
    sectionTitle: "Timepieces & Iconic Watches",
    description: "49mm aerospace-grade titanium case with 3000-nit display, precision dual-frequency GPS, and 72-hour battery life.",
    tags: ["apple", "apple-watch", "ultra2", "smartwatch", "titanium"],
    badge: "HOT",
  },
  {
    id: "fossil-grant-chronograph-leather-watch",
    name: "Fossil Grant Chronograph Leather Watch",
    brand: "Fossil",
    subcategory: "Watches",
    sectionId: "timepieces-watches",
    sectionTitle: "Timepieces & Iconic Watches",
    description: "Roman numeral dial with three-subdial stopwatch and interchangeable genuine leather strap.",
    tags: ["fossil", "chronograph", "leather", "dress-watch"],
  },
  {
    id: "designer-watch",
    name: "Designer Watch",
    brand: "Plugd Time",
    subcategory: "Watches",
    sectionId: "timepieces-watches",
    sectionTitle: "Timepieces & Iconic Watches",
    description: "A polished accessory with a premium feel for everyday outfits and evening occasions.",
    tags: ["watch", "timepiece", "accessory"],
  },

  // === Bags & Backpacks ===
  {
    id: "waterproof-urban-laptop-backpack",
    name: "Urban Roll-Top Waterproof Laptop Backpack 25L",
    brand: "Mokobara",
    subcategory: "Bags",
    sectionId: "bags-backpacks-carry",
    sectionTitle: "Bags, Backpacks & Everyday Carry",
    description: "Weatherproof matte coated fabric with dedicated 16-inch fleece laptop sleeve and luggage pass-through strap.",
    tags: ["backpack", "laptop-bag", "waterproof", "commute", "travel", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "travel-backpack",
    name: "Travel Backpack",
    brand: "Plugd Carry",
    subcategory: "Bags",
    sectionId: "bags-backpacks-carry",
    sectionTitle: "Bags, Backpacks & Everyday Carry",
    description: "A functional carry backpack engineered for work, movement, and creator travels.",
    tags: ["backpack", "travel", "carry"],
  },
  {
    id: "minimalist-leather-crossbody-sling",
    name: "Minimalist Leather Everyday Crossbody Sling",
    brand: "Zara",
    subcategory: "Bags",
    sectionId: "bags-backpacks-carry",
    sectionTitle: "Bags, Backpacks & Everyday Carry",
    description: "Compact hands-free carry crafted in supple pebbled leather with magnetic buckle and quick-access phone pocket.",
    tags: ["sling", "crossbody", "leather-bag", "streetwear", "essentials"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "heavy-canvas-work-tote-bag",
    name: "Heavy Duty 16oz Canvas Work Tote Bag",
    brand: "Uniqlo",
    subcategory: "Bags",
    sectionId: "bags-backpacks-carry",
    sectionTitle: "Bags, Backpacks & Everyday Carry",
    description: "Reinforced box-stitch handles, brass snap closures, and spacious interior organizing compartments.",
    tags: ["tote", "canvas-bag", "tote-bag", "work-bag", "student"],
  },
  {
    id: "leather-structure-shoulder-handbag",
    name: "Structured Leather Flap Shoulder Handbag",
    brand: "Mango",
    subcategory: "Bags",
    sectionId: "bags-backpacks-carry",
    sectionTitle: "Bags, Backpacks & Everyday Carry",
    description: "Clean architectural geometry with gold metallic clasp, dual strap options, and suede-lined interior.",
    tags: ["handbag", "shoulder-bag", "leather", "womens", "luxury"],
    badge: "POPULAR",
  },
  {
    id: "cordura-gym-weekend-duffle-bag",
    name: "Water-Resistant Cordura Gym & Weekend Duffle",
    brand: "Puma",
    subcategory: "Bags",
    sectionId: "bags-backpacks-carry",
    sectionTitle: "Bags, Backpacks & Everyday Carry",
    description: "Separate ventilated sneaker tunnel, padded shoulder strap, and abrasion-resistant ballistic base.",
    tags: ["duffle", "gym-bag", "weekend-bag", "travel", "sportswear"],
  },
  {
    id: "slim-leather-rfid-cardholder-wallet",
    name: "Minimalist Full-Grain Leather RFID Cardholder",
    brand: "Bellroy",
    subcategory: "Accessories",
    sectionId: "jewellery-accessories",
    sectionTitle: "Statement Jewellery & Accessories",
    description: "Slim profile holding 8 cards plus folded currency with quick-access pull tab and RFID shielding.",
    tags: ["wallet", "cardholder", "leather", "minimalist", "edc"],
  },

  // === Accessories & Jewellery ===
  {
    id: "vintage-retro-tinted-sunglasses",
    name: "Vintage 90s Tinted Acetate Sunglasses",
    brand: "Ray-Ban",
    subcategory: "Accessories",
    sectionId: "jewellery-accessories",
    sectionTitle: "Statement Jewellery & Accessories",
    description: "Glossy tortoise and black acetate frame with gradient UV400 lenses and silver metal temple rivets.",
    tags: ["sunglasses", "shades", "retro", "creator-style", "summer", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "sunglasses",
    name: "Sunglasses",
    brand: "Plugd Eyewear",
    subcategory: "Accessories",
    sectionId: "jewellery-accessories",
    sectionTitle: "Statement Jewellery & Accessories",
    description: "A versatile eyewear style upgrade for everyday outfits and travel fits.",
    tags: ["sunglasses", "eyewear", "accessory"],
  },
  {
    id: "cuban-link-stainless-steel-chain",
    name: "8mm Cuban Link Stainless Steel Chain Necklace",
    brand: "Plugd Accessories",
    subcategory: "Jewellery",
    sectionId: "jewellery-accessories",
    sectionTitle: "Statement Jewellery & Accessories",
    description: "High-polish 316L medical-grade stainless steel with custom lobster clasp, tarnish-free and sweatproof.",
    tags: ["chain", "necklace", "cuban-link", "jewellery", "streetwear"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "minimalist-silver-signet-ring",
    name: "Brushed Silver Geometric Signet Ring",
    brand: "Plugd Accessories",
    subcategory: "Jewellery",
    sectionId: "jewellery-accessories",
    sectionTitle: "Statement Jewellery & Accessories",
    description: "Clean flat-top rectangular face with brushed satin finish and comfort-fit inner band.",
    tags: ["ring", "signet-ring", "silver", "jewellery", "menswear"],
  },
  {
    id: "unstructured-dad-cap",
    name: "Washed Cotton 6-Panel Unstructured Dad Cap",
    brand: "New Era",
    subcategory: "Accessories",
    sectionId: "jewellery-accessories",
    sectionTitle: "Statement Jewellery & Accessories",
    description: "Soft washed twill with curved brim, embroidered eyelets, and adjustable brass buckle strapback.",
    tags: ["cap", "hat", "dad-cap", "streetwear", "basics"],
  },
  {
    id: "full-grain-leather-pin-buckle-belt",
    name: "Full-Grain Italian Leather Pin-Buckle Belt",
    brand: "Levi's",
    subcategory: "Accessories",
    sectionId: "jewellery-accessories",
    sectionTitle: "Statement Jewellery & Accessories",
    description: "35mm wide vegetable-tanned full grain leather with brushed nickel buckle and bevelled edges.",
    tags: ["belt", "leather-belt", "menswear", "classic"],
  },

  // === Sportswear ===
  {
    id: "nike-dri-fit-training-t-shirt",
    name: "Nike Dri-FIT High-Ventilation Training Tee",
    brand: "Nike",
    subcategory: "Sportswear",
    sectionId: "activewear-sportswear",
    sectionTitle: "Activewear & Sportswear",
    description: "Sweat-wicking Dri-FIT fabric with mapped mesh zones to keep you cool during intense workouts.",
    tags: ["nike", "dri-fit", "gym", "workout", "sportswear", "training"],
    badge: "POPULAR",
  },
  {
    id: "adidas-tiro-training-track-pants",
    name: "Adidas Tiro 24 Performance Track Pants",
    brand: "Adidas",
    subcategory: "Sportswear",
    sectionId: "activewear-sportswear",
    sectionTitle: "Activewear & Sportswear",
    description: "Classic tapered soccer silhouette with AEROREADY moisture management and ankle zips.",
    tags: ["adidas", "tiro", "track-pants", "joggers", "sportswear"],
    badge: "BESTSELLER",
  },
  {
    id: "under-armour-heatgear-compression-top",
    name: "Under Armour HeatGear Compression Long-Sleeve",
    brand: "Under Armour",
    subcategory: "Sportswear",
    sectionId: "activewear-sportswear",
    sectionTitle: "Activewear & Sportswear",
    description: "Ultra-tight second-skin fit with 4-way stretch and anti-odor technology for athletic training.",
    tags: ["under-armour", "compression", "heatgear", "gym", "sportswear"],
  },
  {
    id: "puma-drycell-running-shorts",
    name: "Puma dryCELL 5\" Lightweight Running Shorts",
    brand: "Puma",
    subcategory: "Sportswear",
    sectionId: "activewear-sportswear",
    sectionTitle: "Activewear & Sportswear",
    description: "Built-in breathable brief liner with reflective details and zippered key pocket.",
    tags: ["puma", "running-shorts", "sportswear", "active"],
  },

  // === Luxury & Premium ===
  {
    id: "ralph-lauren-custom-fit-oxford",
    name: "Polo Ralph Lauren Custom Fit Oxford Shirt",
    brand: "Ralph Lauren",
    subcategory: "Luxury",
    sectionId: "premium-luxury-statements",
    sectionTitle: "Premium & Luxury Statements",
    description: "Heritage preppy staple tailored with multicoloured signature Pony embroidery and split pleated back yoke.",
    tags: ["ralph-lauren", "polo", "luxury", "oxford", "old-money", "designer"],
    badge: "PREMIUM",
    featured: true,
  },
  {
    id: "tommy-hilfiger-yacht-bomber-jacket",
    name: "Tommy Hilfiger Regatta Yachting Bomber Jacket",
    brand: "Tommy Hilfiger",
    subcategory: "Luxury",
    sectionId: "premium-luxury-statements",
    sectionTitle: "Premium & Luxury Statements",
    description: "Water-repellent technical shell with packable hood, fleece-lined collar, and signature flag branding.",
    tags: ["tommy-hilfiger", "bomber", "yachting", "outerwear", "premium"],
    badge: "POPULAR",
  },
  {
    id: "calvin-klein-minimalist-monogram-tee",
    name: "Calvin Klein Monogram Organic Cotton Tee",
    brand: "Calvin Klein",
    subcategory: "Luxury",
    sectionId: "premium-luxury-statements",
    sectionTitle: "Premium & Luxury Statements",
    description: "100% organic cotton jersey with iconic micro-monogram chest print and refined modern fit.",
    tags: ["calvin-klein", "ck", "monogram", "t-shirt", "luxury"],
  },
  {
    id: "coach-leather-tabby-shoulder-bag",
    name: "Coach Tabby 26 Polished Leather Shoulder Bag",
    brand: "Coach",
    subcategory: "Luxury",
    sectionId: "premium-luxury-statements",
    sectionTitle: "Premium & Luxury Statements",
    description: "Modern archival 1970s Coach design in structured polished pebble leather with iconic Signature C hardware.",
    tags: ["coach", "tabby", "leather-bag", "luxury", "handbag", "designer"],
    badge: "PREMIUM",
    featured: true,
  },
  {
    id: "hugo-boss-virgin-wool-blazer",
    name: "BOSS Virgin Wool Slim-Fit Tailored Suit Jacket",
    brand: "Hugo Boss",
    subcategory: "Luxury",
    sectionId: "premium-luxury-statements",
    sectionTitle: "Premium & Luxury Statements",
    description: "Finely woven Super 120s virgin wool with AMF stitching, notch lapels, and silky cupro lining.",
    tags: ["hugo-boss", "boss", "blazer", "suit", "wool", "luxury"],
    badge: "PREMIUM",
  },
];

/**
 * Return all Fashion products with resolved image URLs and display orders.
 */
export function getFullFashionCatalog(): FashionProduct[] {
  return RAW_FASHION_PRODUCTS.map((p, idx) => ({
    id: p.id,
    name: p.name,
    brand: p.brand,
    category: "Fashion",
    subcategory: p.subcategory,
    sectionId: p.sectionId,
    sectionTitle: p.sectionTitle,
    imageUrl: getFashionProductImage(p.id),
    description: p.description,
    tags: p.tags,
    badge: p.badge,
    featured: Boolean(p.featured),
    trending: Boolean(p.trending),
    displayOrder: idx,
  }));
}

/**
 * Get distinct subcategories for fashion navigation
 */
export function getFashionSubcategories(): Array<{ name: string; count: number }> {
  const map = new Map<string, number>();
  for (const item of RAW_FASHION_PRODUCTS) {
    map.set(item.subcategory, (map.get(item.subcategory) || 0) + 1);
  }
  return Array.from(map.entries()).map(([name, count]) => ({ name, count }));
}
