/**
 * Comprehensive Fashion Catalog Data Definition for Plugd
 * 
 * Expansive, creator-ready fashion catalog covering Streetwear, Sneakers,
 * Men's, Women's, Unisex, Ethnic Wear, Watches, Bags, Jewellery, Sportswear,
 * Luxury, and Accessories for the Indian market.
 */

import { getFashionProductImage } from "./product-images";

export interface FashionProduct {
  id: string;
  name: string;
  brand: string;
  category: "Fashion";
  subcategory: string;
  sectionId: string;
  sectionTitle: string;
  imageUrl: string;
  description: string;
  tags: string[];
  badge?: "HOT" | "TRENDING" | "NEW" | "POPULAR" | "PREMIUM" | "BESTSELLER";
  featured?: boolean;
  trending?: boolean;
  displayOrder: number;
}

export interface FashionSection {
  id: string;
  title: string;
  subtitle: string;
  badge?: string;
  displayOrder: number;
  productIds: string[];
}

export const FASHION_SECTIONS: FashionSection[] = [
  {
    id: "trending-fashion",
    title: "Trending Fashion",
    subtitle: "Most desired sneakers, oversized street layers, iconic timepieces, and creator wardrobe staples",
    badge: "🔥 Hot",
    displayOrder: 1,
    productIds: [
      "nike-air-jordan-1-retro-high",
      "adidas-samba-og",
      "heavyweight-oversized-graphic-tee",
      "casio-vintage-digital-a168",
      "new-balance-550",
      "boxy-drop-shoulder-hoodie",
      "relaxed-fit-utilitarian-cargo-pants",
      "waterproof-urban-laptop-backpack",
      "vintage-retro-tinted-sunglasses",
      "asics-gel-kayano-14",
      "handloom-banarasi-silk-saree",
      "tissot-prx-powermatic-80",
      "minimalist-leather-crossbody-sling",
      "satin-slip-midi-dress",
      "birkenstock-boston-clog",
    ],
  },
  {
    id: "sneaker-culture",
    title: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    subtitle: "Hype retros, skate icons, terrace classics, and everyday lifestyle runners",
    badge: "👟 Sneakers",
    displayOrder: 2,
    productIds: [
      "nike-air-jordan-1-retro-high",
      "air-jordan-1",
      "nike-dunk-low-retro",
      "nike-air-force-1-07",
      "adidas-samba-og",
      "adidas-gazelle-indoor",
      "adidas-originals-campus-00s",
      "adidas-originals",
      "new-balance-550",
      "new-balance-9060",
      "new-balance-1906r",
      "asics-gel-kayano-14",
      "asics-gel-nyc",
      "puma-palermo-leather",
      "puma-suede-classic",
      "converse-chuck-70-vintage",
      "vans-old-skool-classic",
      "on-cloudmonster-2",
      "sneakers",
      "new-balance-2002r",
      "new-balance-530",
      "nike-air-max-90",
      "nike-air-max-1",
      "nike-blazer-mid-77",
      "adidas-handball-spezial",
      "on-cloud-5",
      "nike-air-max-97",
      "adidas-gazelle-bold",
      "puma-speedcat-og"
    ],
  },
  {
    id: "streetwear-creator-fits",
    title: "Streetwear & Creator Fits",
    subtitle: "Boxy silhouettes, drop shoulders, utilitarian details, and visual statement pieces for content creators",
    badge: "🛹 Streetwear",
    displayOrder: 3,
    productIds: [
      "heavyweight-oversized-graphic-tee",
      "boxy-drop-shoulder-hoodie",
      "oversized-hoodie",
      "varsity-bomber-jacket",
      "statement-jacket",
      "relaxed-fit-utilitarian-cargo-pants",
      "baggy-90s-skater-jeans",
      "vintage-washed-denim-jacket",
      "cuban-link-stainless-steel-chain",
      "unstructured-dad-cap",
      "minimalist-leather-crossbody-sling",
      "birkenstock-boston-clog",
      "oversized-plain-tee",
      "boxy-fit-tee",
      "vintage-acid-wash-tee",
      "parachute-pants",
      "bomber-jacket",
      "denim-jacket-classic"
    ],
  },
  {
    id: "mens-style-essentials",
    title: "Men's Style & Everyday Essentials",
    subtitle: "Refined polos, breathable linen shirts, tailored chinos, selvedge denim, and versatile loafers",
    badge: "👔 Men's Edit",
    displayOrder: 4,
    productIds: [
      "pure-linen-resort-shirt",
      "tailored-oxford-cotton-shirt",
      "pima-cotton-polo-shirt",
      "levis-501-original-straight-jeans",
      "pleated-tailored-smart-trousers",
      "slim-tapered-stretch-chinos",
      "suede-penny-loafers",
      "chelsea-leather-boots",
      "full-grain-leather-pin-buckle-belt",
      "seiko-5-sports-automatic-watch",
      "basic-heavyweight-t-shirt",
      "oversized-shirt-men",
      "relaxed-fit-shirt",
      "polo-tshirt-classic"
    ],
  },
  {
    id: "womens-contemporary-edit",
    title: "Women's Edit & Contemporary Silhouettes",
    subtitle: "Fluid midi dresses, tailored wide-leg trousers, structured blazers, and versatile capsule staples",
    badge: "✨ Women's Edit",
    displayOrder: 5,
    productIds: [
      "satin-slip-midi-dress",
      "fluid-linen-summer-maxi-dress",
      "oversized-structured-blazer",
      "ribbed-knit-seamless-crop-top",
      "wide-leg-high-waist-trousers",
      "floral-wrap-mini-dress",
      "cotton-poplin-oversized-shirt",
      "leather-structure-shoulder-handbag",
      "strappy-block-heels",
      "chunky-platform-loafers",
      "baby-tee",
      "crop-top-basic",
      "ribbed-tank-top",
      "corset-top",
      "tube-top",
      "off-shoulder-top",
      "graphic-tee-womens",
      "oversized-shirt-womens",
      "cardigan-womens",
      "knit-top-womens",
      "zip-hoodie-womens",
      "oversized-hoodie-womens",
      "baggy-jeans-womens",
      "wide-leg-jeans-womens",
      "cargo-pants-womens",
      "parachute-pants-womens",
      "denim-skirt",
      "mini-skirt-pleated",
      "midi-skirt-satin",
      "maxi-skirt",
      "co-ord-set-womens",
      "casual-dress",
      "bodycon-dress",
      "oversized-jacket-womens",
      "denim-jacket-womens",
      "bomber-jacket-womens",
      "leather-style-jacket-womens",
      "oversized-tee-womens"
    ],
  },
  {
    id: "indian-ethnic-festive",
    title: "Indian & Festive Ethnic Wear",
    subtitle: "Handloom Banarasi sarees, embroidered kurtas, raw silk Nehru jackets, and handcrafted mojaris",
    badge: "🥻 Indian Festive",
    displayOrder: 6,
    productIds: [
      "handloom-banarasi-silk-saree",
      "chikankari-embroidered-cotton-kurta",
      "chanderi-silk-anarkali-suit-set",
      "raw-silk-festive-nehru-jacket",
      "designer-embroidered-lehenga-choli",
      "mens-silk-blend-kurta-pajama-set",
      "traditional-bandhgala-suit",
      "handcrafted-kolhapuri-mojaris",
    ],
  },
  {
    id: "timepieces-watches",
    title: "Timepieces & Iconic Watches",
    subtitle: "Retro digital classics, rugged G-Shocks, Swiss automatics, and smart wearable essentials",
    badge: "⌚ Watches",
    displayOrder: 7,
    productIds: [
      "casio-vintage-digital-a168",
      "casio-g-shock-ga-2100-casioak",
      "titan-edge-ceramic-slim-watch",
      "seiko-5-sports-automatic-watch",
      "tissot-prx-powermatic-80",
      "apple-watch-ultra-2",
      "fossil-grant-chronograph-leather-watch",
      "designer-watch",
      "minimalist-watch"
    ],
  },
  {
    id: "bags-backpacks-carry",
    title: "Bags, Backpacks & Everyday Carry",
    subtitle: "Waterproof tech bags, commuter backpacks, heavy canvas totes, and leather crossbody slings",
    badge: "🎒 Bags & Carry",
    displayOrder: 8,
    productIds: [
      "waterproof-urban-laptop-backpack",
      "travel-backpack",
      "minimalist-leather-crossbody-sling",
      "heavy-canvas-work-tote-bag",
      "leather-structure-shoulder-handbag",
      "cordura-gym-weekend-duffle-bag",
      "slim-leather-rfid-cardholder-wallet",
      "crossbody-bag-men",
      "everyday-backpack"
    ],
  },
  {
    id: "activewear-sportswear",
    title: "Activewear & Sportswear",
    subtitle: "High-performance moisture-wicking tees, training joggers, marathon running shoes, and gym gear",
    badge: "🏃 Sportswear",
    displayOrder: 9,
    productIds: [
      "nike-dri-fit-training-t-shirt",
      "adidas-tiro-training-track-pants",
      "nike-air-max-plus",
      "nike-running-shoes",
      "adidas-ultraboost-light",
      "on-cloudmonster-2",
      "under-armour-heatgear-compression-top",
      "puma-drycell-running-shorts",
      "cordura-gym-weekend-duffle-bag",
    ],
  },
  {
    id: "premium-luxury-statements",
    title: "Premium & Luxury Statements",
    subtitle: "Heritage tailoring, premium leather goods, virgin wool blazers, and iconic designer silhouettes",
    badge: "👑 Luxury",
    displayOrder: 10,
    productIds: [
      "ralph-lauren-custom-fit-oxford",
      "tommy-hilfiger-yacht-bomber-jacket",
      "coach-leather-tabby-shoulder-bag",
      "hugo-boss-virgin-wool-blazer",
      "calvin-klein-minimalist-monogram-tee",
      "tissot-prx-powermatic-80",
      "traditional-bandhgala-suit",
    ],
  },
  {
    id: "footwear-beyond-sneakers",
    title: "Footwear Beyond Sneakers",
    subtitle: "Suede penny loafers, leather Chelsea boots, handcrafted mojaris, and elevated clogs",
    badge: "👞 Footwear",
    displayOrder: 11,
    productIds: [
      "suede-penny-loafers",
      "chelsea-leather-boots",
      "birkenstock-boston-clog",
      "crocs-classic-clog",
      "chunky-platform-loafers",
      "strappy-block-heels",
      "handcrafted-kolhapuri-mojaris",
    ],
  },
  {
    id: "jewellery-accessories",
    title: "Statement Jewellery & Accessories",
    subtitle: "Cuban link chains, signet rings, tinted sunglasses, baseball caps, and full-grain leather belts",
    badge: "💍 Accessories",
    displayOrder: 12,
    productIds: [
      "vintage-retro-tinted-sunglasses",
      "sunglasses",
      "cuban-link-stainless-steel-chain",
      "minimalist-silver-signet-ring",
      "unstructured-dad-cap",
      "full-grain-leather-pin-buckle-belt",
      "slim-leather-rfid-cardholder-wallet",
      "leather-wallet",
      "classic-belt",
      "cap-classic"
    ],
  },
  {
    id: "tops-hoodies-layers",
    title: "Casual Tops, Hoodies & Layers",
    subtitle: "Heavyweight tees, relaxed flannels, corduroy overshirts, and zip hoodies",
    badge: "👕 Tops & Layers",
    displayOrder: 13,
    productIds: [
      "heavyweight-oversized-graphic-tee",
      "boxy-drop-shoulder-hoodie",
      "oversized-hoodie",
      "flannel-plaid-overshirt",
      "corduroy-zip-overshirt",
      "crewneck-minimalist-sweatshirt",
      "knit-boxy-cardigan",
      "basic-heavyweight-t-shirt",
      "zip-up-hoodie",
      "flannel-checkered-shirt",
      "overshirt-men"
    ],
  },
  {
    id: "bottoms-cargos-denims",
    title: "Bottoms: Cargos, Denims & Relaxed Fits",
    subtitle: "Baggy 90s skater cuts, selvedge straight leg jeans, utilitarian cargos, and tailored pleats",
    badge: "👖 Bottoms",
    displayOrder: 14,
    productIds: [
      "relaxed-fit-utilitarian-cargo-pants",
      "levis-501-original-straight-jeans",
      "baggy-90s-skater-jeans",
      "pleated-tailored-smart-trousers",
      "wide-leg-high-waist-trousers",
      "slim-tapered-stretch-chinos",
      "everyday-cotton-drawstring-shorts",
      "wide-leg-jeans-mens",
      "carpenter-pants"
    ],
  },
  {
    id: "budget-wardrobe-essentials",
    title: "Student & Budget Wardrobe Essentials",
    subtitle: "High-value foundational basics, everyday canvas kicks, durable backpacks, and classic tees",
    badge: "💰 Budget Picks",
    displayOrder: 15,
    productIds: [
      "basic-heavyweight-t-shirt",
      "converse-chuck-70-vintage",
      "vans-old-skool-classic",
      "everyday-cotton-drawstring-shorts",
      "casio-vintage-digital-a168",
      "heavy-canvas-work-tote-bag",
      "unstructured-dad-cap",
    ],
  },
  {
    id: "creator-aesthetic",
    title: "Creator Aesthetic (Signature Looks)",
    subtitle: "Curated statement pieces for creators building a distinctive on-camera and street persona",
    badge: "📸 Creator Style",
    displayOrder: 16,
    productIds: [
      "vintage-retro-tinted-sunglasses",
      "varsity-bomber-jacket",
      "statement-jacket",
      "boxy-drop-shoulder-hoodie",
      "adidas-samba-og",
      "nike-air-jordan-1-retro-high",
      "tissot-prx-powermatic-80",
      "minimalist-leather-crossbody-sling",
      "cuban-link-stainless-steel-chain",
    ],
  },
  {
    id: "ipl-sports-jerseys",
    title: "IPL & Sports Jerseys",
    subtitle: "Official match-day jerseys from IPL franchises and European football giants",
    badge: "🏏 Jerseys",
    displayOrder: 17,
    productIds: [
      "rcb-ipl-jersey",
      "mumbai-indians-ipl-jersey",
      "csk-ipl-jersey",
      "fc-barcelona-jersey",
      "real-madrid-jersey"
    ],
  },
  {
    id: "womens-footwear",
    title: "Women's Footwear",
    subtitle: "Trending sneakers, ballet flats, Mary Janes, platforms, heels, and everyday sandals",
    badge: "👡 Women's Footwear",
    displayOrder: 18,
    productIds: [
      "adidas-samba-womens",
      "adidas-gazelle-womens",
      "nike-dunk-low-womens",
      "new-balance-550-womens",
      "ballet-flats",
      "mary-jane-shoes",
      "platform-sneakers-womens",
      "chunky-sneakers-womens",
      "heels-stiletto",
      "everyday-sandals-womens"
    ],
  },
  {
    id: "womens-indian-ethnic",
    title: "Women's Indian & Ethnic Wear",
    subtitle: "Kurta sets, Anarkali suits, sarees, pre-draped sarees, and handcrafted ethnic jewellery",
    badge: "🥻 Ethnic",
    displayOrder: 19,
    productIds: [
      "kurta-set-womens",
      "anarkali-set",
      "co-ord-ethnic-set",
      "pre-draped-saree",
      "silk-saree",
      "lehenga-festive",
      "statement-dupatta",
      "jhumka-earrings",
      "oxidised-jewellery-set",
      "minimal-gold-jewellery"
    ],
  },
  {
    id: "womens-accessories",
    title: "Women's Bags, Jewellery & Accessories",
    subtitle: "Shoulder bags, tote bags, mini bags, scrunchies, claw clips, stacking rings, and layered necklaces",
    badge: "👜 Accessories",
    displayOrder: 20,
    productIds: [
      "shoulder-bag-womens",
      "tote-bag-womens",
      "mini-bag-womens",
      "crossbody-bag-womens",
      "sling-bag-womens",
      "baguette-bag",
      "sunglasses-cat-eye",
      "cap-womens",
      "hair-accessories-set",
      "scrunchies-set",
      "claw-clip-set",
      "belt-womens",
      "minimal-rings-set",
      "bracelet-chain",
      "layered-necklace",
      "earrings-hoop",
      "earrings-statement",
      "sunglasses-retro-womens"
    ],
  }
];

/** Full list of Fashion products */
export const RAW_FASHION_PRODUCTS: Array<{
  id: string;
  name: string;
  brand: string;
  subcategory: string;
  sectionId: string;
  sectionTitle: string;
  description: string;
  tags: string[];
  badge?: "HOT" | "TRENDING" | "NEW" | "POPULAR" | "PREMIUM" | "BESTSELLER";
  featured?: boolean;
  trending?: boolean;
}> = [
  // === EXISTING 53 PRODUCTS ===
  {
    id: "nike-air-jordan-1-retro-high",
    name: "Air Jordan 1 Retro High OG",
    brand: "Jordan",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "The timeless hardwood icon with premium leather upper, encapsulated Air-Sole cushioning, and signature Wings logo.",
    tags: ["nike", "jordan", "aj1", "sneakers", "streetwear", "high-top", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "air-jordan-1",
    name: "Air Jordan 1",
    brand: "Jordan",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "Classic high-top silhouette crafted with durable leather panels and heritage court traction.",
    tags: ["jordan", "sneakers", "lifestyle"],
  },
  {
    id: "nike-dunk-low-retro",
    name: "Nike Dunk Low Retro 'Panda'",
    brand: "Nike",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "Unmistakable monochromatic colorblocking with padded collar, foam midsole, and durable rubber outsole.",
    tags: ["nike", "dunk", "panda", "sneakers", "streetwear", "bestseller"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "nike-air-force-1-07",
    name: "Nike Air Force 1 '07",
    brand: "Nike",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "Crisp all-white leather upper with stitched overlays, perforations on the toe, and classic Nike Air cushioning.",
    tags: ["nike", "af1", "air-force", "sneakers", "white-sneakers", "essential"],
    badge: "BESTSELLER",
  },
  {
    id: "nike-air-max-plus",
    name: "Nike Air Max Plus TN",
    brand: "Nike",
    subcategory: "Sneakers",
    sectionId: "activewear-sportswear",
    sectionTitle: "Activewear & Sportswear",
    description: "Prominent arch inspired by a whale's tail with breathable gradient mesh and revolutionary Tuned Air units.",
    tags: ["nike", "air-max", "tn", "running", "sportswear"],
    badge: "TRENDING",
  },
  {
    id: "nike-running-shoes",
    name: "Nike Running Shoes",
    brand: "Nike",
    subcategory: "Footwear",
    sectionId: "activewear-sportswear",
    sectionTitle: "Activewear & Sportswear",
    description: "Responsive everyday performance running footwear engineered for breathability and energy return.",
    tags: ["nike", "running", "shoes", "sportswear"],
  },
  {
    id: "adidas-samba-og",
    name: "Adidas Samba OG",
    brand: "Adidas",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "The global terrace trendsetter featuring low-profile leather upper, suede T-toe overlay, and iconic gum rubber sole.",
    tags: ["adidas", "samba", "terrace", "sneakers", "streetwear", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "adidas-gazelle-indoor",
    name: "Adidas Gazelle Indoor",
    brand: "Adidas",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "Vintage indoor training shoe with rich suede construction, translucent gum wrap sole, and gold-foil Gazelle branding.",
    tags: ["adidas", "gazelle", "suede", "sneakers"],
    badge: "POPULAR",
  },
  {
    id: "adidas-originals-campus-00s",
    name: "Adidas Originals Campus 00s",
    brand: "Adidas",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "Chunky Y2K skate proportions with plush padded tongue, fat laces, and soft suede upper.",
    tags: ["adidas", "campus", "y2k", "skate", "sneakers"],
    badge: "TRENDING",
  },
  {
    id: "adidas-originals",
    name: "Adidas Originals",
    brand: "Adidas",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "Heritage sportswear kicks carrying the iconic 3-Stripes legacy for easy streetwear styling.",
    tags: ["adidas", "originals", "sneakers"],
  },
  {
    id: "adidas-ultraboost-light",
    name: "Adidas Ultraboost Light",
    brand: "Adidas",
    subcategory: "Sportswear",
    sectionId: "activewear-sportswear",
    sectionTitle: "Activewear & Sportswear",
    description: "30% lighter Light BOOST cushioning with Primeknit+ upper for supreme comfort on long days and runs.",
    tags: ["adidas", "ultraboost", "running", "comfort", "sportswear"],
  },
  {
    id: "new-balance-550",
    name: "New Balance 550",
    brand: "New Balance",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "Retro 1989 basketball low-top with clean streamlined leather construction and vintage aesthetic.",
    tags: ["new-balance", "nb550", "sneakers", "retro", "streetwear"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "new-balance-9060",
    name: "New Balance 9060",
    brand: "New Balance",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "Futuristic sculpted silhouette combining 990-series heritage with Y2K exaggerated ABZORB pods.",
    tags: ["new-balance", "nb9060", "chunky", "sneakers", "trending"],
    badge: "HOT",
  },
  {
    id: "new-balance-1906r",
    name: "New Balance 1906R",
    brand: "New Balance",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "Technical runner aesthetic with N-ergy shock absorption and Stability Web arch support.",
    tags: ["new-balance", "1906r", "gorpcore", "runner", "sneakers"],
  },
  {
    id: "asics-gel-kayano-14",
    name: "ASICS GEL-Kayano 14",
    brand: "Asics",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "Late 2000s technical runner with metallic synthetic overlays, open mesh, and signature GEL cushioning.",
    tags: ["asics", "gel-kayano", "metallic", "running", "streetwear", "trending"],
    badge: "HOT",
    featured: true,
  },
  {
    id: "asics-gel-nyc",
    name: "ASICS GEL-NYC",
    brand: "Asics",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "Heritage fusion borrowing from GEL-NIMBUS 3 and MC-PLUS V with ultra-cushioned midsole.",
    tags: ["asics", "gel-nyc", "lifestyle", "sneakers"],
  },
  {
    id: "puma-palermo-leather",
    name: "Puma Palermo Leather",
    brand: "Puma",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "Iconic 80s terrace shoe with signature signature Formstrip and gold Puma Palermo tag.",
    tags: ["puma", "palermo", "terrace", "sneakers"],
    badge: "NEW",
  },
  {
    id: "puma-suede-classic",
    name: "Puma Suede Classic XXI",
    brand: "Puma",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "Full suede upper with comfortable sockliner and clean street-ready profile.",
    tags: ["puma", "suede", "classic", "sneakers"],
  },
  {
    id: "converse-chuck-70-vintage",
    name: "Converse Chuck 70 Vintage Canvas",
    brand: "Converse",
    subcategory: "Sneakers",
    sectionId: "budget-wardrobe-essentials",
    sectionTitle: "Student & Budget Wardrobe Essentials",
    description: "Heavier 12oz canvas, higher rubber foxing, and cushioned OrthoLite insole for all-day comfort.",
    tags: ["converse", "chuck70", "high-top", "canvas", "classic", "budget"],
    badge: "POPULAR",
  },
  {
    id: "vans-old-skool-classic",
    name: "Vans Old Skool Classic Skate Shoes",
    brand: "Vans",
    subcategory: "Sneakers",
    sectionId: "budget-wardrobe-essentials",
    sectionTitle: "Student & Budget Wardrobe Essentials",
    description: "Durable suede and canvas uppers with the timeless Vans side stripe and signature waffle outsole.",
    tags: ["vans", "old-skool", "skate", "sneakers", "budget"],
  },
  {
    id: "on-cloudmonster-2",
    name: "On Cloudmonster 2",
    brand: "On",
    subcategory: "Sportswear",
    sectionId: "activewear-sportswear",
    sectionTitle: "Activewear & Sportswear",
    description: "Monster-level CloudTec cushioning with Helion superfoam and explosive Speedboard propulsion.",
    tags: ["on", "cloudmonster", "running", "cushioning", "premium"],
    badge: "NEW",
  },
  {
    id: "sneakers",
    name: "Sneakers",
    brand: "Plugd Footwear",
    subcategory: "Sneakers",
    sectionId: "sneaker-culture",
    sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)",
    description: "A fresh pair of lifestyle sneakers curated for daily wear and modern outfits.",
    tags: ["sneakers", "footwear", "streetwear"],
  },
  {
    id: "birkenstock-boston-clog",
    name: "Birkenstock Boston Suede Leather Clogs",
    brand: "Birkenstock",
    subcategory: "Footwear",
    sectionId: "footwear-beyond-sneakers",
    sectionTitle: "Footwear Beyond Sneakers (Loafers, Boots, Mojaris)",
    description: "Velvety suede upper with anatomically shaped cork-latex footbed and adjustable metal pin buckle.",
    tags: ["birkenstock", "boston", "clog", "suede", "comfortable", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "crocs-classic-clog",
    name: "Crocs Classic Clog",
    brand: "Crocs",
    subcategory: "Footwear",
    sectionId: "footwear-beyond-sneakers",
    sectionTitle: "Footwear Beyond Sneakers (Loafers, Boots, Mojaris)",
    description: "Lightweight Croslite construction with ventilation ports and pivoting heel straps.",
    tags: ["crocs", "clogs", "slides", "casual", "waterproof"],
  },
  {
    id: "chelsea-leather-boots",
    name: "Full-Grain Leather Chelsea Boots",
    brand: "Clarks",
    subcategory: "Footwear",
    sectionId: "footwear-beyond-sneakers",
    sectionTitle: "Footwear Beyond Sneakers (Loafers, Boots, Mojaris)",
    description: "Handcrafted burnished leather with elastic side gussets, pull tabs, and Goodyear welted sole.",
    tags: ["boots", "chelsea", "leather", "formal", "menswear"],
    badge: "POPULAR",
  },
  {
    id: "suede-penny-loafers",
    name: "Italian Suede Penny Loafers",
    brand: "Massimo Dutti",
    subcategory: "Footwear",
    sectionId: "footwear-beyond-sneakers",
    sectionTitle: "Footwear Beyond Sneakers (Loafers, Boots, Mojaris)",
    description: "Supple suede slip-on loafers with saddle strap detail and leather-wrapped insole.",
    tags: ["loafers", "suede", "menswear", "smart-casual"],
  },
  {
    id: "chunky-platform-loafers",
    name: "Chunky Lug-Sole Platform Loafers",
    brand: "Zara",
    subcategory: "Footwear",
    sectionId: "footwear-beyond-sneakers",
    sectionTitle: "Footwear Beyond Sneakers (Loafers, Boots, Mojaris)",
    description: "Statement platform sole with polished upper and horsebit metallic hardware.",
    tags: ["loafers", "platform", "womens", "chunky", "trending"],
  },
  {
    id: "strappy-block-heels",
    name: "Minimalist Strappy Block Heels",
    brand: "Mango",
    subcategory: "Footwear",
    sectionId: "footwear-beyond-sneakers",
    sectionTitle: "Footwear Beyond Sneakers (Loafers, Boots, Mojaris)",
    description: "Square-toe silhouette with slender ankle straps and stable mid-height block heel.",
    tags: ["heels", "block-heels", "sandals", "womens", "party"],
  },
  {
    id: "handcrafted-kolhapuri-mojaris",
    name: "Handcrafted Leather Kolhapuri Mojaris",
    brand: "FabIndia",
    subcategory: "Ethnic Wear",
    sectionId: "indian-ethnic-festive",
    sectionTitle: "Indian & Festive Ethnic Wear",
    description: "Authentic vegetable-tanned leather traditional Indian juttis with braided embellishments.",
    tags: ["kolhapuri", "mojari", "juttis", "ethnic-footwear", "festive"],
    badge: "POPULAR",
  },
  {
    id: "heavyweight-oversized-graphic-tee",
    name: "240 GSM Heavyweight Oversized Graphic Tee",
    brand: "H&M",
    subcategory: "T-Shirts",
    sectionId: "streetwear-creator-fits",
    sectionTitle: "Streetwear & Creator Fits",
    description: "Dense 100% combed cotton jersey with dropped shoulders, ribbed crewneck, and vintage wash screenprint.",
    tags: ["t-shirt", "oversized", "graphic-tee", "streetwear", "heavyweight", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "boxy-drop-shoulder-hoodie",
    name: "400 GSM Boxy Drop-Shoulder Fleece Hoodie",
    brand: "Zara",
    subcategory: "Streetwear",
    sectionId: "streetwear-creator-fits",
    sectionTitle: "Streetwear & Creator Fits",
    description: "Ultra-heavy French terry cotton with double-layered hood, hidden kangaroo pocket, and relaxed cropped hem.",
    tags: ["hoodie", "fleece", "oversized", "streetwear", "creator-fit"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "oversized-hoodie",
    name: "Oversized Hoodie",
    brand: "Plugd Street",
    subcategory: "Streetwear",
    sectionId: "streetwear-creator-fits",
    sectionTitle: "Streetwear & Creator Fits",
    description: "Comfort-first wardrobe essential hoodie tailored with relaxed drop shoulders.",
    tags: ["hoodie", "oversized", "comfort"],
  },
  {
    id: "varsity-bomber-jacket",
    name: "Retro Wool-Blend Varsity Bomber Jacket",
    brand: "Tommy Hilfiger",
    subcategory: "Streetwear",
    sectionId: "streetwear-creator-fits",
    sectionTitle: "Streetwear & Creator Fits",
    description: "Classic collegiate aesthetic with contrast vegan leather sleeves, chenille chest patch, and striped ribbed trims.",
    tags: ["varsity", "jacket", "bomber", "streetwear", "creator-style"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "statement-jacket",
    name: "Statement Jacket",
    brand: "Plugd Outerwear",
    subcategory: "Streetwear",
    sectionId: "streetwear-creator-fits",
    sectionTitle: "Streetwear & Creator Fits",
    description: "A bold layer for content creation, travel, and signature outfit building.",
    tags: ["jacket", "outerwear", "statement"],
  },
  {
    id: "flannel-plaid-overshirt",
    name: "Brushed Cotton Plaid Flannel Overshirt",
    brand: "Uniqlo",
    subcategory: "Shirts",
    sectionId: "tops-hoodies-layers",
    sectionTitle: "Casual Tops, Hoodies & Layers",
    description: "Thick double-brushed cotton in a heritage buffalo check pattern, perfect for open layering over tees.",
    tags: ["flannel", "overshirt", "plaid", "layering", "autumn"],
  },
  {
    id: "vintage-washed-denim-jacket",
    name: "Levi's Trucker Denim Jacket",
    brand: "Levi's",
    subcategory: "Streetwear",
    sectionId: "streetwear-creator-fits",
    sectionTitle: "Streetwear & Creator Fits",
    description: "Original 1967 silhouette in rugged non-stretch cotton denim with button-flap chest pockets and side waist adjusters.",
    tags: ["levis", "denim-jacket", "trucker", "streetwear", "classic"],
    badge: "BESTSELLER",
  },
  {
    id: "corduroy-zip-overshirt",
    name: "Fine Wale Corduroy Zip Overshirt",
    brand: "Mango",
    subcategory: "Shirts",
    sectionId: "tops-hoodies-layers",
    sectionTitle: "Casual Tops, Hoodies & Layers",
    description: "Tactile textured corduroy with silver two-way zipper and clean spread collar.",
    tags: ["corduroy", "overshirt", "jacket", "smart-casual"],
  },
  {
    id: "crewneck-minimalist-sweatshirt",
    name: "Minimalist Loopback Cotton Crewneck",
    brand: "Uniqlo",
    subcategory: "Tops",
    sectionId: "tops-hoodies-layers",
    sectionTitle: "Casual Tops, Hoodies & Layers",
    description: "Clean silhouette in premium Japanese loopback terry cotton for effortless daily layering.",
    tags: ["sweatshirt", "crewneck", "minimalist", "basics"],
  },
  {
    id: "knit-boxy-cardigan",
    name: "Textured Knit Boxy Button Cardigan",
    brand: "Zara",
    subcategory: "Tops",
    sectionId: "tops-hoodies-layers",
    sectionTitle: "Casual Tops, Hoodies & Layers",
    description: "Chunky knit ribbed structure with tortoiseshell buttons and contemporary drop-shoulder fit.",
    tags: ["cardigan", "knitwear", "vintage", "autumn"],
  },
  {
    id: "basic-heavyweight-t-shirt",
    name: "Supima Cotton Heavyweight Crewneck Tee",
    brand: "Uniqlo",
    subcategory: "T-Shirts",
    sectionId: "budget-wardrobe-essentials",
    sectionTitle: "Student & Budget Wardrobe Essentials",
    description: "100% extra-long staple Supima cotton providing silky smoothness and shape retention wash after wash.",
    tags: ["t-shirt", "supima", "basics", "essential", "budget"],
    badge: "BESTSELLER",
  },
  {
    id: "pima-cotton-polo-shirt",
    name: "Tailored Pima Cotton Polo Shirt",
    brand: "Lacoste",
    subcategory: "T-Shirts",
    sectionId: "mens-style-essentials",
    sectionTitle: "Men's Style & Everyday Essentials",
    description: "Breathable petit piqué cotton with ribbed collar, mother-of-pearl buttons, and embroidered crocodile logo.",
    tags: ["polo", "lacoste", "smart-casual", "menswear"],
    badge: "POPULAR",
  },
  {
    id: "pure-linen-resort-shirt",
    name: "Pure European Linen Resort Collar Shirt",
    brand: "Westside",
    subcategory: "Shirts",
    sectionId: "mens-style-essentials",
    sectionTitle: "Men's Style & Everyday Essentials",
    description: "Lightweight, airy linen tailored with a modern Cuban camp collar for warm-weather styling.",
    tags: ["linen", "shirt", "cuban-collar", "resort", "summer"],
    badge: "POPULAR",
  },
  {
    id: "tailored-oxford-cotton-shirt",
    name: "Classic Oxford Cloth Button-Down Shirt",
    brand: "Ralph Lauren",
    subcategory: "Shirts",
    sectionId: "mens-style-essentials",
    sectionTitle: "Men's Style & Everyday Essentials",
    description: "Durable basketweave Oxford cotton with button-down collar and box pleat for timeless smart dressing.",
    tags: ["oxford", "shirt", "button-down", "formal", "smart"],
  },
  {
    id: "relaxed-fit-utilitarian-cargo-pants",
    name: "Multi-Pocket Utilitarian Relaxed Cargo Pants",
    brand: "H&M",
    subcategory: "Trousers",
    sectionId: "streetwear-creator-fits",
    sectionTitle: "Streetwear & Creator Fits",
    description: "Durable cotton twill with deep 3D bellows pockets, reinforced knee stitching, and adjustable drawstring ankle cuffs.",
    tags: ["cargos", "pants", "streetwear", "utilitarian", "gorpcore", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "levis-501-original-straight-jeans",
    name: "Levi's 501 Original Straight Fit Jeans",
    brand: "Levi's",
    subcategory: "Jeans",
    sectionId: "mens-style-essentials",
    sectionTitle: "Men's Style & Everyday Essentials",
    description: "The original blueprint denim featuring iconic button fly, straight leg, and authentic raw selvedge finish.",
    tags: ["levis", "501", "jeans", "denim", "straight-leg", "bestseller"],
    badge: "BESTSELLER",
    featured: true,
  },
  {
    id: "baggy-90s-skater-jeans",
    name: "90s Baggy Wide-Leg Skater Jeans",
    brand: "Zara",
    subcategory: "Jeans",
    sectionId: "bottoms-cargos-denims",
    sectionTitle: "Bottoms: Cargos, Denims & Relaxed Fits",
    description: "Generous loose cut through the seat and thigh with vintage stone wash effect stacking perfectly on sneakers.",
    tags: ["jeans", "baggy", "90s", "skate", "streetwear"],
    badge: "POPULAR",
  },
  {
    id: "pleated-tailored-smart-trousers",
    name: "Double-Pleated Tailored Wide Trousers",
    brand: "Mango",
    subcategory: "Trousers",
    sectionId: "mens-style-essentials",
    sectionTitle: "Men's Style & Everyday Essentials",
    description: "Draped wool-blend fabric with clean front double pleats, concealed hook fastening, and fluid drape.",
    tags: ["trousers", "pleated", "tailored", "old-money", "smart-casual"],
    badge: "POPULAR",
  },
  {
    id: "wide-leg-high-waist-trousers",
    name: "High-Waist Fluid Wide-Leg Trousers",
    brand: "Zara",
    subcategory: "Trousers",
    sectionId: "womens-contemporary-edit",
    sectionTitle: "Women's Edit & Contemporary Silhouettes",
    description: "High-rise tailored waistband flowing into a floor-skimming wide-leg silhouette with front pressed creases.",
    tags: ["trousers", "wide-leg", "high-waist", "womens", "elegant"],
  },
  {
    id: "slim-tapered-stretch-chinos",
    name: "Stretch Cotton Slim Tapered Chinos",
    brand: "Uniqlo",
    subcategory: "Trousers",
    sectionId: "mens-style-essentials",
    sectionTitle: "Men's Style & Everyday Essentials",
    description: "High-density twill with 2-way stretch providing all-day comfort for work and evening wear.",
    tags: ["chinos", "trousers", "stretch", "workwear"],
  },
  {
    id: "everyday-cotton-drawstring-shorts",
    name: "Relaxed French Terry Drawstring Shorts",
    brand: "H&M",
    subcategory: "Trousers",
    sectionId: "bottoms-cargos-denims",
    sectionTitle: "Bottoms: Cargos, Denims & Relaxed Fits",
    description: "Comfort-stretch elasticated waist with custom drawcords and side welt pockets.",
    tags: ["shorts", "cotton", "casual", "summer", "lounge"],
  },
  {
    id: "satin-slip-midi-dress",
    name: "Bias-Cut Silk-Satin Slip Midi Dress",
    brand: "Mango",
    subcategory: "Dresses",
    sectionId: "womens-contemporary-edit",
    sectionTitle: "Women's Edit & Contemporary Silhouettes",
    description: "Fluid bias-cut satin draping naturally along body contours with delicate adjustable spaghetti straps.",
    tags: ["dress", "slip-dress", "satin", "midi", "evening", "party", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "fluid-linen-summer-maxi-dress",
    name: "Tiered Pure Linen Summer Maxi Dress",
    brand: "Westside",
    subcategory: "Dresses",
    sectionId: "womens-contemporary-edit",
    sectionTitle: "Women's Edit & Contemporary Silhouettes",
    description: "Airy pure linen with tiered skirt volume, sweetheart neckline, and smocked back detailing.",
    tags: ["dress", "maxi", "linen", "summer", "vacation"],
    badge: "POPULAR",
  },
  {
    id: "oversized-structured-blazer",
    name: "Oversized Double-Breasted Tailored Blazer",
    brand: "Zara",
    subcategory: "Tops",
    sectionId: "womens-contemporary-edit",
    sectionTitle: "Women's Edit & Contemporary Silhouettes",
    description: "Structured shoulder pads, peak lapels, and tortoiseshell double-breasted buttons for power dressing.",
    tags: ["blazer", "tailored", "oversized", "workwear", "streetwear"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "ribbed-knit-seamless-crop-top",
    name: "Seamless Ribbed High-Neck Crop Top",
    brand: "H&M",
    subcategory: "Tops",
    sectionId: "womens-contemporary-edit",
    sectionTitle: "Women's Edit & Contemporary Silhouettes",
    description: "Form-fitting four-way stretch ribbed knit with high cutaway neckline.",
    tags: ["crop-top", "ribbed", "seamless", "basics", "layering"],
  },
  {
    id: "floral-wrap-mini-dress",
    name: "Printed Crepe Floral Wrap Mini Dress",
    brand: "Zara",
    subcategory: "Dresses",
    sectionId: "womens-contemporary-edit",
    sectionTitle: "Women's Edit & Contemporary Silhouettes",
    description: "Flattering adjustable side tie with ruffle hemline and V-neckline.",
    tags: ["dress", "wrap-dress", "floral", "mini", "party"],
  },
  {
    id: "cotton-poplin-oversized-shirt",
    name: "Crisp Cotton Poplin Oversized Boyfriend Shirt",
    brand: "Mango",
    subcategory: "Shirts",
    sectionId: "womens-contemporary-edit",
    sectionTitle: "Women's Edit & Contemporary Silhouettes",
    description: "Generous boyfriend cut in crisp poplin cotton with curved high-low hem.",
    tags: ["shirt", "poplin", "oversized", "capsule-wardrobe"],
  },
  {
    id: "handloom-banarasi-silk-saree",
    name: "Handloom Pure Katan Banarasi Silk Saree",
    brand: "FabIndia",
    subcategory: "Ethnic Wear",
    sectionId: "indian-ethnic-festive",
    sectionTitle: "Indian & Festive Ethnic Wear",
    description: "Heirloom-grade handwoven Banarasi silk with intricate golden Zari floral Kadwa motifs and rich pallu.",
    tags: ["saree", "banarasi", "silk", "handloom", "ethnic", "wedding", "festive", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "chikankari-embroidered-cotton-kurta",
    name: "Handcrafted Lucknowi Chikankari Kurta",
    brand: "FabIndia",
    subcategory: "Ethnic Wear",
    sectionId: "indian-ethnic-festive",
    sectionTitle: "Indian & Festive Ethnic Wear",
    description: "Breezy mulmul cotton adorned with delicate handcrafted Bakhiya and Phanda thread embroidery.",
    tags: ["kurta", "chikankari", "cotton", "ethnic", "summer", "bestseller"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "chanderi-silk-anarkali-suit-set",
    name: "Chanderi Silk Anarkali Kurta Set with Dupatta",
    brand: "FabIndia",
    subcategory: "Ethnic Wear",
    sectionId: "indian-ethnic-festive",
    sectionTitle: "Indian & Festive Ethnic Wear",
    description: "Flared Kalidar Anarkali silhouette with Gota Patti trims, straight pants, and lightweight organza dupatta.",
    tags: ["anarkali", "kurta-set", "chanderi", "ethnic", "festive"],
    badge: "POPULAR",
  },
  {
    id: "raw-silk-festive-nehru-jacket",
    name: "Woven Raw Silk Tailored Nehru Jacket",
    brand: "Manyavar",
    subcategory: "Ethnic Wear",
    sectionId: "indian-ethnic-festive",
    sectionTitle: "Indian & Festive Ethnic Wear",
    description: "Structured mandarin collar sleeveless bandhgala jacket with metallic buttons and welt pocket.",
    tags: ["nehru-jacket", "bandhgala", "ethnic", "menswear", "festive"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "designer-embroidered-lehenga-choli",
    name: "Raw Silk Embroidered Bridal Lehenga Set",
    brand: "Manyavar",
    subcategory: "Ethnic Wear",
    sectionId: "indian-ethnic-festive",
    sectionTitle: "Indian & Festive Ethnic Wear",
    description: "Voluminous flared skirt with heavy Zardozi hand-embroidery, padded blouse, and netted dupatta.",
    tags: ["lehenga", "bridal", "festive", "ethnic", "luxury"],
    badge: "PREMIUM",
  },
  {
    id: "mens-silk-blend-kurta-pajama-set",
    name: "Jacquard Silk Blend Festive Kurta Pajama",
    brand: "Manyavar",
    subcategory: "Ethnic Wear",
    sectionId: "indian-ethnic-festive",
    sectionTitle: "Indian & Festive Ethnic Wear",
    description: "Rich woven jacquard pattern kurta with mandarin collar and churidar pajama.",
    tags: ["kurta", "kurta-set", "ethnic", "menswear", "diwali"],
  },
  {
    id: "traditional-bandhgala-suit",
    name: "Bespoke Royal Bandhgala Jodhpuri Suit",
    brand: "Manyavar",
    subcategory: "Ethnic Wear",
    sectionId: "indian-ethnic-festive",
    sectionTitle: "Indian & Festive Ethnic Wear",
    description: "Impeccably tailored closed-collar jacket with tonal trousers for formal royal heritage occasions.",
    tags: ["bandhgala", "jodhpuri", "suit", "ethnic", "luxury"],
    badge: "PREMIUM",
  },
  {
    id: "casio-vintage-digital-a168",
    name: "Casio Vintage Digital A168WA-1",
    brand: "Casio",
    subcategory: "Watches",
    sectionId: "timepieces-watches",
    sectionTitle: "Timepieces & Iconic Watches",
    description: "The retro cultural icon featuring stainless steel band, EL backlight, 1/100s stopwatch, and daily alarm.",
    tags: ["casio", "vintage", "digital-watch", "stainless-steel", "retro", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "casio-g-shock-ga-2100-casioak",
    name: "Casio G-Shock GA-2100 'CasiOak'",
    brand: "G-Shock",
    subcategory: "Watches",
    sectionId: "timepieces-watches",
    sectionTitle: "Timepieces & Iconic Watches",
    description: "Slim octagonal bezel with Carbon Core Guard structure, 200m water resistance, and shockproof durability.",
    tags: ["casio", "g-shock", "casioak", "sports-watch", "rugged", "bestseller"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "titan-edge-ceramic-slim-watch",
    name: "Titan Edge Ceramic Ultra-Slim Watch",
    brand: "Titan",
    subcategory: "Watches",
    sectionId: "timepieces-watches",
    sectionTitle: "Timepieces & Iconic Watches",
    description: "India's engineering marvel measuring just 4.4mm thin with scratch-resistant ceramic case and sapphire crystal.",
    tags: ["titan", "titan-edge", "ceramic", "slim-watch", "dress-watch", "luxury"],
    badge: "PREMIUM",
    featured: true,
  },
  {
    id: "seiko-5-sports-automatic-watch",
    name: "Seiko 5 Sports Automatic SRPD55K1",
    brand: "Seiko",
    subcategory: "Watches",
    sectionId: "timepieces-watches",
    sectionTitle: "Timepieces & Iconic Watches",
    description: "Iconic Japanese mechanical automatic movement with 41-hour power reserve, diver-style unidirectional bezel, and exhibition caseback.",
    tags: ["seiko", "seiko-5", "automatic-watch", "diver", "mechanical"],
    badge: "POPULAR",
  },
  {
    id: "tissot-prx-powermatic-80",
    name: "Tissot PRX Powermatic 80 Automatic",
    brand: "Tissot",
    subcategory: "Watches",
    sectionId: "timepieces-watches",
    sectionTitle: "Timepieces & Iconic Watches",
    description: "1978 integrated bracelet icon with 80-hour power reserve, Nivachron balance spring, and waffle dial.",
    tags: ["tissot", "prx", "swiss-watch", "automatic", "luxury", "trending"],
    badge: "HOT",
    featured: true,
  },
  {
    id: "apple-watch-ultra-2",
    name: "Apple Watch Ultra 2 Titanium",
    brand: "Apple",
    subcategory: "Watches",
    sectionId: "timepieces-watches",
    sectionTitle: "Timepieces & Iconic Watches",
    description: "49mm aerospace-grade titanium case with 3000-nit display, precision dual-frequency GPS, and 72-hour battery life.",
    tags: ["apple", "apple-watch", "ultra2", "smartwatch", "titanium"],
    badge: "HOT",
  },
  {
    id: "fossil-grant-chronograph-leather-watch",
    name: "Fossil Grant Chronograph Leather Watch",
    brand: "Fossil",
    subcategory: "Watches",
    sectionId: "timepieces-watches",
    sectionTitle: "Timepieces & Iconic Watches",
    description: "Roman numeral dial with three-subdial stopwatch and interchangeable genuine leather strap.",
    tags: ["fossil", "chronograph", "leather", "dress-watch"],
  },
  {
    id: "designer-watch",
    name: "Designer Watch",
    brand: "Plugd Time",
    subcategory: "Watches",
    sectionId: "timepieces-watches",
    sectionTitle: "Timepieces & Iconic Watches",
    description: "A polished accessory with a premium feel for everyday outfits and evening occasions.",
    tags: ["watch", "timepiece", "accessory"],
  },
  {
    id: "waterproof-urban-laptop-backpack",
    name: "Urban Roll-Top Waterproof Laptop Backpack 25L",
    brand: "Mokobara",
    subcategory: "Bags",
    sectionId: "bags-backpacks-carry",
    sectionTitle: "Bags, Backpacks & Everyday Carry",
    description: "Weatherproof matte coated fabric with dedicated 16-inch fleece laptop sleeve and luggage pass-through strap.",
    tags: ["backpack", "laptop-bag", "waterproof", "commute", "travel", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "travel-backpack",
    name: "Travel Backpack",
    brand: "Plugd Carry",
    subcategory: "Bags",
    sectionId: "bags-backpacks-carry",
    sectionTitle: "Bags, Backpacks & Everyday Carry",
    description: "A functional carry backpack engineered for work, movement, and creator travels.",
    tags: ["backpack", "travel", "carry"],
  },
  {
    id: "minimalist-leather-crossbody-sling",
    name: "Minimalist Leather Everyday Crossbody Sling",
    brand: "Zara",
    subcategory: "Bags",
    sectionId: "bags-backpacks-carry",
    sectionTitle: "Bags, Backpacks & Everyday Carry",
    description: "Compact hands-free carry crafted in supple pebbled leather with magnetic buckle and quick-access phone pocket.",
    tags: ["sling", "crossbody", "leather-bag", "streetwear", "essentials"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "heavy-canvas-work-tote-bag",
    name: "Heavy Duty 16oz Canvas Work Tote Bag",
    brand: "Uniqlo",
    subcategory: "Bags",
    sectionId: "bags-backpacks-carry",
    sectionTitle: "Bags, Backpacks & Everyday Carry",
    description: "Reinforced box-stitch handles, brass snap closures, and spacious interior organizing compartments.",
    tags: ["tote", "canvas-bag", "tote-bag", "work-bag", "student"],
  },
  {
    id: "leather-structure-shoulder-handbag",
    name: "Structured Leather Flap Shoulder Handbag",
    brand: "Mango",
    subcategory: "Bags",
    sectionId: "bags-backpacks-carry",
    sectionTitle: "Bags, Backpacks & Everyday Carry",
    description: "Clean architectural geometry with gold metallic clasp, dual strap options, and suede-lined interior.",
    tags: ["handbag", "shoulder-bag", "leather", "womens", "luxury"],
    badge: "POPULAR",
  },
  {
    id: "cordura-gym-weekend-duffle-bag",
    name: "Water-Resistant Cordura Gym & Weekend Duffle",
    brand: "Puma",
    subcategory: "Bags",
    sectionId: "bags-backpacks-carry",
    sectionTitle: "Bags, Backpacks & Everyday Carry",
    description: "Separate ventilated sneaker tunnel, padded shoulder strap, and abrasion-resistant ballistic base.",
    tags: ["duffle", "gym-bag", "weekend-bag", "travel", "sportswear"],
  },
  {
    id: "slim-leather-rfid-cardholder-wallet",
    name: "Minimalist Full-Grain Leather RFID Cardholder",
    brand: "Bellroy",
    subcategory: "Accessories",
    sectionId: "jewellery-accessories",
    sectionTitle: "Statement Jewellery & Accessories",
    description: "Slim profile holding 8 cards plus folded currency with quick-access pull tab and RFID shielding.",
    tags: ["wallet", "cardholder", "leather", "minimalist", "edc"],
  },
  {
    id: "vintage-retro-tinted-sunglasses",
    name: "Vintage 90s Tinted Acetate Sunglasses",
    brand: "Ray-Ban",
    subcategory: "Accessories",
    sectionId: "jewellery-accessories",
    sectionTitle: "Statement Jewellery & Accessories",
    description: "Glossy tortoise and black acetate frame with gradient UV400 lenses and silver metal temple rivets.",
    tags: ["sunglasses", "shades", "retro", "creator-style", "summer", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "sunglasses",
    name: "Sunglasses",
    brand: "Plugd Eyewear",
    subcategory: "Accessories",
    sectionId: "jewellery-accessories",
    sectionTitle: "Statement Jewellery & Accessories",
    description: "A versatile eyewear style upgrade for everyday outfits and travel fits.",
    tags: ["sunglasses", "eyewear", "accessory"],
  },
  {
    id: "cuban-link-stainless-steel-chain",
    name: "8mm Cuban Link Stainless Steel Chain Necklace",
    brand: "Plugd Accessories",
    subcategory: "Jewellery",
    sectionId: "jewellery-accessories",
    sectionTitle: "Statement Jewellery & Accessories",
    description: "High-polish 316L medical-grade stainless steel with custom lobster clasp, tarnish-free and sweatproof.",
    tags: ["chain", "necklace", "cuban-link", "jewellery", "streetwear"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "minimalist-silver-signet-ring",
    name: "Brushed Silver Geometric Signet Ring",
    brand: "Plugd Accessories",
    subcategory: "Jewellery",
    sectionId: "jewellery-accessories",
    sectionTitle: "Statement Jewellery & Accessories",
    description: "Clean flat-top rectangular face with brushed satin finish and comfort-fit inner band.",
    tags: ["ring", "signet-ring", "silver", "jewellery", "menswear"],
  },
  {
    id: "unstructured-dad-cap",
    name: "Washed Cotton 6-Panel Unstructured Dad Cap",
    brand: "New Era",
    subcategory: "Accessories",
    sectionId: "jewellery-accessories",
    sectionTitle: "Statement Jewellery & Accessories",
    description: "Soft washed twill with curved brim, embroidered eyelets, and adjustable brass buckle strapback.",
    tags: ["cap", "hat", "dad-cap", "streetwear", "basics"],
  },
  {
    id: "full-grain-leather-pin-buckle-belt",
    name: "Full-Grain Italian Leather Pin-Buckle Belt",
    brand: "Levi's",
    subcategory: "Accessories",
    sectionId: "jewellery-accessories",
    sectionTitle: "Statement Jewellery & Accessories",
    description: "35mm wide vegetable-tanned full grain leather with brushed nickel buckle and bevelled edges.",
    tags: ["belt", "leather-belt", "menswear", "classic"],
  },
  {
    id: "nike-dri-fit-training-t-shirt",
    name: "Nike Dri-FIT High-Ventilation Training Tee",
    brand: "Nike",
    subcategory: "Sportswear",
    sectionId: "activewear-sportswear",
    sectionTitle: "Activewear & Sportswear",
    description: "Sweat-wicking Dri-FIT fabric with mapped mesh zones to keep you cool during intense workouts.",
    tags: ["nike", "dri-fit", "gym", "workout", "sportswear", "training"],
    badge: "POPULAR",
  },
  {
    id: "adidas-tiro-training-track-pants",
    name: "Adidas Tiro 24 Performance Track Pants",
    brand: "Adidas",
    subcategory: "Sportswear",
    sectionId: "activewear-sportswear",
    sectionTitle: "Activewear & Sportswear",
    description: "Classic tapered soccer silhouette with AEROREADY moisture management and ankle zips.",
    tags: ["adidas", "tiro", "track-pants", "joggers", "sportswear"],
    badge: "BESTSELLER",
  },
  {
    id: "under-armour-heatgear-compression-top",
    name: "Under Armour HeatGear Compression Long-Sleeve",
    brand: "Under Armour",
    subcategory: "Sportswear",
    sectionId: "activewear-sportswear",
    sectionTitle: "Activewear & Sportswear",
    description: "Ultra-tight second-skin fit with 4-way stretch and anti-odor technology for athletic training.",
    tags: ["under-armour", "compression", "heatgear", "gym", "sportswear"],
  },
  {
    id: "puma-drycell-running-shorts",
    name: "Puma dryCELL 5\" Lightweight Running Shorts",
    brand: "Puma",
    subcategory: "Sportswear",
    sectionId: "activewear-sportswear",
    sectionTitle: "Activewear & Sportswear",
    description: "Built-in breathable brief liner with reflective details and zippered key pocket.",
    tags: ["puma", "running-shorts", "sportswear", "active"],
  },
  {
    id: "ralph-lauren-custom-fit-oxford",
    name: "Polo Ralph Lauren Custom Fit Oxford Shirt",
    brand: "Ralph Lauren",
    subcategory: "Luxury",
    sectionId: "premium-luxury-statements",
    sectionTitle: "Premium & Luxury Statements",
    description: "Heritage preppy staple tailored with multicoloured signature Pony embroidery and split pleated back yoke.",
    tags: ["ralph-lauren", "polo", "luxury", "oxford", "old-money", "designer"],
    badge: "PREMIUM",
    featured: true,
  },
  {
    id: "tommy-hilfiger-yacht-bomber-jacket",
    name: "Tommy Hilfiger Regatta Yachting Bomber Jacket",
    brand: "Tommy Hilfiger",
    subcategory: "Luxury",
    sectionId: "premium-luxury-statements",
    sectionTitle: "Premium & Luxury Statements",
    description: "Water-repellent technical shell with packable hood, fleece-lined collar, and signature flag branding.",
    tags: ["tommy-hilfiger", "bomber", "yachting", "outerwear", "premium"],
    badge: "POPULAR",
  },
  {
    id: "calvin-klein-minimalist-monogram-tee",
    name: "Calvin Klein Monogram Organic Cotton Tee",
    brand: "Calvin Klein",
    subcategory: "Luxury",
    sectionId: "premium-luxury-statements",
    sectionTitle: "Premium & Luxury Statements",
    description: "100% organic cotton jersey with iconic micro-monogram chest print and refined modern fit.",
    tags: ["calvin-klein", "ck", "monogram", "t-shirt", "luxury"],
  },
  {
    id: "coach-leather-tabby-shoulder-bag",
    name: "Coach Tabby 26 Polished Leather Shoulder Bag",
    brand: "Coach",
    subcategory: "Luxury",
    sectionId: "premium-luxury-statements",
    sectionTitle: "Premium & Luxury Statements",
    description: "Modern archival 1970s Coach design in structured polished pebble leather with iconic Signature C hardware.",
    tags: ["coach", "tabby", "leather-bag", "luxury", "handbag", "designer"],
    badge: "PREMIUM",
    featured: true,
  },
  {
    id: "hugo-boss-virgin-wool-blazer",
    name: "BOSS Virgin Wool Slim-Fit Tailored Suit Jacket",
    brand: "Hugo Boss",
    subcategory: "Luxury",
    sectionId: "premium-luxury-statements",
    sectionTitle: "Premium & Luxury Statements",
    description: "Finely woven Super 120s virgin wool with AMF stitching, notch lapels, and silky cupro lining.",
    tags: ["hugo-boss", "boss", "blazer", "suit", "wool", "luxury"],
    badge: "PREMIUM",
  },

  // === NEW PRODUCTS: JERSEYS / SPORTSWEAR ===
  { id: "rcb-ipl-jersey", name: "Royal Challengers Bengaluru IPL Jersey", brand: "RCB", subcategory: "Sportswear", sectionId: "ipl-sports-jerseys", sectionTitle: "IPL & Sports Jerseys", description: "Official match-day jersey with Dri-FIT fabric and team crest embroidered on chest.", tags: ["rcb", "ipl", "cricket", "jersey", "sportswear"], badge: "HOT", featured: true },
  { id: "mumbai-indians-ipl-jersey", name: "Mumbai Indians IPL Jersey", brand: "Mumbai Indians", subcategory: "Sportswear", sectionId: "ipl-sports-jerseys", sectionTitle: "IPL & Sports Jerseys", description: "Five-time champions official match jersey with moisture-wicking polyester and MI holographic badge.", tags: ["mi", "ipl", "cricket", "jersey", "sportswear"], badge: "POPULAR", featured: true },
  { id: "csk-ipl-jersey", name: "Chennai Super Kings IPL Jersey", brand: "CSK", subcategory: "Sportswear", sectionId: "ipl-sports-jerseys", sectionTitle: "IPL & Sports Jerseys", description: "Iconic yellow match jersey in breathable mesh fabric with embossed Super Kings lion crest.", tags: ["csk", "ipl", "cricket", "jersey", "sportswear"], badge: "HOT", featured: true },
  { id: "fc-barcelona-jersey", name: "FC Barcelona Home Jersey", brand: "Nike", subcategory: "Sportswear", sectionId: "ipl-sports-jerseys", sectionTitle: "IPL & Sports Jerseys", description: "Legendary blaugrana stripes in Dri-FIT ADV fabric with woven FC Barcelona crest.", tags: ["barcelona", "football", "la-liga", "jersey", "nike"], badge: "POPULAR" },
  { id: "real-madrid-jersey", name: "Real Madrid Home Jersey", brand: "Adidas", subcategory: "Sportswear", sectionId: "ipl-sports-jerseys", sectionTitle: "IPL & Sports Jerseys", description: "Classic all-white AEROREADY jersey with gold club crest and three-stripe shoulder detailing.", tags: ["real-madrid", "football", "la-liga", "jersey", "adidas"], badge: "POPULAR" },

  // === NEW PRODUCTS: ADDITIONAL SNEAKERS ===
  { id: "new-balance-2002r", name: "New Balance 2002R", brand: "New Balance", subcategory: "Sneakers", sectionId: "sneaker-culture", sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)", description: "Premium suede and mesh upper with N-ergy cushioning for retro running aesthetics.", tags: ["new-balance", "2002r", "sneakers", "retro"], badge: "TRENDING" },
  { id: "new-balance-530", name: "New Balance 530", brand: "New Balance", subcategory: "Sneakers", sectionId: "sneaker-culture", sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)", description: "Early 2000s dad-runner silhouette with ABZORB midsole cushioning and mesh-synthetic panels.", tags: ["new-balance", "530", "sneakers", "retro"], badge: "POPULAR" },
  { id: "nike-air-max-90", name: "Nike Air Max 90", brand: "Nike", subcategory: "Sneakers", sectionId: "sneaker-culture", sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)", description: "Iconic visible Air unit with waffle outsole and layered design that defined a generation of street style.", tags: ["nike", "air-max-90", "sneakers", "classic"], badge: "BESTSELLER" },
  { id: "nike-air-max-1", name: "Nike Air Max 1", brand: "Nike", subcategory: "Sneakers", sectionId: "sneaker-culture", sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)", description: "The original Air Max that started the visible air revolution with mini-swoosh and suede mudguard.", tags: ["nike", "air-max-1", "sneakers", "og"], badge: "POPULAR" },
  { id: "nike-blazer-mid-77", name: "Nike Blazer Mid '77", brand: "Nike", subcategory: "Sneakers", sectionId: "sneaker-culture", sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)", description: "Vintage basketball high-top with exposed foam on the tongue and classic oversized Swoosh.", tags: ["nike", "blazer", "sneakers", "retro"], badge: "POPULAR" },
  { id: "adidas-handball-spezial", name: "Adidas Handball Spezial", brand: "Adidas", subcategory: "Sneakers", sectionId: "sneaker-culture", sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)", description: "Heritage handball shoe with soft suede upper, gum sole, and gold-foil Trefoil branding.", tags: ["adidas", "spezial", "terrace", "sneakers", "trending"], badge: "HOT", featured: true, trending: true },
  { id: "on-cloud-5", name: "On Cloud 5", brand: "On", subcategory: "Sneakers", sectionId: "sneaker-culture", sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)", description: "Ultra-lightweight CloudTec sole with speed-lacing and recycled mesh upper for all-day wear.", tags: ["on", "cloud", "sneakers", "comfort"], badge: "NEW" },
  { id: "nike-air-max-97", name: "Nike Air Max 97", brand: "Nike", subcategory: "Sneakers", sectionId: "sneaker-culture", sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)", description: "Full-length visible Air unit with undulating design lines inspired by Japanese bullet trains.", tags: ["nike", "air-max-97", "sneakers", "silver-bullet"] },
  { id: "adidas-gazelle-bold", name: "Adidas Gazelle Bold Platform", brand: "Adidas", subcategory: "Sneakers", sectionId: "sneaker-culture", sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)", description: "Platform-elevated Gazelle with thick rubber outsole, suede upper, and serrated three-stripe mark.", tags: ["adidas", "gazelle-bold", "platform", "sneakers", "womens", "trending"], badge: "TRENDING" },
  { id: "puma-speedcat-og", name: "Puma Speedcat OG", brand: "Puma", subcategory: "Sneakers", sectionId: "sneaker-culture", sectionTitle: "Sneaker Culture (Nike, Jordan, Adidas, NB)", description: "Low-profile motorsport-inspired sneaker with slim suede upper and sleek cat-eye outsole.", tags: ["puma", "speedcat", "sneakers", "trending"], badge: "HOT" },

  // === NEW PRODUCTS: MEN'S STREETWEAR ===
  { id: "oversized-plain-tee", name: "220 GSM Oversized Plain Drop-Shoulder Tee", brand: "Bewakoof", subcategory: "T-Shirts", sectionId: "streetwear-creator-fits", sectionTitle: "Streetwear & Creator Fits", description: "Essential heavyweight cotton blank with drop shoulders and relaxed boxy fit for everyday stacking.", tags: ["t-shirt", "oversized", "plain", "basics", "streetwear"] },
  { id: "boxy-fit-tee", name: "Boxy Fit Cotton Tee", brand: "Urbanic", subcategory: "T-Shirts", sectionId: "streetwear-creator-fits", sectionTitle: "Streetwear & Creator Fits", description: "Cropped boxy cut in soft jersey cotton with ribbed crewneck for a structured minimal look.", tags: ["t-shirt", "boxy", "basics"] },
  { id: "vintage-acid-wash-tee", name: "Vintage Acid-Wash Oversized Tee", brand: "H&M", subcategory: "T-Shirts", sectionId: "streetwear-creator-fits", sectionTitle: "Streetwear & Creator Fits", description: "Heavy enzyme-washed cotton with faded graphic print and raw-cut hem for authentic vintage aesthetic.", tags: ["t-shirt", "vintage", "acid-wash", "streetwear"], badge: "TRENDING" },
  { id: "wide-leg-jeans-mens", name: "Wide-Leg Relaxed Fit Jeans", brand: "Zara", subcategory: "Jeans", sectionId: "bottoms-cargos-denims", sectionTitle: "Bottoms: Cargos, Denims & Relaxed Fits", description: "Full relaxed wide-leg cut in rigid denim with classic five-pocket construction.", tags: ["jeans", "wide-leg", "denim", "menswear"] },
  { id: "parachute-pants", name: "Nylon Parachute Cargo Pants", brand: "H&M", subcategory: "Trousers", sectionId: "streetwear-creator-fits", sectionTitle: "Streetwear & Creator Fits", description: "Lightweight crinkle nylon with toggle drawcords at ankle, elastic waist, and multiple cargo pockets.", tags: ["parachute-pants", "cargo", "nylon", "streetwear", "trending"], badge: "HOT" },
  { id: "carpenter-pants", name: "Relaxed Carpenter Work Pants", brand: "Carhartt WIP", subcategory: "Trousers", sectionId: "bottoms-cargos-denims", sectionTitle: "Bottoms: Cargos, Denims & Relaxed Fits", description: "Double-knee canvas workwear pants with hammer loop, tool pockets, and loose straight fit.", tags: ["carpenter-pants", "workwear", "carhartt", "bottoms"] },
  { id: "zip-up-hoodie", name: "Full-Zip Fleece Hoodie", brand: "Nike", subcategory: "Streetwear", sectionId: "tops-hoodies-layers", sectionTitle: "Casual Tops, Hoodies & Layers", description: "Classic brushed-back fleece full-zip with kangaroo-split pockets and embroidered Swoosh.", tags: ["hoodie", "zip-up", "nike", "basics"] },
  { id: "bomber-jacket", name: "Classic MA-1 Bomber Jacket", brand: "Alpha Industries", subcategory: "Streetwear", sectionId: "streetwear-creator-fits", sectionTitle: "Streetwear & Creator Fits", description: "Military-spec flight jacket with orange reversible lining, utility pocket on sleeve, and ribbed trims.", tags: ["bomber", "jacket", "alpha-industries", "streetwear"], badge: "POPULAR" },
  { id: "denim-jacket-classic", name: "Classic Denim Trucker Jacket", brand: "Levi's", subcategory: "Streetwear", sectionId: "streetwear-creator-fits", sectionTitle: "Streetwear & Creator Fits", description: "Iconic Type III trucker cut in rigid selvedge denim with button-flap chest pockets.", tags: ["denim-jacket", "levis", "trucker", "classic"] },
  { id: "flannel-checkered-shirt", name: "Brushed Flannel Checkered Shirt", brand: "Uniqlo", subcategory: "Shirts", sectionId: "tops-hoodies-layers", sectionTitle: "Casual Tops, Hoodies & Layers", description: "Double-brushed cotton flannel in classic buffalo check with button-down collar.", tags: ["flannel", "checkered", "shirt", "layering"] },
  { id: "oversized-shirt-men", name: "Oversized Linen Blend Shirt", brand: "Zara", subcategory: "Shirts", sectionId: "mens-style-essentials", sectionTitle: "Men's Style & Everyday Essentials", description: "Relaxed-fit camp collar shirt in breathable linen-cotton blend for casual warm-weather styling.", tags: ["shirt", "oversized", "linen", "menswear"] },
  { id: "relaxed-fit-shirt", name: "Relaxed Fit Oxford Shirt", brand: "H&M", subcategory: "Shirts", sectionId: "mens-style-essentials", sectionTitle: "Men's Style & Everyday Essentials", description: "Effortlessly relaxed cut oxford cloth button-down with rolled-cuff details.", tags: ["shirt", "relaxed", "oxford", "basics"] },
  { id: "overshirt-men", name: "Cotton Twill Overshirt Jacket", brand: "Mango", subcategory: "Shirts", sectionId: "tops-hoodies-layers", sectionTitle: "Casual Tops, Hoodies & Layers", description: "Sturdy twill overshirt with chest flap pockets and snap-button closure.", tags: ["overshirt", "jacket", "layering", "menswear"] },
  { id: "polo-tshirt-classic", name: "Classic Fit Piqué Polo Tee", brand: "Ralph Lauren", subcategory: "T-Shirts", sectionId: "mens-style-essentials", sectionTitle: "Men's Style & Everyday Essentials", description: "Signature polo in breathable mesh piqué cotton with ribbed collar and iconic pony embroidery.", tags: ["polo", "ralph-lauren", "smart-casual", "classic"], badge: "POPULAR" },
  { id: "minimalist-watch", name: "Minimalist Mesh Strap Watch", brand: "Daniel Wellington", subcategory: "Watches", sectionId: "timepieces-watches", sectionTitle: "Timepieces & Iconic Watches", description: "Ultra-thin 6mm case with eggshell dial and interchangeable Milanese mesh strap.", tags: ["watch", "minimalist", "daniel-wellington", "dressy"] },

  // === NEW PRODUCTS: MEN'S ACCESSORIES ===
  { id: "crossbody-bag-men", name: "Compact Crossbody Sling Bag", brand: "Nike", subcategory: "Bags", sectionId: "bags-backpacks-carry", sectionTitle: "Bags, Backpacks & Everyday Carry", description: "Quick-access front-zip crossbody with adjustable webbing strap and reflective detailing.", tags: ["crossbody", "sling", "bag", "streetwear"] },
  { id: "leather-wallet", name: "Bi-Fold Genuine Leather Wallet", brand: "Tommy Hilfiger", subcategory: "Accessories", sectionId: "jewellery-accessories", sectionTitle: "Statement Jewellery & Accessories", description: "Full-grain leather bifold wallet with branded hardware, RFID protection, and 6 card slots.", tags: ["wallet", "leather", "tommy-hilfiger", "accessory"] },
  { id: "classic-belt", name: "Reversible Leather Belt", brand: "Tommy Hilfiger", subcategory: "Accessories", sectionId: "jewellery-accessories", sectionTitle: "Statement Jewellery & Accessories", description: "Dual-tone reversible leather belt with brushed silver rotatable buckle.", tags: ["belt", "leather", "reversible", "accessory"] },
  { id: "everyday-backpack", name: "Urban Commuter Backpack 28L", brand: "American Tourister", subcategory: "Bags", sectionId: "bags-backpacks-carry", sectionTitle: "Bags, Backpacks & Everyday Carry", description: "Water-resistant polyester backpack with padded laptop sleeve and organizer pockets.", tags: ["backpack", "commuter", "laptop-bag", "student"] },
  { id: "cap-classic", name: "Cotton Twill Baseball Cap", brand: "Nike", subcategory: "Accessories", sectionId: "jewellery-accessories", sectionTitle: "Statement Jewellery & Accessories", description: "Six-panel structured cap with pre-curved brim and adjustable strapback closure.", tags: ["cap", "baseball", "nike", "streetwear"] },

  // === NEW PRODUCTS: WOMEN'S FOOTWEAR ===
  { id: "ballet-flats", name: "Classic Leather Ballet Flats", brand: "Zara", subcategory: "Footwear", sectionId: "womens-footwear", sectionTitle: "Women's Footwear", description: "Soft nappa leather ballerinas with cushioned insole and elegant round-toe silhouette.", tags: ["ballet-flats", "footwear", "womens", "elegant"], badge: "TRENDING" },
  { id: "mary-jane-shoes", name: "Patent Leather Mary Jane Shoes", brand: "Mango", subcategory: "Footwear", sectionId: "womens-footwear", sectionTitle: "Women's Footwear", description: "Glossy patent leather Mary Janes with adjustable strap, low block heel, and round toe.", tags: ["mary-janes", "footwear", "womens", "trending"], badge: "HOT" },
  { id: "platform-sneakers-womens", name: "Platform Canvas Sneakers", brand: "Converse", subcategory: "Footwear", sectionId: "womens-footwear", sectionTitle: "Women's Footwear", description: "Elevated platform sole on classic canvas high-top with cushioned OrthoLite insole.", tags: ["platform", "sneakers", "converse", "womens"] },
  { id: "chunky-sneakers-womens", name: "Chunky Dad Sneakers", brand: "Fila", subcategory: "Footwear", sectionId: "womens-footwear", sectionTitle: "Women's Footwear", description: "Retro oversized midsole with mixed-material upper and Fila heritage branding.", tags: ["chunky", "sneakers", "fila", "womens", "retro"] },
  { id: "heels-stiletto", name: "Pointed-Toe Stiletto Heels", brand: "Aldo", subcategory: "Footwear", sectionId: "womens-footwear", sectionTitle: "Women's Footwear", description: "Sleek patent-finish pointed-toe pump with slim 90mm stiletto heel for evening dressing.", tags: ["heels", "stiletto", "pumps", "womens", "party"], badge: "POPULAR" },
  { id: "everyday-sandals-womens", name: "Padded Strap Flat Sandals", brand: "H&M", subcategory: "Footwear", sectionId: "womens-footwear", sectionTitle: "Women's Footwear", description: "Cushioned puffy straps with contoured cork-latex footbed for all-day summer comfort.", tags: ["sandals", "flat", "casual", "womens", "summer"] },
  { id: "nike-dunk-low-womens", name: "Nike Dunk Low (Women's)", brand: "Nike", subcategory: "Sneakers", sectionId: "womens-footwear", sectionTitle: "Women's Footwear", description: "Women's exclusive colorways of the iconic Dunk Low with padded collar and foam midsole.", tags: ["nike", "dunk", "sneakers", "womens"], badge: "POPULAR" },
  { id: "adidas-samba-womens", name: "Adidas Samba OG (Women's)", brand: "Adidas", subcategory: "Sneakers", sectionId: "womens-footwear", sectionTitle: "Women's Footwear", description: "Women's sizing of the terrace classic with supple leather upper and signature gum sole.", tags: ["adidas", "samba", "sneakers", "womens", "trending"], badge: "HOT" },
  { id: "adidas-gazelle-womens", name: "Adidas Gazelle (Women's)", brand: "Adidas", subcategory: "Sneakers", sectionId: "womens-footwear", sectionTitle: "Women's Footwear", description: "Women's take on the suede terrace icon with contrast three-stripe mark and trefoil tongue tab.", tags: ["adidas", "gazelle", "sneakers", "womens"], badge: "TRENDING" },
  { id: "new-balance-550-womens", name: "New Balance 550 (Women's)", brand: "New Balance", subcategory: "Sneakers", sectionId: "womens-footwear", sectionTitle: "Women's Footwear", description: "Women's colorways of the retro basketball low-top with clean leather construction.", tags: ["new-balance", "550", "sneakers", "womens"] },

  // === NEW PRODUCTS: WOMEN'S CLOTHING ===
  { id: "baby-tee", name: "Fitted Ribbed Baby Tee", brand: "Zara", subcategory: "Tops", sectionId: "womens-contemporary-edit", sectionTitle: "Women's Edit & Contemporary Silhouettes", description: "Slim-fit cropped baby tee in soft ribbed cotton with cap sleeves.", tags: ["baby-tee", "fitted", "crop", "womens", "trending"], badge: "TRENDING" },
  { id: "crop-top-basic", name: "Cotton Crop Top", brand: "H&M", subcategory: "Tops", sectionId: "womens-contemporary-edit", sectionTitle: "Women's Edit & Contemporary Silhouettes", description: "Essential cropped silhouette in soft jersey cotton with a clean round neckline.", tags: ["crop-top", "basics", "womens"] },
  { id: "ribbed-tank-top", name: "Ribbed Knit Tank Top", brand: "Uniqlo", subcategory: "Tops", sectionId: "womens-contemporary-edit", sectionTitle: "Women's Edit & Contemporary Silhouettes", description: "Slim-fit ribbed tank with wide shoulder straps and a scooped neckline for easy layering.", tags: ["tank-top", "ribbed", "basics", "womens"] },
  { id: "corset-top", name: "Structured Boned Corset Top", brand: "Zara", subcategory: "Tops", sectionId: "womens-contemporary-edit", sectionTitle: "Women's Edit & Contemporary Silhouettes", description: "Statement boned corset bustier top with sweetheart neckline and back zip closure.", tags: ["corset-top", "bustier", "party", "womens", "trending"], badge: "HOT" },
  { id: "tube-top", name: "Strapless Tube Top", brand: "H&M", subcategory: "Tops", sectionId: "womens-contemporary-edit", sectionTitle: "Women's Edit & Contemporary Silhouettes", description: "Stretchy bandeau tube top in cotton-elastane blend with inner silicone grip.", tags: ["tube-top", "strapless", "basics", "womens"] },
  { id: "off-shoulder-top", name: "Off-Shoulder Ruched Top", brand: "Mango", subcategory: "Tops", sectionId: "womens-contemporary-edit", sectionTitle: "Women's Edit & Contemporary Silhouettes", description: "Gathered ruched bodice with elasticated off-shoulder neckline and puffed short sleeves.", tags: ["off-shoulder", "top", "ruched", "womens", "party"] },
  { id: "graphic-tee-womens", name: "Oversized Graphic Tee (Women's)", brand: "H&M", subcategory: "T-Shirts", sectionId: "womens-contemporary-edit", sectionTitle: "Women's Edit & Contemporary Silhouettes", description: "Relaxed oversized fit with vintage-inspired graphic print and washed-out finish.", tags: ["graphic-tee", "oversized", "womens", "streetwear"] },
  { id: "oversized-shirt-womens", name: "Oversized Cotton Poplin Shirt (Women's)", brand: "Zara", subcategory: "Shirts", sectionId: "womens-contemporary-edit", sectionTitle: "Women's Edit & Contemporary Silhouettes", description: "Effortless boyfriend-cut button-down in crisp poplin with curved shirttail hem.", tags: ["shirt", "oversized", "poplin", "womens"] },
  { id: "cardigan-womens", name: "Chunky Knit Oversized Cardigan", brand: "H&M", subcategory: "Tops", sectionId: "womens-contemporary-edit", sectionTitle: "Women's Edit & Contemporary Silhouettes", description: "Cozy oversized cable-knit cardigan with large horn buttons and dropped shoulders.", tags: ["cardigan", "knitwear", "oversized", "womens", "cozy"] },
  { id: "knit-top-womens", name: "Fine Knit Fitted Top", brand: "Uniqlo", subcategory: "Tops", sectionId: "womens-contemporary-edit", sectionTitle: "Women's Edit & Contemporary Silhouettes", description: "Lightweight fine-gauge knit with slim fit and ribbed hem for a polished everyday look.", tags: ["knit-top", "fitted", "basics", "womens"] },
  { id: "zip-hoodie-womens", name: "Cropped Zip-Up Hoodie (Women's)", brand: "Nike", subcategory: "Streetwear", sectionId: "womens-contemporary-edit", sectionTitle: "Women's Edit & Contemporary Silhouettes", description: "Cropped French terry zip-up with kangaroo pockets and embroidered Swoosh.", tags: ["hoodie", "zip-up", "cropped", "womens", "streetwear"] },
  { id: "oversized-hoodie-womens", name: "Oversized Fleece Hoodie (Women's)", brand: "H&M", subcategory: "Streetwear", sectionId: "womens-contemporary-edit", sectionTitle: "Women's Edit & Contemporary Silhouettes", description: "Ultra-soft brushed fleece hoodie with dropped shoulders and kangaroo pocket.", tags: ["hoodie", "oversized", "fleece", "womens"] },
  { id: "baggy-jeans-womens", name: "Baggy Wide-Leg Jeans (Women's)", brand: "Zara", subcategory: "Jeans", sectionId: "womens-contemporary-edit", sectionTitle: "Women's Edit & Contemporary Silhouettes", description: "High-rise baggy fit through hip and thigh with floor-length wide leg in light wash denim.", tags: ["jeans", "baggy", "wide-leg", "womens", "trending"], badge: "POPULAR" },
  { id: "wide-leg-jeans-womens", name: "Wide-Leg Straight Jeans (Women's)", brand: "Levi's", subcategory: "Jeans", sectionId: "womens-contemporary-edit", sectionTitle: "Women's Edit & Contemporary Silhouettes", description: "Levi's Ribcage wide-leg with super high rise for a leg-lengthening effect.", tags: ["jeans", "wide-leg", "levis", "womens"] },
  { id: "cargo-pants-womens", name: "Low-Rise Cargo Pants (Women's)", brand: "H&M", subcategory: "Trousers", sectionId: "womens-contemporary-edit", sectionTitle: "Women's Edit & Contemporary Silhouettes", description: "Relaxed low-rise cargo with multiple flap pockets and adjustable drawcord hems.", tags: ["cargo", "pants", "low-rise", "womens", "streetwear"] },
  { id: "parachute-pants-womens", name: "Nylon Parachute Pants (Women's)", brand: "Zara", subcategory: "Trousers", sectionId: "womens-contemporary-edit", sectionTitle: "Women's Edit & Contemporary Silhouettes", description: "Lightweight crinkle nylon parachute pants with elasticated waist and toggle ankles.", tags: ["parachute", "pants", "nylon", "womens", "trending"], badge: "TRENDING" },
  { id: "denim-skirt", name: "Classic Denim Mini Skirt", brand: "Levi's", subcategory: "Skirts", sectionId: "womens-contemporary-edit", sectionTitle: "Women's Edit & Contemporary Silhouettes", description: "Iconic denim mini with raw-edge hem, five-pocket styling, and button-fly closure.", tags: ["skirt", "denim", "mini", "levis", "womens"], badge: "POPULAR" },
  { id: "mini-skirt-pleated", name: "Pleated Mini Skirt", brand: "Zara", subcategory: "Skirts", sectionId: "womens-contemporary-edit", sectionTitle: "Women's Edit & Contemporary Silhouettes", description: "Preppy box-pleated mini skirt in structured fabric with concealed side zip.", tags: ["skirt", "mini", "pleated", "womens"] },
  { id: "midi-skirt-satin", name: "Satin Midi Slip Skirt", brand: "Mango", subcategory: "Skirts", sectionId: "womens-contemporary-edit", sectionTitle: "Women's Edit & Contemporary Silhouettes", description: "Fluid satin slip skirt with bias cut and elasticated waistband for effortless evening elegance.", tags: ["skirt", "midi", "satin", "womens", "party"] },
  { id: "maxi-skirt", name: "Flowy Maxi Skirt", brand: "H&M", subcategory: "Skirts", sectionId: "womens-contemporary-edit", sectionTitle: "Women's Edit & Contemporary Silhouettes", description: "Floor-length flowy maxi in crinkle viscose with high elasticated waist.", tags: ["skirt", "maxi", "flowy", "womens", "summer"] },
  { id: "co-ord-set-womens", name: "Linen Co-Ord Set", brand: "Zara", subcategory: "Sets", sectionId: "womens-contemporary-edit", sectionTitle: "Women's Edit & Contemporary Silhouettes", description: "Matching linen shirt and wide-leg trouser set for an effortlessly coordinated resort look.", tags: ["co-ord", "set", "linen", "matching", "womens"], badge: "TRENDING" },
  { id: "casual-dress", name: "Cotton T-Shirt Dress", brand: "H&M", subcategory: "Dresses", sectionId: "womens-contemporary-edit", sectionTitle: "Women's Edit & Contemporary Silhouettes", description: "Easy pullover T-shirt dress in soft jersey cotton with relaxed A-line shape.", tags: ["dress", "casual", "t-shirt-dress", "womens"] },
  { id: "bodycon-dress", name: "Ribbed Bodycon Mini Dress", brand: "Zara", subcategory: "Dresses", sectionId: "womens-contemporary-edit", sectionTitle: "Women's Edit & Contemporary Silhouettes", description: "Figure-hugging ribbed-knit mini with scoop neck and racerback detailing.", tags: ["dress", "bodycon", "mini", "party", "womens"] },
  { id: "oversized-jacket-womens", name: "Oversized Leather-Effect Jacket (Women's)", brand: "Zara", subcategory: "Streetwear", sectionId: "womens-contemporary-edit", sectionTitle: "Women's Edit & Contemporary Silhouettes", description: "Oversized faux-leather biker jacket with zip hardware and quilted lining.", tags: ["jacket", "oversized", "leather", "womens", "trending"], badge: "POPULAR" },
  { id: "denim-jacket-womens", name: "Cropped Denim Jacket (Women's)", brand: "Levi's", subcategory: "Streetwear", sectionId: "womens-contemporary-edit", sectionTitle: "Women's Edit & Contemporary Silhouettes", description: "Cropped trucker jacket in stretch denim with classic button-front and chest pockets.", tags: ["denim-jacket", "cropped", "levis", "womens"] },
  { id: "bomber-jacket-womens", name: "Satin Bomber Jacket (Women's)", brand: "Zara", subcategory: "Streetwear", sectionId: "womens-contemporary-edit", sectionTitle: "Women's Edit & Contemporary Silhouettes", description: "Luxe satin bomber with ribbed trims, zip-front closure, and minimal embroidery.", tags: ["bomber", "satin", "jacket", "womens"] },
  { id: "leather-style-jacket-womens", name: "Faux Leather Moto Jacket", brand: "Mango", subcategory: "Streetwear", sectionId: "womens-contemporary-edit", sectionTitle: "Women's Edit & Contemporary Silhouettes", description: "Classic biker moto silhouette in vegan leather with asymmetric zip and snap lapels.", tags: ["leather-jacket", "moto", "faux-leather", "womens"], badge: "POPULAR" },
  { id: "oversized-tee-womens", name: "Oversized Drop-Shoulder Tee (Women's)", brand: "Bewakoof", subcategory: "T-Shirts", sectionId: "womens-contemporary-edit", sectionTitle: "Women's Edit & Contemporary Silhouettes", description: "Relaxed boyfriend-fit tee in premium cotton with drop shoulders and curved hem.", tags: ["t-shirt", "oversized", "womens", "basics"] },

  // === NEW PRODUCTS: WOMEN'S INDIAN / ETHNIC ===
  { id: "kurta-set-womens", name: "Cotton Printed Kurta Set with Dupatta", brand: "FabIndia", subcategory: "Ethnic Wear", sectionId: "womens-indian-ethnic", sectionTitle: "Women's Indian & Ethnic Wear", description: "Hand-block printed cotton kurta with straight pants and matching dupatta for everyday festive wear.", tags: ["kurta", "set", "ethnic", "womens", "indian"], badge: "POPULAR" },
  { id: "anarkali-set", name: "Georgette Anarkali Suit Set", brand: "Biba", subcategory: "Ethnic Wear", sectionId: "womens-indian-ethnic", sectionTitle: "Women's Indian & Ethnic Wear", description: "Flared embroidered Anarkali kurta with churidar and sheer organza dupatta.", tags: ["anarkali", "suit", "ethnic", "womens", "festive"], badge: "POPULAR" },
  { id: "co-ord-ethnic-set", name: "Printed Ethnic Co-Ord Set", brand: "W", subcategory: "Ethnic Wear", sectionId: "womens-indian-ethnic", sectionTitle: "Women's Indian & Ethnic Wear", description: "Modern matching ethnic crop top and palazzo set with traditional Kalamkari print.", tags: ["co-ord", "ethnic", "matching", "womens"] },
  { id: "pre-draped-saree", name: "Pre-Draped Concept Saree", brand: "Manyavar", subcategory: "Ethnic Wear", sectionId: "womens-indian-ethnic", sectionTitle: "Women's Indian & Ethnic Wear", description: "Ready-to-wear pre-pleated and pre-draped saree with attached pallu for effortless festive dressing.", tags: ["saree", "pre-draped", "festive", "womens", "trending"], badge: "TRENDING" },
  { id: "statement-dupatta", name: "Handcrafted Bandhani Statement Dupatta", brand: "FabIndia", subcategory: "Ethnic Wear", sectionId: "womens-indian-ethnic", sectionTitle: "Women's Indian & Ethnic Wear", description: "Vibrant hand-tied Bandhani dupatta in pure silk with contrasting borders and tassels.", tags: ["dupatta", "bandhani", "ethnic", "womens"] },
  { id: "jhumka-earrings", name: "Traditional Silver Jhumka Earrings", brand: "FabIndia", subcategory: "Jewellery", sectionId: "womens-indian-ethnic", sectionTitle: "Women's Indian & Ethnic Wear", description: "Handcrafted sterling silver dome jhumkas with delicate hanging chains and beadwork.", tags: ["jhumkas", "earrings", "silver", "ethnic", "jewellery"], badge: "POPULAR" },
  { id: "oxidised-jewellery-set", name: "Oxidised Silver Statement Necklace Set", brand: "FabIndia", subcategory: "Jewellery", sectionId: "womens-indian-ethnic", sectionTitle: "Women's Indian & Ethnic Wear", description: "Boho-chic oxidised silver necklace with matching earrings featuring intricate tribal motifs.", tags: ["oxidised", "necklace", "jewellery", "ethnic", "boho"] },
  { id: "minimal-gold-jewellery", name: "Minimalist Gold-Plated Jewellery Set", brand: "Accessorize", subcategory: "Jewellery", sectionId: "womens-indian-ethnic", sectionTitle: "Women's Indian & Ethnic Wear", description: "Delicate gold-plated layered chain necklace with matching stud earrings for everyday elegance.", tags: ["gold", "minimalist", "jewellery", "everyday"] },
  { id: "silk-saree", name: "Pure Kanjeevaram Silk Saree", brand: "Nalli", subcategory: "Ethnic Wear", sectionId: "womens-indian-ethnic", sectionTitle: "Women's Indian & Ethnic Wear", description: "Heritage handwoven Kanjeevaram silk with rich zari border and traditional temple motifs.", tags: ["saree", "silk", "kanjeevaram", "festive", "premium"], badge: "PREMIUM" },
  { id: "lehenga-festive", name: "Sequin Embroidered Festive Lehenga", brand: "Biba", subcategory: "Ethnic Wear", sectionId: "womens-indian-ethnic", sectionTitle: "Women's Indian & Ethnic Wear", description: "Lightweight festive lehenga with scattered sequin embroidery and mesh dupatta.", tags: ["lehenga", "festive", "sequin", "womens"] },

  // === NEW PRODUCTS: WOMEN'S ACCESSORIES ===
  { id: "shoulder-bag-womens", name: "Quilted Shoulder Bag", brand: "Mango", subcategory: "Bags", sectionId: "womens-accessories", sectionTitle: "Women's Bags, Jewellery & Accessories", description: "Soft quilted faux leather shoulder bag with chain strap and magnetic flap closure.", tags: ["shoulder-bag", "quilted", "womens", "bag"], badge: "POPULAR" },
  { id: "tote-bag-womens", name: "Structured Canvas Tote Bag", brand: "Coach", subcategory: "Bags", sectionId: "womens-accessories", sectionTitle: "Women's Bags, Jewellery & Accessories", description: "Spacious canvas tote with leather trim handles and interior zip pocket.", tags: ["tote", "canvas", "bag", "womens"] },
  { id: "mini-bag-womens", name: "Mini Crossbody Phone Bag", brand: "Zara", subcategory: "Bags", sectionId: "womens-accessories", sectionTitle: "Women's Bags, Jewellery & Accessories", description: "Compact crossbody just big enough for phone, cards, and keys with adjustable strap.", tags: ["mini-bag", "crossbody", "phone-bag", "womens"], badge: "TRENDING" },
  { id: "crossbody-bag-womens", name: "Leather Crossbody Bag", brand: "Michael Kors", subcategory: "Bags", sectionId: "womens-accessories", sectionTitle: "Women's Bags, Jewellery & Accessories", description: "Pebbled leather crossbody with gold-tone hardware and adjustable chain strap.", tags: ["crossbody", "leather", "bag", "womens"] },
  { id: "sling-bag-womens", name: "Nylon Sporty Sling Bag", brand: "Nike", subcategory: "Bags", sectionId: "womens-accessories", sectionTitle: "Women's Bags, Jewellery & Accessories", description: "Lightweight nylon sling bag with zip compartments and adjustable webbing strap.", tags: ["sling-bag", "nylon", "sporty", "womens"] },
  { id: "baguette-bag", name: "Baguette Shoulder Bag", brand: "Mango", subcategory: "Bags", sectionId: "womens-accessories", sectionTitle: "Women's Bags, Jewellery & Accessories", description: "Compact baguette silhouette with short shoulder strap and decorative buckle closure.", tags: ["baguette", "bag", "shoulder", "womens", "trending"], badge: "HOT" },
  { id: "sunglasses-cat-eye", name: "Cat-Eye Acetate Sunglasses", brand: "Ray-Ban", subcategory: "Accessories", sectionId: "womens-accessories", sectionTitle: "Women's Bags, Jewellery & Accessories", description: "Retro cat-eye frame in polished acetate with gradient UV400 lenses.", tags: ["sunglasses", "cat-eye", "rayban", "womens"] },
  { id: "cap-womens", name: "Cotton Dad Cap (Women's)", brand: "Nike", subcategory: "Accessories", sectionId: "womens-accessories", sectionTitle: "Women's Bags, Jewellery & Accessories", description: "Soft unstructured cotton cap with curved brim and adjustable metal buckle.", tags: ["cap", "dad-cap", "nike", "womens"] },
  { id: "hair-accessories-set", name: "Satin Hair Accessories Set", brand: "Accessorize", subcategory: "Accessories", sectionId: "womens-accessories", sectionTitle: "Women's Bags, Jewellery & Accessories", description: "Set of satin scrunchies, claw clips, and ribbon hair ties in coordinated pastel tones.", tags: ["hair-accessories", "scrunchies", "claw-clips", "womens"] },
  { id: "scrunchies-set", name: "Silk Scrunchie Set (Pack of 5)", brand: "Accessorize", subcategory: "Accessories", sectionId: "womens-accessories", sectionTitle: "Women's Bags, Jewellery & Accessories", description: "Pure mulberry silk scrunchies that are gentle on hair and prevent creasing.", tags: ["scrunchies", "silk", "hair", "womens"] },
  { id: "claw-clip-set", name: "Acrylic Claw Clip Set", brand: "Accessorize", subcategory: "Accessories", sectionId: "womens-accessories", sectionTitle: "Women's Bags, Jewellery & Accessories", description: "Set of tortoiseshell and solid-color jumbo claw clips for effortless updos.", tags: ["claw-clips", "hair-clips", "womens"] },
  { id: "belt-womens", name: "Thin Leather Waist Belt", brand: "Mango", subcategory: "Accessories", sectionId: "womens-accessories", sectionTitle: "Women's Bags, Jewellery & Accessories", description: "Slim leather belt with polished gold-tone buckle for cinching dresses and blazers.", tags: ["belt", "thin", "leather", "womens"] },
  { id: "minimal-rings-set", name: "Minimal Stacking Ring Set", brand: "Accessorize", subcategory: "Jewellery", sectionId: "womens-accessories", sectionTitle: "Women's Bags, Jewellery & Accessories", description: "Set of five delicate gold-plated stacking rings with mixed textures and tiny CZ stones.", tags: ["rings", "stacking", "gold", "minimal", "womens"], badge: "POPULAR" },
  { id: "bracelet-chain", name: "Dainty Chain Bracelet", brand: "Accessorize", subcategory: "Jewellery", sectionId: "womens-accessories", sectionTitle: "Women's Bags, Jewellery & Accessories", description: "Fine gold-plated chain bracelet with lobster clasp and adjustable extender chain.", tags: ["bracelet", "chain", "gold", "dainty", "womens"] },
  { id: "layered-necklace", name: "Layered Chain Necklace Set", brand: "Accessorize", subcategory: "Jewellery", sectionId: "womens-accessories", sectionTitle: "Women's Bags, Jewellery & Accessories", description: "Three-layer chain necklace set in gold plating with pendant, herringbone, and cable chains.", tags: ["necklace", "layered", "gold", "womens", "trending"], badge: "TRENDING" },
  { id: "earrings-hoop", name: "Classic Gold Hoop Earrings", brand: "Accessorize", subcategory: "Jewellery", sectionId: "womens-accessories", sectionTitle: "Women's Bags, Jewellery & Accessories", description: "Medium-size polished gold-plated hoop earrings with click-top closure.", tags: ["earrings", "hoops", "gold", "classic", "womens"] },
  { id: "earrings-statement", name: "Statement Drop Earrings", brand: "Mango", subcategory: "Jewellery", sectionId: "womens-accessories", sectionTitle: "Women's Bags, Jewellery & Accessories", description: "Eye-catching geometric drop earrings with mixed-metal finish for evening looks.", tags: ["earrings", "drop", "statement", "womens"] },
  { id: "sunglasses-retro-womens", name: "Retro Oval Sunglasses", brand: "Mango", subcategory: "Accessories", sectionId: "womens-accessories", sectionTitle: "Women's Bags, Jewellery & Accessories", description: "90s-inspired slim oval frame with tinted lenses and metal temple detailing.", tags: ["sunglasses", "retro", "oval", "womens"] },
];

/**
 * Return all Fashion products with resolved image URLs and display orders.
 */
export function getFullFashionCatalog(): FashionProduct[] {
  return RAW_FASHION_PRODUCTS.map((p, idx) => ({
    id: p.id,
    name: p.name,
    brand: p.brand,
    category: "Fashion",
    subcategory: p.subcategory,
    sectionId: p.sectionId,
    sectionTitle: p.sectionTitle,
    imageUrl: getFashionProductImage(p.id),
    description: p.description,
    tags: p.tags,
    badge: p.badge,
    featured: Boolean(p.featured),
    trending: Boolean(p.trending),
    displayOrder: idx,
  }));
}

/**
 * Get distinct subcategories for fashion navigation
 */
export function getFashionSubcategories(): Array<{ name: string; count: number }> {
  const map = new Map<string, number>();
  for (const item of RAW_FASHION_PRODUCTS) {
    map.set(item.subcategory, (map.get(item.subcategory) || 0) + 1);
  }
  return Array.from(map.entries()).map(([name, count]) => ({ name, count }));
}
