/**
 * Comprehensive Gaming Catalog Data Definition for Plugd
 * 
 * Deep, enthusiast-ready gaming catalog covering PC components, gaming laptops,
 * consoles, handhelds, monitors, peripherals, audio, streaming, sim racing, VR,
 * and gaming furniture.
 */

import { getGamingProductImage } from "./product-images";

export interface GamingProduct {
  id: string;
  name: string;
  brand: string;
  category: "Gaming";
  subcategory: string;
  sectionId: string;
  sectionTitle: string;
  imageUrl: string;
  description: string;
  tags: string[];
  badge?: "HOT" | "TRENDING" | "NEW" | "POPULAR" | "ENTHUSIAST";
  featured?: boolean;
  trending?: boolean;
  displayOrder: number;
}

export interface GamingSection {
  id: string;
  title: string;
  subtitle: string;
  badge?: string;
  displayOrder: number;
  productIds: string[];
}

export const GAMING_SECTIONS: GamingSection[] = [
  {
    id: "trending-gaming",
    title: "Trending in Gaming",
    subtitle: "Most coveted gaming gear, high-demand RTX GPUs, next-gen handhelds, and esports peripherals",
    badge: "🔥 Hot",
    displayOrder: 1,
    productIds: [
      "nvidia-geforce-rtx-5090",
      "nvidia-geforce-rtx-5080",
      "playstation-5-pro",
      "steam-deck-oled",
      "asus-rog-ally-x",
      "wooting-80he",
      "logitech-g-pro-x-superlight-2",
      "samsung-odyssey-oled-g9",
      "asus-rog-strix-scar-18",
      "amd-ryzen-7-7800x3d",
      "steelseries-arctis-nova-pro-wireless",
      "elgato-stream-deck-xl",
      "razer-deathadder-v3-pro",
      "meta-quest-3",
      "secretlab-titan-evo-2024",
    ],
  },
  {
    id: "ultimate-setup",
    title: "Ultimate Gaming Setup (Enthusiast)",
    subtitle: "Aspirational, zero-compromise hardware for top-tier creators, pro gamers, and battlestation enthusiasts",
    badge: "👑 Battlestation",
    displayOrder: 2,
    productIds: [
      "nvidia-geforce-rtx-5090",
      "intel-core-ultra-9-285k",
      "asus-rog-maximus-z890-hero",
      "samsung-odyssey-oled-g9",
      "asus-rog-swift-oled-pg32ucdm",
      "wooting-80he",
      "razer-viper-v3-pro",
      "steelseries-arctis-nova-pro-wireless",
      "shure-sm7b",
      "elgato-stream-deck-xl",
      "herman-miller-x-logitech-embody",
      "secretlab-magnus-pro-desk",
      "fanatec-clubsport-dd-plus",
    ],
  },
  {
    id: "gpu-powerhouse",
    title: "GPU Powerhouse (NVIDIA GeForce & AMD Radeon)",
    subtitle: "Next-gen Blackwell silicon, massive VRAM pools, AI upscaling, and ray-tracing graphics cards",
    badge: "⚡ GPUs",
    displayOrder: 3,
    productIds: [
      "nvidia-geforce-rtx-5090",
      "nvidia-geforce-rtx-5080",
      "nvidia-geforce-rtx-5070-ti",
      "nvidia-geforce-rtx-5070",
      "nvidia-geforce-rtx-5060-ti",
      "nvidia-geforce-rtx-5060",
      "nvidia-geforce-rtx-4090",
      "nvidia-geforce-rtx-4080-super",
      "nvidia-geforce-rtx-4070-ti-super",
      "nvidia-geforce-rtx-4070-super",
      "nvidia-geforce-rtx-4060-ti",
      "nvidia-geforce-rtx-4060",
      "amd-radeon-rx-9070-xt",
      "amd-radeon-rx-9070",
      "amd-radeon-rx-7900-xtx",
      "amd-radeon-rx-7900-xt",
      "amd-radeon-rx-7800-xt",
      "amd-radeon-rx-7700-xt",
      "amd-radeon-rx-7600-xt",
      "rtx-graphics-card",
    ],
  },
  {
    id: "gaming-laptops",
    title: "Gaming Laptops (ROG, Legion, Predator, Omen)",
    subtitle: "High-TGP mobile GPUs, QHD 240Hz screens, advanced vapor chambers, and portable desktop replacement power",
    badge: "💻 Laptops",
    displayOrder: 4,
    productIds: [
      "asus-rog-strix-scar-18",
      "asus-rog-zephyrus-g16",
      "asus-rog-zephyrus-g14",
      "lenovo-legion-pro-7i",
      "lenovo-legion-5i",
      "lenovo-loq-15",
      "acer-predator-helios-16",
      "acer-nitro-v-15",
      "hp-omen-transcend-14",
      "hp-victus-16",
      "alienware-m16-r2",
      "msi-raider-ge78-hx",
      "msi-cyborg-15",
      "dell-g15-gaming",
      "asus-tuf-gaming-a15",
      "gaming-laptop",
    ],
  },
  {
    id: "pc-build-hardware",
    title: "PC Build Hardware (CPUs, Mobos, RAM, SSDs)",
    subtitle: "X3D 3D V-Cache processors, DDR5 memory kits, Gen5 NVMe storage, liquid coolers, and airflow chassis",
    badge: "🛠️ Components",
    displayOrder: 5,
    productIds: [
      "amd-ryzen-7-7800x3d",
      "amd-ryzen-9-9950x3d",
      "amd-ryzen-9-9900x",
      "amd-ryzen-5-7600x",
      "intel-core-ultra-9-285k",
      "intel-core-i7-14700k",
      "intel-core-i5-14600k",
      "asus-rog-maximus-z890-hero",
      "asus-rog-strix-b650e-f",
      "msi-mag-b650-tomahawk-wifi",
      "gigabyte-x870-aorus-elite",
      "corsair-vengeance-rgb-ddr5",
      "gskill-trident-z5-rgb-ddr5",
      "samsung-990-pro-nvme-ssd",
      "crucial-t705-pcie-5-ssd",
      "wd-black-sn850x-nvme",
      "nzxt-kraken-elite-360-rgb",
      "lian-li-o11-dynamic-evo",
      "nzxt-h9-flow",
      "gaming-pc",
      "corsair-one-i500",
    ],
  },
  {
    id: "console-gaming",
    title: "Console Gaming (PlayStation, Xbox, Nintendo)",
    subtitle: "4K 60fps / 120fps home gaming consoles, pro haptic controllers, and couch gaming essentials",
    badge: "🎮 Consoles",
    displayOrder: 6,
    productIds: [
      "playstation-5-pro",
      "playstation-5-slim",
      "playstation-5",
      "xbox-series-x",
      "xbox-series-s",
      "nintendo-switch-oled",
      "dualsense-edge-wireless-controller",
      "xbox-elite-wireless-controller-series-2",
      "sony-dualsense-wireless-controller",
      "xbox-wireless-controller",
      "playstation-portal",
      "custom-controller",
    ],
  },
  {
    id: "handheld-gaming",
    title: "Handheld Gaming (Steam Deck, ROG Ally, Legion Go)",
    subtitle: "AAA gaming on the move with ergonomic controls, 120Hz VRR displays, and custom APUs",
    badge: "🕹️ Handhelds",
    displayOrder: 7,
    productIds: [
      "steam-deck-oled",
      "steam-deck",
      "asus-rog-ally-x",
      "lenovo-legion-go",
      "msi-claw-a1m",
      "nintendo-switch-oled",
      "playstation-portal",
    ],
  },
  {
    id: "gaming-monitors",
    title: "Esports & High-Refresh Gaming Monitors",
    subtitle: "Sub-millisecond OLED response, 360Hz esports panels, 4K clarity, and immersive ultrawide curves",
    badge: "🖥️ Displays",
    displayOrder: 8,
    productIds: [
      "samsung-odyssey-oled-g9",
      "samsung-odyssey-oled-g8",
      "lg-ultragear-oled-32gs95ue",
      "asus-rog-swift-oled-pg32ucdm",
      "alienware-aw3423dwf-qd-oled",
      "benq-zowie-xl2566k-360hz",
      "gigabyte-m27q-170hz",
      "aoc-24g2-165hz",
      "oled-gaming-monitor",
    ],
  },
  {
    id: "keyboards-hall-effect",
    title: "Keyboards & Hall-Effect Magnetic Switches",
    subtitle: "Rapid trigger, adjustable actuation points, custom gaskets, wireless connectivity, and custom keycaps",
    badge: "⌨️ Keyboards",
    displayOrder: 9,
    productIds: [
      "wooting-80he",
      "wooting-60he-plus",
      "keychron-q1-he",
      "razer-huntsman-v3-pro",
      "razer-blackwidow-v4-pro",
      "logitech-g-pro-x-tkl",
      "steelseries-apex-pro-tkl",
      "asus-rog-azoth-75",
      "redragon-k552-kumara",
      "mechanical-keyboard",
    ],
  },
  {
    id: "gaming-mice",
    title: "Pro Esports Gaming Mice",
    subtitle: "Ultra-lightweight chassis, 8000Hz polling rate, flawless optical sensors, and ergonomic shapes",
    badge: "🖱️ Mice",
    displayOrder: 10,
    productIds: [
      "logitech-g-pro-x-superlight-2",
      "razer-deathadder-v3-pro",
      "razer-viper-v3-pro",
      "pulsar-x2v2-wireless",
      "zowie-ec2-cw-wireless",
      "glorious-model-o-2",
      "logitech-g502-x-plus",
      "logitech-g203-lightsync",
    ],
  },
  {
    id: "gaming-audio",
    title: "Immersive Audio & Headsets",
    subtitle: "Spatial 3D audio, active noise cancelling, planar magnetic drivers, and broadcast-grade clear mics",
    badge: "🎧 Sound",
    displayOrder: 11,
    productIds: [
      "steelseries-arctis-nova-pro-wireless",
      "razer-blackshark-v2-pro",
      "logitech-g-pro-x-2-lightspeed",
      "hyperx-cloud-iii-wireless",
      "sony-inzone-h9",
      "corsair-hs80-max",
    ],
  },
  {
    id: "streaming-gear",
    title: "Creator & Pro Streaming Battlestation",
    subtitle: "Macro stream controllers, broadcast dynamic XLR mics, 4K60 capture cards, and studio key lights",
    badge: "🎙️ Streaming",
    displayOrder: 12,
    productIds: [
      "elgato-stream-deck-xl",
      "elgato-stream-deck-plus",
      "elgato-wave-3",
      "shure-sm7b",
      "rode-podmic-usb",
      "focusrite-scarlett-2i2-4th-gen",
      "elgato-key-light-air",
      "elgato-facecam-pro-4k60",
      "elgato-cam-link-4k",
      "capture-card",
      "streaming-microphone",
    ],
  },
  {
    id: "sim-racing",
    title: "Sim Racing & Flight Cockpits",
    subtitle: "Direct-drive force feedback wheelbases, load-cell pedals, sequential shifters, and rigid steel cockpits",
    badge: "🏎️ Sim Racing",
    displayOrder: 13,
    productIds: [
      "fanatec-clubsport-dd-plus",
      "moza-r9-v2-direct-drive",
      "logitech-g-pro-racing-wheel",
      "logitech-g923-racing-wheel",
      "thrustmaster-t300-rs-gt",
      "playseat-trophy-cockpit",
      "racing-wheel",
    ],
  },
  {
    id: "vr-immersive",
    title: "VR & Next-Gen Immersion",
    subtitle: "Wireless 4K VR headsets, OLED HDR passthrough lenses, and haptic motion controllers",
    badge: "🥽 VR",
    displayOrder: 14,
    productIds: [
      "meta-quest-3",
      "playstation-vr2",
      "meta-quest-3s",
      "vr-headset",
    ],
  },
  {
    id: "budget-gaming",
    title: "Student & Budget Gaming Champions",
    subtitle: "Accessible, high-value mechanical keyboards, lightweight mice, 1080p 165Hz monitors, and entry GPUs",
    badge: "💰 Budget",
    displayOrder: 15,
    productIds: [
      "redragon-k552-kumara",
      "logitech-g203-lightsync",
      "aoc-24g2-165hz",
      "nvidia-geforce-rtx-4060",
      "amd-radeon-rx-7600-xt",
      "amd-ryzen-5-5600x",
      "lenovo-loq-15",
      "acer-nitro-v-15",
      "xbox-series-s",
      "8bitdo-ultimate-bluetooth-controller",
    ],
  },
  {
    id: "gaming-furniture-setup",
    title: "Enthusiast Gaming Furniture & Desk Setup",
    subtitle: "Ergonomic gaming chairs, motorized sit-to-stand magnetic desks, RGB ambilight setups, and cable routing",
    badge: "🪑 Furniture & Setup",
    displayOrder: 16,
    productIds: [
      "secretlab-titan-evo-2024",
      "herman-miller-x-logitech-embody",
      "secretlab-magnus-pro-desk",
      "gaming-chair",
      "rgb-setup-kit",
    ],
  },
];

/** Full list of Gaming products */
export const RAW_GAMING_PRODUCTS: Array<{
  id: string;
  name: string;
  brand: string;
  subcategory: string;
  sectionId: string;
  sectionTitle: string;
  description: string;
  tags: string[];
  badge?: "HOT" | "TRENDING" | "NEW" | "POPULAR" | "ENTHUSIAST";
  featured?: boolean;
  trending?: boolean;
}> = [
  // === GPUs ===
  {
    id: "nvidia-geforce-rtx-5090",
    name: "NVIDIA GeForce RTX 5090",
    brand: "NVIDIA",
    subcategory: "GPUs",
    sectionId: "gpu-powerhouse",
    sectionTitle: "GPU Powerhouse (NVIDIA GeForce & AMD Radeon)",
    description: "The ultimate Blackwell gaming and AI powerhouse with 32GB GDDR7, DLSS 4, and unprecedented 4K ray tracing performance.",
    tags: ["nvidia", "rtx", "rtx5090", "gpu", "flagship", "enthusiast", "blackwell", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "nvidia-geforce-rtx-5080",
    name: "NVIDIA GeForce RTX 5080",
    brand: "NVIDIA",
    subcategory: "GPUs",
    sectionId: "gpu-powerhouse",
    sectionTitle: "GPU Powerhouse (NVIDIA GeForce & AMD Radeon)",
    description: "High-end Blackwell GPU offering blistering 4K frame rates, ultra-fast 16GB GDDR7 memory, and advanced generative tensor cores.",
    tags: ["nvidia", "rtx", "rtx5080", "gpu", "flagship", "blackwell", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "nvidia-geforce-rtx-5070-ti",
    name: "NVIDIA GeForce RTX 5070 Ti",
    brand: "NVIDIA",
    subcategory: "GPUs",
    sectionId: "gpu-powerhouse",
    sectionTitle: "GPU Powerhouse (NVIDIA GeForce & AMD Radeon)",
    description: "Sweet-spot enthusiast GPU delivering 1440p and 4K high-refresh raster and ray-tracing performance with 16GB VRAM.",
    tags: ["nvidia", "rtx", "rtx5070ti", "gpu", "midrange", "blackwell"],
    badge: "NEW",
  },
  {
    id: "nvidia-geforce-rtx-5070",
    name: "NVIDIA GeForce RTX 5070",
    brand: "NVIDIA",
    subcategory: "GPUs",
    sectionId: "gpu-powerhouse",
    sectionTitle: "GPU Powerhouse (NVIDIA GeForce & AMD Radeon)",
    description: "Next-gen 1440p gaming champion with full DLSS 4 Frame Generation and high power efficiency.",
    tags: ["nvidia", "rtx", "rtx5070", "gpu", "1440p"],
    badge: "NEW",
  },
  {
    id: "nvidia-geforce-rtx-5060-ti",
    name: "NVIDIA GeForce RTX 5060 Ti",
    brand: "NVIDIA",
    subcategory: "GPUs",
    sectionId: "gpu-powerhouse",
    sectionTitle: "GPU Powerhouse (NVIDIA GeForce & AMD Radeon)",
    description: "Exceptional mainstream graphics card for ultra-smooth 1080p and 1440p gaming with DLSS AI acceleration.",
    tags: ["nvidia", "rtx", "rtx5060ti", "gpu", "value"],
  },
  {
    id: "nvidia-geforce-rtx-5060",
    name: "NVIDIA GeForce RTX 5060",
    brand: "NVIDIA",
    subcategory: "GPUs",
    sectionId: "gpu-powerhouse",
    sectionTitle: "GPU Powerhouse (NVIDIA GeForce & AMD Radeon)",
    description: "Modern entry gaming GPU enabling ray tracing and high fps in competitive esports and AAA titles.",
    tags: ["nvidia", "rtx", "rtx5060", "gpu", "budget", "esports"],
  },
  {
    id: "nvidia-geforce-rtx-4090",
    name: "NVIDIA GeForce RTX 4090",
    brand: "NVIDIA",
    subcategory: "GPUs",
    sectionId: "gpu-powerhouse",
    sectionTitle: "GPU Powerhouse (NVIDIA GeForce & AMD Radeon)",
    description: "Ada Lovelace architecture titan with 24GB G6X memory, DLSS 3.5, and monstrous 4K rendering throughput.",
    tags: ["nvidia", "rtx", "rtx4090", "gpu", "enthusiast", "4k"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "nvidia-geforce-rtx-4080-super",
    name: "NVIDIA GeForce RTX 4080 Super",
    brand: "NVIDIA",
    subcategory: "GPUs",
    sectionId: "gpu-powerhouse",
    sectionTitle: "GPU Powerhouse (NVIDIA GeForce & AMD Radeon)",
    description: "Fully unlocked AD103 die delivering uncompromised 4K gaming and exceptional content creation power.",
    tags: ["nvidia", "rtx", "rtx4080", "gpu", "4k"],
  },
  {
    id: "nvidia-geforce-rtx-4070-ti-super",
    name: "NVIDIA GeForce RTX 4070 Ti Super",
    brand: "NVIDIA",
    subcategory: "GPUs",
    sectionId: "gpu-powerhouse",
    sectionTitle: "GPU Powerhouse (NVIDIA GeForce & AMD Radeon)",
    description: "16GB VRAM on a 256-bit memory bus making it the ideal 1440p and ultra-wide gaming card.",
    tags: ["nvidia", "rtx", "rtx4070ti", "gpu", "1440p"],
  },
  {
    id: "nvidia-geforce-rtx-4070-super",
    name: "NVIDIA GeForce RTX 4070 Super",
    brand: "NVIDIA",
    subcategory: "GPUs",
    sectionId: "gpu-powerhouse",
    sectionTitle: "GPU Powerhouse (NVIDIA GeForce & AMD Radeon)",
    description: "20% more CUDA cores than the standard 4070, making it India's most popular 1440p GPU choice.",
    tags: ["nvidia", "rtx", "rtx4070", "gpu", "value", "bestseller"],
    badge: "POPULAR",
  },
  {
    id: "nvidia-geforce-rtx-4060-ti",
    name: "NVIDIA GeForce RTX 4060 Ti",
    brand: "NVIDIA",
    subcategory: "GPUs",
    sectionId: "gpu-powerhouse",
    sectionTitle: "GPU Powerhouse (NVIDIA GeForce & AMD Radeon)",
    description: "High-efficiency 1080p and 1440p gaming card with low power draw and DLSS 3 support.",
    tags: ["nvidia", "rtx", "rtx4060ti", "gpu"],
  },
  {
    id: "nvidia-geforce-rtx-4060",
    name: "NVIDIA GeForce RTX 4060",
    brand: "NVIDIA",
    subcategory: "GPUs",
    sectionId: "budget-gaming",
    sectionTitle: "Student & Budget Gaming Champions",
    description: "The gold-standard budget 1080p graphics card with under 115W power consumption.",
    tags: ["nvidia", "rtx", "rtx4060", "gpu", "budget"],
  },
  {
    id: "amd-radeon-rx-9070-xt",
    name: "AMD Radeon RX 9070 XT",
    brand: "AMD",
    subcategory: "GPUs",
    sectionId: "gpu-powerhouse",
    sectionTitle: "GPU Powerhouse (NVIDIA GeForce & AMD Radeon)",
    description: "RDNA 4 architecture flagship with 16GB GDDR6, FSR 4 AI upscaling, and dedicated ray-tracing accelerators.",
    tags: ["amd", "radeon", "rx9070xt", "gpu", "rdna4", "flagship"],
    badge: "NEW",
  },
  {
    id: "amd-radeon-rx-9070",
    name: "AMD Radeon RX 9070",
    brand: "AMD",
    subcategory: "GPUs",
    sectionId: "gpu-powerhouse",
    sectionTitle: "GPU Powerhouse (NVIDIA GeForce & AMD Radeon)",
    description: "RDNA 4 graphics card delivering high-refresh 1440p performance with generous VRAM buffer.",
    tags: ["amd", "radeon", "rx9070", "gpu", "rdna4"],
    badge: "NEW",
  },
  {
    id: "amd-radeon-rx-7900-xtx",
    name: "AMD Radeon RX 7900 XTX",
    brand: "AMD",
    subcategory: "GPUs",
    sectionId: "gpu-powerhouse",
    sectionTitle: "GPU Powerhouse (NVIDIA GeForce & AMD Radeon)",
    description: "24GB VRAM beast with DisplayPort 2.1 support and massive native rasterization performance.",
    tags: ["amd", "radeon", "rx7900xtx", "gpu", "24gb", "enthusiast"],
    featured: true,
  },
  {
    id: "amd-radeon-rx-7900-xt",
    name: "AMD Radeon RX 7900 XT",
    brand: "AMD",
    subcategory: "GPUs",
    sectionId: "gpu-powerhouse",
    sectionTitle: "GPU Powerhouse (NVIDIA GeForce & AMD Radeon)",
    description: "20GB high-bandwidth graphics card engineered for 4K gaming and high-resolution textures.",
    tags: ["amd", "radeon", "rx7900xt", "gpu", "4k"],
  },
  {
    id: "amd-radeon-rx-7800-xt",
    name: "AMD Radeon RX 7800 XT",
    brand: "AMD",
    subcategory: "GPUs",
    sectionId: "gpu-powerhouse",
    sectionTitle: "GPU Powerhouse (NVIDIA GeForce & AMD Radeon)",
    description: "16GB VRAM value champion for maximum 1440p raster frame rates.",
    tags: ["amd", "radeon", "rx7800xt", "gpu", "1440p", "value"],
    badge: "POPULAR",
  },
  {
    id: "amd-radeon-rx-7700-xt",
    name: "AMD Radeon RX 7700 XT",
    brand: "AMD",
    subcategory: "GPUs",
    sectionId: "gpu-powerhouse",
    sectionTitle: "GPU Powerhouse (NVIDIA GeForce & AMD Radeon)",
    description: "12GB gaming GPU built for ultra-settings 1440p esports and AAA adventures.",
    tags: ["amd", "radeon", "rx7700xt", "gpu"],
  },
  {
    id: "amd-radeon-rx-7600-xt",
    name: "AMD Radeon RX 7600 XT",
    brand: "AMD",
    subcategory: "GPUs",
    sectionId: "budget-gaming",
    sectionTitle: "Student & Budget Gaming Champions",
    description: "16GB VRAM budget graphics card allowing large texture packs and 1080p high fps.",
    tags: ["amd", "radeon", "rx7600xt", "gpu", "budget"],
  },
  {
    id: "rtx-graphics-card",
    name: "RTX Graphics Card",
    brand: "NVIDIA",
    subcategory: "GPUs",
    sectionId: "gpu-powerhouse",
    sectionTitle: "GPU Powerhouse (NVIDIA GeForce & AMD Radeon)",
    description: "Dedicated ray-tracing graphics processor for smooth PC gaming and high-fps streaming.",
    tags: ["nvidia", "rtx", "gpu", "gaming"],
  },

  // === CPUs ===
  {
    id: "amd-ryzen-7-7800x3d",
    name: "AMD Ryzen 7 7800X3D",
    brand: "AMD",
    subcategory: "CPUs",
    sectionId: "pc-build-hardware",
    sectionTitle: "PC Build Hardware (CPUs, Mobos, RAM, Storage, Cases)",
    description: "Undisputed world champion gaming processor featuring 2nd Gen 3D V-Cache and incredible power efficiency.",
    tags: ["amd", "ryzen", "7800x3d", "cpu", "3dvcache", "gaming", "bestseller"],
    badge: "HOT",
    featured: true,
  },
  {
    id: "amd-ryzen-9-9950x3d",
    name: "AMD Ryzen 9 9950X3D",
    brand: "AMD",
    subcategory: "CPUs",
    sectionId: "pc-build-hardware",
    sectionTitle: "PC Build Hardware (CPUs, Mobos, RAM, Storage, Cases)",
    description: "16-core 32-thread Zen 5 flagship with massive 3D V-Cache for extreme gaming and content creation.",
    tags: ["amd", "ryzen", "9950x3d", "cpu", "zen5", "flagship"],
    badge: "ENTHUSIAST",
    featured: true,
  },
  {
    id: "amd-ryzen-9-9900x",
    name: "AMD Ryzen 9 9900X",
    brand: "AMD",
    subcategory: "CPUs",
    sectionId: "pc-build-hardware",
    sectionTitle: "PC Build Hardware (CPUs, Mobos, RAM, Storage, Cases)",
    description: "12-core Zen 5 architecture processor with 5.6GHz boost clock on the AM5 platform.",
    tags: ["amd", "ryzen", "9900x", "cpu", "am5"],
  },
  {
    id: "amd-ryzen-7-9700x",
    name: "AMD Ryzen 7 9700X",
    brand: "AMD",
    subcategory: "CPUs",
    sectionId: "pc-build-hardware",
    sectionTitle: "PC Build Hardware (CPUs, Mobos, RAM, Storage, Cases)",
    description: "8-core 16-thread high-IPC gaming processor with 65W low TDP efficiency.",
    tags: ["amd", "ryzen", "9700x", "cpu", "am5"],
  },
  {
    id: "amd-ryzen-5-7600x",
    name: "AMD Ryzen 5 7600X",
    brand: "AMD",
    subcategory: "CPUs",
    sectionId: "pc-build-hardware",
    sectionTitle: "PC Build Hardware (CPUs, Mobos, RAM, Storage, Cases)",
    description: "Best-value AM5 entry processor delivering 5.3GHz boost speeds for esports gaming.",
    tags: ["amd", "ryzen", "7600x", "cpu", "value", "am5"],
    badge: "POPULAR",
  },
  {
    id: "amd-ryzen-5-5600x",
    name: "AMD Ryzen 5 5600X",
    brand: "AMD",
    subcategory: "CPUs",
    sectionId: "budget-gaming",
    sectionTitle: "Student & Budget Gaming Champions",
    description: "India's beloved AM4 budget processor offering rock-solid 1080p gaming performance.",
    tags: ["amd", "ryzen", "5600x", "cpu", "budget", "am4"],
  },
  {
    id: "intel-core-ultra-9-285k",
    name: "Intel Core Ultra 9 285K",
    brand: "Intel",
    subcategory: "CPUs",
    sectionId: "pc-build-hardware",
    sectionTitle: "PC Build Hardware (CPUs, Mobos, RAM, Storage, Cases)",
    description: "Arrow Lake desktop flagship with 24 cores, integrated NPU, Lion Cove P-cores, and PCIe 5.0 lanes.",
    tags: ["intel", "core-ultra", "285k", "cpu", "arrow-lake", "flagship"],
    badge: "NEW",
    featured: true,
  },
  {
    id: "intel-core-ultra-7-265k",
    name: "Intel Core Ultra 7 265K",
    brand: "Intel",
    subcategory: "CPUs",
    sectionId: "pc-build-hardware",
    sectionTitle: "PC Build Hardware (CPUs, Mobos, RAM, Storage, Cases)",
    description: "20-core gaming processor with unlocked multipliers and ultra-fast single-threaded response.",
    tags: ["intel", "core-ultra", "265k", "cpu"],
    badge: "NEW",
  },
  {
    id: "intel-core-i9-14900ks",
    name: "Intel Core i9 14900KS",
    brand: "Intel",
    subcategory: "CPUs",
    sectionId: "pc-build-hardware",
    sectionTitle: "PC Build Hardware (CPUs, Mobos, RAM, Storage, Cases)",
    description: "Record-setting 6.2GHz turbo frequency with 24 cores (8P + 16E) on LGA1700 platform.",
    tags: ["intel", "i9", "14900ks", "cpu", "enthusiast"],
    badge: "ENTHUSIAST",
  },
  {
    id: "intel-core-i7-14700k",
    name: "Intel Core i7 14700K",
    brand: "Intel",
    subcategory: "CPUs",
    sectionId: "pc-build-hardware",
    sectionTitle: "PC Build Hardware (CPUs, Mobos, RAM, Storage, Cases)",
    description: "20 cores (8P + 12E) and 28 threads providing ideal blend of high fps gaming and rendering.",
    tags: ["intel", "i7", "14700k", "cpu", "bestseller"],
  },
  {
    id: "intel-core-i5-14600k",
    name: "Intel Core i5 14600K",
    brand: "Intel",
    subcategory: "CPUs",
    sectionId: "pc-build-hardware",
    sectionTitle: "PC Build Hardware (CPUs, Mobos, RAM, Storage, Cases)",
    description: "14-core mid-range king delivering 5.3GHz boost for seamless esports and discord multitasking.",
    tags: ["intel", "i5", "14600k", "cpu", "value"],
  },
  {
    id: "intel-core-i5-13400f",
    name: "Intel Core i5 13400F",
    brand: "Intel",
    subcategory: "CPUs",
    sectionId: "budget-gaming",
    sectionTitle: "Student & Budget Gaming Champions",
    description: "10 cores (6P + 4E) budget powerhouse for cost-effective gaming PC builds.",
    tags: ["intel", "i5", "13400f", "cpu", "budget"],
  },

  // === Motherboards & Components ===
  {
    id: "asus-rog-maximus-z890-hero",
    name: "ASUS ROG Maximus Z890 Hero",
    brand: "ASUS ROG",
    subcategory: "Gaming PCs",
    sectionId: "pc-build-hardware",
    sectionTitle: "PC Build Hardware (CPUs, Mobos, RAM, Storage, Cases)",
    description: "Enthusiast motherboard with 20+1+2+2 power stages, Thunderbolt 4, Wi-Fi 7, and PCIe 5.0 M.2 slots.",
    tags: ["asus", "rog", "motherboard", "z890", "enthusiast"],
    badge: "ENTHUSIAST",
  },
  {
    id: "asus-rog-strix-b650e-f",
    name: "ASUS ROG Strix B650E-F Gaming WiFi",
    brand: "ASUS ROG",
    subcategory: "Gaming PCs",
    sectionId: "pc-build-hardware",
    sectionTitle: "PC Build Hardware (CPUs, Mobos, RAM, Storage, Cases)",
    description: "AM5 gaming motherboard with PCIe 5.0 slot, 12+2 power stages, and SupremeFX audio.",
    tags: ["asus", "rog", "motherboard", "b650", "am5"],
  },
  {
    id: "msi-mag-b650-tomahawk-wifi",
    name: "MSI MAG B650 Tomahawk WiFi",
    brand: "MSI",
    subcategory: "Gaming PCs",
    sectionId: "pc-build-hardware",
    sectionTitle: "PC Build Hardware (CPUs, Mobos, RAM, Storage, Cases)",
    description: "Heavy-duty VRM heatsinks, DDR5 memory boost, and reliable gaming stability for Ryzen chips.",
    tags: ["msi", "motherboard", "tomahawk", "b650", "am5"],
    badge: "POPULAR",
  },
  {
    id: "gigabyte-x870-aorus-elite",
    name: "Gigabyte X870 AORUS Elite WiFi7",
    brand: "Gigabyte",
    subcategory: "Gaming PCs",
    sectionId: "pc-build-hardware",
    sectionTitle: "PC Build Hardware (CPUs, Mobos, RAM, Storage, Cases)",
    description: "Zen 5 ready with twin 16+2+2 digital VRM, M.2 EZ-Latch Click, and ultra-fast Wi-Fi 7.",
    tags: ["gigabyte", "aorus", "motherboard", "x870", "am5"],
  },
  {
    id: "corsair-vengeance-rgb-ddr5",
    name: "Corsair Vengeance RGB DDR5 32GB 6000MHz",
    brand: "Corsair",
    subcategory: "Gaming PCs",
    sectionId: "pc-build-hardware",
    sectionTitle: "PC Build Hardware (CPUs, Mobos, RAM, Storage, Cases)",
    description: "Low-latency EXPO/XMP DDR5 memory with ten-zone dynamic panoramic RGB lighting.",
    tags: ["corsair", "ram", "ddr5", "rgb", "32gb"],
    badge: "POPULAR",
  },
  {
    id: "gskill-trident-z5-rgb-ddr5",
    name: "G.Skill Trident Z5 RGB DDR5 32GB 6400MHz",
    brand: "G.Skill",
    subcategory: "Gaming PCs",
    sectionId: "pc-build-hardware",
    sectionTitle: "PC Build Hardware (CPUs, Mobos, RAM, Storage, Cases)",
    description: "Hyper-speed overclocking DDR5 memory module with sleek brushed aluminum heatsink.",
    tags: ["gskill", "ram", "ddr5", "rgb", "speed"],
  },
  {
    id: "samsung-990-pro-nvme-ssd",
    name: "Samsung 990 PRO 2TB NVMe PCIe 4.0 SSD",
    brand: "Samsung",
    subcategory: "Gaming PCs",
    sectionId: "pc-build-hardware",
    sectionTitle: "PC Build Hardware (CPUs, Mobos, RAM, Storage, Cases)",
    description: "Blistering 7450 MB/s read speeds, custom thermal controller, and near-instant game level loads.",
    tags: ["samsung", "ssd", "nvme", "2tb", "pcie4", "bestseller"],
    badge: "HOT",
  },
  {
    id: "crucial-t705-pcie-5-ssd",
    name: "Crucial T705 2TB PCIe 5.0 NVMe SSD",
    brand: "Crucial",
    subcategory: "Gaming PCs",
    sectionId: "pc-build-hardware",
    sectionTitle: "PC Build Hardware (CPUs, Mobos, RAM, Storage, Cases)",
    description: "Mind-boggling 14,500 MB/s sequential reads with premium copper/aluminum heatsink.",
    tags: ["crucial", "ssd", "nvme", "pcie5", "speed"],
    badge: "ENTHUSIAST",
  },
  {
    id: "wd-black-sn850x-nvme",
    name: "WD_BLACK SN850X 2TB NVMe SSD",
    brand: "WD",
    subcategory: "Gaming PCs",
    sectionId: "pc-build-hardware",
    sectionTitle: "PC Build Hardware (CPUs, Mobos, RAM, Storage, Cases)",
    description: "Official top-tier gaming storage with Game Mode 2.0 predictive loading and heatsink option.",
    tags: ["wd", "wd-black", "ssd", "nvme", "ps5-ready"],
  },
  {
    id: "nzxt-kraken-elite-360-rgb",
    name: "NZXT Kraken Elite 360 RGB AIO Cooler",
    brand: "NZXT",
    subcategory: "Gaming PCs",
    sectionId: "pc-build-hardware",
    sectionTitle: "PC Build Hardware (CPUs, Mobos, RAM, Storage, Cases)",
    description: "2.36-inch wide-angle LCD screen for custom GIFs, Asetek pump, and high-static F120 RGB Core fans.",
    tags: ["nzxt", "aio", "cooler", "liquid-cooling", "rgb", "lcd"],
    badge: "HOT",
  },
  {
    id: "lian-li-o11-dynamic-evo",
    name: "Lian Li O11 Dynamic EVO RGB Case",
    brand: "Lian Li",
    subcategory: "Gaming PCs",
    sectionId: "pc-build-hardware",
    sectionTitle: "PC Build Hardware (CPUs, Mobos, RAM, Storage, Cases)",
    description: "Dual-chamber showcase PC chassis with wrap-around ARGB lighting and reverse mode capability.",
    tags: ["lian-li", "case", "chassis", "o11", "rgb"],
  },
  {
    id: "nzxt-h9-flow",
    name: "NZXT H9 Flow Dual-Chamber Mid-Tower Case",
    brand: "NZXT",
    subcategory: "Gaming PCs",
    sectionId: "pc-build-hardware",
    sectionTitle: "PC Build Hardware (CPUs, Mobos, RAM, Storage, Cases)",
    description: "Seamless glass wrap design with high-airflow perforated panels supporting ten 120mm fans.",
    tags: ["nzxt", "case", "chassis", "airflow"],
  },
  {
    id: "gaming-pc",
    name: "Gaming PC",
    brand: "Plugd Custom",
    subcategory: "Gaming PCs",
    sectionId: "pc-build-hardware",
    sectionTitle: "PC Build Hardware (CPUs, Mobos, RAM, Storage, Cases)",
    description: "Custom hand-built liquid-cooled gaming desktop with RTX GPU and multi-core CPU.",
    tags: ["custom-pc", "desktop", "gaming-pc", "liquid-cooled"],
    featured: true,
  },
  {
    id: "corsair-one-i500",
    name: "Corsair ONE i500 Compact Gaming PC",
    brand: "Corsair",
    subcategory: "Gaming PCs",
    sectionId: "pc-build-hardware",
    sectionTitle: "PC Build Hardware (CPUs, Mobos, RAM, Storage, Cases)",
    description: "Real FSC-certified wood panels, liquid-cooled RTX 4090 and Core i9 in an ultra-compact tower.",
    tags: ["corsair", "prebuilt", "compact-pc", "wood", "flagship"],
    badge: "ENTHUSIAST",
  },

  // === Gaming Laptops ===
  {
    id: "asus-rog-strix-scar-18",
    name: "ASUS ROG Strix SCAR 18",
    brand: "ASUS ROG",
    subcategory: "Gaming Laptops",
    sectionId: "gaming-laptops",
    sectionTitle: "Gaming Laptops (ROG, Legion, Predator, Omen)",
    description: "18-inch 2.5K 240Hz ROG Nebula HDR Mini-LED screen with RTX 4090 (175W) and Intel Core i9 14900HX.",
    tags: ["asus", "rog", "strix-scar", "laptop", "rtx4090", "mini-led", "flagship"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "asus-rog-zephyrus-g16",
    name: "ASUS ROG Zephyrus G16 OLED",
    brand: "ASUS ROG",
    subcategory: "Gaming Laptops",
    sectionId: "gaming-laptops",
    sectionTitle: "Gaming Laptops (ROG, Legion, Predator, Omen)",
    description: "CNC aluminum chassis, Slash Lighting LED lid, 2.5K 240Hz OLED ROG Nebula display, and RTX 4080.",
    tags: ["asus", "rog", "zephyrus", "oled", "slim-laptop", "trending"],
    badge: "HOT",
    featured: true,
  },
  {
    id: "asus-rog-zephyrus-g14",
    name: "ASUS ROG Zephyrus G14",
    brand: "ASUS ROG",
    subcategory: "Gaming Laptops",
    sectionId: "gaming-laptops",
    sectionTitle: "Gaming Laptops (ROG, Legion, Predator, Omen)",
    description: "14-inch 3K 120Hz OLED compact gaming laptop with AMD Ryzen 9 and RTX 4070.",
    tags: ["asus", "rog", "zephyrus-g14", "compact", "oled", "portable"],
  },
  {
    id: "lenovo-legion-pro-7i",
    name: "Lenovo Legion Pro 7i Gen 9",
    brand: "Lenovo Legion",
    subcategory: "Gaming Laptops",
    sectionId: "gaming-laptops",
    sectionTitle: "Gaming Laptops (ROG, Legion, Predator, Omen)",
    description: "AI-tuned Legion Coldfront vapor chamber cooling, 16-inch WQXGA 240Hz display, and full-power RTX 4080.",
    tags: ["lenovo", "legion", "laptop", "rtx4080", "coldfront"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "lenovo-legion-5i",
    name: "Lenovo Legion 5i",
    brand: "Lenovo Legion",
    subcategory: "Gaming Laptops",
    sectionId: "gaming-laptops",
    sectionTitle: "Gaming Laptops (ROG, Legion, Predator, Omen)",
    description: "All-metal A-cover with Intel Core i7 14650HX, RTX 4060, and 165Hz PureSight gaming screen.",
    tags: ["lenovo", "legion", "laptop", "rtx4060", "value"],
  },
  {
    id: "lenovo-loq-15",
    name: "Lenovo LOQ 15",
    brand: "Lenovo Legion",
    subcategory: "Gaming Laptops",
    sectionId: "budget-gaming",
    sectionTitle: "Student & Budget Gaming Champions",
    description: "India's highest value student gaming laptop with 100% sRGB display and Lenovo LA1 AI chip.",
    tags: ["lenovo", "loq", "budget-laptop", "student", "value"],
    badge: "POPULAR",
  },
  {
    id: "acer-predator-helios-16",
    name: "Acer Predator Helios 16",
    brand: "Acer Predator",
    subcategory: "Gaming Laptops",
    sectionId: "gaming-laptops",
    sectionTitle: "Gaming Laptops (ROG, Legion, Predator, Omen)",
    description: "5th Gen AeroBlade 3D metal fans, liquid metal thermal grease, and 240Hz WQXGA panel.",
    tags: ["acer", "predator", "helios", "laptop", "cooling"],
  },
  {
    id: "acer-nitro-v-15",
    name: "Acer Nitro V 15",
    brand: "Acer Predator",
    subcategory: "Gaming Laptops",
    sectionId: "budget-gaming",
    sectionTitle: "Student & Budget Gaming Champions",
    description: "Affordable 144Hz FHD gaming laptop with RTX 4050 / RTX 4060 for popular esports titles.",
    tags: ["acer", "nitro", "budget-laptop", "esports"],
  },
  {
    id: "hp-omen-transcend-14",
    name: "HP Omen Transcend 14",
    brand: "HP Omen",
    subcategory: "Gaming Laptops",
    sectionId: "gaming-laptops",
    sectionTitle: "Gaming Laptops (ROG, Legion, Predator, Omen)",
    description: "World's lightest 14-inch OLED gaming laptop with Intel Core Ultra 9 and HyperX audio tuning.",
    tags: ["hp", "omen", "transcend", "oled", "lightweight"],
  },
  {
    id: "hp-victus-16",
    name: "HP Victus 16",
    brand: "HP Omen",
    subcategory: "Gaming Laptops",
    sectionId: "gaming-laptops",
    sectionTitle: "Gaming Laptops (ROG, Legion, Predator, Omen)",
    description: "Clean minimalist design with OMEN Tempest cooling and high refresh rate display.",
    tags: ["hp", "victus", "laptop", "value"],
  },
  {
    id: "alienware-m16-r2",
    name: "Alienware m16 R2",
    brand: "Alienware",
    subcategory: "Gaming Laptops",
    sectionId: "gaming-laptops",
    sectionTitle: "Gaming Laptops (ROG, Legion, Predator, Omen)",
    description: "Redesigned compact footprint with Stealth Mode button, AlienFX lighting, and Cryo-tech cooling.",
    tags: ["alienware", "laptop", "m16", "cryotech", "premium"],
  },
  {
    id: "msi-raider-ge78-hx",
    name: "MSI Raider GE78 HX",
    brand: "MSI",
    subcategory: "Gaming Laptops",
    sectionId: "gaming-laptops",
    sectionTitle: "Gaming Laptops (ROG, Legion, Predator, Omen)",
    description: "Matrix RGB light bar, 240Hz QHD+ display, Dynaudio 6-speaker system, and RTX 4090 power.",
    tags: ["msi", "raider", "laptop", "rgb", "flagship"],
  },
  {
    id: "msi-cyborg-15",
    name: "MSI Cyborg 15",
    brand: "MSI",
    subcategory: "Gaming Laptops",
    sectionId: "budget-gaming",
    sectionTitle: "Student & Budget Gaming Champions",
    description: "Translucent cybernetic chassis with 144Hz gaming panel and dedicated WASD key highlights.",
    tags: ["msi", "cyborg", "budget-laptop", "cyberpunk"],
  },
  {
    id: "asus-tuf-gaming-a15",
    name: "ASUS TUF Gaming A15",
    brand: "ASUS ROG",
    subcategory: "Gaming Laptops",
    sectionId: "gaming-laptops",
    sectionTitle: "Gaming Laptops (ROG, Legion, Predator, Omen)",
    description: "Military-grade MIL-STD-810H durability with 90Wh battery and AMD Ryzen 7 processor.",
    tags: ["asus", "tuf", "laptop", "durable", "battery"],
  },
  {
    id: "gaming-laptop",
    name: "High-Performance Gaming Laptop",
    brand: "Plugd Gaming",
    subcategory: "Gaming Laptops",
    sectionId: "gaming-laptops",
    sectionTitle: "Gaming Laptops (ROG, Legion, Predator, Omen)",
    description: "High-refresh portable powerhouse with dedicated GPU and cooling for mobile creators.",
    tags: ["laptop", "gaming", "portable"],
  },

  // === Consoles & Handhelds ===
  {
    id: "playstation-5-pro",
    name: "PlayStation 5 Pro",
    brand: "Sony PlayStation",
    subcategory: "Consoles",
    sectionId: "console-gaming",
    sectionTitle: "Console Gaming (PlayStation, Xbox, Nintendo)",
    description: "PlayStation Spectral Super Resolution (PSSR) AI upscaling, 2TB SSD, and 67% more GPU compute units for 4K 60fps ray tracing.",
    tags: ["playstation", "ps5pro", "ps5", "console", "sony", "4k60", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "playstation-5-slim",
    name: "PlayStation 5 Slim (Disc Edition)",
    brand: "Sony PlayStation",
    subcategory: "Consoles",
    sectionId: "console-gaming",
    sectionTitle: "Console Gaming (PlayStation, Xbox, Nintendo)",
    description: "30% smaller volume with 1TB SSD storage, Ultra HD Blu-ray disc drive, and DualSense haptic feedback.",
    tags: ["playstation", "ps5", "console", "sony", "4k", "bestseller"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "playstation-5",
    name: "PlayStation 5",
    brand: "Sony PlayStation",
    subcategory: "Consoles",
    sectionId: "console-gaming",
    sectionTitle: "Console Gaming (PlayStation, Xbox, Nintendo)",
    description: "The flagship home console delivering high-fidelity next-gen gaming with ultra-fast custom SSD.",
    tags: ["playstation", "ps5", "console", "sony"],
  },
  {
    id: "xbox-series-x",
    name: "Xbox Series X 1TB",
    brand: "Xbox",
    subcategory: "Consoles",
    sectionId: "console-gaming",
    sectionTitle: "Console Gaming (PlayStation, Xbox, Nintendo)",
    description: "12 teraflops of raw graphic processing power, Quick Resume for multiple games, and Xbox Game Pass Ultimate integration.",
    tags: ["xbox", "series-x", "console", "gamepass", "microsoft", "4k120"],
    featured: true,
  },
  {
    id: "xbox-series-s",
    name: "Xbox Series S 1TB Carbon Black",
    brand: "Xbox",
    subcategory: "Consoles",
    sectionId: "budget-gaming",
    sectionTitle: "Student & Budget Gaming Champions",
    description: "All-digital compact next-gen gaming console with 1TB SSD and access to hundreds of Game Pass titles.",
    tags: ["xbox", "series-s", "console", "budget", "gamepass"],
  },
  {
    id: "nintendo-switch-oled",
    name: "Nintendo Switch OLED Model",
    brand: "Nintendo",
    subcategory: "Handhelds",
    sectionId: "handheld-gaming",
    sectionTitle: "Handheld Gaming (Steam Deck, ROG Ally, Legion Go)",
    description: "Vibrant 7-inch OLED screen with wide adjustable stand, enhanced audio, and 64GB internal storage for handheld and TV gaming.",
    tags: ["nintendo", "switch", "oled", "handheld", "console"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "steam-deck-oled",
    name: "Valve Steam Deck OLED 1TB",
    brand: "Valve",
    subcategory: "Handhelds",
    sectionId: "handheld-gaming",
    sectionTitle: "Handheld Gaming (Steam Deck, ROG Ally, Legion Go)",
    description: "90Hz HDR OLED display, premium anti-glare etched glass, 50Wh battery, and complete access to the full Steam PC library.",
    tags: ["steam", "steamdeck", "oled", "handheld", "pc-gaming", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "steam-deck",
    name: "Steam Deck",
    brand: "Valve",
    subcategory: "Handhelds",
    sectionId: "handheld-gaming",
    sectionTitle: "Handheld Gaming (Steam Deck, ROG Ally, Legion Go)",
    description: "Portable PC gaming handheld with customizable trackpads and gyro controls.",
    tags: ["steam", "steamdeck", "handheld"],
  },
  {
    id: "asus-rog-ally-x",
    name: "ASUS ROG Ally X Handheld",
    brand: "ASUS ROG",
    subcategory: "Handhelds",
    sectionId: "handheld-gaming",
    sectionTitle: "Handheld Gaming (Steam Deck, ROG Ally, Legion Go)",
    description: "AMD Ryzen Z1 Extreme with massive 80Wh battery, 24GB LPDDR5X RAM, 1TB NVMe, and 120Hz 1080p FreeSync display.",
    tags: ["asus", "rog", "ally-x", "handheld", "windows-gaming", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "lenovo-legion-go",
    name: "Lenovo Legion Go",
    brand: "Lenovo Legion",
    subcategory: "Handhelds",
    sectionId: "handheld-gaming",
    sectionTitle: "Handheld Gaming (Steam Deck, ROG Ally, Legion Go)",
    description: "Huge 8.8-inch QHD+ 144Hz display with detachable TrueStrike controllers and FPS mouse mode.",
    tags: ["lenovo", "legion-go", "handheld", "detachable-controllers", "144hz"],
    featured: true,
  },
  {
    id: "msi-claw-a1m",
    name: "MSI Claw A1M Handheld",
    brand: "MSI",
    subcategory: "Handhelds",
    sectionId: "handheld-gaming",
    sectionTitle: "Handheld Gaming (Steam Deck, ROG Ally, Legion Go)",
    description: "Intel Core Ultra 7 with Cooler Boost HyperFlow technology and ergonomic hall-effect triggers.",
    tags: ["msi", "claw", "handheld", "intel"],
  },
  {
    id: "playstation-portal",
    name: "PlayStation Portal Remote Player",
    brand: "Sony PlayStation",
    subcategory: "Handhelds",
    sectionId: "console-gaming",
    sectionTitle: "Console Gaming (PlayStation, Xbox, Nintendo)",
    description: "8-inch 1080p 60fps screen with integrated DualSense adaptive triggers streaming directly from your PS5 over Wi-Fi.",
    tags: ["playstation", "portal", "remote-play", "sony", "handheld"],
  },

  // === Gaming Monitors ===
  {
    id: "samsung-odyssey-oled-g9",
    name: "Samsung Odyssey OLED G9 49\"",
    brand: "Samsung",
    subcategory: "Monitors",
    sectionId: "gaming-monitors",
    sectionTitle: "Esports & High-Refresh Gaming Monitors",
    description: "49-inch Dual QHD curved 240Hz OLED gaming monitor with 0.03ms response time and Neo Quantum Processor Pro.",
    tags: ["samsung", "odyssey", "g9", "oled", "ultrawide", "240hz", "flagship", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "samsung-odyssey-oled-g8",
    name: "Samsung Odyssey OLED G8 34\"",
    brand: "Samsung",
    subcategory: "Monitors",
    sectionId: "gaming-monitors",
    sectionTitle: "Esports & High-Refresh Gaming Monitors",
    description: "UWQHD 175Hz OLED curved display with CoreSync lighting and smart TV entertainment hub.",
    tags: ["samsung", "odyssey", "g8", "oled", "curved"],
  },
  {
    id: "lg-ultragear-oled-32gs95ue",
    name: "LG UltraGear OLED 32GS95UE Dual-Hz",
    brand: "LG",
    subcategory: "Monitors",
    sectionId: "gaming-monitors",
    sectionTitle: "Esports & High-Refresh Gaming Monitors",
    description: "World's first Dual-Hz OLED monitor switching instantly between 4K 240Hz (AAA immersion) and FHD 480Hz (Pro Esports).",
    tags: ["lg", "ultragear", "oled", "480hz", "4k240hz", "dual-hz", "flagship"],
    badge: "ENTHUSIAST",
    featured: true,
  },
  {
    id: "asus-rog-swift-oled-pg32ucdm",
    name: "ASUS ROG Swift OLED PG32UCDM 32\"",
    brand: "ASUS ROG",
    subcategory: "Monitors",
    sectionId: "gaming-monitors",
    sectionTitle: "Esports & High-Refresh Gaming Monitors",
    description: "32-inch 4K QD-OLED with 240Hz refresh rate, custom graphene heatsink, and 99% DCI-P3 color gamut.",
    tags: ["asus", "rog", "swift", "qd-oled", "4k240hz", "flagship"],
    badge: "HOT",
    featured: true,
  },
  {
    id: "alienware-aw3423dwf-qd-oled",
    name: "Alienware AW3423DWF 34\" Curved QD-OLED",
    brand: "Alienware",
    subcategory: "Monitors",
    sectionId: "gaming-monitors",
    sectionTitle: "Esports & High-Refresh Gaming Monitors",
    description: "Legend 2.0 design with 1800R curve, 165Hz refresh rate, infinite contrast ratio, and AMD FreeSync Premium Pro.",
    tags: ["alienware", "qd-oled", "curved", "ultrawide", "monitor"],
    badge: "POPULAR",
  },
  {
    id: "benq-zowie-xl2566k-360hz",
    name: "BenQ ZOWIE XL2566K 360Hz Esports Monitor",
    brand: "BenQ / Zowie",
    subcategory: "Monitors",
    sectionId: "gaming-monitors",
    sectionTitle: "Esports & High-Refresh Gaming Monitors",
    description: "The competitive FPS tournament standard with DyAc+ motion clarity technology and fast TN panel.",
    tags: ["benq", "zowie", "360hz", "esports", "fps", "cs2", "valorant"],
    badge: "POPULAR",
  },
  {
    id: "gigabyte-m27q-170hz",
    name: "Gigabyte M27Q 27\" 170Hz 1440p Monitor",
    brand: "Gigabyte",
    subcategory: "Monitors",
    sectionId: "gaming-monitors",
    sectionTitle: "Esports & High-Refresh Gaming Monitors",
    description: "India's highest rated 1440p IPS gaming monitor with built-in KVM switch and 0.5ms response time.",
    tags: ["gigabyte", "1440p", "170hz", "kvm", "value", "bestseller"],
  },
  {
    id: "aoc-24g2-165hz",
    name: "AOC 24G2 24\" 165Hz Gaming Monitor",
    brand: "AOC",
    subcategory: "Monitors",
    sectionId: "budget-gaming",
    sectionTitle: "Student & Budget Gaming Champions",
    description: "Affordable 1080p IPS gaming screen with 165Hz refresh, 1ms MPRT, and height-adjustable stand.",
    tags: ["aoc", "1080p", "165hz", "budget", "student"],
  },
  {
    id: "oled-gaming-monitor",
    name: "OLED Gaming Monitor",
    brand: "Plugd Display",
    subcategory: "Monitors",
    sectionId: "gaming-monitors",
    sectionTitle: "Esports & High-Refresh Gaming Monitors",
    description: "High-refresh rate display with deep blacks and fast pixel response.",
    tags: ["monitor", "oled", "gaming"],
  },

  // === Keyboards & Mice ===
  {
    id: "wooting-80he",
    name: "Wooting 80HE Hall Effect Keyboard",
    brand: "Wooting",
    subcategory: "Keyboards",
    sectionId: "keyboards-hall-effect",
    sectionTitle: "Keyboards & Hall-Effect Magnetic Switches",
    description: "World-leading 80% magnetic analog keyboard with 0.1mm Rapid Trigger, 8000Hz polling rate, and PCR switch technology.",
    tags: ["wooting", "80he", "hall-effect", "rapid-trigger", "magnetic", "esports", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "wooting-60he-plus",
    name: "Wooting 60HE+ Analog Gaming Keyboard",
    brand: "Wooting",
    subcategory: "Keyboards",
    sectionId: "keyboards-hall-effect",
    sectionTitle: "Keyboards & Hall-Effect Magnetic Switches",
    description: "The viral 60% tournament board with full analog Lekker switches and web-based Wootility configuration.",
    tags: ["wooting", "60he", "analog", "rapid-trigger", "valorant", "cs2"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "keychron-q1-he",
    name: "Keychron Q1 HE Wireless Magnetic Keyboard",
    brand: "Keychron",
    subcategory: "Keyboards",
    sectionId: "keyboards-hall-effect",
    sectionTitle: "Keyboards & Hall-Effect Magnetic Switches",
    description: "All-metal CNC aluminum custom keyboard with Gateron magnetic switches, 2.4G wireless, and gasket mount acoustic foam.",
    tags: ["keychron", "q1he", "magnetic", "aluminum", "wireless", "custom-keyboard"],
    featured: true,
  },
  {
    id: "razer-huntsman-v3-pro",
    name: "Razer Huntsman V3 Pro TKL",
    brand: "Razer",
    subcategory: "Keyboards",
    sectionId: "keyboards-hall-effect",
    sectionTitle: "Keyboards & Hall-Effect Magnetic Switches",
    description: "Gen-2 analog optical switches with onboard rapid trigger adjustment and textured doubleshot PBT keycaps.",
    tags: ["razer", "huntsman", "rapid-trigger", "optical", "tkl"],
    badge: "POPULAR",
  },
  {
    id: "razer-blackwidow-v4-pro",
    name: "Razer BlackWidow V4 Pro",
    brand: "Razer",
    subcategory: "Keyboards",
    sectionId: "keyboards-hall-effect",
    sectionTitle: "Keyboards & Hall-Effect Magnetic Switches",
    description: "Full-size mechanical keyboard with Razer Command Dial, 8 dedicated macro keys, and underglow RGB.",
    tags: ["razer", "blackwidow", "mechanical", "macros", "rgb"],
  },
  {
    id: "logitech-g-pro-x-tkl",
    name: "Logitech G PRO X TKL LIGHTSPEED",
    brand: "Logitech G",
    subcategory: "Keyboards",
    sectionId: "keyboards-hall-effect",
    sectionTitle: "Keyboards & Hall-Effect Magnetic Switches",
    description: "Tournament-proven wireless mechanical keyboard with LIGHTSPEED wireless and durable dual-shot PBT keycaps.",
    tags: ["logitech", "g-pro", "lightspeed", "wireless", "esports"],
  },
  {
    id: "steelseries-apex-pro-tkl",
    name: "SteelSeries Apex Pro TKL Gen 3",
    brand: "SteelSeries",
    subcategory: "Keyboards",
    sectionId: "keyboards-hall-effect",
    sectionTitle: "Keyboards & Hall-Effect Magnetic Switches",
    description: "OmniPoint 3.0 adjustable magnetic switches with OLED Smart Display and triple-layer acoustic dampening foam.",
    tags: ["steelseries", "apex-pro", "omnipoint", "oled", "magnetic"],
  },
  {
    id: "asus-rog-azoth-75",
    name: "ASUS ROG Azoth 75% Custom Keyboard",
    brand: "ASUS ROG",
    subcategory: "Keyboards",
    sectionId: "keyboards-hall-effect",
    sectionTitle: "Keyboards & Hall-Effect Magnetic Switches",
    description: "Enthusiast gasket mount with pre-lubed ROG NX switches, OLED display, and DIY switch lube kit included.",
    tags: ["asus", "rog", "azoth", "gasket-mount", "custom", "enthusiast"],
    badge: "ENTHUSIAST",
  },
  {
    id: "redragon-k552-kumara",
    name: "Redragon K552 Kumara Mechanical Keyboard",
    brand: "Redragon",
    subcategory: "Keyboards",
    sectionId: "budget-gaming",
    sectionTitle: "Student & Budget Gaming Champions",
    description: "India's highest selling budget mechanical gaming keyboard with dustproof mechanical switches.",
    tags: ["redragon", "k552", "budget", "mechanical", "student"],
  },
  {
    id: "mechanical-keyboard",
    name: "Mechanical Keyboard",
    brand: "Plugd Peripherals",
    subcategory: "Keyboards",
    sectionId: "keyboards-hall-effect",
    sectionTitle: "Keyboards & Hall-Effect Magnetic Switches",
    description: "Satisfying tactile switch mechanical keyboard for responsive keystrokes.",
    tags: ["keyboard", "mechanical", "gaming"],
  },
  {
    id: "logitech-g-pro-x-superlight-2",
    name: "Logitech G PRO X Superlight 2",
    brand: "Logitech G",
    subcategory: "Mice",
    sectionId: "gaming-mice",
    sectionTitle: "Pro Esports Gaming Mice",
    description: "60g ultra-lightweight esports icon with LIGHTFORCE hybrid optical-mechanical switches and HERO 2 sensor.",
    tags: ["logitech", "g-pro", "superlight2", "mouse", "lightweight", "esports", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "razer-deathadder-v3-pro",
    name: "Razer DeathAdder V3 Pro",
    brand: "Razer",
    subcategory: "Mice",
    sectionId: "gaming-mice",
    sectionTitle: "Pro Esports Gaming Mice",
    description: "63g ergonomic shape refined with pro players, Focus Pro 30K Optical Sensor, and 8000Hz HyperPolling support.",
    tags: ["razer", "deathadder", "mouse", "ergonomic", "esports", "bestseller"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "razer-viper-v3-pro",
    name: "Razer Viper V3 Pro",
    brand: "Razer",
    subcategory: "Mice",
    sectionId: "gaming-mice",
    sectionTitle: "Pro Esports Gaming Mice",
    description: "54g symmetrical championship mouse with true 8000Hz wireless polling rate included in the box.",
    tags: ["razer", "viper", "mouse", "8000hz", "lightweight"],
    badge: "HOT",
  },
  {
    id: "pulsar-x2v2-wireless",
    name: "Pulsar X2V2 Wireless Gaming Mouse",
    brand: "Pulsar",
    subcategory: "Mice",
    sectionId: "gaming-mice",
    sectionTitle: "Pro Esports Gaming Mice",
    description: "53g symmetrical claw-grip mouse with optical switches and Nordic MCU sensor controller.",
    tags: ["pulsar", "x2v2", "mouse", "claw-grip", "enthusiast"],
  },
  {
    id: "zowie-ec2-cw-wireless",
    name: "ZOWIE EC2-CW Wireless Esports Mouse",
    brand: "BenQ / Zowie",
    subcategory: "Mice",
    sectionId: "gaming-mice",
    sectionTitle: "Pro Esports Gaming Mice",
    description: "Asymmetrical ergonomic mouse with enhanced wireless receiver dock providing interference-free tournament stability.",
    tags: ["zowie", "ec2", "wireless", "esports", "mouse"],
  },
  {
    id: "glorious-model-o-2",
    name: "Glorious Model O 2 Wireless",
    brand: "Glorious",
    subcategory: "Mice",
    sectionId: "gaming-mice",
    sectionTitle: "Pro Esports Gaming Mice",
    description: "68g honeycomb shell mouse with BAMF 2.0 26K sensor and 210 hours battery life.",
    tags: ["glorious", "model-o", "honeycomb", "mouse"],
  },
  {
    id: "logitech-g502-x-plus",
    name: "Logitech G502 X PLUS LIGHTSPEED",
    brand: "Logitech G",
    subcategory: "Mice",
    sectionId: "gaming-mice",
    sectionTitle: "Pro Esports Gaming Mice",
    description: "The latest evolution of the iconic G502 with 8-zone active RGB, dual-mode hyper-fast scroll wheel, and 13 programmable controls.",
    tags: ["logitech", "g502", "mouse", "rgb", "programmable"],
    badge: "POPULAR",
  },
  {
    id: "logitech-g203-lightsync",
    name: "Logitech G203 Lightsync RGB",
    brand: "Logitech G",
    subcategory: "Mice",
    sectionId: "budget-gaming",
    sectionTitle: "Student & Budget Gaming Champions",
    description: "Classic 6-button gaming shape with 8000 DPI sensor and vibrant Lightsync RGB lighting.",
    tags: ["logitech", "g203", "budget-mouse", "student", "bestseller"],
  },

  // === Headsets & Audio ===
  {
    id: "steelseries-arctis-nova-pro-wireless",
    name: "SteelSeries Arctis Nova Pro Wireless",
    brand: "SteelSeries",
    subcategory: "Headsets",
    sectionId: "gaming-audio",
    sectionTitle: "Immersive Audio & Headsets",
    description: "Multi-system GameDAC Gen 2, Active Noise Cancellation, Infinity Power hot-swappable dual battery system, and 360 Spatial Audio.",
    tags: ["steelseries", "arctis-nova", "headset", "anc", "wireless", "flagship", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "razer-blackshark-v2-pro",
    name: "Razer BlackShark V2 Pro (2024 Edition)",
    brand: "Razer",
    subcategory: "Headsets",
    sectionId: "gaming-audio",
    sectionTitle: "Immersive Audio & Headsets",
    description: "HyperClear Super Wideband mic delivering studio-grade broadcast voice with TriForce Titanium 50mm drivers.",
    tags: ["razer", "blackshark", "headset", "microphone", "esports", "bestseller"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "logitech-g-pro-x-2-lightspeed",
    name: "Logitech G PRO X 2 LIGHTSPEED",
    brand: "Logitech G",
    subcategory: "Headsets",
    sectionId: "gaming-audio",
    sectionTitle: "Immersive Audio & Headsets",
    description: "Revolutionary 50mm Graphene drivers providing unprecedented spatial audio separation and 50-hour battery life.",
    tags: ["logitech", "g-pro", "graphene", "headset", "wireless"],
  },
  {
    id: "hyperx-cloud-iii-wireless",
    name: "HyperX Cloud III Wireless",
    brand: "HyperX",
    subcategory: "Headsets",
    sectionId: "gaming-audio",
    sectionTitle: "Immersive Audio & Headsets",
    description: "Legendary HyperX memory foam comfort with up to 120 hours of battery life and angled 53mm audio drivers.",
    tags: ["hyperx", "cloud3", "headset", "battery", "comfort"],
    badge: "POPULAR",
  },
  {
    id: "sony-inzone-h9",
    name: "Sony INZONE H9 Wireless Gaming Headset",
    brand: "Sony PlayStation",
    subcategory: "Headsets",
    sectionId: "gaming-audio",
    sectionTitle: "Immersive Audio & Headsets",
    description: "Sony Dual Noise Sensor technology, 360 Spatial Sound for Gaming, and seamless PS5 on-screen status sync.",
    tags: ["sony", "inzone", "ps5", "anc", "spatial-audio"],
  },
  {
    id: "corsair-hs80-max",
    name: "Corsair HS80 MAX Wireless",
    brand: "Corsair",
    subcategory: "Headsets",
    sectionId: "gaming-audio",
    sectionTitle: "Immersive Audio & Headsets",
    description: "Dolby Atmos spatial audio with broadcast-grade omnidirectional microphone and Sonarworks SoundID tuning.",
    tags: ["corsair", "hs80", "dolby-atmos", "headset"],
  },

  // === Controllers ===
  {
    id: "dualsense-edge-wireless-controller",
    name: "Sony DualSense Edge Wireless Controller",
    brand: "Sony PlayStation",
    subcategory: "Controllers",
    sectionId: "console-gaming",
    sectionTitle: "Console Gaming (PlayStation, Xbox, Nintendo)",
    description: "Pro controller with replaceable stick modules, changeable stick caps, remappable back buttons, and adjustable trigger stops.",
    tags: ["sony", "dualsense-edge", "controller", "ps5", "pro-controller", "trending"],
    badge: "HOT",
    featured: true,
  },
  {
    id: "xbox-elite-wireless-controller-series-2",
    name: "Xbox Elite Wireless Controller Series 2",
    brand: "Xbox",
    subcategory: "Controllers",
    sectionId: "console-gaming",
    sectionTitle: "Console Gaming (PlayStation, Xbox, Nintendo)",
    description: "Adjustable-tension thumbsticks, wrap-around rubberized grip, shorter hair trigger locks, and 40 hours of rechargeable battery.",
    tags: ["xbox", "elite", "controller", "pc-gaming", "pro"],
    badge: "POPULAR",
  },
  {
    id: "sony-dualsense-wireless-controller",
    name: "Sony DualSense Wireless Controller",
    brand: "Sony PlayStation",
    subcategory: "Controllers",
    sectionId: "console-gaming",
    sectionTitle: "Console Gaming (PlayStation, Xbox, Nintendo)",
    description: "Immersive haptic feedback, dynamic adaptive triggers, and built-in microphone for PS5 and PC gaming.",
    tags: ["sony", "dualsense", "controller", "ps5", "haptics"],
  },
  {
    id: "xbox-wireless-controller",
    name: "Xbox Wireless Controller",
    brand: "Xbox",
    subcategory: "Controllers",
    sectionId: "console-gaming",
    sectionTitle: "Console Gaming (PlayStation, Xbox, Nintendo)",
    description: "Sculpted surfaces and refined geometry with hybrid D-pad and textured grip on triggers and bumpers.",
    tags: ["xbox", "controller", "pc-controller", "bestseller"],
  },
  {
    id: "8bitdo-ultimate-bluetooth-controller",
    name: "8BitDo Ultimate Bluetooth Controller with Charging Dock",
    brand: "8BitDo",
    subcategory: "Controllers",
    sectionId: "budget-gaming",
    sectionTitle: "Student & Budget Gaming Champions",
    description: "Hall Effect drift-free sensing joysticks, 2.4G & Bluetooth, custom profile switch, and magnetic charging dock.",
    tags: ["8bitdo", "hall-effect", "controller", "dock", "value"],
    badge: "POPULAR",
  },
  {
    id: "custom-controller",
    name: "Custom Controller",
    brand: "Plugd Gaming",
    subcategory: "Controllers",
    sectionId: "console-gaming",
    sectionTitle: "Console Gaming (PlayStation, Xbox, Nintendo)",
    description: "Custom textured grips and tactile buttons for competitive tournament gameplay.",
    tags: ["controller", "gamepad", "custom", "custom-controller"],
  },

  // === Streaming Gear ===
  {
    id: "elgato-stream-deck-xl",
    name: "Elgato Stream Deck XL",
    brand: "Elgato",
    subcategory: "Streaming",
    sectionId: "streaming-gear",
    sectionTitle: "Creator & Pro Streaming Battlestation",
    description: "32 customizable LCD keys with folder organization, live integrations for OBS, Twitch, Discord, and studio hardware control.",
    tags: ["elgato", "streamdeck", "streaming", "creator", "macros", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "elgato-stream-deck-plus",
    name: "Elgato Stream Deck +",
    brand: "Elgato",
    subcategory: "Streaming",
    sectionId: "streaming-gear",
    sectionTitle: "Creator & Pro Streaming Battlestation",
    description: "8 LCD keys, dynamic touch strip, and 4 rotary dials for audio mixing, camera zoom, and color grading control.",
    tags: ["elgato", "streamdeck", "audio-mixer", "dials", "streaming"],
    badge: "POPULAR",
  },
  {
    id: "elgato-wave-3",
    name: "Elgato Wave:3 USB Microphone",
    brand: "Elgato",
    subcategory: "Streaming",
    sectionId: "streaming-gear",
    sectionTitle: "Creator & Pro Streaming Battlestation",
    description: "Premium cardioid condenser capsule with Clipguard anti-distortion technology and digital Wave Link audio mixer.",
    tags: ["elgato", "wave3", "microphone", "usb-mic", "streaming"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "shure-sm7b",
    name: "Shure SM7B Cardioid Dynamic Microphone",
    brand: "Shure",
    subcategory: "Streaming",
    sectionId: "streaming-gear",
    sectionTitle: "Creator & Pro Streaming Battlestation",
    description: "The gold-standard vocal broadcasting microphone providing warm, smooth capture with electromagnetic hum shielding.",
    tags: ["shure", "sm7b", "xlr-mic", "broadcast", "studio", "streaming", "flagship"],
    badge: "ENTHUSIAST",
    featured: true,
  },
  {
    id: "rode-podmic-usb",
    name: "Rode PodMic USB / XLR",
    brand: "Rode",
    subcategory: "Streaming",
    sectionId: "streaming-gear",
    sectionTitle: "Creator & Pro Streaming Battlestation",
    description: "Versatile broadcast dynamic mic with dual USB-C and XLR connections, built-in APHEX DSP, and internal pop filter.",
    tags: ["rode", "podmic", "microphone", "streaming", "podcast"],
  },
  {
    id: "focusrite-scarlett-2i2-4th-gen",
    name: "Focusrite Scarlett 2i2 4th Gen Audio Interface",
    brand: "Focusrite",
    subcategory: "Streaming",
    sectionId: "streaming-gear",
    sectionTitle: "Creator & Pro Streaming Battlestation",
    description: "Ultra-low-noise preamps with 120dB dynamic range, Auto Gain, Clip Safe, and redesigned Air Mode.",
    tags: ["focusrite", "scarlett", "audio-interface", "xlr", "dac"],
  },
  {
    id: "elgato-key-light-air",
    name: "Elgato Key Light Air",
    brand: "Elgato",
    subcategory: "Streaming",
    sectionId: "streaming-gear",
    sectionTitle: "Creator & Pro Streaming Battlestation",
    description: "1400 lumens app-controlled edge-lit LED panel with flicker-free diffusion and adjustable color temperature.",
    tags: ["elgato", "lighting", "keylight", "streaming", "studio"],
  },
  {
    id: "elgato-facecam-pro-4k60",
    name: "Elgato Facecam Pro 4K60",
    brand: "Elgato",
    subcategory: "Streaming",
    sectionId: "streaming-gear",
    sectionTitle: "Creator & Pro Streaming Battlestation",
    description: "World's first 4K 60fps webcam with Sony Starvis CMOS sensor and autofocus studio lens.",
    tags: ["elgato", "webcam", "4k60", "camera", "streaming"],
  },
  {
    id: "elgato-cam-link-4k",
    name: "Elgato Cam Link 4K",
    brand: "Elgato",
    subcategory: "Streaming",
    sectionId: "streaming-gear",
    sectionTitle: "Creator & Pro Streaming Battlestation",
    description: "Connect DSLR, mirrorless camera, or action cam directly to PC or Mac as a professional webcam.",
    tags: ["elgato", "camlink", "capture-card", "dslr"],
  },
  {
    id: "capture-card",
    name: "HD Game Capture Card",
    brand: "Plugd Stream",
    subcategory: "Streaming",
    sectionId: "streaming-gear",
    sectionTitle: "Creator & Pro Streaming Battlestation",
    description: "Capture and pass-through ultra low-latency console video directly into OBS.",
    tags: ["capture-card", "stream", "obs"],
  },
  {
    id: "streaming-microphone",
    name: "Studio Streaming Microphone",
    brand: "Plugd Audio",
    subcategory: "Streaming",
    sectionId: "streaming-gear",
    sectionTitle: "Creator & Pro Streaming Battlestation",
    description: "High-clarity studio microphone for voice capture during gaming and live streaming.",
    tags: ["microphone", "voice", "streaming"],
  },

  // === Sim Racing ===
  {
    id: "fanatec-clubsport-dd-plus",
    name: "Fanatec ClubSport DD+ Direct Drive Racing Wheel",
    brand: "Fanatec",
    subcategory: "Sim Racing",
    sectionId: "sim-racing",
    sectionTitle: "Sim Racing & Flight Cockpits",
    description: "Direct-drive 15 Nm consistent torque with FullForce force feedback technology for PC and PlayStation.",
    tags: ["fanatec", "sim-racing", "direct-drive", "wheel", "f1", "gt7", "flagship"],
    badge: "ENTHUSIAST",
    featured: true,
  },
  {
    id: "moza-r9-v2-direct-drive",
    name: "Moza R9 V2 Direct Drive Wheelbase",
    brand: "Moza Racing",
    subcategory: "Sim Racing",
    sectionId: "sim-racing",
    sectionTitle: "Sim Racing & Flight Cockpits",
    description: "9 Nm direct drive torque in an aviation-grade aluminum unibody with Pit House mobile tuning app.",
    tags: ["moza", "direct-drive", "sim-racing", "wheelbase", "value"],
    badge: "POPULAR",
  },
  {
    id: "logitech-g-pro-racing-wheel",
    name: "Logitech G PRO Racing Wheel",
    brand: "Logitech G",
    subcategory: "Sim Racing",
    sectionId: "sim-racing",
    sectionTitle: "Sim Racing & Flight Cockpits",
    description: "11 Nm direct-drive motor with TRUEFORCE high-definition feedback and magnetic paddle shifters.",
    tags: ["logitech", "g-pro", "racing-wheel", "direct-drive", "trueforce"],
    badge: "HOT",
  },
  {
    id: "logitech-g923-racing-wheel",
    name: "Logitech G923 TRUEFORCE Wheel & Pedals",
    brand: "Logitech G",
    subcategory: "Sim Racing",
    sectionId: "sim-racing",
    sectionTitle: "Sim Racing & Flight Cockpits",
    description: "India's most popular sim racing wheel with progressive brake pedal, dual-clutch launch control, and TRUEFORCE feedback.",
    tags: ["logitech", "g923", "racing-wheel", "pedals", "sim-racing", "bestseller"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "thrustmaster-t300-rs-gt",
    name: "Thrustmaster T300 RS GT Edition",
    brand: "Thrustmaster",
    subcategory: "Sim Racing",
    sectionId: "sim-racing",
    sectionTitle: "Sim Racing & Flight Cockpits",
    description: "Dual-belt force feedback system with 1080-degree rotation and detachable GT-style racing wheel.",
    tags: ["thrustmaster", "t300", "racing-wheel", "gran-turismo"],
  },
  {
    id: "playseat-trophy-cockpit",
    name: "Playseat Trophy Logitech G Edition Cockpit",
    brand: "Playseat",
    subcategory: "Sim Racing",
    sectionId: "sim-racing",
    sectionTitle: "Sim Racing & Flight Cockpits",
    description: "Rigid ActiFit steel frame simulator cockpit engineered for high-torque direct-drive wheelbases.",
    tags: ["playseat", "cockpit", "racing-seat", "sim-rig"],
  },
  {
    id: "racing-wheel",
    name: "Simulation Racing Wheel Setup",
    brand: "Plugd Racing",
    subcategory: "Sim Racing",
    sectionId: "sim-racing",
    sectionTitle: "Sim Racing & Flight Cockpits",
    description: "Force-feedback racing wheel and pedal kit for motorsport and driving simulators.",
    tags: ["racing-wheel", "sim-racing", "motorsport"],
  },

  // === VR ===
  {
    id: "meta-quest-3",
    name: "Meta Quest 3 512GB VR Headset",
    brand: "Meta Quest",
    subcategory: "VR",
    sectionId: "vr-immersive",
    sectionTitle: "VR & Next-Gen Immersion",
    description: "High-resolution 4K+ Infinite Display with full-color mixed reality passthrough and Snapdragon XR2 Gen 2 power.",
    tags: ["meta", "quest3", "vr", "mixed-reality", "wireless-vr", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "playstation-vr2",
    name: "PlayStation VR2 Headset & Sense Controllers",
    brand: "Sony PlayStation",
    subcategory: "VR",
    sectionId: "vr-immersive",
    sectionTitle: "VR & Next-Gen Immersion",
    description: "4K HDR OLED displays, eye tracking, headset haptic feedback, and PC compatibility adapter support.",
    tags: ["sony", "psvr2", "vr", "ps5", "oled", "eye-tracking"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "meta-quest-3s",
    name: "Meta Quest 3S",
    brand: "Meta Quest",
    subcategory: "VR",
    sectionId: "vr-immersive",
    sectionTitle: "VR & Next-Gen Immersion",
    description: "Accessible mixed reality gaming headset featuring full color passthrough and Touch Plus controllers.",
    tags: ["meta", "quest3s", "vr", "mixed-reality", "value"],
    badge: "NEW",
  },
  {
    id: "vr-headset",
    name: "Immersive VR Gaming Headset",
    brand: "Plugd VR",
    subcategory: "VR",
    sectionId: "vr-immersive",
    sectionTitle: "VR & Next-Gen Immersion",
    description: "Virtual reality headset with motion controllers for 3D room-scale gaming.",
    tags: ["vr", "virtual-reality", "headset"],
  },

  // === Furniture & Setup ===
  {
    id: "secretlab-titan-evo-2024",
    name: "Secretlab TITAN Evo 2024 Gaming Chair",
    brand: "Secretlab",
    subcategory: "Gaming Setup",
    sectionId: "gaming-furniture-setup",
    sectionTitle: "Enthusiast Gaming Furniture & Desk Setup",
    description: "Ergonomic 4-way L-ADAPT lumbar support, magnetic CloudSwap armrests, and durable SoftWeave Plus fabric.",
    tags: ["secretlab", "titan-evo", "gaming-chair", "ergonomic", "battlestation", "trending"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "herman-miller-x-logitech-embody",
    name: "Herman Miller x Logitech G Embody Gaming Chair",
    brand: "Herman Miller",
    subcategory: "Gaming Setup",
    sectionId: "ultimate-setup",
    sectionTitle: "Ultimate Gaming Setup (Enthusiast)",
    description: "The pinnacle of ergonomic gaming seating with copper-infused cooling foam and BackFit adjustment.",
    tags: ["herman-miller", "logitech", "embody", "ergonomic-chair", "flagship", "enthusiast"],
    badge: "ENTHUSIAST",
    featured: true,
  },
  {
    id: "secretlab-magnus-pro-desk",
    name: "Secretlab MAGNUS Pro XL Sit-to-Stand Metal Desk",
    brand: "Secretlab",
    subcategory: "Gaming Setup",
    sectionId: "gaming-furniture-setup",
    sectionTitle: "Enthusiast Gaming Furniture & Desk Setup",
    description: "Full-metal chassis with integrated power column, magnetic cable management ecosystem, and ultra-smooth motorized lift.",
    tags: ["secretlab", "magnus-pro", "standing-desk", "metal-desk", "cable-management"],
    badge: "HOT",
    featured: true,
  },
  {
    id: "gaming-chair",
    name: "Gaming Chair",
    brand: "Plugd Setup",
    subcategory: "Gaming Setup",
    sectionId: "gaming-furniture-setup",
    sectionTitle: "Enthusiast Gaming Furniture & Desk Setup",
    description: "Comfortable bucket gaming seat with lumbar cushion and multi-tilt recline.",
    tags: ["chair", "gaming-chair", "furniture"],
  },
  {
    id: "rgb-setup-kit",
    name: "RGB Setup Kit",
    brand: "Plugd Setup",
    subcategory: "Gaming Setup",
    sectionId: "gaming-furniture-setup",
    sectionTitle: "Enthusiast Gaming Furniture & Desk Setup",
    description: "Smart dynamic lighting kit for desk underglow, monitor backlights, and stream aesthetics.",
    tags: ["rgb", "lighting", "ambiance", "battlestation", "rgb-setup-kit"],
  },
];

/**
 * Return all Gaming products with resolved image URLs and display orders.
 */
export function getFullGamingCatalog(): GamingProduct[] {
  return RAW_GAMING_PRODUCTS.map((p, idx) => ({
    id: p.id,
    name: p.name,
    brand: p.brand,
    category: "Gaming",
    subcategory: p.subcategory,
    sectionId: p.sectionId,
    sectionTitle: p.sectionTitle,
    imageUrl: getGamingProductImage(p.id),
    description: p.description,
    tags: p.tags,
    badge: p.badge,
    featured: Boolean(p.featured),
    trending: Boolean(p.trending),
    displayOrder: idx,
  }));
}

/**
 * Get distinct subcategories for gaming navigation
 */
export function getGamingSubcategories(): Array<{ name: string; count: number }> {
  const map = new Map<string, number>();
  for (const item of RAW_GAMING_PRODUCTS) {
    map.set(item.subcategory, (map.get(item.subcategory) || 0) + 1);
  }
  return Array.from(map.entries()).map(([name, count]) => ({ name, count }));
}
