/**
 * Comprehensive Mobiles Catalog Data Definition for Plugd
 * 
 * Broad Indian smartphone catalog covering all price tiers (budget to flagship),
 * major brands, subcategories, remote image URLs, and 16 discovery sections.
 */

import { getMobilesProductImage } from "./product-images";

export interface MobileProduct {
  id: string;
  name: string;
  brand: string;
  category: "Mobiles";
  subcategory: string;
  sectionId: string;
  sectionTitle: string;
  imageUrl: string;
  description: string;
  tags: string[];
  badge?: "HOT" | "TRENDING" | "NEW" | "POPULAR";
  featured?: boolean;
  trending?: boolean;
  displayOrder: number;
}

export interface MobileSection {
  id: string;
  title: string;
  subtitle: string;
  badge?: string;
  displayOrder: number;
  productIds: string[];
}

export const MOBILE_SECTIONS: MobileSection[] = [
  {
    id: "trending-phones",
    title: "Trending Phones",
    subtitle: "Most sought-after smartphones popular with Indian creators, power users, and tech enthusiasts",
    badge: "🔥 Hot",
    displayOrder: 1,
    productIds: [
      "iphone-17-pro-max",
      "iphone-17-pro",
      "iphone-17",
      "galaxy-s26-ultra",
      "galaxy-s25-ultra",
      "oneplus-13",
      "oneplus-13r",
      "pixel-10-pro",
      "pixel-9-pro-xl",
      "nothing-phone-3",
      "nothing-phone-2a",
      "iqoo-13",
      "vivo-x200-pro",
      "xiaomi-15-pro",
      "realme-gt-7-pro",
      "motorola-edge-50-ultra",
      "galaxy-z-fold6",
      "oneplus-open",
      "rog-phone-8-pro",
    ],
  },
  {
    id: "new-popular",
    title: "New & Popular",
    subtitle: "Latest smartphone launches delivering cutting-edge AI silicon, refined optics, and fresh designs",
    badge: "✨ Fresh",
    displayOrder: 2,
    productIds: [
      "iphone-17-pro",
      "iphone-17",
      "iphone-air",
      "galaxy-s26-ultra",
      "galaxy-s26",
      "oneplus-13",
      "oneplus-13r",
      "pixel-10-pro-xl",
      "pixel-9a",
      "vivo-x200",
      "oppo-find-x8-pro",
      "iqoo-13",
      "redmi-note-14-pro-plus",
      "realme-14-pro-plus",
      "motorola-razr-50-ultra",
      "nothing-phone-2a-plus",
      "lava-agni-3-5g",
    ],
  },
  {
    id: "best-value",
    title: "Best Value (Mid-Range Champions)",
    subtitle: "Maximum performance per rupee across the sweet spot ₹15k–₹45k Indian segment",
    badge: "🏆 Value",
    displayOrder: 3,
    productIds: [
      "oneplus-nord-4",
      "poco-x6-pro",
      "nothing-phone-2a",
      "motorola-edge-50-fusion",
      "vivo-t3-pro",
      "iqoo-z9s-pro",
      "realme-13-plus-5g",
      "redmi-note-14-pro",
      "cmf-phone-1",
      "galaxy-a36-5g",
      "oppo-f27-pro-plus-5g",
      "infinix-gt-20-pro",
      "lava-blaze-curve-5g",
    ],
  },
  {
    id: "flagship-phones",
    title: "Flagship Phones",
    subtitle: "Top-tier smartphones with uncompromised cameras, premium build, and peak performance",
    badge: "⚡ Flagship",
    displayOrder: 4,
    productIds: [
      "iphone-17-pro-max",
      "galaxy-s26-ultra",
      "galaxy-s25-ultra",
      "oneplus-13",
      "pixel-10-pro-xl",
      "vivo-x200-pro",
      "xiaomi-15-pro",
      "oppo-find-x8-pro",
      "iqoo-13",
      "honor-magic6-pro",
      "motorola-edge-50-ultra",
      "realme-gt-7-pro",
    ],
  },
  {
    id: "camera-phones",
    title: "Camera Phones",
    subtitle: "Industry-leading camera sensors, periscope telephoto zooms, and cinematic video tuning",
    badge: "📷 Optics",
    displayOrder: 5,
    productIds: [
      "vivo-x200-pro",
      "vivo-x100-pro",
      "pixel-9-pro-xl",
      "pixel-10-pro",
      "xiaomi-14-ultra",
      "iphone-16-pro-max",
      "iphone-17-pro-max",
      "galaxy-s25-ultra",
      "galaxy-s26-ultra",
      "oppo-find-x8-pro",
      "honor-200-pro",
      "tecno-camon-30-premier",
    ],
  },
  {
    id: "gaming-phones",
    title: "Gaming Phones",
    subtitle: "Shoulder triggers, active cooling, high-refresh AMOLED screens, and extreme sustained frame rates",
    badge: "🎮 Gaming",
    displayOrder: 6,
    productIds: [
      "rog-phone-8-pro",
      "rog-phone-8",
      "redmagic-9s-pro",
      "redmagic-9-pro",
      "iqoo-13",
      "iqoo-neo-9-pro",
      "poco-f6-pro",
      "poco-f6",
      "realme-gt-6",
      "infinix-gt-20-pro",
      "oneplus-12r",
    ],
  },
  {
    id: "budget-picks",
    title: "Budget Picks & Entry 5G",
    subtitle: "Reliable, battery-first, affordable 5G smartphones designed for Indian everyday users",
    badge: "💰 Budget",
    displayOrder: 7,
    productIds: [
      "redmi-a4-5g",
      "redmi-13c-5g",
      "redmi-13-5g",
      "poco-m6-plus-5g",
      "poco-c65",
      "moto-g45-5g",
      "moto-g64-5g",
      "realme-c65-5g",
      "realme-narzo-70x",
      "lava-blaze-3-5g",
      "lava-yuva-3-pro",
      "infinix-hot-50-5g",
      "infinix-smart-8",
      "tecno-spark-30",
      "galaxy-a26",
      "iqoo-z9-lite",
    ],
  },
  {
    id: "foldables-flips",
    title: "Foldables & Flip Phones",
    subtitle: "Next-generation foldable tablet-phones and pocket-friendly clamshell flip smartphones",
    badge: "📖 Foldable",
    displayOrder: 8,
    productIds: [
      "galaxy-z-fold6",
      "galaxy-z-flip6",
      "galaxy-z-fold5",
      "oneplus-open",
      "motorola-razr-50-ultra",
      "motorola-razr-50",
      "pixel-fold",
      "tecno-phantom-v-fold2",
      "tecno-phantom-v-flip2",
    ],
  },
  {
    id: "brand-apple",
    title: "Apple iPhone Collection",
    subtitle: "From the flagship Pro Max to everyday compact iPhones across generations",
    badge: "🍎 Apple",
    displayOrder: 9,
    productIds: [
      "iphone-17-pro-max",
      "iphone-17-pro",
      "iphone-17",
      "iphone-air",
      "iphone-16-pro-max",
      "iphone-16-pro",
      "iphone-16-plus",
      "iphone-16",
      "iphone-15-pro-max",
      "iphone-15-pro",
      "iphone-15-plus",
      "iphone-15",
      "iphone-14",
      "iphone-13",
      "iphone-se",
    ],
  },
  {
    id: "brand-samsung",
    title: "Samsung Galaxy Series",
    subtitle: "Ultra flagships, versatile A-series, long-lasting M-series, and innovative Z foldables",
    badge: "🌌 Samsung",
    displayOrder: 10,
    productIds: [
      "galaxy-s26-ultra",
      "galaxy-s26-plus",
      "galaxy-s26",
      "galaxy-s25-ultra",
      "galaxy-s25-plus",
      "galaxy-s25",
      "galaxy-s25-fe",
      "galaxy-s24-ultra",
      "galaxy-s24-plus",
      "galaxy-s24",
      "galaxy-a56-5g",
      "galaxy-a36-5g",
      "galaxy-a26",
      "galaxy-m55",
      "galaxy-m35",
      "galaxy-z-fold6",
      "galaxy-z-flip6",
    ],
  },
  {
    id: "brand-oneplus",
    title: "OnePlus Flagships & Nord",
    subtitle: "Fast and Smooth performance, Hasselblad camera tuning, and class-leading fast charging",
    badge: "🔴 OnePlus",
    displayOrder: 11,
    productIds: [
      "oneplus-13",
      "oneplus-13r",
      "oneplus-12",
      "oneplus-12r",
      "oneplus-nord-4",
      "oneplus-nord-ce4",
      "oneplus-nord-ce4-lite",
      "oneplus-open",
    ],
  },
  {
    id: "brand-pixel",
    title: "Google Pixel & Pure Android",
    subtitle: "Computational photography marvels, Google AI features, and clean software support",
    badge: "🤖 Pixel",
    displayOrder: 12,
    productIds: [
      "pixel-10-pro-xl",
      "pixel-10-pro",
      "pixel-10",
      "pixel-9-pro-xl",
      "pixel-9-pro",
      "pixel-9",
      "pixel-9a",
      "pixel-8a",
      "pixel-fold",
    ],
  },
  {
    id: "brand-xiaomi-redmi-poco",
    title: "Xiaomi, Redmi & POCO",
    subtitle: "From Leica-tuned Xiaomi Ultra cameras to high-value Redmi Note and POCO speed champions",
    badge: "🟠 Xiaomi Ecosystem",
    displayOrder: 13,
    productIds: [
      "xiaomi-15-pro",
      "xiaomi-15",
      "xiaomi-14-ultra",
      "xiaomi-14",
      "xiaomi-14t-pro",
      "redmi-note-14-pro-plus",
      "redmi-note-14-pro",
      "redmi-note-14",
      "redmi-13-5g",
      "redmi-13c-5g",
      "redmi-a4-5g",
      "poco-f6-pro",
      "poco-f6",
      "poco-x6-pro",
      "poco-x6-neo",
      "poco-m6-plus-5g",
      "poco-c65",
    ],
  },
  {
    id: "brand-vivo-oppo-iqoo",
    title: "Vivo, Oppo & iQOO",
    subtitle: "Zeiss portrait cameras, ultra-fast charging, and high-performance gaming hardware",
    badge: "🔵 Vivo • Oppo • iQOO",
    displayOrder: 14,
    productIds: [
      "vivo-x200-pro",
      "vivo-x200",
      "vivo-x100-pro",
      "vivo-v40-pro",
      "vivo-v40",
      "vivo-t3-pro",
      "oppo-find-x8-pro",
      "oppo-find-x8",
      "oppo-reno-12-pro",
      "oppo-f27-pro-plus-5g",
      "iqoo-13",
      "iqoo-12",
      "iqoo-neo-9-pro",
      "iqoo-z9s-pro",
      "iqoo-z9s-5g",
    ],
  },
  {
    id: "brand-moto-nothing-cmf",
    title: "Motorola, Nothing & CMF",
    subtitle: "Design-first smartphones, clean Hello UI, iconic Glyph lighting, and modular hardware",
    badge: "💡 Design Innovators",
    displayOrder: 15,
    productIds: [
      "motorola-edge-50-ultra",
      "motorola-edge-50-pro",
      "motorola-edge-50-fusion",
      "motorola-razr-50-ultra",
      "motorola-razr-50",
      "moto-g85-5g",
      "moto-g64-5g",
      "moto-g45-5g",
      "motorola-thinkphone-25",
      "nothing-phone-3",
      "nothing-phone-2",
      "nothing-phone-2a-plus",
      "nothing-phone-2a",
      "cmf-phone-1",
    ],
  },
  {
    id: "brand-challengers",
    title: "Indian Value & Gaming Challengers",
    subtitle: "Homegrown Lava innovations, extreme gamer hardware, and feature-packed devices from Infinix & Tecno",
    badge: "🇮🇳 Market Challengers",
    displayOrder: 16,
    productIds: [
      "lava-agni-3-5g",
      "lava-blaze-curve-5g",
      "lava-blaze-3-5g",
      "infinix-gt-20-pro",
      "infinix-zero-40-5g",
      "infinix-note-40-pro-plus-5g",
      "infinix-hot-50-5g",
      "tecno-phantom-v-fold2",
      "tecno-camon-30-premier",
      "tecno-pova-6-pro-5g",
      "honor-magic6-pro",
      "honor-200-pro",
      "honor-200",
      "rog-phone-8-pro",
      "redmagic-9s-pro",
      "nubia-z60-ultra",
    ],
  },
];

/** Full list of Mobile products across all segments */
export const RAW_MOBILE_PRODUCTS: Array<{
  id: string;
  name: string;
  brand: string;
  subcategory: string;
  sectionId: string;
  sectionTitle: string;
  description: string;
  tags: string[];
  badge?: "HOT" | "TRENDING" | "NEW" | "POPULAR";
  featured?: boolean;
  trending?: boolean;
}> = [
  // === Apple iPhones ===
  {
    id: "iphone-17-pro-max",
    name: "iPhone 17 Pro Max",
    brand: "Apple",
    subcategory: "Flagships",
    sectionId: "trending-phones",
    sectionTitle: "Trending Phones",
    description: "Apple's apex titanium flagship with periscope telephoto zoom, A19 Pro silicon, and Apple Intelligence.",
    tags: ["apple", "iphone", "flagship", "camera", "trending", "premium", "5g"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "iphone-17-pro",
    name: "iPhone 17 Pro",
    brand: "Apple",
    subcategory: "Flagships",
    sectionId: "trending-phones",
    sectionTitle: "Trending Phones",
    description: "Pro performance in a 6.3-inch titanium unibody with 120Hz ProMotion and studio-grade microphones.",
    tags: ["apple", "iphone", "flagship", "camera", "trending", "5g"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "iphone-17",
    name: "iPhone 17",
    brand: "Apple",
    subcategory: "Flagships",
    sectionId: "trending-phones",
    sectionTitle: "Trending Phones",
    description: "The modern daily driver iPhone with 120Hz ProMotion display, dual 48MP cameras, and all-day battery.",
    tags: ["apple", "iphone", "trending", "5g", "popular"],
    badge: "NEW",
    featured: true,
    trending: true,
  },
  {
    id: "iphone-air",
    name: "iPhone Air",
    brand: "Apple",
    subcategory: "Flagships",
    sectionId: "new-popular",
    sectionTitle: "New & Popular",
    description: "An impossibly slim, ultra-lightweight designer iPhone with high-strength aluminum frame.",
    tags: ["apple", "iphone", "air", "slim", "design", "5g"],
    badge: "NEW",
  },
  {
    id: "iphone-16-pro-max",
    name: "iPhone 16 Pro Max",
    brand: "Apple",
    subcategory: "Flagships",
    sectionId: "camera-phones",
    sectionTitle: "Camera Phones",
    description: "6.9-inch Super Retina XDR screen with dedicated Camera Control button and 4K 120fps Dolby Vision.",
    tags: ["apple", "iphone", "pro-max", "camera", "flagship", "5g"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "iphone-16-pro",
    name: "iPhone 16 Pro",
    brand: "Apple",
    subcategory: "Flagships",
    sectionId: "brand-apple",
    sectionTitle: "Apple iPhone Collection",
    description: "Grade 5 titanium chassis with A18 Pro chip, 5x optical telephoto camera, and studio audio recording.",
    tags: ["apple", "iphone", "pro", "camera", "flagship", "5g"],
    badge: "POPULAR",
  },
  {
    id: "iphone-16-plus",
    name: "iPhone 16 Plus",
    brand: "Apple",
    subcategory: "Battery Phones",
    sectionId: "brand-apple",
    sectionTitle: "Apple iPhone Collection",
    description: "Expansive 6.7-inch display paired with exceptional battery life and vibrant color-infused glass.",
    tags: ["apple", "iphone", "battery", "plus", "5g"],
  },
  {
    id: "iphone-16",
    name: "iPhone 16",
    brand: "Apple",
    subcategory: "Mid-Range",
    sectionId: "brand-apple",
    sectionTitle: "Apple iPhone Collection",
    description: "Action button, Camera Control, 48MP Fusion camera, and A18 chip designed for Apple Intelligence.",
    tags: ["apple", "iphone", "popular", "5g"],
  },
  {
    id: "iphone-15-pro-max",
    name: "iPhone 15 Pro Max",
    brand: "Apple",
    subcategory: "Flagships",
    sectionId: "brand-apple",
    sectionTitle: "Apple iPhone Collection",
    description: "Titanium design with 5x telephoto camera, USB-C 10Gbps transfer, and console-quality gaming.",
    tags: ["apple", "iphone", "titanium", "camera", "5g"],
  },
  {
    id: "iphone-15-pro",
    name: "iPhone 15 Pro",
    brand: "Apple",
    subcategory: "Flagships",
    sectionId: "brand-apple",
    sectionTitle: "Apple iPhone Collection",
    description: "Compact titanium powerhouse with A17 Pro chip and customizable Action Button.",
    tags: ["apple", "iphone", "pro", "5g"],
  },
  {
    id: "iphone-15-plus",
    name: "iPhone 15 Plus",
    brand: "Apple",
    subcategory: "Battery Phones",
    sectionId: "brand-apple",
    sectionTitle: "Apple iPhone Collection",
    description: "Dynamic Island, 48MP main camera, and multi-day battery life with USB-C convenience.",
    tags: ["apple", "iphone", "battery", "5g"],
  },
  {
    id: "iphone-15",
    name: "iPhone 15",
    brand: "Apple",
    subcategory: "Mid-Range",
    sectionId: "brand-apple",
    sectionTitle: "Apple iPhone Collection",
    description: "Dynamic Island interface with 2x telephoto crop and durable matte-finish glass back.",
    tags: ["apple", "iphone", "5g", "value"],
  },
  {
    id: "iphone-14",
    name: "iPhone 14",
    brand: "Apple",
    subcategory: "Mid-Range",
    sectionId: "brand-apple",
    sectionTitle: "Apple iPhone Collection",
    description: "Reliable iPhone with Super Retina XDR OLED, Crash Detection, and Photonic Engine imaging.",
    tags: ["apple", "iphone", "value", "5g"],
  },
  {
    id: "iphone-13",
    name: "iPhone 13",
    brand: "Apple",
    subcategory: "Mid-Range",
    sectionId: "brand-apple",
    sectionTitle: "Apple iPhone Collection",
    description: "India's favorite value iPhone with cinematic video mode and dependable A15 Bionic performance.",
    tags: ["apple", "iphone", "value", "bestseller"],
  },
  {
    id: "iphone-se",
    name: "iPhone SE",
    brand: "Apple",
    subcategory: "Budget Phones",
    sectionId: "brand-apple",
    sectionTitle: "Apple iPhone Collection",
    description: "Classic compact iOS smartphone with Touch ID home button and fast A-series chip.",
    tags: ["apple", "iphone", "compact", "budget", "touchid"],
  },

  // === Samsung Galaxy ===
  {
    id: "galaxy-s26-ultra",
    name: "Samsung Galaxy S26 Ultra",
    brand: "Samsung",
    subcategory: "Flagships",
    sectionId: "trending-phones",
    sectionTitle: "Trending Phones",
    description: "Titanium Android monarch with integrated S-Pen, 200MP quad-telephoto zoom, and Galaxy AI 3.0.",
    tags: ["samsung", "galaxy", "ultra", "flagship", "camera", "spen", "trending", "5g"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "galaxy-s26-plus",
    name: "Samsung Galaxy S26+",
    brand: "Samsung",
    subcategory: "Flagships",
    sectionId: "brand-samsung",
    sectionTitle: "Samsung Galaxy Series",
    description: "Expansive 6.7-inch QHD+ 120Hz Dynamic AMOLED with Snapdragon 8 Elite and 45W fast charge.",
    tags: ["samsung", "galaxy", "flagship", "5g"],
  },
  {
    id: "galaxy-s26",
    name: "Samsung Galaxy S26",
    brand: "Samsung",
    subcategory: "Flagships",
    sectionId: "new-popular",
    sectionTitle: "New & Popular",
    description: "Compact Android flagship with symmetrical bezels, armor aluminum frame, and ProVisual Engine.",
    tags: ["samsung", "galaxy", "compact", "flagship", "5g"],
    badge: "NEW",
  },
  {
    id: "galaxy-s25-ultra",
    name: "Samsung Galaxy S25 Ultra",
    brand: "Samsung",
    subcategory: "Flagships",
    sectionId: "camera-phones",
    sectionTitle: "Camera Phones",
    description: "Slimmer titanium frame with rounded ergonomic corners, 50MP 5x periscope lens, and anti-reflective display.",
    tags: ["samsung", "galaxy", "ultra", "camera", "flagship", "5g"],
    badge: "HOT",
    featured: true,
  },
  {
    id: "galaxy-s25-plus",
    name: "Samsung Galaxy S25+",
    brand: "Samsung",
    subcategory: "Flagships",
    sectionId: "brand-samsung",
    sectionTitle: "Samsung Galaxy Series",
    description: "Large 120Hz Dynamic AMOLED display with Galaxy AI live translation and Circle to Search.",
    tags: ["samsung", "galaxy", "plus", "5g"],
  },
  {
    id: "galaxy-s25",
    name: "Samsung Galaxy S25",
    brand: "Samsung",
    subcategory: "Flagships",
    sectionId: "brand-samsung",
    sectionTitle: "Samsung Galaxy Series",
    description: "Premium compact smartphone with Snapdragon flagship processor and 7 years of Android OS updates.",
    tags: ["samsung", "galaxy", "flagship", "compact", "5g"],
  },
  {
    id: "galaxy-s25-fe",
    name: "Samsung Galaxy S25 FE",
    brand: "Samsung",
    subcategory: "Mid-Range",
    sectionId: "brand-samsung",
    sectionTitle: "Samsung Galaxy Series",
    description: "Fan Edition flagship experience with flagship triple cameras, IP68 water resistance, and Galaxy AI.",
    tags: ["samsung", "galaxy", "fe", "value", "5g"],
  },
  {
    id: "galaxy-s24-ultra",
    name: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    subcategory: "Flagships",
    sectionId: "brand-samsung",
    sectionTitle: "Samsung Galaxy Series",
    description: "Gorilla Glass Armor glare-free display with titanium frame, S-Pen, and generative photo editing.",
    tags: ["samsung", "galaxy", "ultra", "camera", "spen", "5g"],
  },
  {
    id: "galaxy-s24-plus",
    name: "Samsung Galaxy S24+",
    brand: "Samsung",
    subcategory: "Flagships",
    sectionId: "brand-samsung",
    sectionTitle: "Samsung Galaxy Series",
    description: "QHD+ display with 12GB RAM standard, Armor Aluminum 2.0, and 4900mAh battery.",
    tags: ["samsung", "galaxy", "5g"],
  },
  {
    id: "galaxy-s24",
    name: "Samsung Galaxy S24",
    brand: "Samsung",
    subcategory: "Flagships",
    sectionId: "brand-samsung",
    sectionTitle: "Samsung Galaxy Series",
    description: "One of the best compact Android phones on the market with high brightness AMOLED.",
    tags: ["samsung", "galaxy", "compact", "5g"],
  },
  {
    id: "galaxy-a56-5g",
    name: "Samsung Galaxy A56 5G",
    brand: "Samsung",
    subcategory: "Mid-Range",
    sectionId: "brand-samsung",
    sectionTitle: "Samsung Galaxy Series",
    description: "Premium glass and metal mid-ranger with IP67 waterproofing and 6 years of software support.",
    tags: ["samsung", "galaxy", "a-series", "midrange", "5g"],
  },
  {
    id: "galaxy-a36-5g",
    name: "Samsung Galaxy A36 5G",
    brand: "Samsung",
    subcategory: "Mid-Range",
    sectionId: "best-value",
    sectionTitle: "Best Value (Mid-Range Champions)",
    description: "Super AMOLED 120Hz display with OIS camera stabilization and Knox security.",
    tags: ["samsung", "galaxy", "a-series", "value", "5g"],
  },
  {
    id: "galaxy-a26",
    name: "Samsung Galaxy A26",
    brand: "Samsung",
    subcategory: "Budget Phones",
    sectionId: "budget-picks",
    sectionTitle: "Budget Picks & Entry 5G",
    description: "Affordable Samsung 5G phone with Infinity-U AMOLED display and 5000mAh battery.",
    tags: ["samsung", "galaxy", "budget", "5g"],
  },
  {
    id: "galaxy-m55",
    name: "Samsung Galaxy M55",
    brand: "Samsung",
    subcategory: "Mid-Range",
    sectionId: "brand-samsung",
    sectionTitle: "Samsung Galaxy Series",
    description: "Ultra-slim 7.8mm Monster series phone with 50MP selfie camera and 45W fast charging.",
    tags: ["samsung", "galaxy", "m-series", "battery", "5g"],
  },
  {
    id: "galaxy-m35",
    name: "Samsung Galaxy M35",
    brand: "Samsung",
    subcategory: "Battery Phones",
    sectionId: "brand-samsung",
    sectionTitle: "Samsung Galaxy Series",
    description: "Massive 6000mAh battery monster with Super AMOLED 120Hz screen and vapor cooling chamber.",
    tags: ["samsung", "galaxy", "battery", "6000mah", "5g"],
  },
  {
    id: "galaxy-z-fold6",
    name: "Samsung Galaxy Z Fold6",
    brand: "Samsung",
    subcategory: "Foldables",
    sectionId: "foldables-flips",
    sectionTitle: "Foldables & Flip Phones",
    description: "Dual-screen foldable with wider cover screen, lighter titanium hinge, and S-Pen canvas.",
    tags: ["samsung", "galaxy", "z-fold", "foldable", "flagship", "5g"],
    badge: "HOT",
    featured: true,
  },
  {
    id: "galaxy-z-flip6",
    name: "Samsung Galaxy Z Flip6",
    brand: "Samsung",
    subcategory: "Flip Phones",
    sectionId: "foldables-flips",
    sectionTitle: "Foldables & Flip Phones",
    description: "Pocket-sized clamshell flip with 3.4-inch FlexWindow, 50MP camera, and vapor chamber cooling.",
    tags: ["samsung", "galaxy", "z-flip", "flip", "compact", "5g"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "galaxy-z-fold5",
    name: "Samsung Galaxy Z Fold5",
    brand: "Samsung",
    subcategory: "Foldables",
    sectionId: "foldables-flips",
    sectionTitle: "Foldables & Flip Phones",
    description: "Flex Hinge zero-gap folding design with multi-window multitasking and Snapdragon 8 Gen 2.",
    tags: ["samsung", "galaxy", "foldable", "5g"],
  },

  // === OnePlus ===
  {
    id: "oneplus-13",
    name: "OnePlus 13",
    brand: "OnePlus",
    subcategory: "Flagships",
    sectionId: "trending-phones",
    sectionTitle: "Trending Phones",
    description: "Snapdragon 8 Elite flagship with 6000mAh Glacier battery, Hasselblad triple 50MP cameras, and IP69 rating.",
    tags: ["oneplus", "flagship", "camera", "battery", "trending", "5g"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "oneplus-13r",
    name: "OnePlus 13R",
    brand: "OnePlus",
    subcategory: "Flagships",
    sectionId: "trending-phones",
    sectionTitle: "Trending Phones",
    description: "Flagship killer phone with 1.5K 120Hz ProXDR display, 6000mAh battery, and 100W SUPERVOOC charging.",
    tags: ["oneplus", "flagship-killer", "performance", "5g"],
    badge: "NEW",
    trending: true,
  },
  {
    id: "oneplus-12",
    name: "OnePlus 12",
    brand: "OnePlus",
    subcategory: "Flagships",
    sectionId: "brand-oneplus",
    sectionTitle: "OnePlus Flagships & Nord",
    description: "4th Gen Hasselblad camera with 3x periscope zoom, 4500 nits 2K display, and 5400mAh battery.",
    tags: ["oneplus", "flagship", "camera", "5g"],
    featured: true,
  },
  {
    id: "oneplus-12r",
    name: "OnePlus 12R",
    brand: "OnePlus",
    subcategory: "Mid-Range",
    sectionId: "gaming-phones",
    sectionTitle: "Gaming Phones",
    description: "Performance powerhouse with 4th Gen LTPO 120Hz screen and Dual Cryo-velocity VC cooling.",
    tags: ["oneplus", "gaming", "performance", "value", "5g"],
  },
  {
    id: "oneplus-nord-4",
    name: "OnePlus Nord 4",
    brand: "OnePlus",
    subcategory: "Mid-Range",
    sectionId: "best-value",
    sectionTitle: "Best Value (Mid-Range Champions)",
    description: "The only all-metal unibody 5G smartphone with Snapdragon 7+ Gen 3 and 6 years of software support.",
    tags: ["oneplus", "nord", "metal-unibody", "midrange", "value", "5g"],
    badge: "HOT",
  },
  {
    id: "oneplus-nord-ce4",
    name: "OnePlus Nord CE4",
    brand: "OnePlus",
    subcategory: "Mid-Range",
    sectionId: "brand-oneplus",
    sectionTitle: "OnePlus Flagships & Nord",
    description: "Qualcomm Snapdragon 7 Gen 3 with 100W fast charging and Sony LYT-600 OIS main camera.",
    tags: ["oneplus", "nord-ce", "value", "fast-charging", "5g"],
  },
  {
    id: "oneplus-nord-ce4-lite",
    name: "OnePlus Nord CE4 Lite",
    brand: "OnePlus",
    subcategory: "Budget Phones",
    sectionId: "brand-oneplus",
    sectionTitle: "OnePlus Flagships & Nord",
    description: "120Hz AMOLED screen with 5500mAh battery, reverse wired charging, and 300% Ultra Volume Mode.",
    tags: ["oneplus", "nord", "budget", "battery", "5g"],
  },
  {
    id: "oneplus-open",
    name: "OnePlus Open",
    brand: "OnePlus",
    subcategory: "Foldables",
    sectionId: "foldables-flips",
    sectionTitle: "Foldables & Flip Phones",
    description: "Widely celebrated foldable with Open Canvas multitasking, Hasselblad zoom, and virtually crease-free screen.",
    tags: ["oneplus", "open", "foldable", "multitasking", "flagship", "5g"],
    badge: "HOT",
    featured: true,
  },

  // === Google Pixel ===
  {
    id: "pixel-10-pro-xl",
    name: "Google Pixel 10 Pro XL",
    brand: "Google",
    subcategory: "Flagships",
    sectionId: "new-popular",
    sectionTitle: "New & Popular",
    description: "Google's flagship super-phone with Google Tensor G5, Super Actua display, and Gemini Nano AI.",
    tags: ["google", "pixel", "flagship", "camera", "ai", "5g"],
    badge: "NEW",
  },
  {
    id: "pixel-10-pro",
    name: "Google Pixel 10 Pro",
    brand: "Google",
    subcategory: "Flagships",
    sectionId: "camera-phones",
    sectionTitle: "Camera Phones",
    description: "Pro photography setup in a compact 6.3-inch frame with 5x telephoto optical zoom.",
    tags: ["google", "pixel", "compact-pro", "camera", "ai", "5g"],
    badge: "NEW",
  },
  {
    id: "pixel-10",
    name: "Google Pixel 10",
    brand: "Google",
    subcategory: "Flagships",
    sectionId: "brand-pixel",
    sectionTitle: "Google Pixel & Pure Android",
    description: "Pure Android 16 with Magic Editor, Best Take, Call Screen, and clean computational photography.",
    tags: ["google", "pixel", "pure-android", "5g"],
  },
  {
    id: "pixel-9-pro-xl",
    name: "Google Pixel 9 Pro XL",
    brand: "Google",
    subcategory: "Flagships",
    sectionId: "trending-phones",
    sectionTitle: "Trending Phones",
    description: "Polished glass and metal flagship with 3000 nits Super Actua screen and 8K Video Boost.",
    tags: ["google", "pixel", "camera", "flagship", "trending", "5g"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "pixel-9-pro",
    name: "Google Pixel 9 Pro",
    brand: "Google",
    subcategory: "Flagships",
    sectionId: "brand-pixel",
    sectionTitle: "Google Pixel & Pure Android",
    description: "All pro features in a handheld 6.3-inch form factor with 16GB RAM for Gemini Advanced.",
    tags: ["google", "pixel", "pro", "camera", "5g"],
    featured: true,
  },
  {
    id: "pixel-9",
    name: "Google Pixel 9",
    brand: "Google",
    subcategory: "Mid-Range",
    sectionId: "brand-pixel",
    sectionTitle: "Google Pixel & Pure Android",
    description: "Sculpted camera visor design with 50MP main sensor, upgraded ultrawide, and Add Me photo feature.",
    tags: ["google", "pixel", "ai", "camera", "5g"],
  },
  {
    id: "pixel-9a",
    name: "Google Pixel 9a",
    brand: "Google",
    subcategory: "Mid-Range",
    sectionId: "new-popular",
    sectionTitle: "New & Popular",
    description: "Affordable Pixel with flush camera bar, Tensor G4 performance, and flagship AI tools.",
    tags: ["google", "pixel", "value", "5g"],
    badge: "NEW",
  },
  {
    id: "pixel-8a",
    name: "Google Pixel 8a",
    brand: "Google",
    subcategory: "Mid-Range",
    sectionId: "brand-pixel",
    sectionTitle: "Google Pixel & Pure Android",
    description: "120Hz Actua display, 7 years of software drops, Audio Magic Eraser, and IP67 protection.",
    tags: ["google", "pixel", "value", "midrange", "5g"],
  },
  {
    id: "pixel-fold",
    name: "Google Pixel Fold",
    brand: "Google",
    subcategory: "Foldables",
    sectionId: "foldables-flips",
    sectionTitle: "Foldables & Flip Phones",
    description: "Passport-sized wide cover screen unfolding into an ultra-thin 7.6-inch OLED workspace.",
    tags: ["google", "pixel", "foldable", "5g"],
  },

  // === Xiaomi, Redmi & POCO ===
  {
    id: "xiaomi-15-pro",
    name: "Xiaomi 15 Pro",
    brand: "Xiaomi",
    subcategory: "Flagships",
    sectionId: "flagship-phones",
    sectionTitle: "Flagship Phones",
    description: "Snapdragon 8 Elite with Leica Summilux optical lenses and massive 6100mAh silicon-carbon battery.",
    tags: ["xiaomi", "leica", "flagship", "camera", "battery", "5g"],
    badge: "HOT",
    featured: true,
  },
  {
    id: "xiaomi-15",
    name: "Xiaomi 15",
    brand: "Xiaomi",
    subcategory: "Flagships",
    sectionId: "brand-xiaomi-redmi-poco",
    sectionTitle: "Xiaomi, Redmi & POCO",
    description: "Golden ratio compact flagship with micro-curved edges and Leica 75mm floating telephoto.",
    tags: ["xiaomi", "compact", "leica", "flagship", "5g"],
  },
  {
    id: "xiaomi-14-ultra",
    name: "Xiaomi 14 Ultra",
    brand: "Xiaomi",
    subcategory: "Flagships",
    sectionId: "camera-phones",
    sectionTitle: "Camera Phones",
    description: "1-inch Sony LYT-900 sensor with stepless variable aperture and quad 50MP Leica cameras.",
    tags: ["xiaomi", "ultra", "camera", "leica", "1inch", "flagship", "5g"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "xiaomi-14",
    name: "Xiaomi 14",
    brand: "Xiaomi",
    subcategory: "Flagships",
    sectionId: "brand-xiaomi-redmi-poco",
    sectionTitle: "Xiaomi, Redmi & POCO",
    description: "6.36-inch compact powerhouse with Snapdragon 8 Gen 3 and 90W HyperCharge.",
    tags: ["xiaomi", "compact", "leica", "5g"],
  },
  {
    id: "xiaomi-14t-pro",
    name: "Xiaomi 14T Pro",
    brand: "Xiaomi",
    subcategory: "Mid-Range",
    sectionId: "brand-xiaomi-redmi-poco",
    sectionTitle: "Xiaomi, Redmi & POCO",
    description: "MediaTek Dimensity 9300+ with 144Hz AI display and Leica professional optical setup.",
    tags: ["xiaomi", "14t", "leica", "performance", "5g"],
  },
  {
    id: "redmi-note-14-pro-plus",
    name: "Redmi Note 14 Pro+",
    brand: "Redmi",
    subcategory: "Mid-Range",
    sectionId: "new-popular",
    sectionTitle: "New & Popular",
    description: "6200mAh silicon-carbon battery with IP68/IP69K water resistance and 50MP Light Hunter sensor.",
    tags: ["redmi", "note14", "battery", "rugged", "value", "5g"],
    badge: "HOT",
  },
  {
    id: "redmi-note-14-pro",
    name: "Redmi Note 14 Pro",
    brand: "Redmi",
    subcategory: "Mid-Range",
    sectionId: "best-value",
    sectionTitle: "Best Value (Mid-Range Champions)",
    description: "Curved 1.5K 120Hz AMOLED screen with King Kong architecture drop resistance.",
    tags: ["redmi", "note14", "curved-amoled", "midrange", "5g"],
  },
  {
    id: "redmi-note-14",
    name: "Redmi Note 14",
    brand: "Redmi",
    subcategory: "Budget Phones",
    sectionId: "brand-xiaomi-redmi-poco",
    sectionTitle: "Xiaomi, Redmi & POCO",
    description: "All-round reliable smartphone with 120Hz OLED screen and 45W turbo charging.",
    tags: ["redmi", "note", "budget", "5g"],
  },
  {
    id: "redmi-13-5g",
    name: "Redmi 13 5G",
    brand: "Redmi",
    subcategory: "Budget Phones",
    sectionId: "budget-picks",
    sectionTitle: "Budget Picks & Entry 5G",
    description: "India's premier budget 5G phone with double-sided glass back and 108MP camera.",
    tags: ["redmi", "budget", "glassback", "108mp", "5g"],
  },
  {
    id: "redmi-13c-5g",
    name: "Redmi 13C 5G",
    brand: "Redmi",
    subcategory: "Budget Phones",
    sectionId: "budget-picks",
    sectionTitle: "Budget Picks & Entry 5G",
    description: "Entry-level 5G connectivity with Dimensity 6100+ chip and dynamic Star Trail design.",
    tags: ["redmi", "budget", "entry5g"],
  },
  {
    id: "redmi-a4-5g",
    name: "Redmi A4 5G",
    brand: "Redmi",
    subcategory: "Budget Phones",
    sectionId: "budget-picks",
    sectionTitle: "Budget Picks & Entry 5G",
    description: "India's most accessible Snapdragon 4s Gen 2 5G smartphone with 120Hz display.",
    tags: ["redmi", "a4", "entry5g", "affordable", "5g"],
    badge: "NEW",
  },
  {
    id: "poco-f6-pro",
    name: "POCO F6 Pro",
    brand: "POCO",
    subcategory: "Gaming Phones",
    sectionId: "gaming-phones",
    sectionTitle: "Gaming Phones",
    description: "WQHD+ Flow AMOLED with Snapdragon 8 Gen 2, LiquidCool 4.0, and 120W HyperCharge.",
    tags: ["poco", "f6", "gaming", "performance", "5g"],
  },
  {
    id: "poco-f6",
    name: "POCO F6",
    brand: "POCO",
    subcategory: "Gaming Phones",
    sectionId: "gaming-phones",
    sectionTitle: "Gaming Phones",
    description: "Snapdragon 8s Gen 3 speed machine delivering over 1.5M AnTuTu score at a mid-range price.",
    tags: ["poco", "f6", "gaming", "performance", "value", "5g"],
    badge: "POPULAR",
  },
  {
    id: "poco-x6-pro",
    name: "POCO X6 Pro",
    brand: "POCO",
    subcategory: "Mid-Range",
    sectionId: "best-value",
    sectionTitle: "Best Value (Mid-Range Champions)",
    description: "Dimensity 8300-Ultra powerhouse with 1.5K 120Hz display and vegan leather back.",
    tags: ["poco", "x6pro", "performance", "midrange", "value", "5g"],
    badge: "HOT",
  },
  {
    id: "poco-x6-neo",
    name: "POCO X6 Neo",
    brand: "POCO",
    subcategory: "Mid-Range",
    sectionId: "brand-xiaomi-redmi-poco",
    sectionTitle: "Xiaomi, Redmi & POCO",
    description: "Ultra-slim 7.69mm bezel-less AMOLED phone with 108MP camera.",
    tags: ["poco", "x6", "slim", "amoled", "5g"],
  },
  {
    id: "poco-m6-plus-5g",
    name: "POCO M6 Plus 5G",
    brand: "POCO",
    subcategory: "Budget Phones",
    sectionId: "budget-picks",
    sectionTitle: "Budget Picks & Entry 5G",
    description: "Dual glass back aesthetic with Snapdragon 4 Gen 2 AE and 108MP 3x in-sensor zoom.",
    tags: ["poco", "m6", "budget", "glassback", "5g"],
  },
  {
    id: "poco-c65",
    name: "POCO C65",
    brand: "POCO",
    subcategory: "Budget Phones",
    sectionId: "budget-picks",
    sectionTitle: "Budget Picks & Entry 5G",
    description: "Big 6.74-inch 90Hz display with 5000mAh battery and up to 16GB dynamic RAM.",
    tags: ["poco", "budget", "entry-level"],
  },

  // === Realme ===
  {
    id: "realme-gt-7-pro",
    name: "Realme GT 7 Pro",
    brand: "Realme",
    subcategory: "Flagships",
    sectionId: "trending-phones",
    sectionTitle: "Trending Phones",
    description: "India's first Snapdragon 8 Elite phone with Mars design, underwater photography mode, and 6500mAh battery.",
    tags: ["realme", "gt7pro", "flagship", "battery", "trending", "5g"],
    badge: "HOT",
    featured: true,
  },
  {
    id: "realme-gt-6",
    name: "Realme GT 6",
    brand: "Realme",
    subcategory: "Gaming Phones",
    sectionId: "gaming-phones",
    sectionTitle: "Gaming Phones",
    description: "Snapdragon 8s Gen 3 with 6000 nits ultra-bright display and Sony LYT-808 OIS camera.",
    tags: ["realme", "gt6", "flagship-killer", "bright-display", "5g"],
  },
  {
    id: "realme-gt-6t",
    name: "Realme GT 6T",
    brand: "Realme",
    subcategory: "Mid-Range",
    sectionId: "best-value",
    sectionTitle: "Best Value (Mid-Range Champions)",
    description: "Snapdragon 7+ Gen 3 performance with 120W SUPERVOOC and LTPO 120Hz AMOLED.",
    tags: ["realme", "gt6t", "performance", "fast-charging", "5g"],
  },
  {
    id: "realme-14-pro-plus",
    name: "Realme 14 Pro+",
    brand: "Realme",
    subcategory: "Mid-Range",
    sectionId: "new-popular",
    sectionTitle: "New & Popular",
    description: "Periscope telephoto camera with Monet luxury-inspired design and curved AMOLED.",
    tags: ["realme", "14pro", "camera", "periscope", "design", "5g"],
    badge: "NEW",
  },
  {
    id: "realme-14-pro",
    name: "Realme 14 Pro",
    brand: "Realme",
    subcategory: "Mid-Range",
    sectionId: "brand-challengers",
    sectionTitle: "Indian Value & Gaming Challengers",
    description: "Curved 120Hz display with Sony OIS portrait sensor and 45W fast charge.",
    tags: ["realme", "14pro", "curved", "5g"],
  },
  {
    id: "realme-13-plus-5g",
    name: "Realme 13+ 5G",
    brand: "Realme",
    subcategory: "Mid-Range",
    sectionId: "best-value",
    sectionTitle: "Best Value (Mid-Range Champions)",
    description: "Dimensity 7300 Energy processor with 90fps mobile gaming support and 80W charge.",
    tags: ["realme", "13plus", "gaming", "value", "5g"],
  },
  {
    id: "realme-p2-pro",
    name: "Realme P2 Pro",
    brand: "Realme",
    subcategory: "Mid-Range",
    sectionId: "best-value",
    sectionTitle: "Best Value (Mid-Range Champions)",
    description: "Curved AMOLED screen with Snapdragon 7s Gen 2 and 80W Ultra Charge.",
    tags: ["realme", "p-series", "curved-screen", "5g"],
  },
  {
    id: "realme-p1-5g",
    name: "Realme P1 5G",
    brand: "Realme",
    subcategory: "Mid-Range",
    sectionId: "best-value",
    sectionTitle: "Best Value (Mid-Range Champions)",
    description: "120Hz AMOLED with Phoenix design and Dimensity 7050 5G processor.",
    tags: ["realme", "p1", "amoled", "budget5g"],
  },
  {
    id: "realme-narzo-70-pro",
    name: "Realme Narzo 70 Pro",
    brand: "Realme",
    subcategory: "Mid-Range",
    sectionId: "best-value",
    sectionTitle: "Best Value (Mid-Range Champions)",
    description: "Flagship Sony IMX890 OIS camera with Air Gesture touchless control.",
    tags: ["realme", "narzo", "camera", "sony-sensor", "5g"],
  },
  {
    id: "realme-narzo-70x",
    name: "Realme Narzo 70x",
    brand: "Realme",
    subcategory: "Budget Phones",
    sectionId: "budget-picks",
    sectionTitle: "Budget Picks & Entry 5G",
    description: "45W fast charge in a budget 5G phone with IP54 splash resistance.",
    tags: ["realme", "narzo", "budget", "fast-charge", "5g"],
  },
  {
    id: "realme-c65-5g",
    name: "Realme C65 5G",
    brand: "Realme",
    subcategory: "Budget Phones",
    sectionId: "budget-picks",
    sectionTitle: "Budget Picks & Entry 5G",
    description: "Ultra-budget 5G phone powered by MediaTek Dimensity 6300.",
    tags: ["realme", "c-series", "budget5g"],
  },

  // === Vivo ===
  {
    id: "vivo-x200-pro",
    name: "Vivo X200 Pro",
    brand: "Vivo",
    subcategory: "Flagships",
    sectionId: "trending-phones",
    sectionTitle: "Trending Phones",
    description: "Zeiss 200MP APO telephoto periscope with Dimensity 9400 and V3+ imaging chip.",
    tags: ["vivo", "zeiss", "camera", "flagship", "periscope", "trending", "5g"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "vivo-x200",
    name: "Vivo X200",
    brand: "Vivo",
    subcategory: "Flagships",
    sectionId: "new-popular",
    sectionTitle: "New & Popular",
    description: "Quad-curved compact flagship with Zeiss optics and 5800mAh BlueVolt battery.",
    tags: ["vivo", "zeiss", "compact-flagship", "camera", "5g"],
    badge: "NEW",
  },
  {
    id: "vivo-x100-pro",
    name: "Vivo X100 Pro",
    brand: "Vivo",
    subcategory: "Flagships",
    sectionId: "camera-phones",
    sectionTitle: "Camera Phones",
    description: "1-inch main sensor with Zeiss T* coating and dedicated sun/stage portrait modes.",
    tags: ["vivo", "zeiss", "camera", "1inch", "flagship", "5g"],
    featured: true,
  },
  {
    id: "vivo-v40-pro",
    name: "Vivo V40 Pro",
    brand: "Vivo",
    subcategory: "Mid-Range",
    sectionId: "brand-vivo-oppo-iqoo",
    sectionTitle: "Vivo, Oppo & iQOO",
    description: "All-round Zeiss multi-focal portrait phone with IP68 rating and 5500mAh battery.",
    tags: ["vivo", "v40pro", "zeiss", "portrait", "camera", "5g"],
  },
  {
    id: "vivo-v40",
    name: "Vivo V40",
    brand: "Vivo",
    subcategory: "Mid-Range",
    sectionId: "brand-vivo-oppo-iqoo",
    sectionTitle: "Vivo, Oppo & iQOO",
    description: "Ultra-slim 3D curved smartphone with Aura Light portrait studio and 80W FlashCharge.",
    tags: ["vivo", "v40", "slim", "portrait", "5g"],
  },
  {
    id: "vivo-v40e",
    name: "Vivo V40e",
    brand: "Vivo",
    subcategory: "Mid-Range",
    sectionId: "brand-vivo-oppo-iqoo",
    sectionTitle: "Vivo, Oppo & iQOO",
    description: "Royal Bronze luxury curved design with 50MP eye autofocus selfie camera.",
    tags: ["vivo", "v40e", "selfie", "design", "5g"],
  },
  {
    id: "vivo-t3-ultra",
    name: "Vivo T3 Ultra",
    brand: "Vivo",
    subcategory: "Mid-Range",
    sectionId: "best-value",
    sectionTitle: "Best Value (Mid-Range Champions)",
    description: "Dimensity 9200+ performance with 3D curved 1.5K AMOLED display.",
    tags: ["vivo", "t3ultra", "performance", "curved", "5g"],
  },
  {
    id: "vivo-t3-pro",
    name: "Vivo T3 Pro",
    brand: "Vivo",
    subcategory: "Mid-Range",
    sectionId: "best-value",
    sectionTitle: "Best Value (Mid-Range Champions)",
    description: "Leather back finish with Snapdragon 7 Gen 3, Sony OIS camera, and 5500mAh battery.",
    tags: ["vivo", "t3pro", "leather", "battery", "value", "5g"],
    badge: "POPULAR",
  },
  {
    id: "vivo-y200-5g",
    name: "Vivo Y200 5G",
    brand: "Vivo",
    subcategory: "Budget Phones",
    sectionId: "brand-vivo-oppo-iqoo",
    sectionTitle: "Vivo, Oppo & iQOO",
    description: "Smart Aura Light camera with ultra-slim glass design and dual stereo speakers.",
    tags: ["vivo", "y-series", "budget5g", "design"],
  },

  // === Oppo ===
  {
    id: "oppo-find-x8-pro",
    name: "Oppo Find X8 Pro",
    brand: "Oppo",
    subcategory: "Flagships",
    sectionId: "camera-phones",
    sectionTitle: "Camera Phones",
    description: "Dual periscope telephoto cameras with Hasselblad Master Camera System and quick capture button.",
    tags: ["oppo", "findx8", "hasselblad", "camera", "flagship", "5g"],
    badge: "HOT",
    featured: true,
  },
  {
    id: "oppo-find-x8",
    name: "Oppo Find X8",
    brand: "Oppo",
    subcategory: "Flagships",
    sectionId: "new-popular",
    sectionTitle: "New & Popular",
    description: "Flat edge design with symmetrical bezels, Hasselblad color calibration, and 5630mAh battery.",
    tags: ["oppo", "findx8", "hasselblad", "flagship", "5g"],
    badge: "NEW",
  },
  {
    id: "oppo-reno-12-pro",
    name: "Oppo Reno 12 Pro",
    brand: "Oppo",
    subcategory: "Mid-Range",
    sectionId: "brand-vivo-oppo-iqoo",
    sectionTitle: "Vivo, Oppo & iQOO",
    description: "Quad micro-curved infinite view display with GenAI photo retouching and damage-proof armor body.",
    tags: ["oppo", "reno", "ai-camera", "portrait", "5g"],
  },
  {
    id: "oppo-reno-12",
    name: "Oppo Reno 12",
    brand: "Oppo",
    subcategory: "Mid-Range",
    sectionId: "brand-vivo-oppo-iqoo",
    sectionTitle: "Vivo, Oppo & iQOO",
    description: "Futuristic fluid design with AI LinkBoost antenna and 80W SUPERVOOC flash charge.",
    tags: ["oppo", "reno", "design", "5g"],
  },
  {
    id: "oppo-f27-pro-plus-5g",
    name: "Oppo F27 Pro+ 5G",
    brand: "Oppo",
    subcategory: "Mid-Range",
    sectionId: "best-value",
    sectionTitle: "Best Value (Mid-Range Champions)",
    description: "India's first IP69/IP68/IP66 waterproof rated smartphone with 360-degree Armor Body.",
    tags: ["oppo", "waterproof", "ip69", "rugged", "midrange", "5g"],
    badge: "HOT",
  },
  {
    id: "oppo-f27-5g",
    name: "Oppo F27 5G",
    brand: "Oppo",
    subcategory: "Mid-Range",
    sectionId: "brand-vivo-oppo-iqoo",
    sectionTitle: "Vivo, Oppo & iQOO",
    description: "Cosmos ring halo light design with dual stereo speakers and party music mode.",
    tags: ["oppo", "f-series", "halo-light", "5g"],
  },
  {
    id: "oppo-a3-pro",
    name: "Oppo A3 Pro",
    brand: "Oppo",
    subcategory: "Budget Phones",
    sectionId: "brand-vivo-oppo-iqoo",
    sectionTitle: "Vivo, Oppo & iQOO",
    description: "All-round damage proof armor body with 120Hz ultra-bright display.",
    tags: ["oppo", "a-series", "budget5g", "durable"],
  },

  // === iQOO ===
  {
    id: "iqoo-13",
    name: "iQOO 13",
    brand: "iQOO",
    subcategory: "Gaming Phones",
    sectionId: "trending-phones",
    sectionTitle: "Trending Phones",
    description: "Snapdragon 8 Elite monster with 2K 144Hz Q10 display, Monster Halo RGB ring, and 6150mAh battery.",
    tags: ["iqoo", "gaming", "snapdragon-8-elite", "flagship", "144hz", "trending", "5g"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "iqoo-12",
    name: "iQOO 12",
    brand: "iQOO",
    subcategory: "Gaming Phones",
    sectionId: "brand-vivo-oppo-iqoo",
    sectionTitle: "Vivo, Oppo & iQOO",
    description: "BMW M Motorsport edition with periscope telephoto zoom and dedicated Supercomputing Q1 chip.",
    tags: ["iqoo", "gaming", "bmw", "camera", "5g"],
    featured: true,
  },
  {
    id: "iqoo-neo-9-pro",
    name: "iQOO Neo 9 Pro",
    brand: "iQOO",
    subcategory: "Gaming Phones",
    sectionId: "gaming-phones",
    sectionTitle: "Gaming Phones",
    description: "Snapdragon 8 Gen 2 with dual-tone leather back, 144Hz LTPO display, and 120W FlashCharge.",
    tags: ["iqoo", "neo9", "gaming", "performance", "5g"],
  },
  {
    id: "iqoo-neo-10",
    name: "iQOO Neo 10",
    brand: "iQOO",
    subcategory: "Gaming Phones",
    sectionId: "brand-vivo-oppo-iqoo",
    sectionTitle: "Vivo, Oppo & iQOO",
    description: "Flagship gaming processor with huge 6100mAh battery and ultra-fast charging.",
    tags: ["iqoo", "neo10", "gaming", "5g"],
    badge: "NEW",
  },
  {
    id: "iqoo-z9-turbo",
    name: "iQOO Z9 Turbo",
    brand: "iQOO",
    subcategory: "Gaming Phones",
    sectionId: "brand-vivo-oppo-iqoo",
    sectionTitle: "Vivo, Oppo & iQOO",
    description: "Snapdragon 8s Gen 3 powerhouse with 6000mAh battery and 144Hz OLED screen.",
    tags: ["iqoo", "turbo", "gaming", "5g"],
  },
  {
    id: "iqoo-z9s-pro",
    name: "iQOO Z9s Pro",
    brand: "iQOO",
    subcategory: "Mid-Range",
    sectionId: "best-value",
    sectionTitle: "Best Value (Mid-Range Champions)",
    description: "Snapdragon 7 Gen 3 with 3D curved 120Hz AMOLED and Sony IMX882 OIS camera.",
    tags: ["iqoo", "z9spro", "curved-screen", "value", "5g"],
    badge: "POPULAR",
  },
  {
    id: "iqoo-z9s-5g",
    name: "iQOO Z9s 5G",
    brand: "iQOO",
    subcategory: "Mid-Range",
    sectionId: "brand-vivo-oppo-iqoo",
    sectionTitle: "Vivo, Oppo & iQOO",
    description: "Dimensity 7300 with 1800 nits curved display and 4K OIS video recording.",
    tags: ["iqoo", "z9s", "midrange", "5g"],
  },
  {
    id: "iqoo-z9-lite",
    name: "iQOO Z9 Lite",
    brand: "iQOO",
    subcategory: "Budget Phones",
    sectionId: "budget-picks",
    sectionTitle: "Budget Picks & Entry 5G",
    description: "MediaTek Dimensity 6300 with IP64 rating and dual 50MP Sony AI camera.",
    tags: ["iqoo", "budget", "entry5g"],
  },

  // === Motorola ===
  {
    id: "motorola-edge-50-ultra",
    name: "Motorola Edge 50 Ultra",
    brand: "Motorola",
    subcategory: "Flagships",
    sectionId: "flagship-phones",
    sectionTitle: "Flagship Phones",
    description: "Real wood and vegan leather backs with Pantone validated cameras and 125W TurboPower.",
    tags: ["motorola", "edge50", "wood-back", "pantone", "flagship", "5g"],
    badge: "HOT",
    featured: true,
  },
  {
    id: "motorola-edge-50-pro",
    name: "Motorola Edge 50 Pro",
    brand: "Motorola",
    subcategory: "Mid-Range",
    sectionId: "brand-moto-nothing-cmf",
    sectionTitle: "Motorola, Nothing & CMF",
    description: "Handmade Italian acetate finish with 1.5K 144Hz curved screen and 50W wireless charging.",
    tags: ["motorola", "edge50pro", "pantone", "wireless-charging", "5g"],
  },
  {
    id: "motorola-edge-50-fusion",
    name: "Motorola Edge 50 Fusion",
    brand: "Motorola",
    subcategory: "Mid-Range",
    sectionId: "best-value",
    sectionTitle: "Best Value (Mid-Range Champions)",
    description: "India's bestseller curved pOLED phone with Sony LYT-700C OIS sensor and IP68 underwater rating.",
    tags: ["motorola", "edge50fusion", "ip68", "poled", "value", "5g"],
    badge: "HOT",
  },
  {
    id: "motorola-razr-50-ultra",
    name: "Motorola Razr 50 Ultra",
    brand: "Motorola",
    subcategory: "Flip Phones",
    sectionId: "foldables-flips",
    sectionTitle: "Foldables & Flip Phones",
    description: "Largest 4.0-inch external cover screen on any flip phone with Snapdragon 8s Gen 3 and IPX8.",
    tags: ["motorola", "razr", "flip", "flagship", "cover-screen", "5g"],
    badge: "HOT",
    featured: true,
  },
  {
    id: "motorola-razr-50",
    name: "Motorola Razr 50",
    brand: "Motorola",
    subcategory: "Flip Phones",
    sectionId: "foldables-flips",
    sectionTitle: "Foldables & Flip Phones",
    description: "Accessible luxury clamshell flip with 3.6-inch external display and vegan leather texture.",
    tags: ["motorola", "razr", "flip", "fashion", "5g"],
  },
  {
    id: "moto-g85-5g",
    name: "Moto G85 5G",
    brand: "Motorola",
    subcategory: "Mid-Range",
    sectionId: "best-value",
    sectionTitle: "Best Value (Mid-Range Champions)",
    description: "Segment's first 3D curved 120Hz pOLED display with Sony LYT-600 OIS camera.",
    tags: ["motorola", "moto-g", "curved", "value", "5g"],
  },
  {
    id: "moto-g64-5g",
    name: "Moto G64 5G",
    brand: "Motorola",
    subcategory: "Battery Phones",
    sectionId: "brand-moto-nothing-cmf",
    sectionTitle: "Motorola, Nothing & CMF",
    description: "Monster 6000mAh battery with Dimensity 7025 processor and 50MP OIS camera.",
    tags: ["motorola", "battery", "6000mah", "budget5g"],
  },
  {
    id: "moto-g45-5g",
    name: "Moto G45 5G",
    brand: "Motorola",
    subcategory: "Budget Phones",
    sectionId: "budget-picks",
    sectionTitle: "Budget Picks & Entry 5G",
    description: "Vegan leather design with Snapdragon 6s Gen 3 5G processor at an entry-level price.",
    tags: ["motorola", "budget", "vegan-leather", "5g"],
  },
  {
    id: "motorola-thinkphone-25",
    name: "Motorola ThinkPhone 25",
    brand: "Motorola",
    subcategory: "Flagships",
    sectionId: "brand-moto-nothing-cmf",
    sectionTitle: "Motorola, Nothing & CMF",
    description: "Aramid fiber business machine with ThinkShield security and seamless PC integration.",
    tags: ["motorola", "thinkphone", "business", "security", "durable"],
  },

  // === Nothing & CMF ===
  {
    id: "nothing-phone-3",
    name: "Nothing Phone (3)",
    brand: "Nothing",
    subcategory: "Flagships",
    sectionId: "trending-phones",
    sectionTitle: "Trending Phones",
    description: "Design icon with full Glyph Matrix interaction, clean Nothing OS, and flagship camera optics.",
    tags: ["nothing", "glyph", "transparent", "design", "trending", "5g"],
    badge: "HOT",
    featured: true,
    trending: true,
  },
  {
    id: "nothing-phone-2",
    name: "Nothing Phone (2)",
    brand: "Nothing",
    subcategory: "Flagships",
    sectionId: "brand-moto-nothing-cmf",
    sectionTitle: "Motorola, Nothing & CMF",
    description: "Custom Glyph interface with Snapdragon 8+ Gen 1, dual 50MP Sony sensors, and wireless charging.",
    tags: ["nothing", "glyph", "transparent", "flagship", "5g"],
  },
  {
    id: "nothing-phone-2a-plus",
    name: "Nothing Phone (2a) Plus",
    brand: "Nothing",
    subcategory: "Mid-Range",
    sectionId: "new-popular",
    sectionTitle: "New & Popular",
    description: "Metallic finish aesthetic with custom Dimensity 7350 Pro 5G and triple 50MP cameras.",
    tags: ["nothing", "2aplus", "metallic", "selfie", "5g"],
    badge: "NEW",
  },
  {
    id: "nothing-phone-2a",
    name: "Nothing Phone (2a)",
    brand: "Nothing",
    subcategory: "Mid-Range",
    sectionId: "best-value",
    sectionTitle: "Best Value (Mid-Range Champions)",
    description: "The viral transparent budget design icon with custom Dimensity 7200 Pro and clean Nothing OS.",
    tags: ["nothing", "2a", "transparent", "value", "trending", "5g"],
    badge: "HOT",
    featured: true,
  },
  {
    id: "cmf-phone-1",
    name: "CMF Phone 1",
    brand: "CMF",
    subcategory: "Budget Phones",
    sectionId: "best-value",
    sectionTitle: "Best Value (Mid-Range Champions)",
    description: "Modular smartphone with swappable back covers, accessory point lanyard/kickstand, and Super AMOLED.",
    tags: ["cmf", "nothing", "modular", "customizable", "budget5g"],
    badge: "POPULAR",
    featured: true,
  },

  // === Honor ===
  {
    id: "honor-magic6-pro",
    name: "Honor Magic6 Pro",
    brand: "Honor",
    subcategory: "Flagships",
    sectionId: "flagship-phones",
    sectionTitle: "Flagship Phones",
    description: "180MP periscope zoom with Falcon camera system, eye-tracking Magic Capsule, and 5600mAh battery.",
    tags: ["honor", "magic", "periscope", "camera", "flagship", "5g"],
    featured: true,
  },
  {
    id: "honor-200-pro",
    name: "Honor 200 Pro",
    brand: "Honor",
    subcategory: "Mid-Range",
    sectionId: "camera-phones",
    sectionTitle: "Camera Phones",
    description: "Studio Harcourt Paris portrait engine with Snapdragon 8s Gen 3 and 100W wireless charging.",
    tags: ["honor", "harcourt", "portrait", "camera", "5g"],
  },
  {
    id: "honor-200",
    name: "Honor 200",
    brand: "Honor",
    subcategory: "Mid-Range",
    sectionId: "brand-challengers",
    sectionTitle: "Indian Value & Gaming Challengers",
    description: "Ultra-slim 3840Hz risk-free dimming eye-care display with 50MP Sony OIS studio cameras.",
    tags: ["honor", "eyecare", "portrait", "5g"],
  },
  {
    id: "honor-x9b",
    name: "Honor X9b",
    brand: "Honor",
    subcategory: "Mid-Range",
    sectionId: "brand-challengers",
    sectionTitle: "Indian Value & Gaming Challengers",
    description: "Ultra-bounce anti-drop 360-degree unbreakable curved display with 5800mAh battery.",
    tags: ["honor", "unbreakable", "durable", "battery", "5g"],
  },

  // === Tecno ===
  {
    id: "tecno-phantom-v-fold2",
    name: "Tecno Phantom V Fold2",
    brand: "Tecno",
    subcategory: "Foldables",
    sectionId: "foldables-flips",
    sectionTitle: "Foldables & Flip Phones",
    description: "Ultra-slim book-style foldable with aerospace grade hinge and dual 120Hz screens.",
    tags: ["tecno", "phantom", "foldable", "5g"],
    badge: "NEW",
  },
  {
    id: "tecno-phantom-v-flip2",
    name: "Tecno Phantom V Flip2",
    brand: "Tecno",
    subcategory: "Flip Phones",
    sectionId: "foldables-flips",
    sectionTitle: "Foldables & Flip Phones",
    description: "Fashion-forward vertical clamshell flip with 3.64-inch cover screen and interactive mini pets.",
    tags: ["tecno", "flip", "fashion", "cover-screen", "5g"],
    badge: "NEW",
  },
  {
    id: "tecno-camon-30-premier",
    name: "Tecno Camon 30 Premier",
    brand: "Tecno",
    subcategory: "Camera Phones",
    sectionId: "camera-phones",
    sectionTitle: "Camera Phones",
    description: "Sony imaging chip with Polaroid camera aesthetics and 4K 60fps portrait video.",
    tags: ["tecno", "camon", "camera", "vintage", "5g"],
  },
  {
    id: "tecno-pova-6-pro-5g",
    name: "Tecno Pova 6 Pro 5G",
    brand: "Tecno",
    subcategory: "Gaming Phones",
    sectionId: "brand-challengers",
    sectionTitle: "Indian Value & Gaming Challengers",
    description: "Mecha sci-fi light strip design with huge 6000mAh battery and 70W fast charging.",
    tags: ["tecno", "pova", "mecha", "gaming", "battery", "5g"],
  },
  {
    id: "tecno-spark-30",
    name: "Tecno Spark 30",
    brand: "Tecno",
    subcategory: "Budget Phones",
    sectionId: "budget-picks",
    sectionTitle: "Budget Picks & Entry 5G",
    description: "Transformers Bumblebee themed edition with 120Hz display and dual speakers.",
    tags: ["tecno", "spark", "budget", "transformers"],
  },

  // === Infinix ===
  {
    id: "infinix-gt-20-pro",
    name: "Infinix GT 20 Pro",
    brand: "Infinix",
    subcategory: "Gaming Phones",
    sectionId: "gaming-phones",
    sectionTitle: "Gaming Phones",
    description: "Official gaming phone with dedicated Pixelworks gaming display chip and cyber mecha LED lighting.",
    tags: ["infinix", "gt20pro", "gaming", "esports", "led", "5g"],
    badge: "POPULAR",
    featured: true,
  },
  {
    id: "infinix-zero-40-5g",
    name: "Infinix Zero 40 5G",
    brand: "Infinix",
    subcategory: "Camera Phones",
    sectionId: "brand-challengers",
    sectionTitle: "Indian Value & Gaming Challengers",
    description: "Vlogging specialist phone with 4K 60fps on both front and rear cameras plus GoPro mode.",
    tags: ["infinix", "vlog", "gopro-mode", "camera", "5g"],
  },
  {
    id: "infinix-note-40-pro-plus-5g",
    name: "Infinix Note 40 Pro+ 5G",
    brand: "Infinix",
    subcategory: "Mid-Range",
    sectionId: "brand-challengers",
    sectionTitle: "Indian Value & Gaming Challengers",
    description: "All-Round FastCharge 2.0 with 100W multi-speed charge and 20W wireless MagCharge.",
    tags: ["infinix", "magcharge", "wireless-charging", "curved", "5g"],
  },
  {
    id: "infinix-hot-50-5g",
    name: "Infinix Hot 50 5G",
    brand: "Infinix",
    subcategory: "Budget Phones",
    sectionId: "budget-picks",
    sectionTitle: "Budget Picks & Entry 5G",
    description: "Slimmest 5G smartphone in the budget segment with 5-year lag-free TUV certification.",
    tags: ["infinix", "hot50", "budget5g", "slim"],
  },
  {
    id: "infinix-smart-8",
    name: "Infinix Smart 8",
    brand: "Infinix",
    subcategory: "Budget Phones",
    sectionId: "budget-picks",
    sectionTitle: "Budget Picks & Entry 5G",
    description: "Magic Ring notch interaction with side fingerprint sensor and 90Hz punch-hole screen.",
    tags: ["infinix", "smart8", "entry-level", "budget"],
  },

  // === Lava ===
  {
    id: "lava-agni-3-5g",
    name: "Lava Agni 3 5G",
    brand: "Lava",
    subcategory: "Mid-Range",
    sectionId: "new-popular",
    sectionTitle: "New & Popular",
    description: "Proudly Indian smartphone with dual AMOLED displays (front 1.5K curved + rear 1.74-inch touch screen).",
    tags: ["lava", "agni3", "madeinindia", "dual-screen", "curved", "5g"],
    badge: "NEW",
    featured: true,
  },
  {
    id: "lava-blaze-curve-5g",
    name: "Lava Blaze Curve 5G",
    brand: "Lava",
    subcategory: "Mid-Range",
    sectionId: "best-value",
    sectionTitle: "Best Value (Mid-Range Champions)",
    description: "3D curved 120Hz AMOLED with clean bloatware-free Android and Dimensity 7050 silicon.",
    tags: ["lava", "blaze", "curved-screen", "clean-android", "5g"],
  },
  {
    id: "lava-blaze-3-5g",
    name: "Lava Blaze 3 5G",
    brand: "Lava",
    subcategory: "Budget Phones",
    sectionId: "budget-picks",
    sectionTitle: "Budget Picks & Entry 5G",
    description: "Segment first Vibe Light studio photography in a budget Indian 5G smartphone.",
    tags: ["lava", "budget5g", "vibelight", "india"],
  },
  {
    id: "lava-yuva-3-pro",
    name: "Lava Yuva 3 Pro",
    brand: "Lava",
    subcategory: "Budget Phones",
    sectionId: "budget-picks",
    sectionTitle: "Budget Picks & Entry 5G",
    description: "Premium glass back finish with 50MP AI camera and side-mounted fingerprint unlock.",
    tags: ["lava", "yuva", "budget", "glassback"],
  },

  // === ASUS ROG & Gaming ===
  {
    id: "rog-phone-8-pro",
    name: "ROG Phone 8 Pro",
    brand: "ASUS",
    subcategory: "Gaming Phones",
    sectionId: "gaming-phones",
    sectionTitle: "Gaming Phones",
    description: "AnimeVision mini-LED rear matrix, IP68 water resistance, AirTrigger capacitive buttons, and Snapdragon 8 Gen 3.",
    tags: ["asus", "rog", "gaming", "airtriggers", "rgb", "flagship", "5g"],
    badge: "HOT",
    featured: true,
  },
  {
    id: "rog-phone-8",
    name: "ROG Phone 8",
    brand: "ASUS",
    subcategory: "Gaming Phones",
    sectionId: "gaming-phones",
    sectionTitle: "Gaming Phones",
    description: "165Hz Samsung AMOLED screen with 6-Axis Hybrid Gimbal Stabilizer camera.",
    tags: ["asus", "rog", "gaming", "165hz", "5g"],
  },
  {
    id: "zenfone-11-ultra",
    name: "Zenfone 11 Ultra",
    brand: "ASUS",
    subcategory: "Flagships",
    sectionId: "brand-challengers",
    sectionTitle: "Indian Value & Gaming Challengers",
    description: "Sleek everyday flagship with AI transcription, 5500mAh battery, and wireless Qi charging.",
    tags: ["asus", "zenfone", "flagship", "ai", "5g"],
  },

  // === Nubia RedMagic ===
  {
    id: "redmagic-9s-pro",
    name: "RedMagic 9S Pro",
    brand: "Nubia",
    subcategory: "Gaming Phones",
    sectionId: "gaming-phones",
    sectionTitle: "Gaming Phones",
    description: "Under-display selfie camera for true full-screen gaming, built-in 22,000 RPM RGB cooling fan, and 6500mAh battery.",
    tags: ["nubia", "redmagic", "gaming", "cooling-fan", "fullscreen", "5g"],
    badge: "HOT",
    featured: true,
  },
  {
    id: "redmagic-9-pro",
    name: "RedMagic 9 Pro",
    brand: "Nubia",
    subcategory: "Gaming Phones",
    sectionId: "gaming-phones",
    sectionTitle: "Gaming Phones",
    description: "Completely flat back design with 520Hz touch shoulder triggers and Snapdragon 8 Gen 3.",
    tags: ["nubia", "redmagic", "gaming", "520hz", "5g"],
  },
  {
    id: "nubia-z60-ultra",
    name: "Nubia Z60 Ultra",
    brand: "Nubia",
    subcategory: "Flagships",
    sectionId: "brand-challengers",
    sectionTitle: "Indian Value & Gaming Challengers",
    description: "Unique 35mm optical street photography lens with bezel-less under-display camera screen.",
    tags: ["nubia", "35mm", "camera", "fullscreen", "flagship", "5g"],
  },
];

/**
 * Return all Mobile products with resolved image URLs and display orders.
 */
export function getFullMobilesCatalog(): MobileProduct[] {
  return RAW_MOBILE_PRODUCTS.map((p, idx) => ({
    id: p.id,
    name: p.name,
    brand: p.brand,
    category: "Mobiles",
    subcategory: p.subcategory,
    sectionId: p.sectionId,
    sectionTitle: p.sectionTitle,
    imageUrl: getMobilesProductImage(p.id),
    description: p.description,
    tags: p.tags,
    badge: p.badge,
    featured: Boolean(p.featured),
    trending: Boolean(p.trending),
    displayOrder: idx,
  }));
}

/**
 * Get distinct subcategories for mobile navigation
 */
export function getMobileSubcategories(): Array<{ name: string; count: number }> {
  const map = new Map<string, number>();
  for (const item of RAW_MOBILE_PRODUCTS) {
    map.set(item.subcategory, (map.get(item.subcategory) || 0) + 1);
  }
  return Array.from(map.entries()).map(([name, count]) => ({ name, count }));
}
