"use client";

import { useState } from "react";
import { ChevronLeft, ChevronRight, Sparkles, Layers, Play } from "lucide-react";

export default function ProductSlidePreview() {
  const [currentSlideIndex, setCurrentSlideIndex] = useState(0);

  const previewSlides = [
    {
      moduleTag: "MODULE 01 · LESSON 01",
      topic: "THE ATTRACTION GAP",
      headline: "ATTENTION IS NOT ATTRACTION.",
      subhead: "A man can give you attention for months without ever having an ounce of genuine attraction or respect.",
      type: "statement",
      metric: "RULE #01",
      highlightText: "Attention is ambient noise. Attraction requires respect, scarcity, and emotional weight.",
    },
    {
      moduleTag: "MODULE 05 · LESSON 01",
      topic: "TEXTING & CALIBRATION",
      headline: "STOP WRITING PARAGRAPHS.",
      subhead: "Over-texting is how high-potential people kill romantic polarity before the first date even occurs.",
      type: "chat",
      messages: [
        { sender: "them", text: "Hey! How was your weekend?" },
        { sender: "you", text: "Unreal. Found a moody mezcal spot in Soho and finished that book we debated. You?" },
      ],
      commentary: "Calibrated brevity triggers curiosity. Essays trigger exhaustion.",
    },
    {
      moduleTag: "MODULE 03 · LESSON 02",
      topic: "THE POLARITY FRAMEWORK",
      headline: "IMPRESSIVE IS NOT ATTRACTIVE.",
      subhead: "Desire is generated by how they feel in your presence when you hold eye contact and don't flinch.",
      type: "framework",
      pillars: [
        { label: "01. FRAME", desc: "You do not seek acceptance; you assess chemistry." },
        { label: "02. TENSION", desc: "Playful friction beats agreeable nodding every time." },
        { label: "03. STILLNESS", desc: "Comfort with silence signals sovereign confidence." },
      ],
    },
  ];

  const slide = previewSlides[currentSlideIndex];

  return (
    <section className="relative overflow-hidden py-20 sm:py-28">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto mb-16">
          <div className="inline-flex items-center gap-2 rounded-full border border-[#E6E1D7] bg-white px-3.5 py-1 text-[11px] font-mono tracking-widest text-[#646059] uppercase mb-4">
            <span className="h-2 w-2 rounded-full bg-[#FF5500] animate-pulse" />
            The Presentation Engine
          </div>
          <h2 className="text-3xl sm:text-5xl font-bold tracking-tight text-[#0E0E10]">
            Every lesson is an experience.
          </h2>
          <p className="mt-4 text-base sm:text-lg text-[#646059] leading-relaxed">
            No endless walls of generic text. No boring corporate PDFs. Each lesson unfolds inside a custom, cinema-grade slide presentation designed for immediate behavioral breakthroughs.
          </p>
        </div>

        {/* 3D Layered Presentation Preview Container */}
        <div className="relative mx-auto max-w-5xl">
          {/* Subtle Ambient Glow Behind Frame */}
          <div className="absolute -inset-4 bg-gradient-to-r from-orange-500/10 via-amber-500/5 to-rose-500/10 blur-2xl -z-10 rounded-3xl" />

          {/* Background Perspective Slide Layer 2 (Behind) */}
          <div className="hidden sm:block absolute -top-6 -right-4 w-full h-full rounded-3xl border border-neutral-300/60 bg-[#ECE7DC] opacity-40 transform rotate-1 scale-[0.98] -z-10 pointer-events-none" />

          {/* Background Perspective Slide Layer 1 (Directly Behind) */}
          <div className="hidden sm:block absolute -top-3 -left-3 w-full h-full rounded-3xl border border-neutral-300/80 bg-[#F3EFE6] opacity-70 transform -rotate-1 scale-[0.99] -z-10 pointer-events-none" />

          {/* Foreground Hero Presentation Frame */}
          <div className="relative overflow-hidden rounded-3xl border border-[#DCD6C9] bg-[#0E0E10] text-white shadow-2xl transition-all">
            {/* Slide Presentation Top Navigation Bar */}
            <div className="flex items-center justify-between border-b border-neutral-800 bg-[#16161A] px-5 py-3 text-xs">
              <div className="flex items-center gap-3">
                <div className="flex items-center gap-1.5">
                  <div className="h-2.5 w-2.5 rounded-full bg-red-500/80" />
                  <div className="h-2.5 w-2.5 rounded-full bg-amber-500/80" />
                  <div className="h-2.5 w-2.5 rounded-full bg-emerald-500/80" />
                </div>
                <span className="font-mono text-[11px] text-neutral-400 font-medium">
                  PLUGD OS // KEYNOTE VIEWER
                </span>
              </div>

              <div className="flex items-center gap-2">
                <span className="font-mono text-[11px] text-neutral-400">
                  SLIDE {currentSlideIndex + 1} OF {previewSlides.length}
                </span>
                <div className="h-1.5 w-24 rounded-full bg-neutral-800 overflow-hidden ml-2">
                  <div
                    className="h-full bg-[#FF5500] transition-all duration-300"
                    style={{
                      width: `${((currentSlideIndex + 1) / previewSlides.length) * 100}%`,
                    }}
                  />
                </div>
              </div>
            </div>

            {/* Slide Stage Body */}
            <div className="min-h-[420px] sm:min-h-[480px] p-6 sm:p-12 flex flex-col justify-between bg-gradient-to-b from-[#111114] via-[#0E0E10] to-[#0A0A0C]">
              {/* Slide Meta Eyebrow */}
              <div className="flex items-center justify-between">
                <div className="inline-flex items-center gap-2 rounded-full border border-neutral-800 bg-neutral-900/80 px-3 py-1 font-mono text-[10px] text-neutral-300 uppercase tracking-widest">
                  <span className="h-1.5 w-1.5 rounded-full bg-[#FF5500]" />
                  {slide.moduleTag} · {slide.topic}
                </div>
                <div className="hidden sm:flex items-center gap-1 text-[11px] font-mono text-neutral-500">
                  <span>KEYNOTE CALIBER</span>
                </div>
              </div>

              {/* Dynamic Slide Content */}
              <div className="my-8 animate-slide-right key={currentSlideIndex}">
                <h3 className="font-editorial-title text-3xl sm:text-5xl lg:text-6xl font-black tracking-tight text-white mb-4">
                  {slide.headline}
                </h3>
                <p className="text-base sm:text-xl text-neutral-400 max-w-2xl leading-relaxed font-light">
                  {slide.subhead}
                </p>

                {/* Type Specific Visual Component */}
                {slide.type === "statement" && (
                  <div className="mt-8 rounded-2xl border border-neutral-800 bg-neutral-900/60 p-5 max-w-xl">
                    <div className="flex items-start gap-3">
                      <div className="rounded-lg bg-[#FF5500]/10 p-2 text-[#FF5500]">
                        <Sparkles className="h-4 w-4" />
                      </div>
                      <div>
                        <div className="text-xs font-mono text-[#FF5500] font-semibold uppercase tracking-wider mb-1">
                          {slide.metric}
                        </div>
                        <div className="text-sm text-neutral-300">
                          {slide.highlightText}
                        </div>
                      </div>
                    </div>
                  </div>
                )}

                {slide.type === "chat" && (
                  <div className="mt-6 max-w-md space-y-2.5">
                    {slide.messages?.map((msg, i) => (
                      <div
                        key={i}
                        className={`flex ${msg.sender === "you" ? "justify-end" : "justify-start"}`}
                      >
                        <div
                          className={`max-w-[80%] rounded-2xl px-4 py-2 text-xs sm:text-sm font-medium ${
                            msg.sender === "you"
                              ? "bg-[#FF5500] text-white rounded-br-xs"
                              : "bg-neutral-800 text-neutral-200 rounded-bl-xs"
                          }`}
                        >
                          {msg.text}
                        </div>
                      </div>
                    ))}
                    <div className="pt-2 text-[11px] font-mono text-neutral-500 italic">
                      // {slide.commentary}
                    </div>
                  </div>
                )}

                {slide.type === "framework" && (
                  <div className="mt-6 grid grid-cols-1 sm:grid-cols-3 gap-3">
                    {slide.pillars?.map((p, i) => (
                      <div
                        key={i}
                        className="rounded-2xl border border-neutral-800 bg-neutral-900/50 p-4"
                      >
                        <div className="text-xs font-mono text-[#FF5500] font-bold mb-1">
                          {p.label}
                        </div>
                        <div className="text-xs text-neutral-300 leading-snug">
                          {p.desc}
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Bottom Interactive Slide Controls */}
              <div className="flex items-center justify-between border-t border-neutral-800/80 pt-4 text-xs">
                <div className="text-neutral-500 text-[11px] font-mono">
                  USE ARROWS TO TEST DRIVE
                </div>

                <div className="flex items-center gap-2">
                  <button
                    onClick={() =>
                      setCurrentSlideIndex((prev) =>
                        prev === 0 ? previewSlides.length - 1 : prev - 1
                      )
                    }
                    className="flex h-8 w-8 items-center justify-center rounded-lg border border-neutral-800 bg-neutral-900 text-neutral-300 transition-colors hover:bg-neutral-800 hover:text-white"
                    aria-label="Previous Slide"
                  >
                    <ChevronLeft className="h-4 w-4" />
                  </button>
                  <button
                    onClick={() =>
                      setCurrentSlideIndex((prev) =>
                        prev === previewSlides.length - 1 ? 0 : prev + 1
                      )
                    }
                    className="flex h-8 w-8 items-center justify-center rounded-lg border border-neutral-800 bg-neutral-900 text-neutral-300 transition-colors hover:bg-neutral-800 hover:text-white"
                    aria-label="Next Slide"
                  >
                    <ChevronRight className="h-4 w-4" />
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
